### ISSUE TITLE
[jss-nested] Nested not working in func

### ISSUE THREAD

**Issue by HeadFox** [cssinjs/jss#1004]
Hi !
I have a problem with jss-nested in my react-app.
This code
```javascript
  container: () => ({
    paddingTop: '3em',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',

    '& > div': {
      backgroundColor: 'red',
    },
  }),
```
render this : 
![image](https://user-images.githubusercontent.com/6277284/51839786-7f115c00-230a-11e9-8eac-cf1c7c4141ec.png)

But when i remove the func like this : 
```javascript
  container: {
    paddingTop: '3em',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',

    '& > div': {
      backgroundColor: 'red',
    },
  },
```
it works perfectly

Versions:

react-jss: 8.6.1,
jss-preset-default: 4.5.0

**Comment by HenriBeck** [comment]
Using `jss-nested` with function rules is currently not supported in `react-jss`

**Comment by kof** [comment]
It is fixed in v10 alpha though.
