### ISSUE TITLE
warn users when allegedly "themed" styles dont use themes. 

### ISSUE THREAD

**Issue by iamstarkov** [cssinjs/jss#1005]
__Is your feature request related to a problem? Please describe.__

Sometimes developers define styles as themed once purely out of habit without real necessity to depend on a theme.

```
export const styles = () => ({
  root: {},
});
```

Apparently people do it a lot.

__Describe the solution you'd like__
When component pulls this trick please warn developer _this component_ doesn't need to use themed styles.

__Are you willing to implement it?__
Yes

**Comment by kof** [comment]
Yeah

**Comment by iamstarkov** [comment]
is master branch a proper branch to base PR on?

**Comment by HenriBeck** [comment]
yes

**Comment by kof** [comment]
yes

**Comment by iamstarkov** [comment]
I'm on it then

**Comment by iamstarkov** [comment]
offtopic question. why author field in react-css is the way it is?
```json
   "author": {
    "name": "Dan Abramov",
    "email": "dan.abramov@me.com"
  },
```

**Comment by kof** [comment]
@gaearon has originally created the first version of react-jss. I am not sure what the traditions are around author field, it has been obviously rewritten several times since then.

**Comment by HenriBeck** [comment]
I think we should make the `author` field something which points to our repo and contributors.

Also, it should be the same for every package in my opinion.

**Comment by kof** [comment]
I agree.

**Comment by kof** [comment]
Actually there is also contributors field in package.json
