### ISSUE TITLE
Accessing styled component class names

### ISSUE THREAD

**Issue by bytasv** [cssinjs/jss#1008]
Hello,

I'm reading through docs and I can't find if it's possible to access locally generated class names for some component?

I.e. I have `Button` component and now I want to add new component `ButtonGroup`, by default I have this rule inside button styles:
```
root: {
  borderRadius: '5px'
}
```

Now inside `ButtonGroup` styles, I would like to target this `root` class of `Button` and reset those border radiuses. Maybe something like:
```
root: {
  '& ${Button.root}': {
    borderRadius: 0
  }
}
```

Is it possible at all? I know the whole deal with class scoping, but this is quite a regular use case where you want to target something that you know

**Comment by HenriBeck** [comment]
No, what you should do instead is provide a `className` prop in your button to override this classes.

In v10 (currently in alpha) you could also do this:
```js
<Button classes={{ root: this.props.classes.button }}></Button>
```
We combine the classes from the user (props classes) with the one from our stylesheet so adding a class to a child is easier.

**Comment by bytasv** [comment]
I knew about the option to pass className, I was just trying to figure out if it's possible to somehow "import" local class names. At least I know now, thanks Henri!
