### ISSUE TITLE
Can we add comments in CSS using cssinjs?

### ISSUE THREAD

**Issue by amitdhawan** [cssinjs/jss#1020]
I want the css to be generated with some comments in css like license info, each font face family license, copyright etc in comments in the css file. Is it possible using cssinjs?

**Comment by kof** [comment]
You mean during SSR extraction?

**Comment by kof** [comment]
So I need to understand why would you want to do that.

**Comment by amitdhawan** [comment]
We would provide the CSS to clients with all the copyright and license comments. This will be a type of end user agreement for client and us.

**Comment by kof** [comment]
You could add that information later on when you compiled the CSS, no?

**Comment by amitdhawan** [comment]
I was looking for a method which could do that same on the lines as createRule method does.

**Comment by kof** [comment]
Yes, but is it avoidable? Do we really need this?

**Comment by amitdhawan** [comment]
It can be, but an api would be a cleaner way to add comments to a CSS rather than adding separately which a developer can do for rules too.

**Comment by kof** [comment]
I don't think its a mainstream case, so far you are the first one in 5 years. I think you should either just add the license string to the compiled CSS output after JSS or create a plugin, which implements something like this:

```js
const styles = {
  '@comment': 'Some text',
  button: {
    ...
  }
}
```

The plugin would implement @comment rule and return proper toString value.

We could add it if you contribute it to the monorepo.

**Comment by amitdhawan** [comment]
ok.I will look into this.Thanks for quick replies.

**Comment by kof** [comment]
check out https://github.com/cssinjs/jss/blob/master/packages/jss/src/plugins/simpleRule.js

**Comment by kof** [comment]
Feel free to reopen if there is something actionable from our side.
