### ISSUE TITLE
Basic minification for SSR

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#1021]
It could be quite expensive to do a complex minification for SSR on each request, so we should provide a  n option to at least remove whitespaces in toString methods.

**Comment by kof** [comment]
On the second thought. Removing new lines is trivial and can be done in the end after .toString() even in user land. Removing all spaces which can be omited less so, because some spaces are required, for example `@media all`. To remove omiitable spaces, we would have to add logic to all toString methods. Also it won't be consistent if user used a string value, since we won't parse it.

**Comment by TriPSs** [comment]
I'm using this currently in production and did not have any problems with it so far (+- 1 year):
```
export default str => (
  str && str.replace(/[ \n\r\t\f\xA0]+/g, function (spaces) {
    return spaces === '\t' ? '\t' : spaces.replace(/(^|\xA0+)[^\xA0]+/g, '$1 ')
  })
)
```

**Comment by cdnbacon** [comment]
@kof Is there a reason the default serialization is roughly a pretty print instead of a minimal, correct representation?

What is the current approach optimizing for?

**Comment by kof** [comment]
@cdnbacon its been done this way for reading in dev tools html view when styles are static (no function values)

**Comment by kof** [comment]
This one was actually already released in https://github.com/cssinjs/jss/releases/tag/v10.8.0
