### ISSUE TITLE
Conditional groups with nested not working (SSR)

### ISSUE THREAD

**Issue by HeadFox** [cssinjs/jss#1025]
__Expected behavior:__
```javascript
const styles = ({ color, breakpoint }) => ({
  container: props => ({
    overflow: props.hidden ? 'auto' : 'unset',
    '&>h2': {
      color: color.text,
      fontSize: '1.5rem',
      paddingBottom: '1rem',
    },
  }),
  [breakpoint.small]: {
    container: {
      overflow: 'unset',
      '&>h2': {
        fontSize: '1.875rem',
        paddingBottom: '1.875rem',
      },
    },
  },
});
```

Normally on desktop my H2 font size must be 1.875rem
__Describe the bug:__
With the first SSR rendering, font-size is correct (1.875rem).
After client load, font-size go back to 1.5rem

__Versions:__
 - jss: v10.0.0-alpha.9
 - next: v7.0.2
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: MacOS

**Comment by HenriBeck** [comment]
How is the temp workaround working? From that, I would assume that the small breakpoint is only defined on the server. When the client loads and we regenerate the styles, the media query will be gone.

**Comment by HeadFox** [comment]
@HenriBeck Sorry the temp workaround wasn't working finally.
Hmm but what I don't understand is that breakpoint is working on non-nested values

**Comment by HenriBeck** [comment]
Can you try moving the breakpoint inside the actual rule?

**Comment by HeadFox** [comment]
Okay now it works 👍 
```javascript
 '&>h2': {
        fontSize: '1.875rem',
        paddingBottom: '1.875rem',
      },
```

**Comment by HenriBeck** [comment]
Not sure why it doesn't work, maybe because your rule is a function.

**Comment by PatrykRudzinski** [comment]
@HeadFox try to write rule inside breakpoint as function too.
