### ISSUE TITLE
[react-jss] 10.0.0-alpha.9 does not remove previously applied styles

### ISSUE THREAD

**Issue by bhupinderbola** [cssinjs/jss#1026]
__Expected behavior:__
passing {borderColor: null} should remove the previously applied borderColor.

__Describe the bug:__
Unable to remove the previously applied style.

__Codesandbox link:__ 
https://codesandbox.io/s/j3nqovqozy
vs
https://codesandbox.io/s/z3mromo1y3

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.9
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows

I would like to help with fixing the bugs, but I am unable to build it locally. I am not sure if it is my local issue or a code issue.
Running "yarn build" was used to give me sizeSnapshot related error. After I commented out rollup-plugin-size-snapshot plugin, I started getting following error:
Error: Could not resolve './SheetsRegistry.js' from ../jss/dist/jss.esm.js

**Comment by HenriBeck** [comment]
This seems to be an issue with `react-jss` or `jss-plugin-rule-value-function` itself, because when I try to change values (remove them from a rule) with `.prop` everything works.

https://codesandbox.io/s/wqmk2w5z98

**Comment by HenriBeck** [comment]
![screenshot 2019-02-13 at 13 20 00](https://user-images.githubusercontent.com/8514706/52711448-1bd22b80-2f92-11e9-83a7-82cda8307371.png)

**Comment by HenriBeck** [comment]
This seems to be an issue with updating a rule: https://codesandbox.io/s/qlvxmpqwjq

**Comment by kof** [comment]
I have an assumption that we remove null values somewhere in react-jss, so the property doesn't get unset.

**Comment by kof** [comment]
Ok it turned out we never removed the props when update comes from a fn rule specifically.

**Comment by kof** [comment]
fixed in 10.0.0-alpha.12
