### ISSUE TITLE
[jss-starter-kit] add test that asserts import isn't in bundle.js

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#1033]
Part of the testing suite should assert that there are no `import` statements in the `.bundle.js` bundles.  This will help prevent regressions that break 

```typescript
import { jss } from "https://unpkg.com/jss-starter-kit"
```

**Comment by TrySound** [comment]
This works for all non-react packages now
```js
import preset from "https://unpkg.com/jss-preset-default?module"
```

**Comment by kof** [comment]
Not sure how to do such a test

**Comment by kof** [comment]
Closing this for now since it's hard to test and starter kit is mostly for demos and similar.
