### ISSUE TITLE
gridColumnGap: number` not appending `px` to css rule

### ISSUE THREAD

**Issue by gibbok** [cssinjs/jss#1034]
__Expected behavior:__
Property `gridColumnGap` with a numeric value should be rendered with px unit as `grid-column-gap: 10px;`.

__Describe the bug:__
Numeric value for property `gridColumnGap`, example: `gridColumnGap: 10`, render with no pixel unit in the browser `, example:  grid-column-gap: 10;`. 

__Versions (please complete the following information):__
 - jss:  "^9.8.7",
 - Browser: Latest Chrome
 - OS: Latest macOS

**Comment by HenriBeck** [comment]
As this seems to be a `jss@9` only bug (https://codesandbox.io/s/mypqok0oy8) this will not be fixed.

**Comment by kof** [comment]
So it's fixed in v10, he has to upgrade
