### ISSUE TITLE
Duplicate jss types declarations with DefinitelyTyped

### ISSUE THREAD

**Issue by VincentLanglet** [cssinjs/jss#1039]
`jss` files have typing in this repository: https://github.com/cssinjs/jss/blob/master/packages/jss/src/index.d.ts

But `@types/jss` does also exist: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jss/index.d.ts

If the `jss` project want to provide his own typings, the DefinitelyTyped should be removed
But actually, both do not have much in common.
It create some weird behaviour.

**Comment by kof** [comment]
Definitely typed are from v9, we started to add own types for v10. Is there a way to prevent collisions? @HenriBeck

**Comment by HenriBeck** [comment]
I don't think we can prevent any collisions. Once we released v10 completely, we could add a deprecated warning to the `@types/jss` package, but we shouldn't remove it because it is needed for backward compatibility.

**Comment by VincentLanglet** [comment]
Hi @HenriBeck 

This has been a problem several times with material-ui. And I can't install the new major version.
https://github.com/mui-org/material-ui/issues/14040#issuecomment-465662508

I hope they'll find a solution if you can't prevent collision...

**Comment by HenriBeck** [comment]
It's a problem on their side, they upgraded `@material-ui/styles` to v10 without upgrading `@material-ui/core` to v10.

**Comment by VincentLanglet** [comment]
@HenriBeck I think they need at least this PR (https://github.com/cssinjs/jss/pull/973) to upgrading `@material-ui/core` to `v10`.

**Comment by HenriBeck** [comment]
Yeah, I will finish the PR today or tomorrow.
