### ISSUE TITLE
generateClassName prefix not working in Production

### ISSUE THREAD

**Issue by vinayg-cp** [cssinjs/jss#1042]
__Expected behavior:__
When using the generateClassName function in production. We expect the stylesheet.options to be populated with appropriate meta data and classNames. 
As a result all the class names are prefixed with undefined,

__Describe the bug:__
![image](https://user-images.githubusercontent.com/43405939/53234722-2be6bb00-36b6-11e9-9425-e85f0a2fa898.png)

Class names are undefined:
![image](https://user-images.githubusercontent.com/43405939/53235440-d0b5c800-36b7-11e9-8342-cfc09977d348.png)

In contrast in development it works fine: 
![image](https://user-images.githubusercontent.com/43405939/53235786-b16b6a80-36b8-11e9-9f6d-5d3d9057d52a.png)

And it is prefixed with appropriate class name in development mode. 
![image](https://user-images.githubusercontent.com/43405939/53235879-e4156300-36b8-11e9-85e4-154d012ec710.png)

The stylesheet options is not populated and instead it is undefined. 

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.
Unfortunately it happens only in production and not in development. 
So I doubt in codesandbox it will be exactly reproducible. 

__Versions (please complete the following information):__
 - jss: 8.6.1
 - Browser [e.g. chrome, safari]: Chrome 72+
 - OS [e.g. Windows, macOS]: Windows, Linux

__Code Snippets:__

![image](https://user-images.githubusercontent.com/43405939/53235264-69981380-36b7-11e9-8967-a0389b4caa07.png)

**Comment by kof** [comment]
Without some reproduction we won't have any prio on this. It should be possible to use production mode on codesandbox.

**Comment by vinayg-cp** [comment]
Noted will try to provide a minimal reproducible code on codesandbox.io

**Comment by HenriBeck** [comment]
The issue is that we pass `undefined` in production [here](https://github.com/cssinjs/react-jss/blob/master/src/createHoc.js#L71). You shouldn't expect to have a `classNamePrefix` on the stylesheets options (typings is located [here](https://github.com/cssinjs/jss/blob/master/packages/jss/src/types/jss.js#L182)).

In v10 we replaced `undefined` with an empty string.

**Comment by vinayg-cp** [comment]
> The issue is that we pass `undefined` in production [here](https://github.com/cssinjs/react-jss/blob/master/src/createHoc.js#L71). You shouldn't expect to have a `classNamePrefix` on the stylesheets options (typings is located [here](https://github.com/cssinjs/jss/blob/master/packages/jss/src/types/jss.js#L182)).
> 
> In v10 we replaced `undefined` with an empty string.

Hi,

Then where should we expect classPrefix to be present in production?

**Comment by HenriBeck** [comment]
Not at all, `classNamePrefix` can also be undefined in `development` (though that's not the case for `react-jss`)

**Comment by micaste** [comment]
@kof I have some reproduction for this.

This code sandbox has a small react-jss setup using the following example:
```
const jss = create(preset());
...
<JssProvider classNamePrefix="test-prefix" jss={jss}>
...
```

Link to the sandbox: https://codesandbox.io/s/react-jss-playground-0e14b
In dev mode, the classnames look like `test-prefixComp-title-0-2-2`.
![Screenshot 2019-09-09 at 15 52 16](https://user-images.githubusercontent.com/6943949/64536689-d1dbd900-d319-11e9-9b86-663b7b947fe8.png)


In prod mode, the classnames look like `test-prefixundefined022`.
Link to the code deployed in production mode: https://csb-0e14b.netlify.com/

![Screenshot 2019-09-09 at 15 51 27](https://user-images.githubusercontent.com/6943949/64536699-d4d6c980-d319-11e9-8c68-de9ebc4e9d7b.png)

**Comment by micaste** [comment]
Actually I found that this was fixed in https://github.com/cssinjs/jss/issues/901. I understand that there is no point backporting the fix
