### ISSUE TITLE
[jss-plugin-nested] Unknown rule @supports

### ISSUE THREAD

**Issue by BrendonSled** [cssinjs/jss#1047]
__Expected behavior:__
In the current version of react-jss @supports media works, yet in alpha 10 it's broken

__Describe the bug:__
Cannot read property 'addRule' of null
Easiest to see with Codesandbox

__Codesandbox link:__ 
https://codesandbox.io/s/r0v2k1854m

__Versions (please complete the following information):__
 - jss: latest
 - Browser: chrome
 - OS: Windows
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
you are missing a space between @supports and condition, I think it wouldn't work in CSS too.

**Comment by BrendonSled** [comment]
Thank you
