### ISSUE TITLE
Example website down?

### ISSUE THREAD

**Issue by ivoiv** [cssinjs/jss#1050]
I can't really find where to report this, I hope this is the right place.
Many of the examples on cssinjs.org link to http://cssinjs.github.io like for example the isolate plugin - http://cssinjs.github.io/examples/plugins/jss-plugin-isolate/simple/index.html but http://cssinjs.github.io returns a 404. 

Have they been moved to a new location?

**Comment by HenriBeck** [comment]
This works for me: https://cssinjs.org/?v=v10.0.0-alpha.12

**Comment by ivoiv** [comment]
Look here for example.
https://cssinjs.org/jss-plugin-isolate?v=v10.0.0-alpha.12

At the bottom there's a demo. The demo link doesn't work.

**Comment by HenriBeck** [comment]
Ohh yeah, we forgot to change the path in the examples repo as we recently renamed some packages.

You can find this example here: http://cssinjs.github.io/examples/plugins/jss-isolate/simple/index.html
