### ISSUE TITLE
[jss-vendor-prefixer] Support for `position: sticky` is missing

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#1059]
__Expected behavior:__
The prefix is added.

__Describe the bug:__
The position sticky prefix is missing on Safari?

__Codesandbox link:__ 
```jsx
import React from "react";
import preset from "jss-preset-default";
import jss from "jss";

jss.setup(preset());

const sheet = jss
  .createStyleSheet({
    root: {
      position: "sticky",
      top: 0,
      background: "black"
    }
  })
  .attach();

function Page() {
  return (
    <div style={{ height: "200vh" }}>
      <div className={sheet.classes.root}>Hello World!</div>
    </div>
  );
}

export default Page;
```

https://codesandbox.io/s/k35yvoxmxr

__Versions:__
 - jss: 10.0.0-alpha.13
 - Browser: Safari 12.0.3

**Comment by kof** [comment]
Confirmed, also tried with v9, it worked. cc @AleshaOleg

**Comment by AleshaOleg** [comment]
Sorry, my mistake!
https://github.com/cssinjs/css-vendor/pull/78

**Comment by oliviertassinari** [comment]
Can we close the issue?

**Comment by AleshaOleg** [comment]
@oliviertassinari after merging this PR - https://github.com/cssinjs/jss/pull/1068

**Comment by kof** [comment]
v10.0.0-alpha.16
