### ISSUE TITLE
[jss] Multiple animation names not being generated

### ISSUE THREAD

**Issue by dsarfati** [cssinjs/jss#1060]
__Expected behavior:__
When combining multiple animations, only the first animation's generated name is being replaced in the compiled style sheet. I would expect each animation's name to be replaced with the generated id.

__Describe the bug:__
JSS stylesheet:
`animation: '$borderAnim 2s linear infinite , $fadein 3s'`

Output:
`animation: _AnimatedBorder-keyframes-borderAnim-0-1-12 2s , $fadein 3s;`

Expected output:
`animation: _AnimatedBorder-keyframes-borderAnim-0-1-12 2s , {SOME-GENERATED-NAME} 3s;`

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.10
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: Windows
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by HenriBeck** [comment]
Thanks for the report, this should be easy to fix.

**Comment by kof** [comment]
Fixed, will be released in 10.0.0-alpha.14
