### ISSUE TITLE
Animation names aren't scoped

### ISSUE THREAD

**Issue by DreadBoy** [cssinjs/jss#1067]
__Expected behavior:__
I expected animation names to be scoped and `$name` replaced with scoped name.

__Describe the bug:__
Animation names are not scoped and `$name` stays verbatim in scoped style rules. I took react-jss sandbox I found in docs, removed clutter and copied in \@keyframes example provided in docs. Compiled style rule contains `$slideRight` variable, if I change it to `slideRight`, `@keyframes slideRight` get attached to element, meaning animation name didn't get scoped, either.

__Codesandbox link:__ 
https://codesandbox.io/s/qz1pjzx9r4

__Versions (please complete the following information):__
 - react-jss: 8.6.1
 - Browser: Chrome
 - OS: Window
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
scoping for keyframes was added in v10

**Comment by DreadBoy** [comment]
Shoot, didn't notice docs are versioned, too. Thank you!
