### ISSUE TITLE
Override/extend extended definition from parent stylesheet

### ISSUE THREAD

**Issue by orpheus** [cssinjs/jss#1069]
[Style object own properties always take precedence over extended objects, so you can always override the extended definition. An exception is function values.](https://cssinjs.org/jss-plugin-extend?v=v10.0.0-alpha.14#extending-styles)

I was wondering how you'd be able to extend the extended defintion from another stylesheet.

for instance I have

```
const parentTheme = {
    base: { backgroundColor: 'black'}
}
const childTheme = {
    base: {backgroundColor: 'white'},
    textField: {extend: 'base'},
    numberField: {extend: 'base'},
    emailField: {extend: 'base'},
    dateField: {extend: 'base'},
}
const ChidComponent = ({classes}) => {
    return <>
        <input type='text' className={classes.textField} />
        <input type='number' className={classes.numberField} />
        <input type='email' className={classes.emailField} />
        <input type='date' className={classes.dateField} />
    </>
}
const ParentComponent = ({classes}) => {
    const StyledChildComp = withStyles(childTheme)(ChildComponent)
    return <StyledChildComp classes={classes} />
}
const StyledParentComp = withStyles(parentTheme)(ParentComponent)

// 
<StyledParentComp />
//
```
Essentially I'm looking to change all of the inputs at once while still keeping their individuality so I can style them seperately from the parent component now that class-merging is working in v10-a. Is there a way or a workaround to do this?

Because the `base` classname never gets applied to a className, the parent `base` class has no effect.

**Comment by kof** [comment]
Extending with string refs only works inside of a single style sheet.

**Comment by kof** [comment]
You should not generate styled components in side of other components. This will have some overhead.

**Comment by kof** [comment]
If you really need to override a child component at render time you can do 2 things
1. Use rule function and pass the styles object over props
2. Pass a class name from the parent

It looks like though you don't need to do that at render time, so you can statically create those styled components and reuse a base style object in all.

**Comment by orpheus** [comment]
Are those the only two ways to ovveride/extend child components? I didn't make my example accurate to my situation.

My idea is to create a component with default static jss styles and then export that component.
Then be able to import that component in another project and completely ovveride and/or extend any style rule I want. 

I was hoping to do this without having to wrap the imported component in a withStyles hoc (to make it simpler for end users). Currently, I'm doing twice what you said not to do which is generate styled components within other components. 

How much overhead are we talking because my current solution allows me to remove all styles, extend all styles, and override any styles I want from props without having to wrap my imported component in a withStyles HOC. 

[If you wouldn't mind taking a look at how I'm currently building my component.](https://github.com/oipwg/oip-react-v2/blob/master/src/components/DynamicComplexSearch/DynamicComplexSearch.js)

[And how I'm [wanting to] implementing it.](https://github.com/oipwg/oip-react-v2/blob/master/stories/DynamicComplexSearch.stories.js)
