### ISSUE TITLE
Can you use a '+' combinator on a global that also refers to a local rulename?

### ISSUE THREAD

**Issue by orpheus** [cssinjs/jss#1073]
You say [here](https://github.com/cssinjs/jss/issues/751) to look at global and nested, but I cannot seem to get the `+` combinator to work

Trying to [make a toggle switch from W3](https://www.w3schools.com/howto/howto_css_switch.asp)
```
input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}
```

I'm trying something like this: 
```
	'@global': {
		input: {
			'&:checked, &slider': {
				backgroundColor: 'black'
			},
			'&:focus, &slider': {
				boxShadow: '0 0 1px #2196F3',
			},
			'&:checked, &slider:before': `
			    -webkit-transform: translateX(26px);
			    -ms-transform: translateX(26px);
			    transform: translateX(26px);
			`,
		}
	},
```

Especially the last part: `input:checked + .slider:before {` , how are you supposed to add a selecter to a local rule in a nested rule selector?

Even at the basic level, I cannot seem to get this to register: 
```
	'@global': {
		input: {
			'&:checked': {
				backgroundColor: '#2196F3'
			},
		}
	},
```

**Comment by kof** [comment]
You want `'&:checked, &.slider'`. Please use https://cssinjs.org/repl/ before posting issues.
