### ISSUE TITLE
Ref: odd styled-jss benchmarks

### ISSUE THREAD

**Issue by jeremy-coleman** [cssinjs/jss#1081]
When benchmarking several frameworks, i found styled-jss to be extremely fast ,4-15x faster than others. Any insight as to why? I know its using jss 9.x and the older preset plugin

Please see this issue for more info
https://github.com/mui-org/material-ui/issues/15241

This is the original benchmark
https://github.com/mui-org/material-ui/blob/next/packages/material-ui-benchmark/src/styles.js

**Comment by kof** [comment]
not sure

**Comment by kof** [comment]
mb @lttb knows

**Comment by lttb** [comment]
at first glance, this benchmark uses only static styles, and in that case `styled-jss` is actually quite effective with that across different instances of styled components. but such extremely fast results (as I see your example, it looks like even faster than `naked` button) really look quite odd

I'll try to reproduce your benchmarks, and maybe I'll get any insight then 🙂

**Comment by jeremy-coleman** [comment]
Accidently closes/opened this on mobile, as i was typing to say thank you@lttb

**Comment by kof** [comment]
@lttb were you able to look into that?

**Comment by kof** [comment]
in case there is an update, please reopen
