### ISSUE TITLE
createRule in react

### ISSUE THREAD

**Issue by alonronin** [cssinjs/jss#1082]
__Expected behavior:__
want to use `jss.createRule` as inline style in react, benefits autoprefixer and other plugins.
 
__Describe the bug:__
`jss.createRule(rule).toJSON()` works, however it emits warning in react since the styles are not camelCase.

__Codesandbox link:__ 
https://codesandbox.io/s/3y3vvnpp6p

__Versions (please complete the following information):__
 - react-jss: 8.6.1
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
Yeah, the reason is that the setup of Jss instance you are using is for style tag rendering, so you need a custom setup for inline styles, without came-case plugin. We should document this somewhere.

Also you are a living proof this API is used and we probably shouldn't remove it in #1076

**Comment by HenriBeck** [comment]
What use case does this have? I couldn’t come up with any

**Comment by alonronin** [comment]
@HenriBeck 
I have a dynamic creation of components by the users from a JSON file with a style object on it.
I just wanted to vendor prefix the style object and pass it back to the component.

@kof 
Yes, it is nice to have the possibility to use plugins for some inline styles.
My components are created dynamically and the same app can be rendered across the page multiple times, so it would also create a stylesheet for each app (because the classes could be completely different for each app).

It was the easiest way to inline-style the rules, however, I'm considering to refactor it using stylesheets instead.

**Comment by kof** [comment]
Sounds like you can do the same with StyleSheet without attaching it.

**Comment by alonronin** [comment]
yep.
