### ISSUE TITLE
Css properties order are different between nodejs versions

### ISSUE THREAD

**Issue by justbrody** [cssinjs/jss#1084]
__Expected behavior:__
I've set up snapshot-testing for CSS that is generated by cssinjs. When there is no change made in the source, I expect to have the same css-snapshot output on different nodejs environments.

__Describe the bug:__
Sadly the snapshots do differ on different nodejs version. The order of the properties in a stylesheet are different between node 10 and node 11.

__Codesandbox link:__ 
I don't know how to reproduce it as a codesandbox. But I have created a project on github. The project has one simple react component and a snapshot test for the component. The snapshot is also committed and is made with nodejs 10. Then I created two Pull-Request one with node9 and one with node11. You can see that nodejs 11 has a failed snapshot-test with some properties on different positions compared with the snapshot of node 10.

[Snapshot testcase on GitHub](https://github.com/justbrody/jss-snapshot-problem)

__Versions (please complete the following information):__
 - jss: react-jss@8.6.1
 - Browser [e.g. chrome, safari]:Not in the browser, testing in node
 - OS [e.g. Windows, macOS]:Linux/Windows/iMac
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by justbrody** [comment]
The nodejs 11 has an updated v8 engine, which has a changed implementation of Array.sort
https://github.com/nodejs/node/issues/24294

**Comment by kof** [comment]
We have discussed this on gitter. Our assumption is that between those node versions a different V8 version is used which has a change in sort implementation https://github.com/nodejs/node/issues/24294

We use sort in props-sort plugin

**Comment by kof** [comment]
We are basically sorting based on property name, I haven't learned yet how and why stable/unstable sort is influencing thouse. Anyone wants to look into it?

**Comment by HenriBeck** [comment]
I can give you the reason: [here](https://travis-ci.com/justbrody/jss-snapshot-problem/builds/107596489) the order is only different for style property names with the same length.
I think we should compare the string when they have the same length.

**Comment by justbrody** [comment]
I checked in my production code and it is always the case when the length is the same.

**Comment by HenriBeck** [comment]
@justbrody for you a fix would be to align your node versions across the project, for example via https://github.com/creationix/nvm or https://github.com/Schniz/fnm

We will try out the fix with the comparing strings when the props have the same length

**Comment by justbrody** [comment]
Thanks, a fix comparing the strings sounds good.

I've setup nvm today on my machine and that is a good solution for us. I'll inform my collegues tomorrow. Thank you for the time and help.

**Comment by justbrody** [comment]
If I can help, please let me know.

**Comment by HenriBeck** [comment]
#1084 will fix your problem. I added some logic to return `1` or `-1` when the strings have the same length to ensure consistent sorting between different node versions.

**Comment by justbrody** [comment]
Thank you @HenriBeck, I will keep an eye on the PR and see in with version it will be release.
