### ISSUE TITLE
Channel context to withTheme

### ISSUE THREAD

**Issue by afrankel-sfdo** [cssinjs/jss#1086]
__Describe the solution you'd like__

- injectSheet supports theming channels via: 
  - `injectSheet(styles, { theming: CUSTOM_THEME })`
- similar support for `withTheme` is required to gain context to that same theme provider when running multiple themes.
  - Tried (with no luck): `withTheme(TestComponent, { theming: CUSTOM_THEME })`

__Are you willing to implement it?__
Maybe, would need some direction.

**Comment by HenriBeck** [comment]
You have access to a `withTheme` HOC on your custom theming object.

https://github.com/cssinjs/theming#createthemingcontext

**Comment by afrankel-sfdo** [comment]
@HenriBeck totally missed that, thanks!
