### ISSUE TITLE
Update Aphrodite , glamor, and styled to v10

### ISSUE THREAD

**Issue by jeremy-coleman** [cssinjs/jss#1095]
ive updated aphrodite glamor and styled with some small changes to use jss10 , do these fall under the scope of the monorepo? 

__Are you willing to implement it?__
Yes

The glamor impl wouldnt work without removing the original versions selector normalization plugin.

Aphrodite version works mostly fine, i made several variants id like some feedback on

Styled version i removed the theming v1.3 and related code, i also removed attribute checking but can easily add it back in 1 line

Would someone like to look it over in a test repo or something?

**Comment by kof** [comment]
I am working on a new styled interface implementation https://github.com/cssinjs/jss/pull/1094
Also we are working on a hooks based api https://github.com/cssinjs/jss/pull/1089
Regarding aphoridte api - currently I don't have any bandwidth for it.
Glamor API - where did you find it on this org?

**Comment by jeremy-coleman** [comment]
The glamor impl isnt from the jss org but i think it has its place. The big benefit is that is uses data selectors so u dont have to worry about over/under writing classname or style. 

For the aphrodite version, I also put the stylesheet creator inside a class constructor , with 3 different create() equivalents for overriding the classname and optional css() call built in . I can easily add a styled() call to create react components also if thatd be useful - one thing i dont understand is why to remove the stylesheet on component unmount?

**Comment by kof** [comment]
> The big benefit is that is uses data selectors 

Not sure what you mean by that

> why to remove the stylesheet on component unmount

A large CSSOM at runtime can negatively impact the rendering, it needs to be quite big though for this.  Also there have been some limits in older browser about amount of total CSS one can render.

**Comment by HenriBeck** [comment]
I would also be up for importing the `styled` API into this monorepo as we are doing in #1094 

I don't think the other to syntaxes were previous versions of a css-in-js implementation where the community has moved away.

**Comment by kof** [comment]
The styled API in #1094 will be as close as possible to emotion/SC. Also some other parts in the old styled are simply not needed because we assume one can use injectSheet in such cases.

**Comment by jeremy-coleman** [comment]
By data selector, i mean the generateRuleId uses data-(ruleName) attributes on the target element instead of className

**Comment by kof** [comment]
How is that a big benefit, I don't get it @jeremy-coleman

**Comment by jeremy-coleman** [comment]
Because you dont have to deal with over riding class names

**Comment by kof** [comment]
You mean in case where a class name is used otherwise, you can use data attribute and not have to concatenate classes, is that it?

**Comment by jeremy-coleman** [comment]
Yes, anyway, let me know which impl’s you want , if you have slack or something i can show you a few different versions and discuss which features should be in the final api

**Comment by kof** [comment]
Our focus is right now the new hooks api, the new styled api and releasing stable v10

**Comment by kof** [comment]
So if you are using glamor/aphrodite implementation feel free to update them to v10

**Comment by jeremy-coleman** [comment]
I was testing the aphrodite impl yesterday, and cannot figure out what the problem is... i even tried switching out the original merge and generate functions with the ones from the mui jss implementation and still got parse warnings. stuck:\

**Comment by kof** [comment]
@jeremy-coleman ping me on gitter with details
