### ISSUE TITLE
[react-jss][jss-nested] Function values do not work with nested classes

### ISSUE THREAD

**Issue by LeeKevin** [cssinjs/jss#1096]
__Expected behavior:__

Function values should work with nested classes.

__Describe the bug:__

The following style does not work:

```
  main: ({ value }) => ({
    background: "red",
    width: 100,
    height: 50,
    marginBottom: 10,

    "&:before": {
      content: `"${value}"`
    }
  }),
```

It produces:

```
.ReactJssTest-main-1-1-3 {
    background: red;
    width: 100px;
    height: 50px;
    margin-bottom: 10px;
    &: before: [object Object];
}
```

However, this is working:

```
  works: {
    background: "green",
    width: 100,
    height: 100,

    "&:before": {
      content: `"works!"`
    }
  }
```

```
.ReactJssTest-works-1-1-2 {
  width: 100px;
  height: 100px;
  background: green;
}
.ReactJssTest-works-1-1-2:before {
  content: "works!";
}
```

__Codesandbox link:__ 
https://codesandbox.io/s/oqxr32l2w6

__Versions (please complete the following information):__
 - jss: latest
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by HenriBeck** [comment]
This was fixed in one of the alphas of v10 of jss and react-jss. If you need this fixed, please upgrade to the latest alpha version (it is really stable)

Example: https://codesandbox.io/s/jz9k1m56q3

**Comment by LeeKevin** [comment]
Woo! Thanks!
