### ISSUE TITLE
@keyframes identifiers aren't escaped and don't work if contain, e.g., parentheses

### ISSUE THREAD

**Issue by synchronos-t** [cssinjs/jss#1098]
__Expected behavior:__
@keyframes identifiers should work even if they contain injected parentheses and should escape them properly.

__Describe the bug:__
Material UI, from version 4.0.0-alpha.6 onwards, has been injecting HOCs to JSS class names with parentheses, e.g. `Connect(ComponentName)` (for react-redux connect()), instead of `Connect--ComponentName`. These work well with class names and the parentheses are properly escaped. However, when used with `@keyframes`, they appear in styles unescaped and hence stop working.

__Codesandbox link:__ 
https://codesandbox.io/s/74m7qv4qrj

The above Codesandbox creates two buttons, which should be spinning, but don't. If you remove the connect() from TestComponent, the left button starts spinning again.

The right button (TestComponent2) tries to directly put parentheses in the identifier name, which causes the identifier to drop everything from the opening parenthesis onwards in `@keyframes` as well. (I'm not sure if it's needed for JSS to allow direct referring to ids containing parentheses, however.)

The related issue at Material UI: https://github.com/mui-org/material-ui/issues/15604

**Comment by HenriBeck** [comment]
I think we can just remove all non A-Z characters from the name of the component

**Comment by kof** [comment]
we have a escape utility, why not use it?

**Comment by HenriBeck** [comment]
Actually, the problem is that we are not escaping the `keyframes` selector. We are doing it for normal class names
