### ISSUE TITLE
[jss-nested] 

### ISSUE THREAD

**Issue by abcxyzmarte** [cssinjs/jss#1101]
I'm trying to modify in Material-ui using the $rulename, but the rule doesn't work.

```
.MuiOutlinedInput-root-344 .MuiOutlinedInput-notchedOutline-351 {
    border-color: rgba(0, 0, 0, 0.23);
}
```

I did like this:

```
MuiOutlinedInput: {
     "&$root &$notchedOutline": {
                borderColor: "red"
            },
}
```

I want to change the borderColor of a TextField using the MuiThemeProvider

**Comment by HenriBeck** [comment]
This is a question for material ui how to change their styles.

Either have a look at [how you can change the theme](https://material-ui.com/customization/themes/) or file a bug in their repo.
