### ISSUE TITLE
[FEATURE REQUEST] Config to make internal styles in head AND to insert rules directly to the CSSStyleSheet

### ISSUE THREAD

**Issue by o-alexandrov** [cssinjs/jss#1102]
## Related issue

- [[Material-UI 4.0.1-beta] Unwanted CSSStyleSheet.insertRule behavior when using styled (passing a function as a param for styles)](https://github.com/mui-org/material-ui/issues/15660)

## Issues

| Issue | Effect |
| ----- | ------ |
| JSS doesn't follow the exact same process to apply styles for all cases by default. **At least two cases are already documented** in the related issue above. | Worsens developer experience and performance |

## How to solve

Set the default mode to insert style rules directly to the CSSStyleSheet using [CSSStyleSheet.insertRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule)
- instead of doing the extra step of inlining styles to the `<head>`, making styles internal and leaving the browser to process style rules from the HTML finally applying them to the CSSStyleSheet of the StyleSheet interface.

**Comment by kof** [comment]
There are 2 assumptions here

1. it reduces dev experience
2. it reduces performance

I would like to challenge both of it:

1. This only matters if you go into the html view of the dev tools and start reading styles. The question is why would you want to do that, because you have all the style rules visible in the styles tab if you select an element.

2. It does not exactly slows down the performance. There are different kinds of rendering

1. If a big chunk of CSS is generated at once. In that case  `style.textContent` DOM API will outperform the `sheet.insertRule` CSSOM API, because the last one needs to be called per rule and the first one only once and the rest happens in native code. 
2. If you need to insert specific rules, `sheet.insertRule` will outperform `style.textContent` because the last one is a DOM API and does more work that the CSSOM one, but the CSSOM one won't be visible in DOM inspector's style element representation, because those rules won't be part of innerHTML/textContent.


Philosophy I am trying to follow is to use the best approach depending on the case.

**Comment by HenriBeck** [comment]
Agree with @kof here. Unless you can provide some solid argument with a real explanation why it’s better I don’t see a reason for this request.

**Comment by o-alexandrov** [comment]
@kof 
Ok, let me continue on the points you summarized:
1. it reduces dev experience
2. it reduces performance

1. Hopefully, understanding the aspects that lead to the worsened dev experience are now clear, after reading the comments starting from [this one in the related issue](https://github.com/mui-org/material-ui/issues/15660#issuecomment-491580850).

@kof @HenriBeck 
2. @kof is correct the insertRule cannot insert multiple rules at once.

However, he is also misleading the readers by stating:
> the rest happens in native code
- this wording might lead to the false notion that [CSSStyleSheet.insertRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) is not native. The call to trigger the method of the CSSStyleSheet instance is **not native**, however, the actual method is performed by the Web API, so the **CSSStyleSheet.insertRule() is native**.

This leads to the question:
- What is more performant? 
  - Unfortunately, yes, it is highly subjective to judge performance without running a benchmark against the following two cases. However, I feel converting styles to string, inserting a long string, then parsing that string would be less performant than the O(n) way that doesn't require extra steps. 

|Case | Operations |
| ---- | ----------- |
| 1. Rendering a very long string and then to wait until the Web API parses it, applying style rules one by one | - Non-native call to convert a JavaScript object to a CSS string<br>- Non-native call to add a string to HTML<br>- Native call to parse text<br>- Native call to add style rules to the CSSStyleSheet instance |
| 2. Inserting rules directly to the CSSStyleSheet instance | O(n) pairs of calls:<br>- Non-native call to trigger the CSSStyleSheet.insertRule()<br>- Native CSSStyleSheet.insertRule()|

**Comment by HenriBeck** [comment]
I think you forgot a few steps in the second case. We still convert the rule to a string, and the browser still needs to do the parsing.

We do especially more work for container rules like media queries when they are dynamic as we first need to insert the container and then add the child rules to it. 

The benefit of the first case is that it's happening in a batch and not rule by rule.

**Comment by o-alexandrov** [comment]
Yes, good catch, in the attempt to make it as descriptive:
- I missed that JSS still needs to stringify the style rule as the [CSSStyleSheet.insertRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule#Parameters) accepts the string for the first parameter.
  - the same as with the first case

I adjusted the table above, to add the missing step to the second case.

Then, I thought back about the first case and realized that JSS doesn't actually work in a O(1) way as @kof claimed above:
> If a big chunk of CSS is generated at once. In that case style.textContent DOM API will outperform the sheet.insertRule CSSOM API, because the last one needs to be called per rule and the first one only once and the rest happens in native code.
- Please see the edited table for the first case above. **Note, all `<style>` tags are actually added separately.**

In the end, your points didn't convince me, but actually while talking I realized more and more flaws, so I wanted to create a simple benchmark for you 😄 
- https://codesandbox.io/embed/l5wkxo3m9m
  - There two flaws I left in my example:
    - I don't use **virtual DOM**, so the performance of the inlining could be slightly better than what we see in the logs.
    - When measuring inlining style rules, I don't even measure the browser's CSS parsing from the DOM to CSSOM by Web API.
      - I left it unmeasured, because **inlining is slower even without that last step**.

**Comment by HenriBeck** [comment]
Of course your benchmark "proves" that it's faster as you do more work on the `inline` step which doesn't reflect our usage.

You are creating for every rule which is inlined into a sheet a completely new sheet and even using an already defined sheet for the `insertRule` calls.

A better benchmark would be to have a set of randomly generated rules with some properties.

For the `insertRule` API, you would create a sheet and then loop over each created rule, parse it to a string and then use `insertRule`

For the `inlining`, you would need to parse all of the rules to a giant string and then do the inlining exactly once.

**Comment by HenriBeck** [comment]
Also, how do you solve the issue of `prerendering`? You will still need a similar setup to the SSR one as now no styled would be "visible" in the head.

**Comment by o-alexandrov** [comment]
@HenriBeck
> Of course your benchmark "proves" that it's faster as you do more work on the inline step which doesn't reflect our usage.

I mentioned in above the use of JSS in Material UI. In Material UI, JSS inlines every single statement in a separate `style` tag.

> You are creating for every rule which is inlined into a sheet a completely new sheet and even using an already defined sheet for the insertRule calls.

- Inlining. This is exactly what is happening when using JSS in Material UI, so no mistake in the benchmark.

> A better benchmark would be to have a set of randomly generated rules with some properties.

Actual style rules contents don't matter, we are measuring the addition of of the style rules using two different approaches.

> For the insertRule API, you would create a sheet and then loop over each created rule, parse it to a string and then use insertRule

Sheet isn't needed to be created, it could already be predefined in the `head` as I have in the example in `index.html`:
```html
<style></style>
<div id="root"></div>
```

> For the inlining, you would need to parse all of the rules to a giant string and then do the inlining exactly once.

You are not mentioning:
- beforehand, you need to add a watcher for the style properties' changes to measure the time DOM parsing by the browser, so the styles are applied to CSSOM. 
  - I don't measure that in the provided example benchmark as the inlining is already slower given the current use, you are welcome to continue the work and share fully completed benchmark on top of that.

> Also, how do you solve the issue of prerendering? You will still need a similar setup to the SSR one as now no styled would be "visible" in the head.

It is quite simple, after:
```js
ReactDOM.render(<ReactApp>, document.getElementById("app"))
```

run
```js
if (prerendering) { // add your condition for the prerendering
  const getAllCSS = () => {
    let styles = ""
    const stylesheets = document.styleSheets

    for (const stylesheet of stylesheets) {
      if (
        !stylesheet.href &&
        stylesheet.cssRules &&
        stylesheet.cssRules.length
      ) {
        for (const rule of stylesheet.cssRules) {
          styles += rule.cssText
        }
      }
    }

    return styles
  }
  const styles = getAllCSS()

  const removeAllStyleTagsFromHead = (head) => {
    const styleTags = head.querySelectorAll("style")
    for (const styleTag of styleTags) {
      styleTag.remove()
    }
  }

  const head = document.head
  removeAllStyleTagsFromHead(head)

  const elStyle = document.createElement("style")
  elStyle.innerHTML = styles
  head.appendChild(elStyle)
}
```

**Comment by o-alexandrov** [comment]
However, I hope the JSS maintainers are not distracted from the actual issue that is document in the original (first) message.

Please make a decision to apply style rules consistently; then, I would try to dedicate time to assist in benchmarking.

Issue mentioned in the first message:
> JSS doesn't follow the exact same process to apply styles for all cases by default. At least two cases are already documented in the related issue above.

@kof disappeared for some reason, but is pinging here with emojis after the following message that asks for the consistency also:
- https://github.com/mui-org/material-ui/issues/15660#issuecomment-491623352

Consistency is practically all I need from this library as of now.

**Comment by HenriBeck** [comment]
```js
if (prerendering) { // add your condition for the prerendering
  const getAllCSS = () => {
    let styles = ""
    const stylesheets = document.styleSheets

    for (const stylesheet of stylesheets) {
      if (
        !stylesheet.href &&
        stylesheet.cssRules &&
        stylesheet.cssRules.length
      ) {
        for (const rule of stylesheet.cssRules) {
          styles += rule.cssText
        }
      }
    }

    return styles
  }
  const styles = getAllCSS()

  const removeAllStyleTagsFromHead = (head) => {
    const styleTags = head.querySelectorAll("style")
    for (const styleTag of styleTags) {
      styleTag.remove()
    }
  }

  const head = document.head
  removeAllStyleTagsFromHead(head)

  const elStyle = document.createElement("style")
  elStyle.innerHTML = styles
  head.appendChild(elStyle)
}
```

I have no idea how you consider this more friendly than just wrapping your main component in a `JssProvider`, create a `SheetsRegistry` and then call `sheets.toString` on it.

This code is just not consumer friendly.

**Comment by o-alexandrov** [comment]
@HenriBeck 
`JssProvider` and `SheetsRegistry` are part of `JSS`.
You are welcome to similarly add a method as part of `JSS` and call it as follows:

```js
if (prerendering) { // add your condition for the prerendering
  jss.prerender()
}
```

> This code is just not consumer friendly.
Hopefully, above clears this point.

Again, both @HenriBeck and @kof are completely ignoring the mentioned issue and @kof shows all signs of unwillingness to even admit the presence of an issue:
- in this thread
- in the related one: mui-org/material-ui#15660 (comment)

I believe the consistency, i.e. predictability of the dev experience is crucial and `jss` ignores so many [messages](https://github.com/mui-org/material-ui/issues/15660#issuecomment-491623352), [screencasts](https://github.com/mui-org/material-ui/issues/15660#issuecomment-491620606), even detailed [attempts to express terminology](https://github.com/mui-org/material-ui/issues/15660#issuecomment-491626399) to one of the most famous use cases to one of the maintainers.

In my opinion, Material UI team did incredible job overall; hopefully, they will improve further and [their consideration](https://github.com/mui-org/material-ui/issues/6115#issuecomment-471274295) to start using [styled-components](https://github.com/styled-components/styled-components) is highly appreciated.

**Comment by kof** [comment]
@o-alexandrov I didn't have time to dig through your verbose communication. We are working on releasing v10 and I will look into it once I get time.

**Comment by HenriBeck** [comment]
> JssProvider and SheetsRegistry are part of JSS.

So? where is the problem????

**Comment by o-alexandrov** [comment]
@kof 
I totally understand being busy with work and I highly appreciate as well as admire your work on the open source libraries.

However, when you say:
> I didn't have time to dig through your verbose communication. We are working on releasing v10 and I will look into it once I get time.

This is either:
- a false statement
- or your already present 👍 emojis indicating agreement with the @HenriBeck replies are not based on the thoughtful evaluation and instead are misleading the readers.

**Comment by HenriBeck** [comment]
> Again, both @HenriBeck and @kof are completely ignoring the mentioned issue and @kof shows all signs of unwillingness to even admit the presence of an issue:

Not sure who you are talking to in that case as we are the only maintainers at the moment.

> I believe the consistency, i.e. predictability of the dev experience is crucial and jss ignores so many messages, screencasts, even detailed attempts to express terminology of one of the most famous use cases, prerendering, to one of the jss maintainers.

`Many` being here your comments, you have been to the first one to complain about this.

You expect us to be open about your points and arguments but you are not open to ours. Even though we most likely know our own library better than you.

> I mentioned above the use of JSS in Material UI. In Material UI, JSS inlines every single statement in a separate style tag.

This is simply not true, you can have multiple rules in the same stylesheet in `jss`. MUI AFAIK and `react-jss` are not creating for every rule a single stylesheet.

> Inlining. This is exactly what is happening when using JSS in Material UI, so no mistake in the benchmark.

This issue should not use code like it's being used in material UI. They simply use our core library.

> This is either:

a false statement
or your already present 👍 emojis indicating agreement with the @HenriBeck replies are not based on the thoughtful evaluation and instead are misleading the readers.

You expect us to put work into your request, but why don't you create a PR for it and we can review it then. We simply have other stuff to do right now which is more important (to us).

**Comment by kof** [comment]
I put thumbs up when I understand the points. If you want to talk, ping me in dm on twitter or gitter. I honestly lost your point and at the moment don't really know what you want.

**Comment by kof** [comment]
I have been playing around with a way to render styles in dev mode over DOM API to make it visible in style tags DOM inspector and editable in styles tab. I think I have some ideas. Opening a new clean issue #1125
