### ISSUE TITLE
Usage with TypeScript. WithStyles type

### ISSUE THREAD

**Issue by vtereshyn** [cssinjs/jss#1107]
Recently, I created a new project with the latest versions each of dependencies. I did all step by step according to [documentation](https://cssinjs.org/react-jss?v=v10.0.0-alpha.16) . But got an error that `WithStyles` doesn't exist in `react-jss`. 
Later, I found that `WithStyles` exists in alpha pre-release version only (v10.0.0-alpha.16). It's OK, but let's add this to documentation as well, since it can be confused for new `jss` users as me :) 

Please, let me know if it works for you and I'll create a PR

**Comment by HenriBeck** [comment]
Sounds great, the TS types are since version 10 (which is currently in alpha) in this repo just FYI.

So not only `v10.0.0-alpha.16`

**Comment by vtereshyn** [comment]
Oh, found that documentation is already fixed in https://github.com/cssinjs/jss/pull/1078, but hasn't released yet :)

**Comment by HenriBeck** [comment]
Hmmm, that's weird because any docs changes should be live as soon as they are merged to master

**Comment by vtereshyn** [comment]
@HenriBeck okay, let me create one more PR

**Comment by vtereshyn** [comment]
Yes, so master is incompatible with current website and docs version

**Comment by HenriBeck** [comment]
Oh wait, no, so docs are not automatically updated 🤦‍♂ 
They will be updated once we release a new version and create a new GitHub release.

I think we will release the next version in a few days.
