### ISSUE TITLE
Typing props in styles object. React & Typescript & JSS

### ISSUE THREAD

**Issue by vtereshyn** [cssinjs/jss#1110]
Probably duplicate, but couldn't find similar issues.

Have structure like this:

```
const styles = {
	button: props => ({
		color: props.active ? 'red' : 'white'
	})
};

interface Props extends WithStyles<typeof styles> {
    active: boolean
};
```

I want to add types to `props` in `styles` object. But my `Props` interface is declared after. So I can't use Props interface before in case to have `typeof styles`. So, what can be a solution for this?

I guess the best way in the current implementation is to create interface `OwnProps` before styles and use it in `styles` and in `Props` interface as well.

For example:

```
interface OwnProps {
    active: boolean
}

const styles = {
	button: (props: OwnProps) => ({
		color: props.active ? 'red' : 'white'
	})
};

interface Props extends WithStyles<typeof styles>, OwnProps {};
```

My questions:
- is this behavior expected?
- do you have another solution for this case to improve the structure to:

```
---imports

---styles

---types
```

or

```
---imports

---types

---styles
```

Let me know if you need something else from me or you have any questions.
Thank you in advance!

**Comment by HenriBeck** [comment]
There is no way around this sadly. Your best option is to use your `OwnProps` before `styles` solution.
