### ISSUE TITLE
[react-jss] withStyles typings should take strings as object values

### ISSUE THREAD

**Issue by rafamel** [cssinjs/jss#1114]
__Is your feature request related to a problem?__
`withStyles` gives a type error when taking a string as object value despite `jss-plugin-template` being a default plugin:

```javascript
withStyles({
  root: `font-size: 1em;`
});
```

__Describe the solution you'd like__
`withStyles` should not error out when taking strings as object values. This should also be taken into account for the new hooks api.

__Are you willing to implement it?__
Yes

**Edit:** It looks like the culprit is `jss` exported `Style`: `export type Style = { [key: string]: Style | any }`.

**Comment by kof** [comment]
Are you talking about flowtype or typescript?

**Comment by rafamel** [comment]
Hi @kof , this is a TS issue :)

**Comment by HenriBeck** [comment]
Will be fixed in #1155
