### ISSUE TITLE
[Question]How to generate inline styles using jss?

### ISSUE THREAD

**Issue by StringKe** [cssinjs/jss#1115]
```javascript
import jss from 'jss'
import preset from 'jss-preset-default'

jss.setup(preset())

const styles = {
  c:{
    padding: 40,
    background: '#f7df1e',
    textAlign: 'center'
  }
}

console.log(jss.createStyleSheet(styles).toString());
```
I don't need to generate a class name, how do I get an inline style?

**Comment by kof** [comment]
```js
jss.createStyleSheet(styles).getRule('c').toJSON()
```

https://cssinjs.org/jss-api?v=v10.0.0-alpha.16#convert-a-rule-to-json

**Comment by StringKe** [comment]
> ```js
> jss.createStyleSheet(styles).getRule('c').toJSON()
> ```
> 
> https://cssinjs.org/jss-api?v=v10.0.0-alpha.16#convert-a-rule-to-json

thks
