### ISSUE TITLE
keyframes animations doesn't work

### ISSUE THREAD

**Issue by AleshaOleg** [cssinjs/jss#1120]
__Expected behavior:__
Animation with `keyframes` doesn't work.

__Describe the bug:__
Seems for some reason JSS@10 doesn't understand `keyframes` syntax and don't animate necessary things. For JSS@9 everything works as expected.

__Codesandbox link:__ 
https://codesandbox.io/s/core-jss-playground-rp536

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.17
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
JSS 10 scopes keyframe names by default, `  animation: "$backgroundAfter 1s infinite"`

For global identifiers the keyframe needs to be inside of @global rule

**Comment by kof** [comment]
see https://github.com/cssinjs/jss/blob/master/changelog.md#breaking-changes-2

**Comment by kof** [comment]
Documentation seems ok to me, if you think we need to improve in communication or documentation please reopen.
