### ISSUE TITLE
Angular support - 'global' is not defined

### ISSUE THREAD

**Issue by LukeTOBrien** [cssinjs/jss#1150]
Hi there,

It seems to me that JSS and JS-in-CSS libraries are geared towards React, but do you also support Angular?

I have installed your modules using the command:  
`npm install --save jss jss-preset-default`

At first I had an issue whereby the modules could not be found, after updating my project to Angular v8 and TypeScript 3.4.5 I no longer get that issue.  
Now I am getting a runtime error in the DevTool console `'global' is not defined` is I open up the debugger to see the src I get the following section:

```TypeScript
Object.defineProperty(exports, "__esModule", {
  value: true
});
var CSS = global.CSS;   // <- Error here

var env = "development";

var escapeRegex = /([[\].#*$><+~=|^:(),"'`])/g;

exports['default'] = function (str) {
  // We don't need to escape it in production, because we are not using user's
  // input for selectors, we are generating a valid selector.
  if (env === 'production') return str;

  if (!CSS || !CSS.escape) {
    return str.replace(escapeRegex, '\\$1');
  }

  return CSS.escape(str);
};
```

This is frustrating because I have ran the app and tested my feature, it all worked.... and then magically started not working!

Any ideas?  
Has anyone used JSS with Angular before?

**Comment by kof** [comment]
what JSS version are you trying to use? How do you bundle it?

**Comment by kof** [comment]
I assume it's one of the 9.x, try latest 10 alpha
