### ISSUE TITLE
Fix examples links

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#1156]
Since we changed plugin names, we broke examples links.

Also, mb it's better to maintain examples repo in the jss monorepo?

**Comment by m4theushw** [comment]
I wanna make my first contribution. Is this an issue yet?

**Comment by kof** [comment]
Yes, totally

**Comment by kof** [comment]
Depending how far you think you can take it, this issue may be just fixing links or moving examples into the monorepo. The last one wouldn't be easy.

**Comment by m4theushw** [comment]
I'm copying the [examples](https://github.com/cssinjs/examples/) repo to the monorepo and fixing the npm scripts to point to the right locations. GitHub Pages will be enabled on branch `master` to keep examples [like this](http://cssinjs.github.io/examples/perdido/) working?

**Comment by kof** [comment]
Wait a sec, lets sync this with @HenriBeck there is also another option to make all examples in sandbox format, so that they are in the repo and loadable with codesandbox here is an example https://github.com/cssinjs/egghead/tree/master/from-sass-to-cssinjs/default-values

**Comment by kof** [comment]
In any case we need to decide if we really want them in the monorepo or not.

**Comment by HenriBeck** [comment]
@kof, Yes codesandbox would be the preferred way IMO. It allows to directly fork them and start using them which is very nice.

I think they can be in the monorepo in a `examples/` directory. The question is if codesandbox supports this

**Comment by kof** [comment]
yes and also embed on a site

**Comment by kof** [comment]
for codesandbox it's just a directory, that monorepo package.json will need stuff that codesandbox needs

**Comment by kof** [comment]
I am sometimes wondering though how do we decide what goes into monorepo and what not, one way to think about it is monorepo packages should have/need the same setup, so that we can have same management from the root, but examples turns out different, so I am not sure any more

**Comment by m4theushw** [comment]
@kof [react-admin](https://github.com/marmelab/react-admin) follows the same logic. They have a monorepo and also some examples.

I think I'll move examples to an `examples/` directory and embed them in the docs using codesandbox. This way we can remove the compiled files. Each example will have its own package.json.

**Comment by kof** [comment]
@m4theushw you mean in jss repository? `jss/examples`

**Comment by m4theushw** [comment]
@kof Yes, like @HenriBeck suggested

**Comment by kof** [comment]
alright, let's go with this

**Comment by kof** [comment]
released in 10.1.0
