### ISSUE TITLE
[rule-value-function|camel-case] Cannot read property 'fallbacks' of undefined (or null)

### ISSUE THREAD

**Issue by akomm** [cssinjs/jss#1159]
Exactly the same issue, as [this](https://github.com/cssinjs/jss/issues/489), except the null / undefined value comes from a rule-function:

```js
{
  font: () => null
}
```
**update: added sandbox**
Version: 10.0.0-alpha.22
Sandbox: https://codesandbox.io/s/hungry-glitter-pb2p2

**Comment by HenriBeck** [comment]
What version are you using and could you please create a codesandbox where this issue exists?

**Comment by akomm** [comment]
Version: alpha.22
Sandbox: https://codesandbox.io/s/hungry-glitter-pb2p2

Must be a bug introduced in alpha, because in the sandbox switching ONLY jss to latest 9.x.x fixed the issue. :)

**Comment by akomm** [comment]
This works:
```js
jss.createStyleSheet({
  a: undefined,
});
```
This works:
```js
jss.createStyleSheet({
  a: {
    fontSize: () => undefined,
  },
});
```

This is does not work:
```js
jss.createStyleSheet({
  a: () => undefined,
});
```

PluginRegistry checks rule.style for null in onProcessRule and passes it to onProcessStyle, however onProcessStyle runs through plugins and does not check whether the result is null/undefined. So when the function plugin returns null or undefined, it then passes it to camelCase. So bug is not in the plugin, but jss PluginRegistry. Will provide PR soon.
