### ISSUE TITLE
createUseStyles not working with react-hot-loader

### ISSUE THREAD

**Issue by raminious** [cssinjs/jss#1162]
__Expected behavior:__
Basically, it should work when hot-loader is enabled

__Describe the bug:__
What I figured out is it doesn't attach styles after hot-reloading.

__Codesandbox link:__ 
It's working with sandbox. I'm using an ejected create-react-app

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.22
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS
Feel free to add any additional versions which you may think are relevant to the bug.  

I know it's an alpha version, just tried to report to get it fixed in the next version. also, I'll try to provide a repo later if you can't reproduce that.

PS: I lovvvvve this new API !!!!!

https://streamable.com/5t62s

**Comment by HenriBeck** [comment]
Your `createUseStyles` should not be in your component! It should be outside for us to do some optimizations.

This could also be the reason why the code is not working.

**Comment by kof** [comment]
Fix https://github.com/cssinjs/jss/pull/1237 is going to be released with 10.0.1, feel free to try out
