### ISSUE TITLE
React-jss prepend 'bound' to classNamePrefix of component styles

### ISSUE THREAD

**Issue by friconelli** [cssinjs/jss#1163]
In Dev mode, on a stateless component,
react-jss prepend the string 'bound' on the classNamePrefix of component
![Schermata 2019-07-16 alle 12 53 09](https://user-images.githubusercontent.com/22241497/61289268-3f133800-a7c9-11e9-9dd8-e9608cddc63b.png)
![Schermata 2019-07-16 alle 12 57 02](https://user-images.githubusercontent.com/22241497/61289269-3f133800-a7c9-11e9-88c4-292042d8932a.png)

**Comment by HenriBeck** [comment]
We are using the components `displayName` as a prefix in `react-jss`. Either check your `displayName` for function components.

You can also customize your class names, see [here](https://cssinjs.org/react-jss?v=v10.0.0-alpha.22#class-name-generator-options).

**Comment by HenriBeck** [comment]
As an example: https://codesandbox.io/s/dazzling-cdn-k2vpt

Note that the `createGenerateId` is very simple and probably should not be used for production code.
