### ISSUE TITLE
[jss-vendor-prefixer]  prefixes not applying to animation properties

### ISSUE THREAD

**Issue by fuleinist** [cssinjs/jss#1167]
**Expected behavior:**
prefixes apply properly to animation properties in runtime

**Describe the bug:**
prefixes not applying to animation properties

**Codesandbox link:**
TBD today

**Versions:**
Jss: ^9.8.7
jss-vendor-prefixer: ^8.0.1
Browser: IE11, IOS Safari
OS: Windows, Safari

**Comment by AleshaOleg** [comment]
@fuleinist hey, thanks for a report. Just checked with [caniuse](https://caniuse.com/#search=animation). We're not doing this because `animation` property doesn't need to be prefixed.

**Comment by fuleinist** [comment]
@AleshaOleg Thanks for your response. 

My issue was with animation-[properties] in styles described in https://www.w3schools.com/css/css3_animations.asp.

My case is to build a animation makestyle using '@keyframes [animationName]' & '$[animationName]' reference in css classes.

It is working using standard properties in Chrome, Firefox & Andriod Webview.

However it's confirmed not working in IE11 and Safari in iOS.

Some SO discussion were notices per https://stackoverflow.com/questions/15772889/animation-delay-in-ios-not-working-correctly.

I tried to add @-prefix-keyframes manually with [prefix]AnimationName, while the $ reference will only work once to populate the jss style name.

Will build a codesandbox to populate this issue soon.

**Comment by fuleinist** [comment]
Issue was identified as react ploy fill rather than jss and animation. Apologies for the wrong report.

Closing this issue now.
