### ISSUE TITLE
Dynamic styles can't works in a class components in react-jss

### ISSUE THREAD

**Issue by tcetin** [cssinjs/jss#1169]
At the explanation of https://cssinjs.org/react-jss?v=v10.0.0-alpha.24#dynamic-values you applied just functional component for dynamic style.

Since React doesnt allow hooks function in the class it is getting this error:
`Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)`

So I think it  should be possible using the Dynamic styles  in a react class component.

**Comment by kof** [comment]
I don't understand, are you saying docs are wrong or there is a bug?

**Comment by tcetin** [comment]
@kof There is a bug. It couldn't possible to use with in "React Class".

**Comment by kof** [comment]
You are not supposed to use a hooks interface with class components, this is a limitation of react, not this interface. You can still use withStyles HOC.

**Comment by tcetin** [comment]
@kof Thanks but  I think it could be works also in a class. `withStyles` couldn't provide dynamic styles.

**Comment by esr360** [comment]
@kof, @tcetin is asking how to use the "dynamic values" feature when using class components; he isn't asking how to use hooks inside class components.

@tcetin, is this what you're looking for? https://cssinjs.org/react-jss/?v=v10.0.0-alpha.9#dynamic-values - it looks like you should be able to use dynamic values with `withStyles` in more or less the same way as `useStyles`.

**Comment by tcetin** [comment]
@esr360 Thanks,I will try `withStyles` for dynamic values.
