### ISSUE TITLE
[react-jss] Styles not updating with custom context theme change?

### ISSUE THREAD

**Issue by JamesDonnelly** [cssinjs/jss#1173]
I'm sure I'm missing something really obvious, but I've had a read through the docs and can't find anything which states how styles can be updated following a theme context change.

I have two themes, `light` (`{ background: 'white' }`) and `dark` (`{ background: 'black' }`).

My application entry point is set up similar to this:

```
import { ThemeContext, themes } from 'contexts/theme';
import { createTheming } from 'react-jss';

const { ThemeProvider } = createTheming(ThemeContext);

function myApp() {
  const [theme, setTheme] = useState({
      ...themes.light,
      change: handleThemeChange
    });

  function handleThemeChange(theme) {
    setTheme({
      ...theme,
      change: handleThemeChange
    });
  }

  return (
    <ThemeProvider theme={theme}>
      <SomeNestedComponent />
      <SomeOtherNestedComponent />
    </ThemeProvider>
  )
}
```

Within `SomeNestedComponent` I have a button which updates the theme as follows:

```
import { ThemeContext, themes } from 'contexts/theme';

function SomeNestedComponent() {
  const theme = useContext(ThemeContext);

  return (
    <button onClick={() => theme.change(themes.dark)}>
      Dark Mode
    </button>
  );
}
```

In `SomeOtherNestedComponent` I'm logging the value of `useContext(ThemeContext)` to the console in my browser and can see that the component has received the updated theme, however none of the applied styles are changed.

For reference, I'm using `createUseStyles` to apply the theme. My `SomeOtherNestedComponent` looks like this:

```
import { ThemeContext } from 'contexts/theme';
import { createUseStyles } from 'react-jss'

function SomeOtherNestedComponent() {
  const theme = useContext(ThemeContext);

  const classes = createUseStyles((theme => ({
    example: {
      background: theme.background
    }
  })(theme))();

  console.log(theme);

  return (
    <p className={classes.example}>Hello, world!</p>
  )
}
```

On first load the component logs my light theme (`{ background: 'white' }`) and after clicking the theme change button in `SomeNestedComponent` it logs the dark theme (`{ background: 'black' }`), however the `<p>` element remains unchanged.

What am I missing?

**Comment by JamesDonnelly** [comment]
Turns out I was using `createUseStyles` completely incorrectly!

**Comment by vnoitkumar** [comment]
> Turns out I was using `createUseStyles` completely incorrectly!

@JamesDonnelly What was the solution!
