### ISSUE TITLE
Features section in docs improvement 

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/jss#1174]
Mentioning the docs (React integration section):
> Function values and rules are updated automatically with props as an argument.

With new hooks approach you can pass whatever you want to `useStyles()` and I'm indeed passing both props and state values I need.

This was before not possible, real world example:
```
const useStyles = createUseStyles(theme => ({
    root: {
        position: 'relative', // needed to center the spinner
        minWidth: ({ minWidth }) => minWidth,
        minHeight: ({ minHeight }) => minHeight,
        display: 'grid',
        alignContent: 'start',
        alignItems: ({ data }) => data === undefined ? 'start' : 'end', // when data is not loaded we want title and description on top, spinner in the center; otherwise align everything (bar, chart, pie...) to end
    },
}));

const Chart = ({ query, minWidth, minHeight = 450 }) => {
    const [data, setData] = useState(undefined);
    const classes = useStyles({ data, minWidth, minHeight });
    ... using the classes.root class on rendered element
};
```

I suggest adding this to docs:
> Function values and rules are updated automatically with props, state values, or both, as an argument.

**Comment by kof** [comment]
a6e48b3071cc51dc49dbff1a08b5127985914840
