### ISSUE TITLE
Expose `props` argument to `createUseStyles` function

### ISSUE THREAD

**Issue by esr360** [cssinjs/jss#1175]
Currently I can use `createUseStyles` to expose a theme to my styles, which may exist like so:

```jsx
import { createUseStyles } from 'react-jss';

const styles = (theme) => ({
  root: (props) => ({
    fontFamily: theme.fontFamily,
    fontSize: props.fizz ? '18px' : '12px',
    marginBottom: '1em'
  }),
  
  heading: (props) => ({
    color: props.fizz ? theme.colorPrimary : 'blue'
  }),

  content: (props) => ({
    display: props.isActive ? 'block' : 'none'
  })
});

const useStyles = createUseStyles(styles);
```

I find it a bit cumbersome having to expose `props` manually to each element (i.e `root`, `heading`, `content`). I feel as though a better experience would be:

```jsx
import { createUseStyles } from 'react-jss';

const styles = ({ props, theme }) => ({
  root: {
    fontFamily: theme.fontFamily,
    fontSize: props.fizz ? '18px' : '12px',
    marginBottom: '1em'
  },
  
  heading: {
    color: props.fizz ? theme.colorPrimary : 'blue'
  },

  content: {
    display: props.isActive ? 'block' : 'none'
  }
});

const useStyles = createUseStyles(styles);
```

What do you think? Thanks.

**Comment by kof** [comment]
Thanks, we thought about it, this makes caching hard.

**Comment by esr360** [comment]
Hi @kof, so is this suggestion something that could  be implemented, it's just difficult to do so? Could/should this issue be left open in case it's something that can be figured out in the future?

**Comment by HenriBeck** [comment]
@esr360 This will most likely never be implemented as this removes all of our possibilities with sharing the styles between multiple components

**Comment by esr360** [comment]
Thanks @HenriBeck I appreciate the answer.

**Comment by kof** [comment]
Another way to achieve what you want is btw. to pass the theme together with the props or whatever data you pass in: 

```js
const theme = useTheme()
const classes = useStyles({...props, theme})`
```

**Comment by SevenZark** [comment]
> Another way to achieve what you want is btw. to pass the theme together with the props or whatever data you pass in:
> 
> ```js
> const theme = useTheme()
> const classes = useStyles({...props, theme})`
> 
> // then later in styles
> {
>   button: (props) => ({
>     color: props.fizz ? props.theme.colorPrimary : 'blue'
>   })
> }
> ```

Have you actually gotten this to work in practice? It does not work for me. For me, when using ThemeProvider, createUseStyles clobbers any argument passed in, replacing it with the theme object.
