### ISSUE TITLE
[react-jss] Why HOC API gets deprecated in future versions?

### ISSUE THREAD

**Issue by rtivital** [cssinjs/jss#1180]
[In react-jss documentation](https://cssinjs.org/react-jss/?v=v10.0.0-alpha.24) you are saying that HOC API will be deprecated in future versions. I cannot understand how this limitation will improve react-jss library. The only thing it does – forces people to use new fancy hooks. 

For new projects this is fine. But for existing this will be a disaster. For example, I have a project with around 1500 components that are using react-jss. Half of those components are using React.Component (no hooks for them). So with the deprecation of HOC API you are trying to force me to rewrite all my codebase, with half of rewrites very complex (as React.Component based components sometimes use other libraries like redux or just component state). 

Hooks are not designed to force me to rewrite entire codebase, but just to bring extra convenience in certain situations. react-jss trying to do completely opposite thing. Please consider supporting HOC API.

**Comment by kof** [comment]
This is a long term strategy, you can continue using the HOC for quite some time and all older versions are still there.

If we don't migrate we will have to support 2 different interfaces with some subtile differences. You will probably have to learn 2 interfaces. It is more work for everyone.

**Comment by kof** [comment]
Just because React team told everyone to not rewrite to hooks today and only use it for new projects doesn't mean react wants you to use HOCs, they don't. 

It would be a hard sell for them to ask everyone to rewrite, so they sell it as an option. In reality hooks is the future and noone will use HOCs in that future.

**Comment by kof** [comment]
Also noone is forcing you to rewrite here either. All previous versios will always be awailable.

**Comment by rtivital** [comment]
As I see situation – until React.Component and other class based stuff gets deprecated, it is not a good idea to forbid people to use react-jss with class based components. This will lead to one of these situations: either you will support extra version with react-jss old hoc based api (some security updates, maybe future react versions compatibility, etc.) or you will drop the support of this version entirely. 

If you continue to support older version with updates then it will be same work of supporting two different interfaces, that you've said above that you do not want to do.

If you drop support, at one point of time next react version will not be compatible with older version of react-jss. And apps that use react-jss will be stuck with older and older react version over time. Until it requies a complete rewrite.

I think in this situation the best option is to keep sync with react itself and not to go ahead with deprecations until it is really necessary.

**Comment by kof** [comment]
> it is not a good idea to forbid people to use react-jss with class based components

Who said we forbid? We say it will be deprecated at some point so we don't have to maintain it. It is additional work and friction for users. Noone is paying us to do that work and we don't have time for that.

**Comment by Jony-Y** [comment]
@kof So just to be clear, you intend of removing said API or just deprecating (not maintaining it).
The issue is legacy code that might get affected in the future. If the current API remains in perpetuity then it's fine. But removing the API might cause serious breaking changes and will stop people from upgrading to 11.

As a person who wants to stay up to date, this is a problem. Our company will not have the ability to refactor old code and we want to sure we don't break

**Comment by kof** [comment]
It can't be removed from the published packages on npm.

**Comment by kof** [comment]
In addition one can always recreate the old HOC interface using the approach described here https://reacttraining.com/blog/using-hooks-in-classes/

**Comment by Jony-Y** [comment]
@kof 
> It can't be removed from the published packages on npm.

That is irrelevant.
The major question is in v11 will I have the HOC API or with the HOC be removed from react-jss which will mean that all apps using the HOC API will break or in other words that you will by definition will not support class components (which react have said that they will not remove that API)

**Comment by rtivital** [comment]
> In addition one can always recreate the old HOC interface 
@kof why not then recreate this directly in react-jss package? This will save people a lot of time.

**Comment by HenriBeck** [comment]
We will not remove the HOC Api in version 11. We will most likely drop support for React without hooks and internally transition the HOC to our hooks API, so we don't need to maintain two versions.

We have not yet decided when we will completely remove the HOC Api

**Comment by danlourenco** [comment]
I find the documentation incredibly lacking for such a significant API change. One shouldn't just link to another blog post on the internet. What if it gets taken down? What if the examples therein are too abstract for those not as familiar with hooks? How about showing a real-life example on the docs about how one would accomplish this?
