### ISSUE TITLE
10.0.0-alpha.24 broken in IE 11 due to Number.MIN_SAFE_INTEGER

### ISSUE THREAD

**Issue by tcrognon** [cssinjs/jss#1183]
__Expected behavior:__
I expect to be able to use react-jss in IE 11 without having to bring my own polyfill for Number.MIN_SAFE_INTEGER.

__Describe the bug:__
This line https://github.com/cssinjs/jss/blob/b946ddebe10f1a073ef2a7431c20c287ba9b02db/packages/react-jss/src/utils/getSheetIndex.js#L16 makes options.index `NaN` in IE 11 because Number.MIN_SAFE_INTEGER is `undefined` and `undefined++ // === NaN`

This line https://github.com/cssinjs/jss/blob/d53092cbb81e2d829f9c9d27bfd42e6ce38c9eb2/packages/jss/src/Jss.js#L84 doesn't catch the problem and doesn't fall back to global sheets index because `typeof NaN // === "number"`

The result of this is that if you create multiple stylesheets with `createUseStyles`, only the first one is ever actually added because they all have the same `NaN` index.

__Codesandbox link:__ 
codesandbox.io doesn't work in IE 11, but I at least provide a minimal reproducible project that you could copy and try out locally: https://codesandbox.io/s/loving-boyd-3iiz0

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.24
 - Browser: IE 11 (or any browser that doesn't have Number.MIN_SAFE_INTEGER)
 - OS: Windows

**Comment by kof** [comment]
Snap, we should have at least documented this. I didn't check and thought it's in the spec for a long time. On the other hand I wonder why babel doesn't polyfill it automatically.

**Comment by tcrognon** [comment]
I don't use babel so I could be wrong, but it looks like `@babel/env` https://github.com/cssinjs/jss/blob/7f1fe82b1f244c61cc8f2d2a070ddcc0afd8378e/rollup.config.js#L40 is needs `useBuiltIns` explicitly set in order to include polyfills. https://babeljs.io/docs/en/babel-preset-env#usebuiltins
