### ISSUE TITLE
[jss-autoreset][jss-initial] Plugins to reset styles.

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#119]
Inspired by [autoreset](https://www.npmjs.com/package/postcss-autoreset) and [initial](https://github.com/maximkoretskiy/postcss-initial) we need to port those to jss, because its an awesome thing and basically a first time true encapsulation for css.

Additionally we can:
- [ ] feature test if "all: initial" property is supported
- [ ] if supported add it to every rule 
- [ ] if not generate a style sheet with a rule which resets everything and add every selector to it
- [ ] support "all: inherit" by doing nothing?

**Comment by kof** [comment]
updated description, thanks for input @ai

**Comment by maximkoretskiy** [comment]
I'd like to implement it

**Comment by kof** [comment]
Yay, lets discuss the details, maybe in gitter? https://github.com/jsstyles/jss

**Comment by kof** [comment]
Now we have [jss-isolate](https://github.com/cssinjs/jss-isolate) which allows isolate rules from inheritance and to globally define default values.

The next stage is to think how to allow isolation from global selectors.

**Comment by maximkoretskiy** [comment]
We can reset all props like [postcss-initial](https://github.com/maximkoretskiy/postcss-initial) does.

**Comment by kof** [comment]
Yep, however the question is if we can do that at runtime without loading the static json ...

**Comment by ahmad2smile** [comment]
was this ever implemented ?

**Comment by kof** [comment]
Not exactly as described here, but yes! https://github.com/cssinjs/jss-isolate

**Comment by ahmad2smile** [comment]
Thanks, Appreciate the quick update.
