### ISSUE TITLE
TypeError: Date.now is not a function on import jss from 'jss'

### ISSUE THREAD

**Issue by malmil** [cssinjs/jss#1191]
__Expected behavior:__
Expect my tests to run without failing

__Describe the bug:__
I get the error "TypeError: Date.now is not a function" when running Jest tests with ts on
import jss from 'jss';
I've tried to remove all dates from the solution, but the error persist. 

_Note: Replacing Date.now() with new Date() in functions.js and index.js in jss-preset-default solves the error, but I don't know if that's a desired solution._

__Versions (please complete the following information):__
using:
```
"@types/jss": "9.5.8",
"jss": "9.8.7",
"jss-preset-default": "4.5.0",
"typescript": "3.6.3"
```

Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
What browser are you using? Date.now is supported natively even in IE9. Either something is very wrong with your bundling or you should not be using this project if you need to support browsers like IE8 and similar.
