### ISSUE TITLE
:last-child::before combined with other selectors doesn't seem to work

### ISSUE THREAD

**Issue by TatiTheFreaK** [cssinjs/jss#1192]
__Expected behavior:__
Show this little triangle on the side of the div by using :last-child::before
![image](https://user-images.githubusercontent.com/11199668/64783074-3460ef00-d53d-11e9-9415-2947c03839bd.png)

__Describe the bug:__
![image](https://user-images.githubusercontent.com/11199668/64784351-50b25b00-d540-11e9-8a83-3e11d0ea8c94.png)
:last-child::before combined with other selectors doesn't seem to work, I've tried many variations but I wasn't able to make the desired effect appear. Only :last-child works, but I can't use ::before

__Codesandbox link:__ 
https://codesandbox.io/s/charming-snow-q78vu

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.24
 - Browser [e.g. chrome, safari]: Firefox
 - OS [e.g. Windows, macOS]: Windows
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
Can you please reduce the example to pure JSS without external libaries?

**Comment by HenriBeck** [comment]
You are missing a `content` attribute for `before` to work: https://codesandbox.io/s/distracted-http-xcgyy
