### ISSUE TITLE
CSS Properties TypeScript definitions 

### ISSUE THREAD

**Issue by janhartmann** [cssinjs/jss#1199]
__Expected behavior:__
Being able to auto-complete on CSS properties using the `createUseStyles`.

__Describe the bug:__
Not being able to do the auto-complete of CSS properties because of a `// @ts-ignore` block of the `Style` definition of: https://github.com/cssinjs/jss/blob/master/packages/jss/src/index.d.ts#L3

If I remove the `// @ts-ignore` block, I get an error from TypeScript about a circular dependency: `Type alias 'Style' circularly references itself.`

I am not sure wether or not to remove the circularly `Style` reference, or rework it to be:

```ts
export type Style = css.StandardProperties<string | number | (() => string | number)> & {
  [key: string]: { [key: string]: Style } | string | number
}
```

__Codesandbox link:__ 
https://codesandbox.io/s/magical-blackwell-04it0

__Versions (please complete the following information):__
 - jss:
 - Browser [e.g. chrome, safari]:
 - OS [e.g. Windows, macOS]:
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
released in 10.0.3
