### ISSUE TITLE
[react-jss] createGenerateId breaks with webpack production build with SSR

### ISSUE THREAD

**Issue by kevinludwig** [cssinjs/jss#1200]
I am using SSR, and so I have two different webpack files, one for the server bundle and one for the client bundle. When I run in production mode, the minify process changes the CSS class names such that the server generated name no longer matches the client generated name. In particular, the JSS names created by createGenerateId make ids of the form
MyComponentName-myCssClassName-0-0-1. In looking at the source code "MyComponentName" comes from react component displayName. The in the prod build this value is just "t" for all classes so my css is something like "t-root-0-0-1" which is _sort of_ fine, I guess, except that I might get namespace collisions, but that's not my particular problem here. The problem is that the server build ends up with class names like "e-root-0-0-1" and the client bundle generates ids like "t-root-0-0-1".

This was with webpack 4.x and react-jss:10.0.0. This did not happen with react-jss 8.x but I believe the way ids are generated has changed substantially between these versions so that makes some sense to me. 

I don't claim to know how or why the prefix changes in minified builds (between client or server build) but I was able to get around this issue by configuring the minifier to not mangle class names and not mangle function names. Maybe this is expected, and users are expected to configure the minifier this way, but it wasn't super obvious to me. My example was identical (in terms of code) to the react-jss SSR example (but obviously, using webpack as well).

I would understand if you don't want to fix this since its a weird interaction between react-jss and webpack but it might be useful to call this out in the docs somewhere (the workaround is perfectly acceptable to me).

**Comment by HenriBeck** [comment]
Seems weird, yes. So for some reason, your server bundled code mangles the function name to `e` but the client uses `t` which then causes the mismatch when hydrating.

I guess one solution for your problem would be to override your class name generator which ignores the classNamePrefix on a stylesheet. Then you could still have class/function name mangling turned on.

```js
/**
 * Returns a function which generates unique class names based on counters.
 * When new generator function is created, rule counter is reseted.
 * We need to reset the rule counter for SSR for each request.
 */
const createGenerateId: CreateGenerateId = (options = {}) => {
  let ruleCounter = 0

  return (rule: Rule, sheet?: StyleSheet): string => {
    ruleCounter += 1

    if (ruleCounter > maxRules) {
      warning(false, `[JSS] You might have a memory leak. Rule counter is at ${ruleCounter}.`)
    }

    let jssId = ''
    let prefix = ''

    if (sheet) {
      // Don't use the classNamePrefix in production
      // if (sheet.options.classNamePrefix) {
      //  prefix = sheet.options.classNamePrefix
      // }

      if (sheet.options.jss.id != null) {
        jssId = String(sheet.options.jss.id)
      }
    }

    if (options.minify) {
      // Using "c" because a number can't be the first char in a class name.
      return `${prefix || 'c'}${jssId}${ruleCounter}`
    }

    return `${prefix + rule.key}-${jssId ? `-${jssId}` : ''}-${ruleCounter}`
  }
}
```

**Comment by bungu** [comment]
I have the same issue. It seems that `options.minify` in `createGenerateId` is always falsy: https://github.com/cssinjs/jss/blob/master/packages/jss/src/utils/createGenerateId.js#L43

I tried to set it true in `create` method from package `jss`, but it did not work:

```javascript
import { create } from 'jss';
import preset from 'jss-preset-default';

const jss = create({ minify: true }).setup(preset());
```

**Comment by bungu** [comment]
I ended up with custom `createGenerateId` function that is not using prefix for minified names and checks for minifying by `process.end.NODE_ENV === 'production'` instead of `options.minify`:

```typescript
export const MAX_RULES = 1e10;
export const MODULE_ID = 'o3';
export function createGenerateId(_options = {}) {
	let ruleCounter = 0;
	return function generateId(rule, sheet) {
		ruleCounter += 1;

		if (ruleCounter > MAX_RULES && process.env.NODE_ENV !== 'production') {
			// tslint:disable-next-line
			console.error(
				'[JSS] You might have a memory leak. Rule counter is at ' + ruleCounter + '.',
			);
		}

		let jssId = '';
		let prefix = '';

		if (sheet) {
			if (sheet.options.classNamePrefix) {
				prefix = sheet.options.classNamePrefix;
			}

			if (sheet.options.jss.id) {
				jssId = String(sheet.options.jss.id);
			}
		}

		if (process.env.NODE_ENV === 'production') {
			return '' + MODULE_ID + jssId + ruleCounter;
		}

		return prefix + rule.key + '-' + MODULE_ID + (jssId ? '-' + jssId : '') + '-' + ruleCounter;
	};
}
```

**Comment by HenriBeck** [comment]
Yes, we are aware. The only way for overriding the `createGenerateId` in `react-jss` is currently using the `JssProvider` `createGenerateId` itself.

**Comment by j3ko** [comment]
This is still a problem with the latest release (10.4.0).  I can't seem to find an acceptable workaround for this.  

Everything works fine in dev mode locally but when building and running in production mode w/ ssr the client side classnames just do not match the server generated ones.

This is a basic example of the problem from the next.js examples library:
https://codesandbox.io/s/pjrvj

the code is based off running:
`yarn create next-app --example with-react-jss with-react-jss-app`

if you download the code and run:
`yarn build`
`yarn start`

you can see how the css classnames are broken.  eg. the server generates: `test_component_TestComponent-container-0-2-3` while the corresponding client side classname is: `r-container-0-2-3`

**Comment by kof** [comment]
If this is the same as #1328, I am closing it as duplicate, but feel free to reopen if they are different
