### ISSUE TITLE
Media query using dynamic styling function does not work for a delayed component

### ISSUE THREAD

**Issue by angrybacon** [cssinjs/jss#1201]
__Expected behavior:__

I need to apply custom styling from a JSON object, contained in a "configuration" object. Read from the styles of my components. Some of which must be applied for smaller viewports.

__Describe the bug:__

The 5 elements are supposed to have custom styling (pink background) in smaller viewports. Works for the first 4. Does not for the 5th which is rendered with a delay of 1 second.

__Codesandbox link:__ 

https://codesandbox.io/s/green-dust-g8xzc

__Versions:__

![image](https://user-images.githubusercontent.com/5608624/65966885-00545c00-e461-11e9-9249-db1c7f444eb1.png)

**Comment by kof** [comment]
Seems like a bug, can you please reduce the example to the absolute minimum so we have easier time narrowing down the problem?

**Comment by angrybacon** [comment]
@kof Trimmed most I could. Will try to remove the JSON-to-JS part, hopefully today :-)

**Comment by angrybacon** [comment]
@kof Sandbox updated :-) https://codesandbox.io/s/green-dust-g8xzc

**Comment by kof** [comment]
For some reason codesandbox doesn't allow me to save anything right now, probably it's broken. I released v10.0.1, this issue might be fixed there

**Comment by kof** [comment]
Please reopen if issue is still there

**Comment by angrybacon** [comment]
@kof Looks sandboxes were lost since then and I can't retrieve them. Will reopen if I still face the issue thanks!
