### ISSUE TITLE
[react-jss] Not working HMR with RHL (v10.0.0+)

### ISSUE THREAD

**Issue by BEGEMOT9I** [cssinjs/jss#1202]
__Expected behavior:__
HMR must working after styles changing.

__Describe the bug:__
An application with `HMR` `(react-hot-loader, react-jss-hmr)` does not work in place with new version of `react-jss`:
![Снимок экрана 2019-10-01 в 17 35 32](https://user-images.githubusercontent.com/11138075/65972115-06066d80-e472-11e9-9f78-0362bbde1fa5.png)
In this case, it seems, the problem is that the HOC `withStyles` returns a `JssContextSubscriber` instead of a HOC-function.

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.25
 - react-jss: 10.0.0-alpha.27
 - Browser [e.g. chrome, safari]: all
 - OS [e.g. Windows, macOS]: all
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
Fix https://github.com/cssinjs/jss/pull/1237 is going to be released with 10.0.1, feel free to try out

**Comment by BEGEMOT9I** [comment]
@kof #1237 does not fix this problem, since it is typical only for the HOC. However, the #1230 just allows you to use the HOC to the fullest without a plugin. Or are you going to rewrite the HOC so that it uses the hook functionality?

**Comment by kof** [comment]
Alright, thanks for testing. Reopening then. Yeah I think we should refactor HOC to use hooks interface.
