### ISSUE TITLE
Vendor prefixer doesn't work

### ISSUE THREAD

**Issue by vtereshyn** [cssinjs/jss#1205]
I use `jss-preset-default` for using jss plugins. But I noticed that none of the classes has vendor prefixes. 

example:
https://prnt.sc/pece2x
https://prnt.sc/pecdp0
https://prnt.sc/pecdua

How do I init JSS:

```
import jss from 'jss';
import preset from 'jss-preset-default';

jss.setup(preset());
```

Maybe its because I use separate package for global styles and then I use these packages in a monorepo. But other plugins do work well.

**Comment by kof** [comment]
prefixes addded when needed specifically for the browser. Does your browser need a prefix for properties you are testing? I suppsoe not.
