### ISSUE TITLE
create({id: {minify: true}}) does not compile in typescript.

### ISSUE THREAD

**Issue by bhupinderbola** [cssinjs/jss#1210]
__Expected behavior:__
create({id: {minify: true}}) should not fail in typescript

__Describe the bug:__
jss/src/index.d.ts is not in sync with jss/src/types/jss.js.
In index.d.ts, JssOptions  is missing id?: CreateGenerateIdOptions

__Versions (please complete the following information):__
 - jss: 10.0.0
 - OS [e.g. Windows, macOS]: Windows

![jss-issue](https://user-images.githubusercontent.com/2565028/66256220-9934f100-e759-11e9-84e6-6ca2377e2cf2.PNG)

**Comment by kof** [comment]
released in 10.0.3
