### ISSUE TITLE
[react-jss] wrong displayName of components given by withStyles HOC

### ISSUE THREAD

**Issue by dannystyleart** [cssinjs/jss#1211]
__Expected behavior:__
Our jest snapshots ( using enzyme ) should not failing due components's displayName change.

__Describe the bug:__
Migrated from 8.6.1 to 10.0.0 our jest snapshots are failing. We have set up the theming context as the docs and the code is working fine in browser but the components's displayName have changed from Jss($componentName) to JssContextSubscriber.

![Failing tests](https://snipboard.io/n4G1o9.jpg)

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.
Here is our case in a nutshell: https://codesandbox.io/s/react-jss-withstyles-hoc-displayname-fails-04eob

__Versions (please complete the following information):__
 - jss: 10.0.0
- React: 16.10.2
- enzyme: 3.10.0
- enzyme-adapter-react-16: 1.15.0
- enzyme-to-json: 3.4.2
- jest: 24.9.0
 - OS [Linux deepin/Window 10/ Mac Os Catalina & Mojave]

**Comment by HenriBeck** [comment]
You will just need to update your snapshot tests. This change is expected when upgrading to version 10 of react jss

**Comment by dannystyleart** [comment]
@HenriBeck So complete loss of component naming is expected?

I have looked up how the withStyles HOC is doing name creation and it does kinda same as before.

My problem is that when snapshots are created from a component that contains jss styled components, all children has the same name.

If I'm changing a children in the markup and leaving the props the snapshot will no differ and not catches the change.

**Comment by HenriBeck** [comment]
No, the `Jss(FormControl)` should be the child of `JssContextSubscriber` now as you can also see that in the diff

**Comment by dannystyleart** [comment]
@HenriBeck It is.
We use the original HOC approach that is exported by default, our components are defined like in the codesandbox link above.

We found that the main reason that causes this is in the [withStyles.js:181](https://github.com/cssinjs/jss/blob/b1602dcd6a5514e29c899f23d11cb6346a1cf6aa/packages/react-jss/src/withStyles.js#L181)

`
    JssContextSubscriber.displayName = 'JssContextSubscriber'
`

Changing this line to fallowing, would solve the problem:
`
    JssContextSubscriber.displayName = `Jss(${displayName})`
`
