### ISSUE TITLE
[react-jss] Styles are not injected in DOM on first render

### ISSUE THREAD

**Issue by sntptrck** [cssinjs/jss#1212]
__Expected behavior:__
Styles are injected in DOM on first render;

__Describe the bug:__
Styles are not injected in DOM on first render;
Its causes some problems with components which calcultes inline styles on first render (like antd table) and transitions runs on init;
problem reproduced in development and productions modes;

__Codesandbox link:__ 
https://codesandbox.io/s/strange-chatterjee-z9qgo?fontsize=14 (just include debugger in sandbox from one of previous issues)

 - react-jss: 10.0.0 (also alpha 27)
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows

screenshots 1 and 2 with debugger after useStyles, scr. 3 with no debugger (styles injected with delay)

![1](https://user-images.githubusercontent.com/25454834/66663808-09f57500-ec54-11e9-9861-ad29d313d974.PNG)
![2](https://user-images.githubusercontent.com/25454834/66663811-0bbf3880-ec54-11e9-807f-9dc94bd8e9b8.PNG)
![3](https://user-images.githubusercontent.com/25454834/66663817-0e219280-ec54-11e9-9c6f-ed66f4a74564.PNG)

**Comment by HenriBeck** [comment]
You are just not seeing the styles itself. They are there, for this you can inspect the styled element itself and you should see all styles listed correctly.

**Comment by lukasjoho** [comment]
@sntptrck I am running into the same problem and threw everything at it.
My jss styles will only be injected after second render. Did you come up with a solution?

**Comment by sntptrck** [comment]
> @sntptrck I am running into the same problem and threw everything at it.
> My jss styles will only be injected after second render. Did you come up with a solution? 

No, I just use inline Jsx style instead of JSS

**Comment by benistary** [comment]
I have same problem

**Comment by kof** [comment]
I don't see the fact that styles are not rendered.  If you think this issue was resolved incorrectly please reopen a new one with an example and how you validate the outcome.

**Comment by SimpleCreations** [comment]
I reported a similar issue here some time ago: [#1324](https://github.com/cssinjs/jss/issues/1324)
It is essentially the same and has a reproducible example.

**Comment by kof** [comment]
Lets discuss in #1324
