### ISSUE TITLE
Function rule unable to reference local non-function rule

### ISSUE THREAD

**Issue by ryancogswell** [cssinjs/jss#1213]
__Expected behavior:__
A function rule (or a rule containing function values) should be able to reference a local rule in the same style sheet (when using the jss-nested and jss-plugin-rule-value-function plugins via Material-UI) even if the referenced rule is not a function rule.

__Describe the bug:__
When referencing non-function local rules ("otherRule" in the warning below) from a function rule, I see the warning below and the rule reference does not work.
> Warning: [JSS] Could not find the referenced rule "otherRule" in "makeStyles". 

__Codesandbox link:__ 
Reproduction: https://codesandbox.io/s/jss-bug-reproduction-huv3l
Workaround (makes "otherRule" a function rule): https://codesandbox.io/s/jss-bug-reproduction-cmp1t

__Versions (please complete the following information):__
 - jss: v10.0.0 (via Material-UI 4.5.0)
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by ryancogswell** [comment]
Based on comment from @oliviertassinari, it looks like this is an issue with how Material-UI is using JSS rather than a bug in JSS itself.

**Comment by oliviertassinari** [comment]
@ryancogswell For the context, Material-UI creates two style sheet, one for the static styles, one for the dynamic ones, this isolation is the source of a couple of open issues in the Material-UI repository.
