### ISSUE TITLE
The doc isn't clear about theming and hooks

### ISSUE THREAD

**Issue by oallouch** [cssinjs/jss#1219]
Hi,

I might have missed something, but, according the documentation, passing the theme to useStyles seems mandatory. It looks like we have to use useTheme, but having a default theme seems to work very fine, useStyle seems to look for it in the context.

Thx,
Olivier (from Paris)

**Comment by Chrazy** [comment]
Just wanted to chime in here. I also did like the documentation states and used `useTheme` and passed it to `useStyles` and then noticed that it's not really needed. So either the documentation needs to be updated or it's not working as intended.

As it is now the only use for `useTheme` is if you need to access a property from the theme in your component.

**Comment by oallouch** [comment]
Any news on this one ?

**Comment by kof** [comment]
Hopefully, the docs fix made it clear now
