### ISSUE TITLE
How to inject classes with hooks API?

### ISSUE THREAD

**Issue by DreadBoy** [cssinjs/jss#1221]
__Expected behavior:__
With HOC API, I could use `classes` prop to override styles. Building on example in https://github.com/cssinjs/jss/blob/master/docs/react-jss-hoc.md#basic I could write 
```ts
<StyledButton classes={{myLabel: classes.overrideMyLabel}}>Submit</StyledButton>
```

__Describe the bug:__
Not really a bug but question. Is it possible to do this with hooks API? If so, how?

__Versions (please complete the following information):__
 - react-jss@10.0.0
-  jss@10.0.0

**Comment by HenriBeck** [comment]
Of course, you can overwrite classes, you have to do it manually. 

See [this codesandbox](https://codesandbox.io/s/elastic-jones-mxbrv) as an example. The benefit of using hooks is that you can decide if you want to override the classes completely or maybe allow adding custom classes for some of the elements.
