### ISSUE TITLE
Asterisk selector has escaped output

### ISSUE THREAD

**Issue by shash7** [cssinjs/jss#1226]
__Expected behavior:__
```
* {
color: 'red';
}
```

__Describe the bug:__
When I use the asterisk selector and output the stylesheet via toString, the output class name is escaped:
```
const styles = {
			" * ": {
				color: "red"
			}
		};
		var obj = jss.createStyleSheet(styles);
		console.log(obj);
		var style = obj.toString();
```

Output:
```
.\ \*\ -0-0-1 {
  color: "red";
}
```

__Versions:__
 - jss:10.0.0

**Comment by shash7** [comment]
Hmm, actually all selectors have string escape issues when I use the toString() method. Anyone knows a workaround?

**Comment by HenriBeck** [comment]
I think what you are looking here for is the [jss-plugin-global](https://cssinjs.org/jss-plugin-global?v=v10.0.0).
