### ISSUE TITLE
Styles compiled properly but error is thrown anyway /shrug

### ISSUE THREAD

**Issue by heyitsbash** [cssinjs/jss#1229]
__Expected behavior:__
No error in the console.

__Describe the bug:__
This line:
`right: (props) => _.get(props.customStyles, 'rangeDatepickerContainerBefore.right', 30),`
Throws the following error:
`Warning: Rule is not linked. Missing sheet option "link: true".`
While fallback option is set to 30, jss still properly converts it to 30px.
So behavior is expected, but the error is still thrown.

When changing the line to look like this:
`right: (props) => _.get(props.customStyles, 'rangeDatepickerContainerBefore.right', '30px'),`
The error is gone.

The screenshot shows that 30 was properly converted to 30px
![image](https://user-images.githubusercontent.com/50231226/68470565-5c16bf80-022d-11ea-9352-6c4d765f59e8.png)

__Versions (please complete the following information):__
 - jss: "react-jss": "^8.6.1"
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: windows

**Comment by HenriBeck** [comment]
Please provide a reproducible example on [codesandbox.io](https://codesandbox.io/)

The error that you are experiencing has nothing to with the conversion of numbers to strings.
