### ISSUE TITLE
Media query rules disappear on page transitions

### ISSUE THREAD

**Issue by cibulka** [cssinjs/jss#1231]
__Expected behavior:__
Rules in media queries should always be applied, no matter if the page is rendered in server, client or otherwise. 

__Describe the bug:__
I'm using `react-jss` with Next.js. I see that my media query rules are not always applied. They are applied correctly on first render (SSR), but on most of the client side renderings they disappear. 

__Codesandbox link:__ 
Is it okay that I reproduced the issue by [GitHub repo](https://github.com/cibulka/next-jss-bug)? It seems as an easier route for everybody as I needed to demonstrate the page transitions (and disappearing of media query rules). You can clone it, install it with `npm run install` and make it run with `npm run dev`. 

__Versions (please complete the following information):__
 - jss: 10.0.0
 - Browser [e.g. chrome, safari]: Chrome 78
 - OS [e.g. Windows, macOS]: macOS
- Next: 9.1.3
- React: 16.11.0

[EDIT]

[This](https://github.com/cssinjs/jss/pull/1144) seem to be related, but the issue is not fixed for me even on the latest alpha (which I use on the real project, not at the reproduction above).

Also, I setup JSS to make it work with Next.js by [those instructions](https://github.com/zeit/next.js/tree/master/examples/with-react-jss).

**Comment by kof** [comment]
Hi, thanks for the report. It would help a lot if you could reproduce the behavior with less dependencies, ideally with just react-jss.

I assume at least 2 situations are possible: 
- Media queries you wrote don't actually render as expected at all
- After hydration media rules are not rendered, because the component is not rendered which is supposed to also make those rules render. This can be a failure in your logic with conditional component rendering.

**Comment by cibulka** [comment]
Thanks for a quick response! I think my issue is somewhat related to https://github.com/cssinjs/jss/issues/1201, https://github.com/cssinjs/jss/issues/1118 and https://github.com/cssinjs/jss/issues/1025, but I have not been able to reproduce it in an isolated environment reliably. 

My media query setup works if I use plain objects (or at least not nested functions), so I will stick to that for the time being, as I'm in a bit of a hurry. After I'll have more free time on my hands, I will try to reproduce the situation and reopen the issue, ok?

Thanks!

**Comment by lawrence-witt** [comment]
I'm running up against this issue at the moment. I've [created a repo](https://github.com/lawrence-witt/next-jss-query-demo) which I think quite succinctly demonstrates the problem.

Essentially, it seems that when two different Next.js pages share the same component, any Media Queries contained within function rules for that component will be lost when the page transition happens. Refreshing the page will then load in the correct styles. This does not happen when the queries are not in function rules.

This is causing quite a few headaches at the moment as I'm trying to generate queries dynamically based on `theme` and `props`. I cannot see a good way to do this either inside `createUseStyles`, or in the component itself and then passing complete props, without using a function rule.

Awesome library by the way, I love the JSS and `useStyles` syntax and would be sad to have to start pulling stuff out.

**Comment by kof** [comment]
@lawrence-witt  This issue was closed because the original author figured out the source of the issue is one of those posted above. If this is not  the case for you, you may want to create a separate issue.
