### ISSUE TITLE
Does react-jss createUseStyles memoize data?

### ISSUE THREAD

**Issue by BenF-Lumedic** [cssinjs/jss#1232]
I wasn't able to find an answer to this in the documentation. I found some references to memoization in the code, but it wasn't obvious to me exactly where and when it is applied.

In basic usage (and with `useTheme()`) will createUseStyles memoize all or part of the classes it builds for a component? Or will it recreate them on every re-render?

```
const useStyles = createUsestyles((theme) => ({
  root: {
    color: theme.color,
  },
}))

const Component = function Component() {
  const classes = useStyles(useTheme())

  return (<div className={classes.root}>content</div>)
}
```

**Comment by kof** [comment]
What's the problem you are trying to solve? I assume you are worried if JSS rerenders styles on each render? In that case it doesn't.

**Comment by BenF-Lumedic** [comment]
Yes, that's what I was wondering - no particular issue I'm trying to solve. Thanks for the quick reply!
