### ISSUE TITLE
[jss-isolate] Reseting vendor-suffixed selectors not working due to resulting css rule being invalid 

### ISSUE THREAD

**Issue by shamakhov** [cssinjs/jss#1240]
__Expected behavior:__
Resulting reset rules are valid

__Describe the bug:__
I am using Material UI widgets with vendor selectors like `::-ms-input-placeholder`, `-moz-placeholder`, etc, and applying isolate plugin results in this errors in Chrome:
<details> 
  <summary>
Warning: [JSS] Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule</summary> <pre>'.MuiPaper-root,
.MuiPaper-rounded,
.MuiPaper-elevation0,
.MuiPaper-elevation1,
.MuiPaper-elevation2,
.MuiPaper-elevation3,
.MuiPaper-elevation4,
.MuiPaper-elevation5,
.MuiPaper-elevation6,
.MuiPaper-elevation7,
.MuiPaper-elevation8,
.MuiPaper-elevation9,
.MuiPaper-elevation10,
.MuiPaper-elevation11,
.MuiPaper-elevation12,
.MuiPaper-elevation13,
.MuiPaper-elevation14,
.MuiPaper-elevation15,
.MuiPaper-elevation16,
.MuiPaper-elevation17,
.MuiPaper-elevation18,
.MuiPaper-elevation19,
.MuiPaper-elevation20,
.MuiPaper-elevation21,
.MuiPaper-elevation22,
.MuiPaper-elevation23,
.MuiPaper-elevation24,
.MuiTable-root,
.MuiTable-root caption,
.MuiTable-stickyHeader,
.MuiTableHead-root,
.MuiTableRow-root,
.MuiTableRow-root.Mui-selected,
.MuiTableRow-root.MuiTableRow-hover:hover,
.Mui-selected,
.MuiTableRow-hover,
.MuiTableRow-head,
.MuiTableRow-footer,
.MuiTableCell-root,
.MuiTableCell-head,
.MuiTableCell-body,
.MuiTableCell-footer,
.MuiTableCell-sizeSmall,
.MuiTableCell-sizeSmall:last-child,
.MuiTableCell-sizeSmall.MuiTableCell-paddingCheckbox,
.MuiTableCell-sizeSmall.MuiTableCell-paddingCheckbox:last-child,
.MuiTableCell-sizeSmall.MuiTableCell-paddingCheckbox > *,
.MuiTableCell-paddingCheckbox,
.MuiTableCell-paddingCheckbox:last-child,
.MuiTableCell-paddingNone,
.MuiTableCell-paddingNone:last-child,
.MuiTableCell-alignLeft,
.MuiTableCell-alignCenter,
.MuiTableCell-alignRight,
.MuiTableCell-alignJustify,
.MuiTableCell-stickyHeader,
.MuiAutocomplete-root,
.MuiAutocomplete-root:hover .MuiAutocomplete-clearIndicatorDirty, .MuiAutocomplete-root.Mui-focused .MuiAutocomplete-clearIndicatorDirty,
.Mui-focused,
.MuiAutocomplete-tag,
.MuiAutocomplete-tagSizeSmall,
.MuiAutocomplete-inputRoot,
.MuiAutocomplete-inputRoot .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiInput-root"],
.MuiAutocomplete-inputRoot[class*="MuiInput-root"] .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiInput-root"] .MuiAutocomplete-input:first-child,
.MuiAutocomplete-inputRoot[class*="MuiInput-root"][class*="MuiInput-marginDense"],
.MuiAutocomplete-inputRoot[class*="MuiInput-root"][class*="MuiInput-marginDense"] .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiInput-root"][class*="MuiInput-marginDense"] .MuiAutocomplete-input:first-child,
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"],
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"] .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"] .MuiAutocomplete-input:first-child,
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"] .MuiAutocomplete-endAdornment,
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"][class*="MuiOutlinedInput-marginDense"],
.MuiAutocomplete-inputRoot[class*="MuiOutlinedInput-root"][class*="MuiOutlinedInput-marginDense"] .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiFilledInput-root"],
.MuiAutocomplete-inputRoot[class*="MuiFilledInput-root"] .MuiAutocomplete-input,
.MuiAutocomplete-inputRoot[class*="MuiFilledInput-root"] .MuiAutocomplete-endAdornment,
.MuiAutocomplete-inputRoot[class*="MuiFilledInput-root"][class*="MuiFilledInput-marginDense"],
.MuiAutocomplete-inputRoot[class*="MuiFilledInput-root"][class*="MuiFilledInput-marginDense"] .MuiAutocomplete-input,
.MuiAutocomplete-input,
.MuiAutocomplete-inputFocused,
.MuiAutocomplete-endAdornment,
.MuiAutocomplete-clearIndicator,
.MuiAutocomplete-clearIndicatorDirty,
.MuiAutocomplete-popupIndicator,
.MuiAutocomplete-popupIndicatorOpen,
.MuiAutocomplete-popper,
.MuiAutocomplete-popperDisablePortal,
.MuiAutocomplete-paper,
.MuiAutocomplete-paper > ul,
.MuiAutocomplete-listbox,
.MuiAutocomplete-loading,
.MuiAutocomplete-noOptions,
.MuiAutocomplete-option,
.MuiAutocomplete-option[aria-selected="true"],
.MuiAutocomplete-option[data-focus="true"],
.MuiAutocomplete-option[aria-disabled="true"],
.MuiAutocomplete-option:active,
.MuiAutocomplete-groupLabel,
.MuiAutocomplete-groupUl,
.MuiTextField-root,
.MuiFormControl-root,
.MuiFormControl-marginNormal,
.MuiFormControl-marginDense,
.MuiFormControl-fullWidth,
.MuiInputLabel-root,
.Mui-disabled,
.Mui-error,
.Mui-required,
.MuiInputLabel-asterisk,
.MuiInputLabel-formControl,
.MuiInputLabel-marginDense,
.MuiInputLabel-shrink,
.MuiInputLabel-animated,
.MuiInputLabel-filled,
.MuiInputLabel-filled.MuiInputLabel-marginDense,
.MuiInputLabel-filled.MuiInputLabel-shrink,
.MuiInputLabel-filled.MuiInputLabel-shrink.MuiInputLabel-marginDense,
.MuiInputLabel-outlined,
.MuiInputLabel-outlined.MuiInputLabel-marginDense,
.MuiInputLabel-outlined.MuiInputLabel-shrink,
.MuiFormLabel-root,
.MuiFormLabel-root.Mui-focused,
.MuiFormLabel-root.Mui-disabled,
.MuiFormLabel-root.Mui-error,
.MuiFormLabel-colorSecondary,
.MuiFormLabel-colorSecondary.Mui-focused,
.MuiFormLabel-filled,
.MuiFormLabel-asterisk,
.MuiFormLabel-asterisk.Mui-error,
.MuiInput-root,
.MuiInput-formControl,
label + .MuiInput-formControl,
.MuiInput-colorSecondary,
.MuiInput-colorSecondary.MuiInput-underline:after,
.MuiInput-underline,
.MuiInput-underline:after,
.MuiInput-underline.Mui-focused:after,
.MuiInput-underline.Mui-error:after,
.MuiInput-underline:before,
.MuiInput-underline:hover:not(.Mui-disabled):before,
.MuiInput-underline.Mui-disabled:before,
.MuiInput-marginDense,
.MuiInput-multiline,
.MuiInput-fullWidth,
.MuiInput-input,
.MuiInput-inputMarginDense,
.MuiInput-inputMultiline,
.MuiInput-inputTypeSearch,
.MuiInputBase-root,
.MuiInputBase-root.Mui-disabled,
.MuiInputBase-formControl,
.MuiInputBase-adornedStart,
.MuiInputBase-adornedEnd,
.MuiInputBase-marginDense,
.MuiInputBase-multiline,
.MuiInputBase-multiline.MuiInputBase-marginDense,
.MuiInputBase-colorSecondary,
.MuiInputBase-fullWidth,
.MuiInputBase-input,
.MuiInputBase-input::-webkit-input-placeholder,
.MuiInputBase-input::-moz-placeholder,
.MuiInputBase-input:-ms-input-placeholder,
.MuiInputBase-input::-ms-input-placeholder,
.MuiInputBase-input:focus,
.MuiInputBase-input:invalid,
.MuiInputBase-input::-webkit-search-decoration,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input::-webkit-input-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input::-moz-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input:-ms-input-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input::-ms-input-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input:focus::-webkit-input-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input:focus::-moz-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input:focus:-ms-input-placeholder,
label[data-shrink=false] + .MuiInputBase-formControl .MuiInputBase-input:focus::-ms-input-placeholder,
.MuiInputBase-input.Mui-disabled,
.MuiInputBase-input:-webkit-autofill,
.MuiInputBase-inputMarginDense,
.MuiInputBase-inputMultiline,
.MuiInputBase-inputTypeSearch,
.MuiInputBase-inputAdornedStart,
.MuiInputBase-inputAdornedEnd,
.MuiInputBase-inputHiddenLabel {
  top: auto;
  clip: auto;
  left: auto;
  clear: none;
  color: initial;
  float: none;
  order: 0;
  right: auto;
  width: auto;
  bottom: auto;
  cursor: auto;
  filter: none;
  height: auto;
  quotes: initial;
  resize: none;
  widows: 2;
  azimuth: center;
  content: normal;
  display: inline;
  hyphens: manual;
  opacity: 1.0;
  orphans: 2;
  z-index: auto;
  ime-mode: auto;
  overflow: visible;
  position: static;
  tab-size: 8;
  clip-path: none;
  flex-grow: 0;
  flex-wrap: nowrap;
  font-size: medium;
  isolation: auto;
  mask-type: luminance;
  max-width: none;
  min-width: 0;
  transform: none;
  word-wrap: normal;
  align-self: auto;
  block-size: auto;
  box-shadow: none;
  box-sizing: content-box;
  column-gap: normal;
  flex-basis: auto;
  font-style: normal;
  line-break: auto;
  margin-top: 0;
  max-height: none;
  min-height: 0;
  object-fit: fill;
  overflow-x: visible;
  overflow-y: visible;
  ruby-align: space-around;
  ruby-merge: separate;
  text-align: initial;
  visibility: visible;
  word-break: normal;
  align-items: stretch;
  break-after: auto;
  caret-color: auto;
  column-fill: balance;
  column-span: none;
  empty-cells: show;
  flex-shrink: 1;
  font-family: initial;
  font-weight: normal;
  inline-size: auto;
  line-height: normal;
  margin-left: 0;
  padding-top: 0;
  perspective: none;
  text-indent: 0;
  text-shadow: none;
  white-space: normal;
  will-change: auto;
  break-before: auto;
  break-inside: auto;
  caption-side: top;
  column-count: auto;
  column-width: auto;
  font-kerning: auto;
  font-stretch: normal;
  font-variant: normal;
  grid-row-end: auto;
  grid-row-gap: 0;
  margin-right: 0;
  padding-left: 0;
  shape-margin: 0;
  table-layout: auto;
  text-justify: auto;
  touch-action: auto;
  word-spacing: normal;
  align-content: stretch;
  counter-reset: none;
  margin-bottom: 0;
  outline-color: initial;
  outline-style: none;
  outline-width: medium;
  overflow-wrap: normal;
  padding-right: 0;
  shape-outside: none;
  text-overflow: clip;
  transform-box: border-box ;
  -ms-appearance: none;
  animation-name: none;
  border-spacing: 0;
  flex-direction: row;
  font-synthesis: weight style;
  grid-auto-flow: row;
  grid-auto-rows: auto;
  grid-row-start: auto;
  letter-spacing: normal;
  min-block-size: 0;
  mix-blend-mode: normal;
  outline-offset: 0;
  padding-bottom: 0;
  pointer-events: auto;
  text-rendering: auto;
  text-transform: none;
  vertical-align: baseline;
  -moz-appearance: none;
  animation-delay: 0s;
  background-clip: border-box;
  background-size: auto auto;
  border-collapse: separate;
  grid-column-end: auto;
  grid-column-gap: 0;
  image-rendering: auto;
  justify-content: flex-start;
  list-style-type: disc;
  min-inline-size: 0;
  object-position: 50% 50%;
  scroll-behavior: auto;
  text-align-last: auto;
  transform-style: flat;
  background-color: transparent;
  background-image: none;
  border-top-color: currentcolor;
  border-top-style: none;
  border-top-width: medium;
  font-size-adjust: none;
  image-resolution: 1dppx;
  list-style-image: none;
  margin-block-end: 0;
  offset-block-end: auto;
  page-break-after: auto;
  scroll-snap-type: none;
  text-orientation: mixed;
  transform-origin: 50% 50% 0;
  transition-delay: 0s;
  -webkit-mask-clip: border-box;
  -webkit-mask-mode: match-source;
  -webkit-mask-size: auto;
  background-origin: padding-box;
  background-repeat: repeat;
  border-left-color: currentcolor;
  border-left-style: none;
  border-left-width: medium;
  column-rule-color: currentcolor;
  column-rule-style: none;
  column-rule-width: medium;
  counter-increment: none;
  font-variant-caps: normal;
  grid-auto-columns: auto;
  grid-column-start: auto;
  image-orientation: 0deg;
  offset-inline-end: auto;
  padding-block-end: 0;
  page-break-before: auto;
  page-break-inside: auto;
  -webkit-appearance: none;
  -webkit-margin-end: 0;
  -webkit-mask-image: none;
  animation-duration: 0s;
  border-image-slice: 100%;
  border-image-width: 1;
  border-right-color: currentcolor;
  border-right-style: none;
  border-right-width: medium;
  grid-template-rows: none;
  margin-block-start: 0;
  offset-block-start: auto;
  perspective-origin: 50% 50%;
  -webkit-mask-origin: border-box;
  -webkit-mask-repeat: repeat;
  -webkit-padding-end: 0;
  animation-direction: normal;
  animation-fill-mode: none;
  backface-visibility: visible;
  background-position: 0% 0%;
  border-bottom-color: currentcolor;
  border-bottom-style: none;
  border-bottom-width: medium;
  border-image-outset: 0s;
  border-image-repeat: stretch;
  border-image-source: none;
  grid-template-areas: none;
  list-style-position: outside;
  offset-inline-start: auto;
  padding-block-start: 0;
  transition-duration: 0s;
  transition-property: all;
  -webkit-margin-start: 0;
  -webkit-writing-mode: horizontal-tb;
  animation-play-state: running;
  font-variant-numeric: normal;
  scroll-snap-points-x: none;
  scroll-snap-points-y: none;
  text-combine-upright: none;
  text-decoration-line: none;
  -webkit-mask-position: 0% 0%;
  -webkit-padding-start: 0;
  -webkit-ruby-position: over;
  background-attachment: scroll;
  background-blend-mode: normal;
  font-feature-settings: normal;
  font-variant-position: normal;
  grid-template-columns: none;
  shape-image-threshold: 0.0;
  text-decoration-color: currentcolor;
  text-decoration-style: solid;
  -webkit-mask-composite: add;
  border-block-end-color: currentcolor;
  border-block-end-style: none;
  border-block-end-width: medium;
  border-top-left-radius: 0;
  font-language-override: normal;
  font-variant-ligatures: normal;
  scroll-snap-coordinate: none;
  border-top-right-radius: 0;
  font-variant-alternates: normal;
  font-variant-east-asian: normal;
  scroll-snap-destination: 0px 0px;
  text-underline-position: auto;
  -webkit-border-end-color: currentcolor;
  -webkit-border-end-style: none;
  -webkit-border-end-width: medium;
  border-block-start-color: currentcolor;
  border-block-start-style: none;
  border-block-start-width: medium;
  animation-iteration-count: 1;
  animation-timing-function: ease;
  border-bottom-left-radius: 0;
  -webkit-border-start-color: currentcolor;
  -webkit-border-start-style: none;
  -webkit-border-start-width: medium;
  border-bottom-right-radius: 0;
  transition-timing-function: ease;
  -webkit-text-emphasis-color: currentcolor;
  -webkit-text-emphasis-style: none;
  -webkit-box-decoration-break: slice;
  -webkit-text-emphasis-position: over right;
}'.</pre>
 </details> 

__Versions (please complete the following information):__
 - jss: 10.0.0
 - Browser [e.g. chrome, safari]: any
 - OS [e.g. Windows, macOS]: Windows 10

**Comment by kof** [comment]
See some soughts on this https://github.com/cssinjs/jss/pull/1241#issuecomment-565728142

**Comment by tlenex** [comment]
Any progress on this? Seems like isolation plugin is not working due to this issue. It won't add any isolation styles even in production build - without a warning.

**Comment by xyleen** [comment]
@kof 
In #1241 you've written:
> Another way is to avoid logging when something is wrong by checking after error was thrown if selector has a vendor prefix that doesn't fit current runtime and NOT log a warrning in this particular case.

Here's an extract of selectors that are giving me this warning in Chrome:
```
.Dropdown-input-0-2-19::-ms-expand {
.Input-input-0-2-211:-moz-placeholder {
```
etc. 

What about trying to do something similar as in #1241 – if an Error is caught in the `insertRule` method
https://github.com/cssinjs/jss/blob/d9cca31ad2d058aa0108fa6ec48fe872b0e7e886/packages/jss/src/DomRenderer.js#L272-L287
we could try to use the `isSelectorValid` from #1241 on modified selectors with the vendor suffix removed, e.g. (very-quick mashup, just to illustrate)
```js
// [...]
} catch (err) {
    const selectorWithoutVendor = rule.split(':')[0];
    let shouldHideWarning = false;
    if (process.env.NODE_ENV !== "production" && isSelectorValid(selectorWithoutVendor)) {
        shouldHideWarning = true;
    }
    warning(false, `[JSS] ${err.message}`)
}
```

What do you think about that? Do you have any other suggestions? I'd be happy to try to prepare a PR if we can agree on how to tackle that issue 😉


Background – I've done some upgrading of npm packages in my project  – one of the targets was to have a clear console with no warnings and errors (that didn't go so well due to this issue 😂)

**Comment by kof** [comment]
@xyleen just so I understand, this is what you wrote in your jss styles `.Dropdown-input-0-2-19::-ms-expand`? So you vendor prefixed  with -ms prefix but you run it in chrome, right?

**Comment by xyleen** [comment]
One of the examples:
```js
const styles = theme => ({
  ...theme,
  wrapper: {
    position: 'relative',
    '& select::-ms-expand': {
      display: 'none'
    },
  },
});
```

There are some rules defined in an analogous way in that 'theme' object:
```js
{
  input: {
    '&:-moz-placeholder': {
      color: colors.placeholderGrey,
    },
    '&::-ms-expand': {
      display: 'none',
    },
  }
}
```

**Comment by kof** [comment]
yeah, you are basically writing a bad selector yourself in this case, it's not generated by jss vendor prefixes. 

They idea with vendor prefixed is that you don't write vendor prefixed specific selectors yourself, but get them auto generated ... I am not sure if for this particular case vendor prefixed will add the right prefix automatically ... but one option would be to look into  https://github.com/cssinjs/css-vendor and use it to  only add a correct prefixer

**Comment by xyleen** [comment]
I'll have a look at `css-vendor` and I'll see if my use-case can be handled by that tool. Thanks for your reply and your time :)

**Comment by kof** [comment]
Please reopen if still valid
