### ISSUE TITLE
Question: potential security issue with nonce usage (Content Security Policy)

### ISSUE THREAD

**Issue by stkao05** [cssinjs/jss#1243]
The security promise provided by the nonce is based on the pre-condition that - the attackers didn't know the value of this secret and they also could not guess it.

However, from the "Setting up Content Security Policy with JSS` doc page, it seems that we need to expose the nonce value in HTML for JSS to pick it up.

```html
<head>
    <meta property="csp-nonce" content="{{ styleNonce }}">
</head>
```

This seems to break the above-mentioned pre-condition that the attacker should not be able to access the secret; the nonce could be now accessed by a malicious script and could potentially create an inline style with the same nonce?

**Comment by kof** [comment]
If your attacker has a full access to your document, you are already hacked, nonce won't help there,  it's for different kind of attacks.

**Comment by kof** [comment]
@stkao05 just curios, is doist using JSS? If yes please ping me on twitter (https://twitter.com/oleg008) I would like to chat abou something.
