### ISSUE TITLE
Yandex crawler doesn't see some styles

### ISSUE THREAD

**Issue by perevezencev** [cssinjs/jss#1245]
__Describe the bug:__
I have a problem with Yandex Webvisor. JSS injects some styles to CSSOM. Because of this yandex bot can't render page properly. The similar [issue](https://github.com/styled-components/styled-components/issues/2038) had in `styled-components` 

__Versions (please complete the following information):__
 - jss: 10.0.0
 - Browser [e.g. chrome, safari]: no data
 - OS [e.g. Windows, macOS]: no data

**Comment by kof** [comment]
I don't have a solution here, I think yandex should learn how to render pages, the API is an official w3c API, if they don't support it it sucks.

You can avoid it by not using the insertRule API. I don't know if you use react-jss, if you do, don't use function values.

If you use jss directly, don't use option link: true and als no function values.

**Comment by kof** [comment]
I just realized the problem actually can only exist if you want to rely on client-side crowling. If you have SSR it should actually work, right?

**Comment by perevezencev** [comment]
I don’t have SSR, I’ll try to turn on SSR mode to test your hypothesis
