### ISSUE TITLE
'& + &' do not work in react-jss@10.0.1

### ISSUE THREAD

**Issue by jian263994241** [cssinjs/jss#1253]
```
{
 root: {
  '& + &': {
    marginLeft:  props => 10   //not work
   }
 }
}
```

```
{
 root: {
  '& + &': {
    marginLeft:  10   //work!
   }
 }
}
```

use  react-jss 10.0.1

__Versions (please complete the following information):__
 - jss: 10.0.1
 - Browser [e.g. chrome, safari]:
 - OS [e.g. Windows, macOS]:
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
Please provide codesandbox for faster verification

**Comment by jian263994241** [comment]
> Please provide codesandbox for faster verification

https://codesandbox.io/s/goofy-visvesvaraya-ye3k9?fontsize=14&hidenavigation=1&theme=dark

**Comment by thalelinh** [comment]
@jian263994241 your codesandbox have a small mistake, where you've written `marginTop: () => "blue"`, instead of `background: () => "blue"`.

I've tried to reproduce your problem changing `marginTop` to `background`, as well as replacing both to use `marginTop`, but the styling worked .-.

**Comment by jian263994241** [comment]
Thanks, It is my mistake.
