### ISSUE TITLE
[react-jss] getSheetOptions argument options replaced by default 

### ISSUE THREAD

**Issue by yeliex** [cssinjs/jss#1256]
__Expected behavior:__
`createStyleSheet ` could get options.generateId correctly

__Describe the bug:__
https://github.com/cssinjs/jss/blob/17f54cfbe63009838c48fd2a12751302698ef200/packages/react-jss/src/utils/sheets.js#L34-L57 input options replace default options correctly

__Versions (please complete the following information):__
 - jss: 10.0.3

**Comment by yeliex** [comment]
@kof

**Comment by kof** [comment]
Can you please explain in a greater detail? Ideally use the structure in the template and evtl a codesandbox example of the bug that reproduces the problem.

**Comment by yeliex** [comment]
@kof 
as type defined https://github.com/cssinjs/jss/blob/17f54cfbe63009838c48fd2a12751302698ef200/packages/jss/src/index.d.ts#L132-L140
`withStyles` method can accept an option with prop `generateId`

but in https://github.com/cssinjs/jss/blob/17f54cfbe63009838c48fd2a12751302698ef200/packages/react-jss/src/utils/sheets.js#L49-L57 , the property would be replaced by `options.context.generateId `, and the passed one would be ignored

For example, 
```js
import injectSheet from 'react-jss'
const StyledComponent = injectSheet(styles, {
    generateId: (rule) => rule.key
});
```
the passed generateId would be ignored

**Comment by yeliex** [comment]
```js
return { 
     ...options.sheetOptions, 
     index: options.index, 
     meta, 
     classNamePrefix, 
     link, 
     generateId: options.context.generateId // undefined
   }  // => {generateId: undefined}
```

**Comment by kof** [comment]
Understood, cc @HenriBeck

**Comment by yeliex** [comment]
The similar code snip in the old version:

https://github.com/cssinjs/jss/blob/v9.7.0/src/Jss.js#L84-L90

**Comment by kof** [comment]
gonna be released with the next version, subscribe to releases!

**Comment by yeliex** [comment]
@kof Can you publish a new release, we want to update `jss` in our component library but now processed because of the issue.
