### ISSUE TITLE
@global styles Typescript definitions are broken

### ISSUE THREAD

**Issue by vtereshyn** [cssinjs/jss#1259]
Before I updated to `10.0.3` all worked fine.

But after the update I receive Typescript error during the build:

```
error TS2345: Argument of type '{ '@global': { html: { fontSize: string; }; body: { margin: number; padding: number; overscrollBehavior: string; overflowScrolling: string; font: { size: string; family: string; weight: string; }; }; 'h1, h2, h3, h4, h5, h6': { ...; }; ... 8 more ...; a: { ...; }; }; }' is not assignable to parameter of type 'Partial<Record<"@global", string | JssStyleP<JssStyleP<JssStyleP<JssStyleP<JssStyleP<JssStyleP<JssStyleP<void>>>>>>>>>'.
```

Also, 
```
'*': {
	boxSizing: 'border-box'
}
```
doesn't work.

Let me know if you need anything else from my side.
Thank you in advance.

**Comment by HenriBeck** [comment]
Same issue as #1258
For more information regarding that see the https://github.com/cssinjs/jss/issues/1258#issuecomment-573231475 and https://github.com/cssinjs/jss/issues/1258#issuecomment-573425236
