### ISSUE TITLE
Adding multiply font families ends up with WARNING

### ISSUE THREAD

**Issue by IsmayilAghazada** [cssinjs/jss#1267]
I'm using the latest version of React Styleguidist.
When I upgrade version of React Styleguidist I faced with font-face problem of Styled component.And I couldn't use multiply font families.In console there is following warning:

<img width="1680" alt="Screen Shot 2020-01-24 at 10 57 11 AM" src="https://user-images.githubusercontent.com/48431337/73064385-8be37400-3eba-11ea-9bd3-0bc4e7ea5d37.png">

Btw when I add only one font family to the array it works well.I mean:
'@font-face': [
        {
            fontFamily: 'RubikAZ Regular',
            fontStyle: 'normal',
            fontWeight: '400',
            src: 'url(./static/fonts/RubikAZ-Regular.woff2) format("woff2")'
        },
    ],

**Comment by m4theushw** [comment]
Could you create a codesandbox showing the problem?

I [tried](https://codesandbox.io/s/modest-poitras-6exzc) but I couldn't see the warning.
