### ISSUE TITLE
Can't use number's arrays in some props like margin or padding

### ISSUE THREAD

**Issue by mzygmunt** [cssinjs/jss#1269]
__Expected behavior:__
I can use number's arrays in props like margin or padding.

__Describe the bug:__
I can't use number's arrays in some props like margin or padding after last update of types. Types of  padding or margin are not allowed to use arrays.

__Versions (please complete the following information):__
 - jss: 10.0.3
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: macOS

**Comment by kof** [comment]
fixed in 10.0.4
