### ISSUE TITLE
Would it be feasible for useStyles to accept a function that returns a class object?

### ISSUE THREAD

**Issue by awdyson** [cssinjs/jss#1272]
Not sure about the performance implications, but I keep running into situations where writing this...
```
const useStyles = createUseStyles((theme) => (props) => {
  // some logic involving props (and theme)
  return {
    root: {...},
    child: {...},
  };
});
```
feels a lot cleaner than writing this...
```
const useStyles = createUseStyles((theme) => ({
  root: () => {
    // some logic involving props (and theme)
    return {...};
  },
  child: () => {
    // some logic involving props (and theme)
    return {...};
  }
}));
```

Or maybe there's a way to write something similar that I just haven't noticed in the docs? I know I could write some helper functions, but part of what I love about JSS is the readability of these hooks. Anyway, thanks for the good work :)

**Comment by kof** [comment]
It would take a much better example that illustrates the problem you want to solve.
