### ISSUE TITLE
React-JSS styles aren't injected on componentDidMount in class components

### ISSUE THREAD

**Issue by sabotag** [cssinjs/jss#1278]
Hi, I have some question, all history of debug and reproduce you can see in other repository [https://github.com/KingSora/OverlayScrollbars/issues/182](https://github.com/KingSora/OverlayScrollbars/issues/182)

__Expected behavior:__
React on componentDidMount for class Component inject styles before `componentDidMount`

__Describe the bug:__
now I have trouble with lib that calculate content size for custom scroll without styles on `componentDidMount`

__Codesandbox link:__ 
not work correctly - [class Component](https://codesandbox.io/s/sweet-edison-nvpb4)
work correctly - [hook Component](https://codesandbox.io/s/lucid-keldysh-sfmqx)

__Versions (please complete the following information):__
 - jss: latest
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: macOS

Thank you!

**Comment by kof** [comment]
Since hooks work for you, can you use them instead of a class component? We will migrate to using hooks anyway, so it's probably not worth fixing  https://github.com/cssinjs/jss/issues/1505
