### ISSUE TITLE
Styles applied by classname doesn't get overridden in development environment

### ISSUE THREAD

**Issue by nico-w** [cssinjs/jss#1283]
__Expected behavior:__
Here `<h1 className={"headlineGreen " + classes.headlineOverride}/>` `headlineGreen` should get overriden by `classes.headlineOverride`.

__Describe the bug:__
When we're changing `headlineOverride` in the code it won't override - it will actually be the opposite - so `headlineGreen` is overriding `headlineOverride`. This only happens in development. In 10.0.0 it was working.

__Codesandbox link:__ 
https://codesandbox.io/s/solitary-pine-05mri

__Versions (please complete the following information):__
 - jss: 10.0.1 and higher
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows 10, Ubuntu

**Comment by kof** [comment]
It is overridden here 

<img width="1402" alt="Screenshot 2021-04-26 at 13 20 26" src="https://user-images.githubusercontent.com/52824/116074602-43ed6700-a692-11eb-9da7-edb822f85a4e.png">
