### ISSUE TITLE
[react-jss] classes overriding when using hook

### ISSUE THREAD

**Issue by chapa** [cssinjs/jss#1289]
Hello,

It is more a question than a feature request or bug report, but I notice a feature regression between the HOC and the hook API. Since the first one is deprecated and will be removed in v11, I would like to know why (or maybe it's juste an oversight).

When you create a component with the `withStyles()` HOC you can override classes used inside the component by passing an object in the `classes` prop, which will be merged with the object provided by `withStyles()`. That way you can create customizable components like [Material-UI does](https://material-ui.com/customization/components/#overriding-styles-with-classes).

When using `createUseStyles()`, this doesn't work because `classes` is not a prop anymore but the result of `useStyles()`.
I thought it would work if I pass the props to the hook, but that doesn't work either.

Here's a codesandbox so you can see : https://codesandbox.io/s/optimistic-shamir-qywop

If you want to have the same behavior that HOC provides while using the hook, you have to merge classes yourself :
```js
const classes = {
  ...useStyles(),
  ...props.classes
};
```

So here's my questions : is it a normal behavior ? Is there a reason why `useStyles({ classes })` doesn't override the given classes like `withStyles()` does ?

Thank you

**Comment by kof** [comment]
Duplicate https://github.com/cssinjs/jss/issues/1276
