### ISSUE TITLE
JssProvider ignores generateId prop when id prop is also set

### ISSUE THREAD

**Issue by felthy** [cssinjs/jss#1297]
__Expected behavior:__
To work with multiple React trees, we need to pass a `generateId` prop [as documented](https://cssinjs.org/react-jss/?v=v10.0.0-alpha.9#multi-tree-setup). But to get proper minification, we also need to pass the `id` prop due to how the `minify` variable is initialized here: https://github.com/cssinjs/jss/blob/b36ef074e69aef21dc764a54f572d7ced76041bc/packages/react-jss/src/utils/sheets.js#L35-L38

Given the code below, I would expect my `generateId` function to be used to generate classnames.

```
const id = {
  minify: true
}
const generateId = createGenerateId(id)

ReactDOM.render(
  <JssProvider id={id} generateId={generateId}>
    ...
  </JssProvider>,
  root
)
```

__Describe the bug:__

My custom `generateId` is not used, because `context.generateId` is overwritten with a newly created generator here: https://github.com/cssinjs/jss/blob/b36ef074e69aef21dc764a54f572d7ced76041bc/packages/react-jss/src/JssProvider.js#L79-L81

`prevContext` above is initialized from `initialContext` (an empty object), so this if clause is always true when an `id` prop is present.

Furthermore, `createGenerateId` here is the default implementation exported by `jss`, even if jss itself has been configured to use a custom `createGenerateId` function.

__Versions (please complete the following information):__
 - jss: `10.0.4`
 - Browser: Google Chrome
 - OS: macOS

**Comment by kof** [comment]
released in 10.1.0
