### ISSUE TITLE
Attribute selectors are escaped?

### ISSUE THREAD

**Issue by JohMun** [cssinjs/jss#1300]
Hello, I would like to select an element with any HTML attribute value e.g. title:

```
<div class="test" title="hey">text</div>
``` 

So I pass this to `createStyleSheet`:

```
const sheet = jss.createStyleSheet({
  'test[title=hey]': {
    color: 'blue',
  },
});

sheet.attach();
```
However, JSS escapes characters like `[`

```
 sheet.toString() // output: .test\[title\=hey\] { color: blue; }
```

So in Chome  80.0.3987.132 the rules don't match. Doubtless I am missing something here and this is the expected behaviour for some reason.

**Comment by JohMun** [comment]
If I use [jss-plugin-global](https://cssinjs.org/jss-plugin-global?v=v10.0.4) special Characters are not escaped, so this would fix my issue. However, the function `generateId` ist never invoked then, which I depend on.

**Comment by JohMun** [comment]
```
"jss": "10.0.4",
"jss-preset-default": "10.0.4",
```

**Comment by kof** [comment]
This is by design, you can use nesting and the global rules to do that. If you want have a scoped parent - use nesting.
