### ISSUE TITLE
"tiny-warning" missing from dependencies in "jss-plugin-rule-value-function@10.1.1"

### ISSUE THREAD

**Issue by dgreuel** [cssinjs/jss#1313]
When installing using yarn PnP, I get the following error:

`Module not found: Package "jss-plugin-rule-value-function@10.1.1" (via "/Users/dgreuel/Library/Caches/Yarn/v6/npm-jss-plugin-rule-value-function-10.1.1-be00dac6fc394aaddbcef5860b9eca6224d96382-integrity/node_modules/jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.esm.js") is trying to require the package "tiny-warning" (via "tiny-warning") without it being listed in its dependencies (@babel/runtime, jss, jss-plugin-rule-value-function)`

**Comment by kof** [comment]
Confirmed, please feel free to send a PR.

**Comment by oliviertassinari** [comment]
We might want to replace *tiny-warning* with a console log. It would be one less dependency, and one less potential source of issues to worry about.

**Comment by kof** [comment]
Released in v10.2.0
