### ISSUE TITLE
Including react-jss via systemjs; ReferenceError: module is not defined.

### ISSUE THREAD

**Issue by rocetspace** [cssinjs/jss#1329]
Hi! ✋

__Expected behavior:__
When connect library to the project via systemjs doesn't throw a reference error.

__Describe the bug:__
It happens because of two places in the code. If I wrap them into `try catch` - everything works great.

__dist/react-jss.js:line: 484__
```
module.exports = shouldUseNative() ? Object.assign : function (target, source) {
  	...
};
```
Pay attention on __shouldUseNative__ method (line: 484):
<img width="315" alt="Снимок экрана 2020-04-12 в 18 17 33" src="https://user-images.githubusercontent.com/9079164/79072501-f18d1280-7ce9-11ea-9ee2-8ca5f586aca9.png">

and dist/react-jss.js:line:1180
```
{
    module.exports = require('./cjs/react-is.development.js');
}
```

__GitHub link:__ 
https://github.com/rocetspace/modules
`npm i && npm start` -> localhost:9000

__Versions (please complete the following information):__
 - jss: 10.1.1
- react-jss: 10.1.1
 - Browser [e.g. chrome, safari]: all browsers
 - OS [e.g. Windows, macOS]: all OS
Feel free to add any additional versions which you may think are relevant to the bug.

<img width="702" alt="Снимок экрана 2020-04-12 в 15 14 31" src="https://user-images.githubusercontent.com/9079164/79069016-a36d1480-7cd3-11ea-889e-b8f1c04984e6.png">

**Comment by kof** [comment]
Seems like  a problem with systemjs

**Comment by khanakia** [comment]
still same issue `  <script src="https://unpkg.com/react-jss@10.10.0/dist/react-jss.js"></script>`
