### ISSUE TITLE
Troubleshooting guide for $animationName not getting converted?

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/jss#1334]
I just went back to an app I haven't touched in awhile that's on JSS 10, yet animation names are getting  conversion, and it's making my life suck 😢

Any tips on what the problem could be?  I really wish there were a troubleshooting guide for this because I vaguely remember running into this problem before but I don't remember what the deal was.

![image](https://user-images.githubusercontent.com/1448194/79810740-49a2c500-8339-11ea-85d0-f209febeb3b6.png)

```
andy@Andys-MacBook-Pro-2:clarity-gateway (master) $ yarn list | grep jss
│  ├─ jss-plugin-camel-case@^10.0.3
│  ├─ jss-plugin-default-unit@^10.0.3
│  ├─ jss-plugin-global@^10.0.3
│  ├─ jss-plugin-nested@^10.0.3
│  ├─ jss-plugin-props-sort@^10.0.3
│  ├─ jss-plugin-rule-value-function@^10.0.3
│  ├─ jss-plugin-vendor-prefixer@^10.0.3
│  ├─ jss@^10.0.3
├─ jss-expand@5.3.0
├─ jss-nested@6.0.1
├─ jss-plugin-camel-case@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-compose@10.1.1
│  ├─ jss@10.1.1
├─ jss-plugin-default-unit@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-expand@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-extend@10.1.1
│  ├─ jss@10.1.1
├─ jss-plugin-global@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-nested@10.1.1
│  ├─ jss@10.1.1
├─ jss-plugin-props-sort@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-rule-value-function@10.1.1
│  └─ jss@10.1.1
├─ jss-plugin-rule-value-observable@10.1.1
│  ├─ jss@10.1.1
├─ jss-plugin-template@10.1.1
│  ├─ jss@10.1.1
├─ jss-plugin-vendor-prefixer@10.1.1
│  └─ jss@10.1.1
├─ jss-preset-default@10.1.1
│  ├─ jss-plugin-camel-case@10.1.1
│  ├─ jss-plugin-compose@10.1.1
│  ├─ jss-plugin-default-unit@10.1.1
│  ├─ jss-plugin-expand@10.1.1
│  ├─ jss-plugin-extend@10.1.1
│  ├─ jss-plugin-global@10.1.1
│  ├─ jss-plugin-nested@10.1.1
│  ├─ jss-plugin-props-sort@10.1.1
│  ├─ jss-plugin-rule-value-function@10.1.1
│  ├─ jss-plugin-rule-value-observable@10.1.1
│  ├─ jss-plugin-template@10.1.1
│  ├─ jss-plugin-vendor-prefixer@10.1.1
│  └─ jss@10.1.1
├─ jss@10.1.1
```

**Comment by kof** [comment]
Not the best way to report a problem, I see nothing

**Comment by jedwards1211** [comment]
I was just hoping you might know of something that typically goes wrong

**Comment by jedwards1211** [comment]
```js
const styles = {
  '@keyframes spinner-rotation': {
    from: {transform: 'rotate(0deg)'},
    to: {transform: 'rotate(360deg)'},
  },
  spinner: {
    animation: [
      '$spinner-rotation linear infinite 1s',
    ],
```
For some reason this works on the server side but not the client
When I get rid of the array wrapper it works on the client too, but I don't understand why.
I'm creating jss with the default preset exactly the same way on the server and client.
If you have any tips about how I could debug this it would be a big help

**Comment by kof** [comment]
begin with taking your jss styles and putting it into a codesandbox, also check why do you have 3 different versions of jss and plugins and their corresponding changelogs and what you are actually using in the bundle `jss.version`

**Comment by jedwards1211** [comment]
Would you be open to a PR to make JSS warn if some of the plugins are an incompatible version?

**Comment by jedwards1211** [comment]
@kof sadly, after removing the mismatching plugin versions, I'm still having the problem.  As much as I love JSS, periodic issues like this are kind of the bane of my existence with it.  I really believe there have to be ways to make the dev experience better and catch problems like this with runtime checks instead of leaving the user in the dark about what went wrong.

**Comment by kof** [comment]
Problems don't came without any actions unless you don't have a lockfile. You must have upgraded versions. That being said there is always room for improvement, so if you see a chance - contribute a PR.

**Comment by jedwards1211** [comment]
which plugin is responsible for converting $ prefixed animation names?

**Comment by kof** [comment]
that's in the core and it was introduced with a major version bump

**Comment by jedwards1211** [comment]
@kof after looking through the `jss-plugin-expand` source code it seems like array values for `animation` aren't actually supported, and that's why it doesn't work on the client side?  The confusing thing is that it does work in the server-generated styles, though maybe something to do with `@material-ui/styles`' `StylesProvider` is the culprit there 😕

**Comment by kof** [comment]
client side and server side are exactly the same unless you are using different versions everywhere, which is really bad

**Comment by jedwards1211** [comment]
I confirmed in a sandbox that `SheetsRegistry` generates the same unconverted animation name, so maybe it's an issue with `@material-ui/styles`' SSR stuff.  I'll see if I can get to the bottom of it.  The way they fragmented SSR kinda sucks

**Comment by jedwards1211** [comment]
@kof I figured out where my confusion is coming from.  On the server side, `jss-plugin-vendor-prefixer` is unwrapping that `animation` array in my styles, then core replaces the animation name.  But on the client side, `jss-plugin-vendor-prefixer` leaves the array as-is, so core doesn't replace the animation name.

Should I file a bug about this?  I fully understand now that array values for `animation` don't seem intended to be supported, but even if so the fact that the server-side styles accidentally worked was confusing.  I'd be happy to make a full-blown repo to reproduce the issue.

**Comment by kof** [comment]
vendor prefixer does nothing at all on the server afaik, there is an issue somewhere for serverside static prefixing, it's a different approach that needs to be taken and haven't been implemented

I am not sure though why you say this happened now, this is since ever

**Comment by jedwards1211** [comment]
@kof I stepped through [`onProcessStyle`](https://github.com/cssinjs/jss/blob/master/packages/jss/src/PluginsRegistry.js#L73) in the debugger on server side and client side.  I observed that after applying the vendor prefixer on the server side, the array was unwrapped for whatever reason.  But on the client the array remained the same after applying the vendor prefixer.

**Comment by jedwards1211** [comment]
Here's the vendor prefixer unwrapping the array on the server side ![image](https://user-images.githubusercontent.com/1448194/79814511-09950f80-8344-11ea-96b2-31d37bc696a7.png)

**Comment by jedwards1211** [comment]
On the client side `vendor.supportedValue` returns `false` for that array
