### ISSUE TITLE
Complex and nested css selectors

### ISSUE THREAD

**Issue by just-Bri** [cssinjs/jss#1354]
__Expected behavior:__
I should be able to use nested selectors, like css/sass etc.

__Describe the bug:__
No atter what selector I use nothing seems to work.
Following normal css/sass:
```
parentClass: {
  ...styles,
  '& .childClassname': {
    ...styles
  }
}
```
Saw this suggestion on SO:
```
childClassname: {
  ...styles,
  'parentClass &': {
    ...styles
  }
}
```
__Aside__
If this kind of scss is too complex, or out of scope, for JSS please let me know. I'm trying to convert our project from scss modules to css in js, not sure if JSS is the right choice.

I initially enjoyed working with JSS, especially since it is very similar to React Native's styling and we're going to be using that for our mobile app. I'm having a lot of issues trying to apply complex/nested styles.

__Codesandbox link:__ 
This is just my scss module code. The component I'm working on is pretty complex and I can't import everything I need to codesandbox, but I wanted to let you see the scss I'm trying to convert to jss. 
https://codesandbox.io/s/elastic-bash-flcgj?file=/src/styles.css

__Versions (please complete the following information):__
 - jss: N/A
 - react-jss: "^10.2.0",
 - Browser: all of them
 - OS: N/A

**Comment by reifnotreef** [comment]
Sorry to post again on a now closed issue.
I wanted to leave an example here for future reference if anyone else is having issues getting some more complex styling to work. I cleaned up my original css because it was overly complex, then converted everything over to jss.

https://pastebin.com/VXAnyTyZ

**Comment by idarbuashvili** [comment]
Hi, couldn't find answer anywhere on this. Actually docs should have at least some kind of info on this. Can I use '&-bold', nested classNaming in JSS? 

With objects and hooks approach not sure how mapping will happen, but in SCSS this is the very first thing you see. Example: 

{
	parentClass: {
		'&-bold': {
			fontWeight: 'bold',
		}
	}
}

Thanks!

**Comment by idarbuashvili** [comment]
As I found out, BEM approach not works well with JSS. This is seems pretty understandable, but let me know what are your ideas, is there any approach where BEM and JSS could work well together? Thanks again for the efforts, great library 🙌 🙏
