### ISSUE TITLE
Want to convert SCSS flow controls like @for with CSS in JS

### ISSUE THREAD

**Issue by onlyreddy** [cssinjs/jss#1356]
__Expected behavior:__
CSS in JS should support SCSS all control flows like @for,@if and @else.

__Describe the bug:__
As a user needs to converts SCSS control flows with CSS in JS. But it's not supporting the feature.
Is there any demo available for it.

Below is my sample code:

`@for $i from 1 to 50 {

 .ag-ltr .ag-row-group-indent-#{$i} {
        padding-left: $i * 16px !important;
      }
      .ag-rtl .ag-row-group-indent-#{$i} {
        padding-right: $i * 16px !important;
      }
    }
`
It's not supported in all versions.

**Comment by kof** [comment]
this is one of the reasons why cssinjs exists, you can use JS for this
