### ISSUE TITLE
Default unit not applied when value is 0

### ISSUE THREAD

**Issue by mitchellstern** [cssinjs/jss#1363]
__Expected behavior:__
Default units should be applied to all numerical values, not just non-zero values. For instance, `transitionDuration: 300` should give `transition-duration: 300ms` and `transitionDuration: 0` should give `transition-duration: 0ms`.

__Describe the bug:__
When the value is 0, no unit is being applied, resulting in invalid styles like `transition-duration: 0`. The plain property value `0` is not recognized by the browser where time values are expected, and should have a unit according to https://developer.mozilla.org/en-US/docs/Web/CSS/time.

I believe the line responsible for this is the following:

https://github.com/cssinjs/jss/blob/4094410d82dfdae772e1c09f0cd187cb48fa1cdc/packages/jss-plugin-default-unit/src/index.js#L27

__Codesandbox link:__ 
https://codesandbox.io/s/cranky-gould-yuyq5?file=/src/App.tsx

Note the invalid style being produced by JSS on the indicated element:

<img width="379" alt="Screen Shot 2020-07-16 at 10 02 16 AM" src="https://user-images.githubusercontent.com/3311523/87680611-a43a9a00-c74b-11ea-8ede-e8a34e2584fc.png">

__Versions (please complete the following information):__
 - jss: 10.3.0
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: macOS

**Comment by reifnotreef** [comment]
I'm not sure if this is a bug.

This has to do with default units. This happens with lineHeight as well, it has no default unit so if you say ```lineHeight: 8``` instead of ```lineHeight: '8px'``` you're gonna have a BAD time.

**Comment by mitchellstern** [comment]
Since no default unit is given for `line-height` in https://github.com/cssinjs/jss/blob/master/packages/jss-plugin-default-unit/src/defaultUnits.js, any value will get translated without a unit, so the library is functioning as intended here. (Incidentally, the documentation at https://developer.mozilla.org/en-US/docs/Web/CSS/line-height suggests using unitless numbers for line-height values when possible, so this seems like a reasonable default.)

The issue I'm mentioning here is that properties that *should* have a unit don't have one when a value of 0 is supplied.

To illustrate the problem, here are some examples from the current version of the library.

Line height (no unit expected):
✅ `lineHeight: 0` gets turned into `line-height: 0`
✅ `lineHeight: 8` gets turned into `line-height: 8`

Border width (default unit of `px` expected):
⚠️ `borderWidth: 0` gets turned into `border-width: 0` (this happens to be okay, because browsers interpret this as `0px`)
✅ `borderWidth: 4` gets turned into `border-width: 4px`

Transition duration
❌ `transitionDuration: 0` gets turned into `transition-duration: 0` (this is **invalid**, and will be ignored by browsers)
✅ `transitionDuration: 300` gets turned into `transition-duration: 300ms`

I'm advocating for a default unit (if one exists) to get applied to all values, not just non-zero values, since dropping the unit is not valid for some units (like `ms`).
