### ISSUE TITLE
Can someone please guide me what how to run react-jss in browser using only <script> tags?

### ISSUE THREAD

**Issue by FieryCod** [cssinjs/jss#1364]
Dear jss community I would like to use react-jss by injecting all scripts in index.html. I would highly appreciate the example how to do it.

**Comment by ichisadashioko** [comment]
I think these step might a good start.

- Clone the `jss` repo.
- Use a bundler (e.g. `parcel`) to bundle `react-jss` package (`jss/packages/react-jss/index.js`) targeting `UMD`.
- Now you have a script that you can use to include in the `<script>` tag.

**Comment by ichisadashioko** [comment]
I failed with `parcel` because it cannot resolve `jss` in the `packages` directory.

**Comment by FieryCod** [comment]
Already resolved the issue by using webpack. Thought that if CDN links are provided then those injected will just work.

Closing the issue!
