### ISSUE TITLE
Nonces added for CSP support are still policy-blocked

### ISSUE THREAD

**Issue by eliperelman** [cssinjs/jss#1371]
__Expected behavior:__

Configuring CSP and `csp-nonce` meta tag to use nonces with JSS should render without the need for `unsafe-inline`.

__Describe the bug:__

I am using `material-ui`, and transitively JSS, to inject styles. When released to production, the CSP directive is blocking the loading of the styles, even though it appears that the nonces configured for CSP and JSS match.

<img width="660" alt="Screen Shot 2020-07-24 at 6 38 24 PM" src="https://user-images.githubusercontent.com/285899/88443172-df3c6d80-cddc-11ea-95db-b8611274e847.png">

Taking a look at the meta tags present in the HTML response:

<img width="792" alt="Screen Shot 2020-07-24 at 6 39 50 PM" src="https://user-images.githubusercontent.com/285899/88443226-14e15680-cddd-11ea-9013-39dca2af7919.png">

So the CSP meta tag defines the style nonce as `nonce-gq/sneT99hwrwvvbNkbMWg==`, which matches the exact value set by the `csp-nonce` tag. Next, let's take a look at the style tags injected into the page:

<img width="611" alt="Screen Shot 2020-07-24 at 6 43 57 PM" src="https://user-images.githubusercontent.com/285899/88443366-a5b83200-cddd-11ea-9116-4fb288dd3f7f.png">

🤔 It appears that all the style tags also have the same nonce set correctly.

__Codesandbox link:__ 

May try to create something to replicate this, but CSP is hard to make this happen.

__Versions:__
 - jss: 10.3.0 (via material-ui)
 - Browser [e.g. chrome, safari]: Chrome 84
 - OS [e.g. Windows, macOS]: macOS Catalina

**Comment by eliperelman** [comment]
Closing as resolved. Turns out that the `nonce` attribute needed for JSS should not actually include the `nonce-` portion of the nonce.

**Comment by gsi-chao** [comment]
> **Expected behavior:**
> 
> Configuring CSP and `csp-nonce` meta tag to use nonces with JSS should render without the need for `unsafe-inline`.
> 
> **Describe the bug:**
> 
> I am using `material-ui`, and transitively JSS, to inject styles. When released to production, the CSP directive is blocking the loading of the styles, even though it appears that the nonces configured for CSP and JSS match.
> 
> <img alt="Screen Shot 2020-07-24 at 6 38 24 PM" width="660" src="https://user-images.githubusercontent.com/285899/88443172-df3c6d80-cddc-11ea-95db-b8611274e847.png">
> 
> Taking a look at the meta tags present in the HTML response:
> 
> <img alt="Screen Shot 2020-07-24 at 6 39 50 PM" width="792" src="https://user-images.githubusercontent.com/285899/88443226-14e15680-cddd-11ea-9013-39dca2af7919.png">
> 
> So the CSP meta tag defines the style nonce as `nonce-gq/sneT99hwrwvvbNkbMWg==`, which matches the exact value set by the `csp-nonce` tag. Next, let's take a look at the style tags injected into the page:
> 
> <img alt="Screen Shot 2020-07-24 at 6 43 57 PM" width="611" src="https://user-images.githubusercontent.com/285899/88443366-a5b83200-cddd-11ea-9116-4fb288dd3f7f.png">
> 
> 🤔 It appears that all the style tags also have the same nonce set correctly.
> 
> **Codesandbox link:**
> 
> May try to create something to replicate this, but CSP is hard to make this happen.
> 
> **Versions:**
> 
> * jss: 10.3.0 (via material-ui)
> * Browser [e.g. chrome, safari]: Chrome 84
> * OS [e.g. Windows, macOS]: macOS Catalina

Can you share an example repo with these configurations?
