### ISSUE TITLE
I want to implement jss for vue, if I do, can I PR to this repo?

### ISSUE THREAD

**Issue by Jokcy** [cssinjs/jss#1377]
Just like React-jss, if I want to implement Vue-jss. Can I PR to this repo?

**Comment by Jokcy** [comment]
Actually I already implement one, see [vue-jss](https://github.com/pure-vue/vue-jss)

**Comment by kof** [comment]
For now I think the best way is to link it from the docs, we can put it under the cssinjs org umbrella but I am not sure what this will bring.
