### ISSUE TITLE
useStyles not properly passing props

### ISSUE THREAD

**Issue by gSarciotto** [cssinjs/jss#1386]
__Expected behavior:__
Expected stylesProps inside the createUseStyles callback to be:
```
{
  theme: {
    palette: {
      primary: "green"
    }
  }
}
```

__Describe the bug:__
Instead of the value above, stylesProps is undefined. I'm new to JSS, so dunno if this is a bug or if I'm doing something very wrong.

__Codesandbox link:__ 
[Sandbox](https://codesandbox.io/s/jss-theming-problem-7ho9k?file=/src/MyComponent.tsx)

__Versions (please complete the following information):__
 - jss: 10.4.0
 - Browser [e.g. chrome, safari]: both chrome and firefox
 - OS [e.g. Windows, macOS]: Linux (Ubuntu 19)
- Typescript: 3.7.5

**Comment by kof** [comment]
You are using it wrong, see function values and function rules syntax https://cssinjs.org/jss-plugin-rule-value-function
