### ISSUE TITLE
Dynamic values in React-jss are not working!

### ISSUE THREAD

**Issue by Zhengy1995** [cssinjs/jss#1394]
Well, as you see in the first picture, the part 1 and 2 are not working as i respect, but the part3 is normal, i just use the `dynamic values` like the [docs](https://cssinjs.org/react-jss/?v=v10.4.0#dynamic-values) says, in my opinion, it's a bug, please answer me at time, tks so much.

See my [example](https://codesandbox.io/s/cold-sun-pwc4i?file=/src/App.js) here

![image](https://user-images.githubusercontent.com/30064447/93989392-6cd81180-fdbc-11ea-86d0-f15097d68bb8.png)
![image](https://user-images.githubusercontent.com/30064447/93991004-6185e580-fdbe-11ea-8736-45f8d618e3ec.png)

**Comment by kof** [comment]
duplicate https://github.com/cssinjs/jss/issues/1216
