### ISSUE TITLE
Support use other window's document

### ISSUE THREAD

**Issue by IronLu233** [cssinjs/jss#1397]
__Is your feature request related to a problem? Please describe.__
  I maintain an online meeting application, which use React and Material-UI. 

   the application has a feature is that, open an detached window(using window.open in code), and render video session to it.

  The video sission has some control button, for example, an hang up button, which use Material-UI Button component. 

  but unexpectly, the Button's CSS is rendered into the main window. so the control buttons in detached window lost their style.
![image](https://user-images.githubusercontent.com/20639676/94253868-81e9a780-ff58-11ea-9bbe-39554ab5e9a0.png)
  In current, I have to copy styles between main window and detached window.
__Describe the solution you'd like__
We can specify the `document` when we instantiate Jss. in default, the `document` object is from current javascript execution context.
My temporary solution is extends DomRenderer and override attach method. but in fact, the DomRenderer class is not exported.I access it from another Jss instance. This is not good enough. https://paste.ubuntu.com/p/3VkX8rsGT9/
__Are you willing to implement it?__
Yes
We only need change a litte code, the DOM renderer can get head from different `document` object!
https://github.com/cssinjs/jss/blob/cc3cea8b6d6b32b7706d62c00b46a600ec6ebe67/packages/jss/src/DomRenderer.js#L125

**Comment by kof** [comment]
jss core has an option for passing your own insertionPoint, you will have to follow the guildines on how to set up your own jss instance or pass that option through material-ui if it supports it https://cssinjs.org/jss-api?v=v10.5.1#setup-jss-instance
