### ISSUE TITLE
`tiny-warning` causing a `process is undefined` error in the browser

### ISSUE THREAD

**Issue by Qix-** [cssinjs/jss#1410]
__Expected behavior:__
No crash

__Describe the bug:__
The `tiny-warning` dependency attempts to use `process` in the browser without checking to see if it exists first.

I would imagine it has gone unnnoticed for so long due to many packagers allowing `process.env` be replaced at build time - but that isn't a guarantee anyone should be relying on at the library level.

An `npm ls tiny-warning` showed me:

```
@museum/www@0.0.0 /src/wavetilt/museum/packages/www
├─┬ jss@10.4.0
│ └── tiny-warning@1.0.3
└─┬ jss-preset-default@10.4.0
  ├─┬ jss-plugin-compose@10.4.0
  │ └── tiny-warning@1.0.3  deduped
  ├─┬ jss-plugin-extend@10.4.0
  │ └── tiny-warning@1.0.3  deduped
  ├─┬ jss-plugin-nested@10.4.0
  │ └── tiny-warning@1.0.3  deduped
  ├─┬ jss-plugin-rule-value-function@10.4.0
  │ └── tiny-warning@1.0.3  deduped
  └─┬ jss-plugin-template@10.4.0
    └── tiny-warning@1.0.3  deduped
```

I've already filed a bug report and a PR upstream.

Bug: alexreardon/tiny-warning#24
Upstream PR: alexreardon/tiny-warning#25

However, I seriously suggest ditching that dependency as was suggested in https://github.com/cssinjs/jss/issues/1313#issuecomment-620186271. It's not much more than an if statement in package form.

__Versions (please complete the following information):__
 - jss: `jss@10.4.0`
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows

**Comment by kof** [comment]
I am guessing your build does not replace process.env variables, it probably is gonna hit you in various other places as well, so I am not sure fixing it here is the right place

**Comment by Qix-** [comment]
What. Process environment variables do not belong in the build process, that has always been a hack.

Please fix this. You're breaking browser conventions.

**Comment by kof** [comment]
Assuming we don't want to get rid of tiny-warning, the right place to fix it would be https://github.com/alexreardon/tiny-warning/issues/24 , right?

**Comment by Qix-** [comment]
@kof yes, correct. :)
