### ISSUE TITLE
Linked sheet.update doesn't work – rules are not attached to the DOM

### ISSUE THREAD

**Issue by amatiash** [cssinjs/jss#1432]
![frustrated, shame](https://media.giphy.com/media/P8WZZ0NYdbXAA/giphy.gif)

__Expected behavior:__
Expect rules to be attached to the DOM

__Describe the bug:__
Using `link: true` with `sheet.update` doesn't work – rules are not attached.

__Codepen link:__ 
Here is an [example](https://codepen.io/amatiash/pen/jOMVVqE) with the issue.
I took the code from original [documentation](https://cssinjs.org/jss-api?v=v10.5.0#update-function-values).

__Versions:__
 - jss: 10.5.0
 - Browser: Chrome 87.0.4280.88
 - OS: macOS 10.14.1

Had the same bug with jss 9.8.7

**Comment by kof** [comment]
You are looking in a wrong way. CSSOM API changes don't show up in the DOM, use a class on an element and style panel or go into the style sheet properties inspector.

<img width="1436" alt="Screenshot 2021-04-26 at 12 13 30" src="https://user-images.githubusercontent.com/52824/116066962-f4566d80-a688-11eb-9d27-1fb957181c39.png">

**Comment by amatiash** [comment]
Thanks for explanation!
