### ISSUE TITLE
px unit is not appended to css rowGap property

### ISSUE THREAD

**Issue by VineethK336** [cssinjs/jss#1435]
__Expected behavior:__
When we give the css `rowGap: 10`, jss should have ideally translated it to `row-gap: 10px`
[css row-gap](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap)

__Describe the bug:__
However, it was translated to `row-gap: 10` (The unit `px` is missing)

__Codesandbox link:__ 
Here's a simple reproduction of the issue: https://codesandbox.io/s/vigilant-pine-z4ytr?file=/src/App.js

__Versions (please complete the following information):__
 - jss: 10.5.0
 - Browser [e.g. chrome, safari]: Chrome 87
 - OS [e.g. Windows, macOS]: macOS 10.15.6

Came here following this issue: https://github.com/mui-org/material-ui/issues/23505

If the fix is to add an entry for row-gap in `packages/jss-plugin-default-unit/src/defaultUnits.js`, I'd be happy to create a PR as well.

**Comment by kof** [comment]
Released https://github.com/cssinjs/jss/releases/tag/v10.5.1
