### ISSUE TITLE
text-decoration-thickness value does not default to px

### ISSUE THREAD

**Issue by vepasto** [cssinjs/jss#1437]
__Expected behavior:__
when I set `text-decoration-thickness: 1` I expect to see `text-decoration-thickness: 1px` in browser

__Describe the bug:__
I see `text-decoration-thickness: 1` in browser

__Codesandbox link:__ 
https://codesandbox.io/s/hardcore-smoke-zd3tr?file=/src/App.js

__Versions (please complete the following information):__
 - jss: 10.5
 - Browser Chrome
 - OS macOS

**Comment by kof** [comment]
Released https://github.com/cssinjs/jss/releases/tag/v10.5.1
