### ISSUE TITLE
[cli] Conver jss to css

### ISSUE THREAD

**Issue by ppsirius** [cssinjs/jss#1440]
__Expected behavior:__
Convert styles.js file to CSS

__Describe the bug:__
I install jss-cli globally and try to convert files but without success.
In the documentation, I can't find any description that help me convert jss styles. What config I should make to this transformation that could work?
I try with 
`jss convert ./style.js -f css > style.css`
but got only empty css files

__Versions (please complete the following information):__
 - jss-cli@6.0.2
 - macOS

**Comment by kof** [comment]
https://github.com/cssinjs/cli script is very simple, feel free to fix it and submit a PR, otherwise it won't happen soon

**Comment by kof** [comment]
without an example of the file or specific errors we can't work on this
