### ISSUE TITLE
Support Input Range Pseudo Selectors

### ISSUE THREAD

**Issue by jonathan-l-rivera** [cssinjs/jss#1441]
__Is your feature request related to a problem? Please describe.__
Yes, currently JSS is unable to style input[type="range"] shadow elements.

__Describe the solution you'd like__
All of the below pseudo selectors should be supported.

&::-moz-focus-outer'
'&::-moz-focus-inner'
'&::-ms-track'
'&::-webkit-slider-thumb'
'&::-moz-range-thumb'
'&::-ms-thumb'
'&::-webkit-slider-runnable-track'
'&::-moz-range-track'
'&::-ms-track'
'&::-ms-fill-lower'

__Are you willing to implement it?__
Perhaps, but not familiar enough with the source to contribute at the moment.

**Comment by kof** [comment]
any pseudo selector is supported exactly the way you described, using nested plugin syntax, if you don't see it work, test it in the browser with pure css, then validate what jss has generated, closing this for now

**Comment by jonathan-l-rivera** [comment]
Good to know. I'm getting an error on my end saying these are not valid, I'll have to troubleshoot further. Thanks @kof
