### ISSUE TITLE
Reference a $localrule in main scope

### ISSUE THREAD

**Issue by rickstaa** [cssinjs/jss#1443]
__Is your feature request related to a problem? Please describe.__

I'm currently trying to declare several shared properties for two commas separated classes:

```CSS
A, B {
   height:  "40px"
},
A {
    color: "#fff"
}
B {
    color: "#000"
}
```

I tried using the `$rulename` [operator](https://cssinjs.org/jss-plugin-nested?v=v10.5.0) to do this. While doing this, I noticed that the local rule operator does not seem to work when I use it in the main scope. However, the operator works when I put the `or` selection rule inside a parent `root` element (see image below). I was also able to get the desired behaviour using the [extend operator](https://cssinjs.org/jss-plugin-extend?v=v10.5.0).

![image](https://user-images.githubusercontent.com/17570430/105198005-835d6200-5b3d-11eb-88ab-028d28290053.png)

__Describe the solution you'd like__

I expected the `$rulename` local rule operator to also work at the main scope.

__Are you willing to implement it?__

~~Yes~~/No: At the moment I think we have enough methods to achieve the desired behaviour. I just wanted to check if I am doing something wrong.

**Comment by kof** [comment]
$rulename was designed to reference parent rules inside the nested rules, what you wanted is like you said extend operator
