### ISSUE TITLE
Decarator innerSheet  -> Error: Super expression must either be null or a function

### ISSUE THREAD

**Issue by kozlikov** [cssinjs/jss#1447]
__Expected behavior:__
Normal extends class

__Codesandbox link:__ 
https://codesandbox.io/s/confident-torvalds-zne64?file=/src/App.js

P.S. in version 8.6.1 this code works well!

__Versions (please complete the following information):__
 - jss: 10.5.1
 - Browser [e.g. chrome, safari]: chrome
 - OS [e.g. Windows, macOS]: Windows

**Comment by kof** [comment]
I don't know why it worked in v8, but you are not supposed to extend react components at all. The only place where you were supposed to use extend is to extend React.Component. Never anything else.
