### ISSUE TITLE
Using Number.isNaN breaks JSS in IE11

### ISSUE THREAD

**Issue by GertSallaerts** [cssinjs/jss#1455]
I wasn't able to find documentation on which browsers are officially supported but as IE11 used to work I'm guessing this might be a bug. 

https://github.com/cssinjs/jss/blob/105d854d4c0e3ea541f78cbd78cca583f4d83cf9/packages/jss-plugin-default-unit/src/index.js#L43

The above code was introduced in https://github.com/cssinjs/jss/pull/1446.

**Comment by kof** [comment]
You are right, it should have been the global `isNaN` cc @oliviertassinari I wonder why it didn't break mui sooner

**Comment by oliviertassinari** [comment]
Oh right, oops. To be honest, we don't care about IE 11 on Material-UI.

**Comment by kof** [comment]
I wonder if we should drop it in JSS too ... not sure how to make that decision

**Comment by oliviertassinari** [comment]
> not sure how to make that decision

We broke it for weeks and nobody noticed/complained. I would say it's a great signal.

**Comment by kof** [comment]
@GertSallaerts how did you notice, in a product?

**Comment by kof** [comment]
@oliviertassinari it might be that users upgrade only with a delay, then they don't test in IE11 every day, so they figure that out only in a few weeks that it's broken, not sure the delay in signal can be interpreted as "not used"

**Comment by kof** [comment]
JSS core is probably used in a few different type of places than MUI as being lower level abstraction.

**Comment by GertSallaerts** [comment]
Yes, we are updating our stack to React 17 at [ambassify.com](https://www.ambassify.com) and as a result also updated `react-jss` (which we use for our styling) to the latest version which is how I ran into this.

**Comment by kof** [comment]
I am even more surprised because we run tests in IE 9, 10 and 11 and that PR had a test in it

**Comment by GertSallaerts** [comment]
On IE11 specifically I'd suggest you drop it in the next major version and add a list of browsers you do officially support to the documentation, but that's just my two cents :sweat_smile:

**Comment by kof** [comment]
Btw. we do have a list of supported browsers and it was linked in the docs, but now I don't see it being linked any more, we should be more explicit about it https://github.com/cssinjs/jss/blob/master/browsers.json

**Comment by kof** [comment]
I think we should deprecate IE9-11 along with a scoped custom props support https://github.com/cssinjs/jss/issues/1015 because it makes sense for this feature to be in the core and we couldn't do it with IE11 support.

**Comment by kof** [comment]
Tests didn't fail because use webpack for tests and rollup for builds ... looking to use the same config at least

**Comment by kof** [comment]
I just realized that the polyfills is not part of any JSS package and never was. Polyfills is always something you put into your consumer bundle. We started using Number.isNaN and it wasn't needed before, there for it should have been a minor version increment and part of the changelog, but as I see it now it's not a bug.

We could improve this whole story by adding a separate page for browsers support and this strategy with polyfills.

**Comment by kof** [comment]
Our tests run with a all polyfills and I think that's ok if we expect users to use them too, depending on their target

https://github.com/cssinjs/jss/blob/a27b9ac71cbd0a07b8ecc7851076f5434bba3de6/karma.conf.js#L19-L20

**Comment by kof** [comment]
@GertSallaerts please review the PR in particular if the documentation I added is sufficient

**Comment by GertSallaerts** [comment]
@kof what I would take away from that documentation is that there is no explicit browser support and every JSS user would be required to always transpile/polyfill regardless of which browsers they target. Because if I understand correctly all your tests are run using polyfills but you don't ship any at all.

Theoretically (extreme example) this means a change like the one discussed above could be introduced in a patch release that breaks JSS even in the latest Chrome if it uses a feature that's polyfilled by `@babel/polyfill` but not yet implemented in Chrome. And the tests wouldn't catch this because all the latest polyfills are loaded.

If this is the way you want to go, I would try to make this just a little clearer in the documentation you added. Something along the lines of:

> We run our tests against a [number of browsers](../browsers.json). All tests are run using `@babel/polyfill` to make sure all stable ES features are polyfilled during testing . However we do NOT include any of these polyfills in the published packages. It is up to the user to include polyfills depending on what environment they want to support.

**Comment by kof** [comment]
I guess at this point "support" is the word that we need to clarify in that document. We are testing it even in IE9 on a real browser, this is more "support" than 99% of other libraries that claim such without testing in them on CI. 

So the question is what do I need to point out more clearly
1. We aim to support older browsers as long as it doesn't create serious maintenance or performance downsides for modern browsers
2. We do test in real browsers including IE9
3. We do expect users to run babel over it with the settings for the environment they want to support. I wonder if users have different expectations when they include bundles directly over unpkg cdn.
4. Version management is a good question. In theory it's not a regression on JSS side if it uses something user didn't polyfill and they didn't use auto-polyfilling, but I can imagine this causing problems and wonder what a common expectation is.

**Comment by kof** [comment]
Maybe we should stop using a complete polyfill with karma tests, so that we know exactly what polyfills we are using and it should fail if there is a new one required. This way we can link to that list and user can decide if they don't need some of them or they just use auto polyfilling.

**Comment by kof** [comment]
Yeah, here is the plan
1. Link to browsers.json for a complete list of supported browsers
2. Link to a list of manually defined polyfills for all supported browsers (if you don't use some of them as a user - its on you)
3. As already done  - recommend auto polyfilling
4. CI will fail next time and notify us to include a new polyfill and make it a breaking change or otherwise don't rely on it.

**Comment by GertSallaerts** [comment]
Sounds good to me. Do you want me to update the issue title/description or close it or something?

**Comment by kof** [comment]
It's fine, I didn't have time yet to figure out the specific polyfills we currently need and replace the m in karma config, so that we have a definitive list.

**Comment by kof** [comment]
Released in [v10.6.0](https://github.com/cssinjs/jss/releases/tag/v10.6.0)
