### ISSUE TITLE
Can we migrate to Typescript?

### ISSUE THREAD

**Issue by hosseinmd** [cssinjs/jss#1463]
The New version of Typescript is more flexible and has many good features. I think it is time to migrate to TypeScript.

__Are you willing to implement it?__
Yes

We could test types in commit lint or on GitHub actions.

In this the article, attractive features of Typescript are introduced.
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

**Comment by kof** [comment]
What downsides do we know we have if we keep typescript in separate .d.ts files?

**Comment by hosseinmd** [comment]
There is tow side

Internally:
Typescript could help us to develop more clearly and safety, This repo is more complex and typescript could help clear complexity.

Externally:
When we separate .d.ts files, we should take care types files in after changes and some time maybe we missed types.
But with Typescript we don't need to .d.ts. anything we developed and exported have type.

**Comment by kof** [comment]
The problem you are talking about is that changes in js are not in sync with TS? Can't this be avoided by having tests for TS?

**Comment by hosseinmd** [comment]
This code help but not completely, for example we have a function declaration in .d.ts if original function be change, still test will pass.

**Comment by kof** [comment]
Is that a frequent problem for a lib?  For product it definitely is, but are we changing such things frequently in JSS?

**Comment by hosseinmd** [comment]
Currently, we have many bug in exported types.

Now JSS have flow for types, IMO typescript have more benefit.

**Comment by hosseinmd** [comment]
If we want to migrate on TypeScript i think we don't changed more code.

**Comment by kof** [comment]
We actually have a long standing issue about it https://github.com/cssinjs/jss/issues/1035 feel free to close this one if you agree we should not have 2 of them
