### ISSUE TITLE
Dynamic values don't work together with the extend plugin [React]

### ISSUE THREAD

**Issue by ilyador** [cssinjs/jss#1471]
In the following code, the extending classes do not receive `width` but receive other styles from `agenda`:

```js
agenda: {
  width: ({ baseSize }) => baseSize * 0.3,
  position: 'absolute',
  top: 4
},
firstAgenda: {
  extend: 'agenda',
  left: 2
},
secondAgenda: {
  extend: 'agenda',
  left: 52
}
```

If I copy it manually into each, it works:

```js
agenda: {
  position: 'absolute',
  top: 4
},
firstAgenda: {
  width: ({ baseSize }) => baseSize * 0.3,
  extend: 'agenda',
  left: 2
}
```

Working example:
https://codesandbox.io/s/objective-bassi-qn04t?file=/src/App.js

react-dom: 17.0.1
react-jss: 10.6.0

**Comment by kof** [comment]
we already have this issue reported #1134
