### ISSUE TITLE
Question: peer dependency or dependency when installed in a library

### ISSUE THREAD

**Issue by sag1v** [cssinjs/jss#1481]
My question is more related to `styled-jss` but i guess it depends on `JSS` implementation.

When we use JSS inside a library/package, should we install it as `peerDependencies` or regular `dependencies`?

Is there something to watch out for, regarding multiple instances or versions conflict when a library use `jss` / `styled-jss` as well as the consumer?

**Comment by kof** [comment]
Here is a place for support questions https://github.com/cssinjs/jss/discussions

I would use it as a dependency to ensure the version you use works with how you use it. Shouldn't be any conflict with user dependency.
