### ISSUE TITLE
extending of extending doesnt work

### ISSUE THREAD

**Issue by heyymarco** [cssinjs/jss#1486]
If I exteding an object that the object itself extending multiple objects (an array), the jss seem doesn't work.

See my sandbox: https://codesandbox.io/s/green-mountain-urirw?file=/src/App.tsx

```
const useStyles = createUseStyles({
    test: {
       extend: { // extending single object
          extend: [ // extending double object
             {
               color: 'blue',
             },
             {
               background: 'pink'
             },
          ] as JssStyle
       }
    }
});
```

but if i extending an object **as array** the object itself extending multiple objects (an array), the jss works fine

```
const useStyles = createUseStyles({
    test: {
       extend: [{ // extending single object AS AN ARRAY
          extend: [ // extending double object
             {
               color: 'blue',
             },
             {
               background: 'pink'
             },
          ] as JssStyle
       }] as JssStyle
    }
});
```

Is that a bug?

**Comment by kof** [comment]
This isn't a syntax it supports. I am sure what you want to express can be done in a different way.

**Comment by heyymarco** [comment]
JSS do support the extend by default.
See: https://cssinjs.org/jss-plugin-extend?v=v10.5.1

Spread operator is _not satisfied_ for me, it's **not deeply** merged.

I created a jss libs that contain many "mixins" (a js function returning JssStyle), each mixins may includes another mixin too.
So to **safely includes them** I use the **extend** feature.

To temporary workaround the bug (maybe), I wrapped the mixin into an array, like this `extend: [ this.complexMixin() ]`
Hopefully the extend can accept single mixin without wrapping into array.
Note: the extend _worked fine in prev version of jss_ (i forget the ver), but after i upgraded to the latest JSS the extend has a quite bit weird behavior.
Why the extend worked fine both for singular and array in prev version but in newest version doesn't?

Here the illustration of my code:

```
class ButtonStyleBuilder {
    fooMixin() { return {
        color: 'red',
    }}

    coolMixin() { return {
        background: 'pink',
    }}

    complexMixin() { return {
        extend: [
        this.fooMixin(),
        this.coolMixin(),
        ] as JssStyle,
    }}

    myFirstStyle(): Styles<'btnAwesome'> { return {
        btnAwesome: {
            extend: this.complexMixin(), // DOESN'T WORK
        }
    }}

    mySecondStyle(): Styles<'btnAwesome'> { return {
        btnAwesome: {
            extend: [ this.complexMixin() ] as JssStyle, // NOW WORKS!
        }
    }}

    _useStyleCache : ((() => Classes<'btnAwesome'>)|null) = null;
    useStyle() {
        if (!this._useStyleCache) this._useStyleCache = createUseStyles(this.mySecondStyle());
        return this._useStyleCache();
    }
}
class CoolButtonStyleBuilder extends ButtonStyleBuilder
{
    // overrides:
    coolMixin() { return {
        background: 'lightBlue',
    }}
}
export const style = new CoolButtonStyleBuilder();
```
