### ISSUE TITLE
Wrong path in react-jss.js

### ISSUE THREAD

**Issue by rvsia** [cssinjs/jss#1494]
__Describe the bug:__
In`react-jss.js` and `react-jss.bundle.js` there is this line 

```
module.exports = require('./cjs/react-is.development.js');
```  

However, there is no such file and folder, so it fails . It should probably lead to something like `./node_modules/react-is/cjs/...`

__Reproduction:__ 

https://stackblitz.com/edit/vkydg7-lgcuda?file=index.js

__Versions (please complete the following information):__
 - jss: 10.6.0

**Comment by kof** [comment]
It must be something with stackblitz build, tons of users use react-jss without this problem

**Comment by rvsia** [comment]
@kof yeah, I think the same - it should definitely use esm module files. But still, the path looks wrong to me (as it does not lead to any actual file).

However, thank you for your response and feel free to close this.

**Comment by kof** [comment]
Feel free to reopen if you find out JSS can do something here
