### ISSUE TITLE
[question] how to use react-jss with CSS stylesheet rather than inline styles? [next-js] [CSP header] [static website]

### ISSUE THREAD

**Issue by didrip** [cssinjs/jss#1517]
_Hello, first I apologize if it is the wrong place to but I did not find a specific repo for the package `react-jss` and also I am not sure it is a problem that could be solved by JSS (maybe by a post CSS plugin)._

I am using `react-jss` on a static website which is generated via nextJS, following this setup => https://github.com/vercel/next.js/tree/master/examples/with-react-jss

I have implemented CSP header but I would like to avoid `unsafe-inline` for `style-src`, I cannot use `nonce` because well, it is a static website. Therefore I would like to include all the CSS generated by react-jss in one external stylesheet. Is it possible ?

I read [the documentation](https://cssinjs.org/jss-api) but I am not sure to understand how `SheetsRegistry` or `JssProvider` works (could not find the reference for it but from the typescript definitions the only interesting option is `disableStylesGeneration`).

Do I need a post CSS plugin to transform the inline styles into one external stylesheet?

**Comment by kof** [comment]
Hi, use https://github.com/cssinjs/jss/discussions for asking for help.

We don't support static extraction out of the box. There are ways to get it but it would limit the way you use the library by a lot.
