### ISSUE TITLE
react-jss 10.7.0 broke useStyle()

### ISSUE THREAD

**Issue by viko16** [cssinjs/jss#1525]
__Expected behavior:__
Use `useStyle` without arguments. It works in `<=10.6.0`.

__Describe the bug:__
I updated to 10.7.0 and found the following error. 
`Cannot read property 'theme' of undefined`.

It looks like an error was reported here 👇
https://github.com/cssinjs/jss/blob/v10.7.0/packages/react-jss/src/createUseStyles.js#L43

I updated to 10.7.0 and found that previously normal code was reporting the following error, which appears to be reported here.

__Reproduction:__ 

```js
const useLabelStyles = createUseStyles({
  label: {
    color: "red"
  }
});
const Label = ({ children }) => {
  const classes = useLabelStyles(); // <=== Here
  return <label className={classes.button}>{children}</label>;
};
```

I copied the example code from the official website and reproduced the problem on CodeSandbox.
https://codesandbox.io/s/react-jss-1070-broke-usestyle-zv6lg

__Versions (please complete the following information):__
- react-jss: 10.7.0

**Comment by imemir** [comment]
I have this problem too @kof

**Comment by ashkanahrabi** [comment]
+1

**Comment by k4rli** [comment]
Same problem. 10.6.0 works fine.

**Comment by kof** [comment]
Releasing a patch in a bit

**Comment by kof** [comment]
released in https://github.com/cssinjs/jss/releases/tag/v10.7.1
