### ISSUE TITLE
Support @container query

### ISSUE THREAD

**Issue by a-maggi** [cssinjs/jss#1629]
__Is your feature request related to a problem? 

I would like to be able to use the new media query property "@container" on my styles.

__Describe the solution you'd like__
I would like to be able to use the property @container in the same way as we use @media queries in the library.

__Are you willing to implement it?__
No

**Comment by behnammodi** [comment]
@a-maggi Thanks to report this issue, could you tell us what happens when you use `@container`? or could you reproduce  it on a `repo` or `sandbox` link

**Comment by pearcake** [comment]
@behnammodi long story short its a new syntax that allows developers to use rules similar to @media min-max width rules, but on element level - depending on parent container size: [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries)

I also came here looking for a solution to wrap all of my JSS in `@layer LAYERNAME {}` tag, which is already supported by all major browsers. It allows developers to assign render priorities to different CSS code segments (like an !important rule, but more sophisticated and global). And JSS is currently does not support neither of those.

**Comment by behnammodi** [comment]
@pearcake I'm not sure it's possible for now but let me check from my side

**Comment by Isti115** [comment]
I've opened a pull request with a minimal fix, meanwhile if you wish you can apply the following patch using `patch-package`: [jss+10.9.2.patch](https://github.com/cssinjs/jss/files/10376637/jss%2B10.9.2.patch)

**Comment by a-maggi** [comment]
@Isti115 Thanks you so much for introducing this update! Do you know the ETA for releasing this as a new version in NPM?

**Comment by kof** [comment]
released https://github.com/cssinjs/jss/releases/tag/v10.10.0

**Comment by a-maggi** [comment]
@kof Thanks!

**Comment by MarcusNotheis** [comment]
Thanks for developing and releasing this feature! Is it just me or is the new release somehow [missing in npm](https://www.npmjs.com/package/react-jss?activeTab=versions)?
```
npm view react-jss@10.10.0
npm ERR! code E404
npm ERR! 404 No match found for version 10.10.0
npm ERR! 404
npm ERR! 404  'react-jss@10.10.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by kof** [comment]
Released it. Tons of problems: npm added OTP we don't have support of, lerna is way newer now and I wasn't able to upgrade easily. If anyone could help with the release process, it would help releasing updates as soon as we merge PRs.

Right now I spent hours to do that.
