### ISSUE TITLE
[all]  consistent testing across all jsstyles repositories

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#163]
- [x] create a separate repository for tests, build, lint, which is essentially the same we have in jss repo
- [x] lint tests of plugins, convert them to es6
- [x] rewrite plugins tests to mocha

**Comment by umidbekkarimov** [comment]
Maybe it's worth to follow [monorepo](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) approach before starting with this ?

**Comment by umidbekkarimov** [comment]
@kof 
>  lint tests of plugins, convert them to es6
So you want to test everything in node js env only?

**Comment by kof** [comment]
not sure about monorepo, in our plugins based architecture it would make a wrong impression. 

> So you want to test everything in node js env only?

Why? We are testing now here in all browsers.

**Comment by umidbekkarimov** [comment]
> Why? We are testing now here in all browsers.

I mean, if you want to use es6 syntax, files should be transpiled to es5 somehow before passing them to browser

**Comment by umidbekkarimov** [comment]
@kof 

> not sure about monorepo, in our plugins based architecture it would make a wrong impression.

Why? Babel is also plugin based tool and still has third party plugins.

So you have `jss` and core `jss-*` plugins, lets say there are 8 of them
9 npm packages
Now you want to add repo for crosstestings
You wan't be able test third party plugins there, until they get merged to `jsstyles` namespace.

In `monorepo` case:
You have one repo
All testings in it (also crosstestings)
Still 9 npm packages
Still can not test third party plugins

So in both cases it's problem of third party plugin developers to test and ship working plugins

**Comment by kof** [comment]
1. If we provide one repo which has everything common for all jss repositories, it could be also used by third-party projects too and would lead to a consistent code base.
1. I could think of a way to run tests from all third-party plugins. However this is a separate topic. This would be useful to see if a release is going to break something and additionally notify plugin developer.

**Comment by kof** [comment]
Of course we could do exactly the same in monorepo style too. I am just not sure if there is much of a benefit.

**Comment by kof** [comment]
The biggest benefit I can see is being able to make pull requests with all changes for all plugins.

**Comment by kof** [comment]
done
