### ISSUE TITLE
[css-vendor] handle special props and values

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#167]
We should handle some props and values differently for e.g. https://github.com/moliver-bb/css-legacy-browsers/blob/master/lib/legacy-browsers.js

**Comment by kof** [comment]
cc @alexkuz

**Comment by alexkuz** [comment]
Maybe legacy mode should be enabled with options, like
```js
jss.use(jssVendorPrefixer({ legacy: true }));
```
?

**Comment by kof** [comment]
Lets look if we can support any browser without any options and without overhead.

**Comment by kof** [comment]
First of all we need unit tests for all specific browsers.

**Comment by kof** [comment]
Basically the hardest part is to get all failing tests for every browser. Maybe we can learn from  https://github.com/postcss/autoprefixer

**Comment by kof** [comment]
Just found this package ... we could switch to this one or copy knowledge/ideas from there https://github.com/rofrischmann/inline-style-prefixer

**Comment by kof** [comment]
Its used by https://github.com/callemall/material-ui/

**Comment by kof** [comment]
This is already in process in https://github.com/cssinjs/css-vendor
