### ISSUE TITLE
Build rules with even higher performance.

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#169]
By using technic behind immutable.js. Currently plugins copy rules a lot. We could speed up things by inheriting from original object.

But first we need a bench before we can start with optimizations.

**Comment by joshgillies** [comment]
Definitely interested in seeing something like this come into JSS, chiming in to register interest. 👍

**Comment by kof** [comment]
There are 2 ways how this could be done, built in tools into jss or make jss and all plugins support any lib like immutable.js

**Comment by kof** [comment]
But to do it right, we need need to create a setup where all plugins are used and write some style sheet where all plugins do apply.

Then we can compare optimized and current version.

**Comment by kof** [comment]
Couldn't find any better approach than it is right now.
