### ISSUE TITLE
Functional DOM utilities lib for styles

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#204]
I am thinking of creating a functional library around style sheets as well as inline styles. 

Use the most performant way to render style sheets, there are lots of ways: innerHTML, textContent, text node, insertRule/addRule, cssText.

Currently I know of the need for:
- rendering a style element with CSS text
- adding 1 rule to style
- adding multiple rules  to style at once
- modifying rule.styles
- modifying rule.selectorText
- normalizing style props and values
- generating vendor prefixes

**Comment by mindjuice** [comment]
This sounds interesting.  Just to make sure I understand, you're thinking to essentially rewrite something like JSS, but in a functional/immutable style, right?

I really like the benefits of JSS so far, and I love functional/immutable libs, so I'd be willing to help when/where I can with that.

**Comment by kof** [comment]
Nope, just functional utilities like lodash, we can use than in jss and hopefully in other css in js libs. I want to share the effort of writing this functions because all implementations can benefit from it and because this DOM parts are a mess.

**Comment by kof** [comment]
Of course I also like immutability, also I want to experiment with something minimal for the styles object, but this is a different issue #169

**Comment by kof** [comment]
Also you are welcome to share your ideas about an immutable, functional jss version in a separate issue ... we can always experiment.

**Comment by mindjuice** [comment]
:+1:
