### ISSUE TITLE
[jss-expand] Plugin for using css shorthands in a MUCH nicer way

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#225]
Currently in CSS and JSS we write:

```javascript
button: {
  background: 'no-repeat 50% 50%'
  backgroundSize: 'auto 22px'
}
```

Much nicer would be to write:

```javascript
button: {
  background: {
    repeat: 'no-repeat',
    position: '50% 50%', 
    size: ['auto', 22] // bonus - numeric value will allow jss-default-unit to set the default unit.
  }
}
```

**Comment by typical000** [comment]
@kof https://github.com/typical000/jss-shorthand created and published a new plugin for this purposes. But there are 2 main issues:
1. It doesn't work with **jss-default-unit** plugin;
2. It breaks 'fallback' feature from jss core.

**Comment by typical000** [comment]
@kof Maybe, if it's a good idea, I can transfer this repo from my personal repository to **jsstyles** organisation, if you want :)

**Comment by kof** [comment]
cool @typical000, lets see if we can fix it and then add it to the org.

**Comment by typical000** [comment]
@kof I have no idea how to solve issue about beaking 'fallback' because there is no visual difference between writing shorthand background (for example, in my case) and fallback background. All those rules are arrays:
```javascript
export default {
  container: {
    background: [
      'red',
      'linear-gradient(to right, red 0%, green 100%)'
    ]
  }
}
```

And about default units bug - maybe add some tests if is not only a *number* but an *array with numbers* too...

**Comment by kof** [comment]
You got a visual difference, in your example above, background value is an array, it is a fallback case. If background would be an object - this is a case for shorthand (not sure shorthand is the best name)

**Comment by kof** [comment]
So first of all this plugin needs to run before jss-default-unit and it needs to normalize original objects like this:

```javascript
button: {
  background: {
    repeat: 'no-repeat',
    position: '50% 50%', 
    size: ['auto', 22] 
  }
}
```

to 

```javascript
button: {
  backgroundRepeat: 'no-repeat',
  backgroundPosition: '50% 50%',
  backgroundSize: 'auto 22px'
}
```

Regarding default-unit, we need to find a way to use it directly, because  'auto 22px' is not going to get a default.

**Comment by kof** [comment]
Regarding fallbacks, the only case we can't have is: fallbacks inside of the expanded notation:

```javascript
{
  button: {
    background: {
      color: ['black', 'white']
    }
  }
}
```

**Comment by typical000** [comment]
> If background would be an object

Yes, it's the only right solution that don't break JSS 'fallback' feature - change this syntax
```javascript
button: {
    background: [
      'linear-gradient(to left, #f00, transparent)',
      'linear-gradient(to top, #0f0, transparent)'
    ]
}
```
to
```javascript
button: {
    background: {
      image: [
        'linear-gradient(to left, #f00, transparent)',
        'linear-gradient(to top, #0f0, transparent)'
      ]
    }
}
```

**Comment by kof** [comment]
Yes, the only problem is multi-value props (don't know the right name), for e.g. `background-size: auto 20px`, I have suggested to use this syntax backgroundSize: ['auto', 20], to enable default unit and this is not compatible with fallbacks, that's why I have suggested something like a `fallbacks` property to re-enable fallbacks.

**Comment by kof** [comment]
Basically this issue is about 2 features:

1. being able to write in the expanded way
2. being able to use default units everywhere

**Comment by typical000** [comment]
> Regarding default-unit, we need to find a way to use it directly, because 'auto 22px' is not going to get a default.
I'ts a trouble. I think the only right way is just use **default-unit** before **shorthand** and, maybe, check not only if prop is a *number* but if it is an *array that contains numbers* and try add units to those numbers with plugin

**Comment by typical000** [comment]
> So first of all this plugin needs to run before jss-default-unit and it needs to normalize original objects like this

Now, my plugin, as result, creates short rules like *background, padding, margin* etc. like:
```css
background: #ccc url(image.png) no-repeat 0 0;
```
And if we normalize original object to separated rules as you say, like this:
```javascript
button: {
  backgroundRepeat: 'no-repeat',
  backgroundPosition: '50% 50%',
  backgroundSize: 'auto 22px'
}
```
The resulting CSS will look as separated piceces of *background* shorthand rule:
```css
background-color: #ccc;
background-image: url(image.png);
background-repeat: no-repeat;
background-position: 0 0;
```
So the question: @kof there is any important difference to write 'short' rules or to write them expanded?

**Comment by kof** [comment]
The problem is for e.g. background-size property can't be part of background shorthand notation. Am I wrong? In this case we need to know all props with this problem to write them separately.

Another benefit would be: plugins could potentially check/modify stuff based on expanded props. Using shorthand requires string parsing, which would make the whole thing slow and error prone.

**Comment by typical000** [comment]
There is other problem. If we take other rule, not `background` but, for example, `box-shadow` it will look very messy if we decide to write some multiple shadow:

What we need as output:
```css
box-shadow: 0 0 50px 10px rgba(0, 0, 0, 0.5), 10px 10px 10px 0 rgba(0, 0, 0, 0.5), inset 0 0 5px 0 rgba(255, 255, 255, 0.8);
```
How we can write now:
```javascript
button: {
  // Very, veeeery strange code :(
  boxShadow: '0 0 50px 10px rgba(0, 0, 0, 0.5), 10px 10px 10px 0 rgba(0, 0, 0, 0.5), inset 0 0 5px 0 rgba(255, 255, 255, 0.8)';
}
```
In case of current version of **jss-shorthand**:
```javascript
button: {
  boxShadow: [
    // A little better, I think :)
    '0 0 50px 10px rgba(0, 0, 0, 0.5)',
    '10px 10px 10px 0 rgba(0, 0, 0, 0.5)',
    'inset 0 0 5px 0 rgba(255, 255, 255, 0.8)'
  ];
  // OR
  boxShadow: [{
    // Too much code, but looks separated one box-shadow part from another
    x: 0,
    y: 0,
    blur: '50px',
    spread: '10px',
    color: 'rgba(0,0,0,0.5)'
  }, {
    blur: '5px',
    color: 'rgba(0,0,0,0.5)'
  }, {
    x: 0,
    y: 0,
    blur: '50px',
    spread: '10px',
    color: 'rgba(0,0,0,0.5)',
    inset: 'inset'
  }]
}
```
And finally, if we normalize objects before, as @kof say, it will look like this:
```javascript
button: {
  // It looks like VERY STRANGE construction and it is not so usable in real life :(
  boxShadow: {
    x: [0, '10px'],
    y: [0, '10px'],
    blur: ['10px', '10px', '5px'],
    spread: ['10px', 0, 0],
    color: [
      'rgba(0, 0, 0, 0.5)',
      'rgba(0, 0, 0, 0.5)',
      'rgba(255, 255, 255, 0.8)'
    ],
    inset: [
      // Don't know what to do here, only set 'outset'
      'outset',
      'outset',
      'inset'
    ]
  }
}
```

**Comment by typical000** [comment]
And in case of `box-shadow` we can't make any normalizations like you described in `background`

**Comment by kof** [comment]
Your last example is not what I ment, your second example sounds about right.

```javascript
button: {
  boxShadow: [
    // A little better, I think :)
    '0 0 50px 10px rgba(0, 0, 0, 0.5)',
    '10px 10px 10px 0 rgba(0, 0, 0, 0.5)',
    'inset 0 0 5px 0 rgba(255, 255, 255, 0.8)'
  ];
  // OR
  boxShadow: [{
    // Too much code, but looks separated one box-shadow part from another
    x: 0,
    y: 0,
    blur: '50px',
    spread: '10px',
    color: 'rgba(0,0,0,0.5)'
  }, {
    blur: '5px',
    color: 'rgba(0,0,0,0.5)'
  }, {
    x: 0,
    y: 0,
    blur: '50px',
    spread: '10px',
    color: 'rgba(0,0,0,0.5)',
    inset: 'inset'
  }]
}
```

**Comment by typical000** [comment]
But second example is how it works now, but this is an **array** of object. And this array breaks 'fallback' feature. How can we modify this code keeping in mind:
1. Code must be clear and understandable as much as possible
2. Don't break 'fallback' feature
?

**Comment by kof** [comment]
True, need to think about it more.

**Comment by typical000** [comment]
As for me - in **jss-shorthand** from syntax "point of view" it's all ok and all code is clear and understandable. As for 'fallback' feature by itself - I think, that combination **prop.constructor === Array => is fallback** is bad and unclear solution and can create more and more problems when JSS with plugins growth.

Maybe we need to rethink not *how to adjust shorthands plugin to avoid breaking fallback* but *how to change or make fallback feature more clear* ?  As I see it - create separated plugin, something like *jss-fallback* wich apllies fallbacks in this way:
```javascript
button: {
  background: linear-gradient(bla-bla),
  fallback: {
    background: red
  }
}
```
Why plugin - because, in my case, i haven't used such fallbacks for arount 1 or more years. Although I write CSS almost every day

**Comment by kof** [comment]
yep, you are right, fallbacks syntax is in the way.

**Comment by kof** [comment]
However fallbacks is kinda part of css and I feel like it should be part of the core in jss ...

**Comment by kof** [comment]
### So currently we have ideas:

Deprecation of array values as fallbacks:

```javascript
button: {
  background: linear-gradient(bla-bla),
  fallbacks: [
    {background: 'red'}
  ]
}
```

Keep array values for fallbacks, use a function for value formatting:

```javascript

import {boxShadow} from 'css-functions'

button: {
  background: ['linear-gradient(bla-bla)', 'red'],
  ... boxShadow([{
      x: 0,
      y: 0,
      blur: '50px',
      spread: '10px',
      color: 'rgba(0,0,0,0.5)'
  }])
}
```

**Comment by typical000** [comment]
As for me - first approach is better, because:
1. Visually, inspecting source code (styles) you can easly identify fallbacks (because they are a separated block) and remove them in near future if you need to drop supporting old browsers
2. They are used not so frequently

**Comment by kof** [comment]
updated examples

**Comment by kof** [comment]
Yep, I agree, seems like we gonna have a breaking change soon.

**Comment by typical000** [comment]
but, why we need to use array and inside object? 
```javascript
fallbacks: [
    {background: 'red'}
  ],
```
maybe just:
```javascript
fallbacks: {
    background: 'red',
    someOtherFallbackValue: value
},
```

**Comment by kof** [comment]
because you may want to have not just one fallback, you can do that in css and there are practical use casees, however we can allow both, array and object literal.

**Comment by typical000** [comment]
So:
1. Fallbacks are done. Need to adapt tests of **jss-shorthand** and possibly improve alogrythm due to https://github.com/jsstyles/jss/commit/2bee87e051bf0982afd99120b2cc3ad0561cd6d0 or just retest.
2. Solve problem with using **jss-default-unit** and **jss-shorthand** together. Because default-unit grabs only props as number, in my case there are arrays or object with nested numbers. I have already created a pull request https://github.com/jsstyles/jss-default-unit/pull/6

@kof can you have a look to pull request?

**Comment by kof** [comment]
Did a CR, see the PR. Regarding "jss-shorthand" plugin name. Any better suggestions? Because basically we are allowing a more expaneded syntax, maybe a better name would be "jss-unfold" or "jss-expand" ...

**Comment by typical000** [comment]
Ok, thanks. I'll see comments.
About name - you're right. I think that **jss-expand** will be better. I will rename it soon

**Comment by typical000** [comment]
1. Based on code review, added some fixes to jss-default-unit pull request https://github.com/jsstyles/jss-default-unit/pull/6
2. Renamed and updates **jss-shorthand** plugin.
  * New name is **jss-expand** https://github.com/typical000/jss-expand
  * Added additinal tests based on new fallback feature https://github.com/jsstyles/jss/commit/2bee87e051bf0982afd99120b2cc3ad0561cd6d0

**Comment by kof** [comment]
now version 5 is released and we can continue on this

**Comment by kof** [comment]
@typical000 do you want to host jss-expand under jsstyles organization?

**Comment by typical000** [comment]
@kof Yes. Why not. But I think it's better to add after:
1. https://github.com/jsstyles/jss-default-unit/pull/6 fixes to PR and merging it to master
2. Reorganizing code and removing now inutile functionality from **jss-expand** due to 5.1.0 version release

**Comment by kof** [comment]
What do you plan to do in jss-expand?

**Comment by typical000** [comment]
@kof https://github.com/typical000/jss-expand/issues/3 this.

**Comment by typical000** [comment]
Maybe we can close this issue? :)

**Comment by kof** [comment]
Yeah lets create more specific issues for remaining tasks.
