### ISSUE TITLE
CSS functions collection

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#226]
CSS function calls ([full list](https://docs.webplatform.org/wiki/css/functions)) can be noted as js function calls.

Currently we write things like rgba(255, 255, 255, 0.5) this way

``` javascript
button: {
  background: 'rgba(255, 255, 255, 0.5)'
}
```

Much nicer would be to create equal js functions for this css functions:

``` javascript
import {rgba} from 'css-functions'
button: {
  background: rgba(255, 255, 255, 0.5) // rgba function just returns the string we had before, it can potentially also do a fallback.
}
```

**Comment by kof** [comment]
@rofrischmann is on it

**Comment by rofrischmann** [comment]
Functions:
- [x] hsl
- [x] hsla
- [x] matrix
- [x] matrix3d
- [x] perspective
- [x] rgb
- [x] rgba
- [x] rotate
- [x] rotate3d
- [x] rotateX
- [x] rotateY
- [x] rotateZ
- [x] scale
- [x] scale3d
- [x] scaleX
- [x] scaleY
- [x] scaleZ
- [x] skew
- [x] skewX
- [x] skewY
- [x] translate
- [x] translate3d
- [x] translateX
- [x] translateY
- [x] translateZ

Validation:
- [ ] hsl
- [ ] hsla
- [ ] matrix
- [ ] matrix3d
- [ ] perspective
- [ ] rgb
- [ ] rgba
- [ ] rotate
- [ ] rotate3d
- [ ] rotateX
- [ ] rotateY
- [ ] rotateZ
- [ ] scale
- [ ] scale3d
- [ ] scaleX
- [ ] scaleY
- [ ] scaleZ
- [ ] skew
- [ ] skewX
- [ ] skewY
- [ ] translate
- [ ] translate3d
- [ ] translateX
- [ ] translateY
- [ ] translateZ

(More are added soon)

**Comment by kof** [comment]
How is it going? Can we possibly announce it on tuesday?)

**Comment by rofrischmann** [comment]
Have be away this weekend. Might continue this week :P So perhaps next week? We might release a first version without validation and add this later as I do not know how much time Ill have next weeks.

**Comment by kof** [comment]
What kind of validation would we need?

**Comment by rofrischmann** [comment]
e.g. color validation

RGB is valid if: 
* R, G and B are percentage values
* R, G and B are integers within the range [0, 255]

HSL is valid if:
* H is a number; S and L are percentage values

and so on ...

**Comment by kof** [comment]
Ah I see, we can for sure release it without it, not even sure its really needed, because one can tell if something is wrong optically.

**Comment by kof** [comment]
I think the basic implementation done, all other issues can be created on the https://github.com/cssinjs/css-functions repo. Closing this.
