### ISSUE TITLE
Clearly document public api for plugins

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#228]

**Comment by cvle** [comment]
I'm still working on the typescript definitions for jss and its plugins. This would be of good help!

**Comment by iamstarkov** [comment]
this is important for sure

**Comment by kof** [comment]
Is this good enough for now? https://github.com/cssinjs/jss/blob/master/docs/plugins.md#authoring-plugins

**Comment by kof** [comment]
We need to document the rule objects too.

**Comment by kof** [comment]
Closing this for now, once someone asks we can do more.
