### ISSUE TITLE
[jss-nested] @-rules inside of regular rules

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#246]
- [ ] Sometimes it is more practical to have @-rules like @media inside of a regular rule. 
- [ ] When extending a rule with an at-rule inside, all of them should apply to the extended rule

```js
return {
  button: {
    fontSize: 12,
    '@media (min-width: 1024px)': {
      width: 200
    }
  },
  ctaButton: {
    extend: 'button',
    '&:hover': {
      background: 'red'
    }
  }
}
```

**Comment by alebiavati** [comment]
Hi, I would like to try implementing this. Could you give me some pointers to get started?

**Comment by kof** [comment]
Allright, create a repo, take  jss-nested as a template. Let me know on gitter if you need help.

**Comment by kof** [comment]
Hmm, maybe it could be even part of jss-nested instead of a separate plugin.

**Comment by kof** [comment]
In this case you may want to fork jss-nested and try to add this functionality.

**Comment by kof** [comment]
Let me know if this requires any changes in core.

**Comment by kof** [comment]
@alebiavati any updates?

**Comment by johann-sonntagbauer** [comment]
@kof @alebiavati any updates on that topic? tried to implement that feature as well and it seems strait forward. One question is how to test in combination with jss-extend. Where should we place tests where several plugins are involved?

**Comment by kof** [comment]
I think it is ok to add a plugin as a dev dependency and just add tests for it right away.

**Comment by johann-sonntagbauer** [comment]
all right then I will add the testcases and formulate a PR. 
@kof Is there already some utility to merge styles of a rule?

**Comment by kof** [comment]
using es6 {...}

**Comment by johann-sonntagbauer** [comment]
of course :)

**Comment by alebiavati** [comment]
Sorry for the delay, I couldn't find the time to work on it. Thanks @johann-sonntagbauer for picking this up!

**Comment by kof** [comment]
@johann-sonntagbauer this feature is very important because after we have it, I will create an official release of  https://github.com/cssinjs/aphrodisiac

**Comment by johann-sonntagbauer** [comment]
oh nice ;) i will finalize over the weekend

**Comment by johann-sonntagbauer** [comment]
formulated a PR with the changes. Added the missing test case with jss-extend. 
https://github.com/cssinjs/jss-nested/pull/14

**Comment by kof** [comment]
released

**Comment by trusktr** [comment]
Its so cool that this is actually close to the official CSS Nesting syntax that is now out in all browsers. :D

```css
.foo {
  color: red;

  @media (min-width: 400px) {
    color: blue;
  }
}
```
