### ISSUE TITLE
Peer warnings after v5.x update

### ISSUE THREAD

**Issue by jacksonrayhamilton** [cssinjs/jss#249]
I am getting the following peer warnings after updating to v4.x:

```
npm WARN jss-nested@1.0.3 requires a peer of jss@>=3.0.0 < 4.0.0 but none was installed.
npm WARN jss-vendor-prefixer@2.0.0 requires a peer of jss@^3.3.0 but none was installed.
```

Should those packages' version ranges be updated?

**Comment by kof** [comment]
yep

**Comment by umidbekkarimov** [comment]
@kof maybe you should integrate [greenkeeper](https://greenkeeper.io/) support and configure [travis-ci](https://docs.travis-ci.com/user/deployment/npm) deployment to get rid of publishing routine

**Comment by kof** [comment]
I have tried greenkeeper before, it was very spammy because of some frequently updating dependencies. How do you want to automate exact this issue?

**Comment by umidbekkarimov** [comment]
@kof 

> I have tried greenkeeper before, it was very spammy

Yeah it's spammy, but you can update all dependencies with several clicks.

> How do you want to automate exact this issue?

Greenkeeper would update package versions for you - all you need is to accept PRs
Travis CI will track changes in branch and publish it to NPM (if you change `version` property of course)

Here example of [travis.yml](https://github.com/umidbekkarimov/react-should-update/blob/master/.travis.yml) file that I use

**Comment by kof** [comment]
It's not that simple, I tried.

**Comment by kof** [comment]
And it has nothing to do with this issue.

**Comment by kof** [comment]
Once you get the PR from greenkeeper and it contains major version increminations and tests fail, you need to fix incompatibility by yourself. It's not a big help those pr, much more work is to do the rest. I prefer to just periodically run `npm outdated` when I got time to upgrade and ensure everything works.

**Comment by kof** [comment]
Now version 5 is released, need to update all plugins, feel free to help

**Comment by kof** [comment]
should be no warnings any more, please reopen if there are still any.
