### ISSUE TITLE
[jss-compose] Plugin for classes composition

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#265]
Original issue #247 

In order to use a pure CSS framework together with JSS, we can introduce  a plugin, which will compose the selector similar to [css-modules compose](https://github.com/css-modules/css-modules#composition)

```javascript
export default {
  button: {
    composes: ['btn',  'btn-primary'],
    color: 'red'
  }
}
```

Compiles to

```css
.button-12345 {
   color: red;
}
```

However when you use it (React example):

```html
<button className={sheet.classes.button}>My Button</button>
```

It renders to

```html
<button class="btn btn-primary button-12345">My Button</button>
```

**Comment by kof** [comment]
Another use case is to use local rules for composition:

```javascript
export default {
  button: {
    display: 'inline-block'
  },
  ctaButton: {
    composes: ['$button'],
    color: 'red'
  }
}
```

**Comment by zerkalica** [comment]
Why not to merge ctaButton with button?

```js
const button = {display: 'inline-block'}

const ctaButton = {
  ctaButton: {
    ...button,
    color: red
  }
}
```

**Comment by kof** [comment]
Because this way you can have 2 separate rules, but still be able to put them both at once:
```html
<div className={classes.ctaButton}></div>
```
Will result in

```html
<div class="button-123456 ctaButton-345234"></div>
```

**Comment by typical000** [comment]
I'll try to implement this plugin

**Comment by typical000** [comment]
@kof Good news! :) https://github.com/typical000/jss-compose pushed first stable version of jss compose. Can you take a look and review it? If it's all ok - I'll transfer repo to cssinjss org.

**Comment by typical000** [comment]
@kof Did you watched jss-compose? :)

**Comment by kof** [comment]
Yep, I was busy with other tasks you probably saw in the recent releases. It looks good.

Here are the next steps:
- [ ] move it to cssinjs org
- [ ] some stylistic changes in code (reduce indentation level), will do it myself
- [ ] review documentation (will do or @nathanmarks or anybody are welcome as well)
- [ ] add it to the test suite in jss repository same way jss-nested is added
- [ ] add it to jss-default-preset
- [ ] announce an official release

**Comment by typical000** [comment]
Transfered

**Comment by typical000** [comment]
Added pull request to jss-preset-default: https://github.com/cssinjs/jss-preset-default/pull/2

**Comment by typical000** [comment]
> add it to the test suite in jss repository same way jss-nested is added

@kof did you mean inside branch **feature/plugins-test-219** ?

**Comment by kof** [comment]
nope, will add it, I am on it for react-jss right now.

**Comment by kof** [comment]
@typical000 can you add me to the package on npm ?

**Comment by kof** [comment]
@typical000 I would publish it, it is ready, but I need npm package access.

**Comment by typical000** [comment]
@kof sure. Just added you. Can you try to publish new version? Now console tells:
``````````
> npm owner ls
kof <oleg008@gmail.com>
typical000 <typical000@gmail.com>

**Comment by typical000** [comment]
@kof Not about jss-compose, but I have just added you to https://www.npmjs.com/package/jss-expand too

**Comment by kof** [comment]
Released.
