### ISSUE TITLE
Is there any way I can use sass features with jss?

### ISSUE THREAD

**Issue by techyrajeev** [cssinjs/jss#276]
I am trying to generate styles dynamically based on color provided.

```
const styles = function(btnColor){
    return {
        btnTest : {
            borderColor     : darken(btnColor, '20%'),
            backgroundColor : btnColor
        }
    }
};
```

I am getting error as darken is not defined. How can I use sass features with jss ? 
Please guide.
 Thanks

**Comment by kof** [comment]
You can use this library for color conversions. It is unrelated to jss. https://www.npmjs.com/package/color
