### ISSUE TITLE
[jss-vendor-prefixer] Unmet peer dependency

### ISSUE THREAD

**Issue by techyrajeev** [cssinjs/jss#277]
I got this warning while installing  jss-vendor-prefixer, although I have installed jss@latest version

```
+-- UNMET PEER DEPENDENCY jss@5.2.0
`-- jss-vendor-prefixer@2.0.0 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN jss-camel-case@1.1.0 requires a peer of jss@>= 3.0.0 < 4.0.0 but none was installed.
npm WARN jss-extend@1.2.1 requires a peer of jss@>=3.1.1 < 4.0.0 but none was installed.
npm WARN jss-nested@1.0.3 requires a peer of jss@>=3.0.0 < 4.0.0 but none was installed.
npm WARN jss-vendor-prefixer@2.0.0 requires a peer of jss@^3.3.0 but none was installed.
```

**Comment by kof** [comment]
not all peerDeps are updated yet.

**Comment by kof** [comment]
in plugins packages.

**Comment by kof** [comment]
duplicate #249

**Comment by techyrajeev** [comment]
I think problem still persists with other plugins

npm WARN jss-camel-case@1.1.0 requires a peer of jss@>= 3.0.0 < 4.0.0 but none was installed.
npm WARN jss-extend@1.2.1 requires a peer of jss@>=3.1.1 < 4.0.0 but none was installed.
npm WARN jss-nested@1.0.3 requires a peer of jss@>=3.0.0 < 4.0.0 but none was installed.

**Comment by kof** [comment]
yes I know, you can fix it too.

**Comment by techyrajeev** [comment]
I have some confusion here. I need these packages to be installed on server side via post install script. How can I then update the peer dependencies?

**Comment by kof** [comment]
How is a warning a problem ...?

**Comment by techyrajeev** [comment]
I am not able to push to heroku. It rejects the build.

**Comment by kof** [comment]
Why, because of warnings?

**Comment by techyrajeev** [comment]
remote:        npm ERR! node v4.4.5
remote:        npm ERR! npm  v2.15.5
remote:        npm ERR! code EPEERINVALID
remote:        
remote:        npm ERR! peerinvalid The package jss@5.2.0 does not satisfy its siblings' peerDependencies requirements!
remote:        npm ERR! peerinvalid Peer jss-camel-case@1.1.0 wants jss@>= 3.0.0 < 4.0.0
remote:        npm ERR! peerinvalid Peer jss-default-unit@4.0.0 wants jss@^5.1.0
remote:        npm ERR! peerinvalid Peer jss-extend@1.2.1 wants jss@>=3.1.1 < 4.0.0
remote:        npm ERR! peerinvalid Peer jss-nested@1.0.3 wants jss@>=3.0.0 < 4.0.0
remote:        npm ERR! peerinvalid Peer jss-vendor-prefixer@2.0.0 wants jss@^3.3.0
remote:        
remote:        npm ERR! Please include the following file with any support reque

It is giving me error not warning.

**Comment by kof** [comment]
Oh errors is bad, this needs to be fixded in the plugins asap.

**Comment by kof** [comment]
Will update the plugins in a few hours.

**Comment by techyrajeev** [comment]
Thanks a lot @kof

**Comment by kof** [comment]
now you need to run `npm outdated` and update all jss related dependencies

**Comment by techyrajeev** [comment]
Yes did that and installed the latest ones. Now its working :+1:

**Comment by kof** [comment]
👍
