### ISSUE TITLE
Todo app example

### ISSUE THREAD

**Issue by tizmagik** [cssinjs/jss#278]
Here's a TODO app example using JSS. Not sure if this is helpful or if you'd like to include it in examples doc or whatever, but I thought I'd bring it to your attention. :)

https://github.com/tizmagik/react-todomvc-jss

**Comment by kof** [comment]
Nice, has this been submitted to todomvc repository?

**Comment by kof** [comment]
https://github.com/tastejs/todomvc

**Comment by kof** [comment]
Added a link http://cssinjs.github.io/examples/index.html

**Comment by kof** [comment]
Would be nice to have  an online version of it, for e.g. generate everything in the gh-pages branch ...
