### ISSUE TITLE
[jss-camel-case] Integration with jss-expand plugin

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#281]
Need to update plugin with recursive tree traversing like it was done in **jss-default-unit** - cssinjs/jss-default-unit#6
More expanded description was added in issue from **jss-expand** repo:
https://github.com/typical000/jss-expand/issues/5

**Comment by kof** [comment]
yep

**Comment by kof** [comment]
which props from jss-expand require camelization?

**Comment by typical000** [comment]
You can find them here: https://github.com/typical000/jss-expand/blob/master/src/props.js
1. timing-function
2. iteration-count
3. fill-mode
4. play-state

But, now, I thinked more and - if I'll add camelCased options to my config such: 
````````````````````js
  'transition': {
    property: null,
    duration: null,
    'timing-function': null,
    timingFunction: null, // Needed for avoiding issues with jss-camel-case
    delay: null
  },
````````````````````
there is no need to update **jss-camel-case** and make it less performant. But this solution from one point of view looks like hardcode :)

**Comment by kof** [comment]
Good idea, I think that's ok if we know exactly all cases.

**Comment by typical000** [comment]
So, we can close this. Further updates will be done in **jss-expand** repo
