### ISSUE TITLE
[jss-hex][idea] Allow to write colors without strings

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#282]
Idea was came to me from recent experience with three.js where one of methods to define colors was hex format like: `new THREE.Color(0xd4d4d5)`.
So, we can try to write a plugin that enables for us writing colors in HEX format like:
````````````````````js
foo: {
  color: 0xF00, // Shorthand HEX syntax. Will be converted to '#f00' or 'rgba(255, 0, 0)'
  backgroundColor: 0xFF0000, // Normal HEX syntax
}
````````````````````
Also, we can write in terms of plugin a punch of color functions like (I'm looking SASS functions as reference: http://sass-lang.com/documentation/Sass/Script/Functions.html )
````````````````````js
foo: {
  color: rgba(0xFF0000, 0.5), // Converts to 'rgba(255, 0, 0, 0.5)'
  backgroundColor: lighten(0xFF0000, 1.2), // Make color lighten by 1.1x (by 10%)
  backgroundColor: lighten(0xFF0000, '10%'), // Make color lighten by 10%
  color: darken(0xFF0000, 1.5), // The same as lighten but darken :)
  ...
}
````````````````````

But there is one big question - how to detect that number was defined in HEX format.
Because if we write `0x000000` in reality it is just `0`. And I haven't fond any solution or function like `isHexNumber`. Only functions that detects if string is hex number (but the main goal of this plugin is to discard writing strings).

Other solution is, if there is no way to detect if number is hex - add a config like:
````````````````````js
foo: {
  color: true,
  backgroundColor: true,
  borderColor: true,
  ...
  etc.
}
````````````````````
But this case:
1. Is less performant
2. Need a config that must be updated and maintained

**Comment by kof** [comment]
1. What is the benefit of using hex colors?
2. I use this tool for colors conversion https://github.com/qix-/color

**Comment by typical000** [comment]
1. In most of cases colors are set in rgb format, without opacity. Just for writing colors without strings, and don't use side plugins\tools
2. Interesting... And looks good. Need to try. Maybe, if it's so easy and convenient in use - add somewhere link to this tool as "reccomended"?

**Comment by kof** [comment]
I don't see any generic way to detect if a number is in hex. Writing a plugin which knows all specific color properties and converts hex number to hex string is a bit too much overhead for a feature that is mostly just for fun.

Yes we should recommend this color util somewhere.

**Comment by kof** [comment]
Maybe just use it in the example ... and additionally link it somewhere in the JSON dsl.

**Comment by kof** [comment]
I think we can close this issue for now.
