### ISSUE TITLE
[jss-nested] Unexpected order in generated style

### ISSUE THREAD

**Issue by cvle** [cssinjs/jss#285]
This stylesheet generates classes in wrong order:

    const stylesheet = {
      button: {
        "&:hover": {
          background: "rgba(255, 255, 255, 0.1)",
        },
        background: "none",
      },
      // This disables hover on mobile devices.
      "@media (hover:none)": {
        button: {
          "&:hover": {
            background: "none",
          },
        },
      },
    };

Output:

    .button-2260332263 {
      background: none;
    }
    @media (hover:none) {
      .button-2260332263:hover {
        background: none;
      }
    }
    .button-2260332263:hover {
      background: rgba(255, 255, 255, 0.1);
    }

Should be:

    .button-2260332263 {
      background: none;
    }
    .button-2260332263:hover {
      background: rgba(255, 255, 255, 0.1);
    }
    @media (hover:none) {
      .button-2260332263:hover {
        background: none;
      }
    }

Workaround using `!important`:

    const stylesheet = {
      button: {
        background: "none",
        "&:hover": {
          background: "rgba(255, 255, 255, 0.1)",
        },
      },
      // This disables hover on mobile devices.
      "@media (hover:none)": {
        button: {
          "&:hover": {
            background: "none !important",
          },
        },
      },
    };

**Comment by kof** [comment]
Yeah, the problem is that plugins are processed in a separate loop since c40c616fc0b5c68eabb1e34f842229a40f674c08

**Comment by kof** [comment]
This has been done to allow referencing rules from nested rules.

**Comment by kof** [comment]
Now the problem is that we need to put nested rules in the old order, which is actually not that easy ... it requires either to sort the rules map on every nested rule or to introduce additional mechanism for saving the order of rules and using this order when generating css.

**Comment by cvle** [comment]
I removed the workaround because it's not working, still trying to find a way to get around this.

**Comment by kof** [comment]
adding an !important would work ...

**Comment by cvle** [comment]
Confirmed. Pretty ugly but works for me, at least for now. Adding a workaround above.

**Comment by kof** [comment]
Released.
