### ISSUE TITLE
[jss-camel-case] Add links to plugins wiki on all plugin readmes

### ISSUE THREAD

**Issue by vass-david** [cssinjs/jss#286]
My code:

```
const styles = {
    test2: {
        '& $testBla': {
            color: 'black',
        },
    },
    testBla: {
        color: 'white',
    },
};
```

Output:
```
.testBla-1336468699 {
  color: white;
}
.test2-1635931442 test-bla {
  color: black;
}
```

When I comment jss-camel-case, the output is correct:
```
.testBla-1336468699 {
  color: white;
}
.test2-1635931442 .testBla-1336468699 {
  color: black;
}
```

My jss config:
```
import jss from 'jss';
import jssCamelCase from 'jss-camel-case';
import jssNested from 'jss-nested';
import jssVendorPrefixer from 'jss-vendor-prefixer';
import jssDefaultUnit from 'jss-default-unit';

jss.use(
    jssCamelCase(),
    jssNested()
);

export default jss;
```

However it works when classname is not in camelCase.

**Comment by kof** [comment]
Thanks, sounds like a but, will check it soon.

**Comment by vass-david** [comment]
Found problem and solution. If you configure jss like this:
```
jss.use(
    jssCamelCase(),
    jssNested()
);
```
the input to jss-camel-case is pure unprocessed javascript object and jss-camel-case thinks that every property of nested object is css property. However if you put it to the end like this:
```
jss.use(
    jssNested(),
    jssCamelCase()
);
```
it works! And there is a question, is it a bug? IMHO it should be expected. I think that only "solution" would be to write a warning to jss-nested README.md, so users will put jss-nested as first argument of `use` method, if any other plugin depends or modifies css properties. What do you think?

**Comment by kof** [comment]
Right, this is actually documented https://github.com/cssinjs/jss/blob/master/docs/plugins.md#order-does-matter-here-is-the-right-one

Lets link all plugins to this page. @vass-david can you send me pr's in all plugins repositories?

**Comment by vass-david** [comment]
Done

**Comment by kof** [comment]
Thanks.
