### ISSUE TITLE
compatibility with hyperscript on server

### ISSUE THREAD

**Issue by tusharmath** [cssinjs/jss#292]
[Hyperscript]() depends on [html-element](https://github.com/1N50MN14/html-element/blob/master/index.js#L1) which internally setups a mock `document` object on the `global` object when run in node.js env.

This causes the [findRenderer](https://github.com/cssinjs/jss/blob/master/src/findRenderer.js#L15) to bailout because it depends on the `document` object.

```stack
TypeError: document.getElementsByTagName is not a function
    at DomRenderer.createElement (/Users/tushar.mathur/Documents/Projects/funag/node_modules/jss/lib/backends/DomRenderer.js:39:45)
    at new StyleSheet (/Users/tushar.mathur/Documents/Projects/funag/node_modules/jss/lib/StyleSheet.js:59:19)
    at Jss.createStyleSheet (/Users/tushar.mathur/Documents/Projects/funag/node_modules/jss/lib/Jss.js:100:19)
    at create (CreateStyle.js:16:26)
    at Object.<anonymous> (loader.style.js:9:16)
    at Module._compile (module.js:541:32)
    at loader (/Users/tushar.mathur/Documents/Projects/funag/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tushar.mathur/Documents/Projects/funag/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

I guess the better way to do this would be to use something like [detect-node](https://github.com/iliakan/detect-node)

**Comment by kof** [comment]
html-element creates a wrong document object and breaks anything that detects dom and tries to use it. I don't see jss is doing anything wrong here ....

**Comment by kof** [comment]
html-element was created to make hyperscript work, not any dom dependent code.

**Comment by kof** [comment]
Also you can explicitly pass the VirtualRenderer backend to avoid any DOM related methods.

**Comment by kof** [comment]
> I guess the better way to do this would be to use something like detect-node

JSS is not detecting node, it is detecting dom. Potentially jss could run on any serverside platform. It doesn't need to have node specific logic.

**Comment by kof** [comment]
Closing this for now, let me know if you could achieve what you wanted.

**Comment by kof** [comment]
I found something that makes sense and should help you.

**Comment by kof** [comment]
@tusharmath please try master version, if it doesn't work please reopen.

**Comment by tusharmath** [comment]
thanks a ton!

**Comment by tusharmath** [comment]
@kof It's not possible to directly consume it via master seems. Would it be possible for you to release it via a different `npm dist-tag` ? It would be really nice to finally be able to use this feature.

**Comment by kof** [comment]
what is the problem with `npm i cssinjs/jss#master` ?

**Comment by alexkuz** [comment]
> I found something that makes sense and should help you.

@kof as far as I understand, this solution relies on module bundler using `browser` or `main` setting in `package.json`. I think it's worth mentioning [here](https://github.com/cssinjs/jss/blob/master/docs/ssr.md), that using this with webpack for server rendering requires `resolve.packageMains` to be changed (`browser` should be omitted):
https://webpack.github.io/docs/configuration.html#resolve-packagemains

**Comment by kof** [comment]
this is a matter of webpack configuration, why should we document this in jss?

**Comment by alexkuz** [comment]
Hm, you're probably right - I guess `browser` shouldn't be there anyway for SSR. It's just here is the first case I'm facing this issue - haven't seen this approach before (and if it relies on non-popular technique, I suppose, it wouldn't hurt to mention it). Maybe it is more common in `browserify` world, I don't know.
