### ISSUE TITLE
[JssProvider] React component

### ISSUE THREAD

**Issue by umidbekkarimov** [cssinjs/jss#295]
Currently i'm migrating my single page application to work on server and found some solvable problems.

#### Problem 1: (from #279)
`jss-vendor-prefixer` works only on client side 
##### Solution:
Make `jss-vendor-prefixer` work with `user-agent`,
e.g. `jss.use(jssVendorPrefixer({userAgent: req.headers['user-agent']}))`

#### Problem 2: (from https://github.com/cssinjs/jss/issues/279#issuecomment-241276092)
`jss` singleton is handy for client side, but on server side you need to create new instance for it in order to solve **Problem 1** but `useSheet` from `react-jss` works only with singleton versions of `jss`
##### Solution:
Make `useSheet` also work with React `context` e.g.
```javascript
// in react-jss

class StyleSheetWrapper extends React.Component {
    static wrapped = DecoratedComponent
    static displayName = `JSS(${displayName})`
   
    static contextTypes = {
        jss: React.PropTypes.object
    }
    componentWillMount() {
      this.jss = _jss /* instance passed in `useSheet` */ || this.context.jss /* instance from context */ || jss /* jss singleton */
      this.sheet = ref()
    }

// In your app
const jss = createJSS()
jss.use(jssVendorPrefixer({userAgent}))

render( // or renderToString for ssr
    <JssProvider jss={jss}>
        {/* ... */}
    </JssProvider>
)
```

#### Problem 3: (Just a proposal)
[Server side rendering](https://github.com/cssinjs/jss/blob/master/docs/ssr.md) works, but can be improved for react apps
##### Solution:
`JssRender` - component to generate style tags with rules
`JssAttach` - component to attach jss rules (will use `JssRender` under the hood, so react will take care of replacing rules)
e.g.
```javascript
// On server side
const stylesheets = renderToString(<JssRender jss={jss}/>)
// On client side
render(<JssAttach jss={jss}>, document.getElementById('jss-styles'))
```
##### Problem with proposal:
It's not possible to render array of components, so `JssRender` have to render style tags inside of another element (`div`), so it can't be mounted inside `head` element and this is not right, so this proposal not finished yet

**Comment by kof** [comment]
Problem 1 -> please comment on the corresponding issue.

> but useSheet from react-jss works only with singleton versions of jss

You can pass your jss instace and get a useSheet function which knows your jss.
https://github.com/cssinjs/react-jss#es6

Problem 3 -> there is already an issue on react-jss project, we have discussed a lot, it's time to prototype something, also we may not need to because @nathanmarks is implementing a full featured integration https://github.com/nathanmarks/jss-theme-reactor

**Comment by kof** [comment]
> Make useSheet also work with React context

This is easy, however this is needs to be a complete solution, well through thought. Will just adding jss from context to react-jss help you?
