### ISSUE TITLE
Move same dependencies and npm tasks to a separate repo

### ISSUE THREAD

**Issue by okonet** [cssinjs/jss#310]
https://github.com/FormidableLabs/builder allows having a separate repository for same dependencies and common tasks for different common projects. JSS looks like a great use case for it and I think it's worth trying.

**Comment by kof** [comment]
Another option is https://github.com/lerna/lerna

**Comment by kof** [comment]
I still feel like I could write something way more simple:

1. Create a package for e.g. named "merge-package"
1. Put into that package a package.json file with a base defaults.json which should act like a defaults when merging it with your local package.json.
1. Create a  runnable script which will merge the defaults with the local package.json and write into it.

The workflow will look like that:

1. Keep the one repository updated with defaults.json
1. Go into one of the managed repositiories
1. Run package.json updater.
1. Commit the updated package.json, release as always.

**Comment by kof** [comment]
Ok the plan for now is:

1. Every package we want to test from jss test runner creates a build into `tests` dir. That built contains all tests as well the sources compiled to cjs/es3 (yes es3 is needed to support IE9 stuff like "default"). 
2. JSS repository has all devDependencies needed to run the tests those packages. Yes, it will potentially break if some of the packages expects a newer version than the one used in the main repo, however we will see it as we run the tests.
3. JSS main test entry will import tests from `tests` folder of those packages.

**Comment by kof** [comment]
So far didn't see a good fit for jss. Will go for a boilerplate for now.
