### ISSUE TITLE
Use "warning" package

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#314]
We currently use in jss-nested and in jss-extend (I think thats only 2 places, but need to search) `console.warn` to write some warnings into console. Package "warning" seems to be a good thing because it also creates a stacktrace. Also it will be removed in production, so its size doesn't matter. It is a clone of fbjs/warning modules.

https://github.com/BerkeleyTrue/warning/

**Comment by kof** [comment]
As discussed @nathanmarks

**Comment by typical000** [comment]
https://github.com/cssinjs/jss/issues/265 in jss-compose warnings are used too

**Comment by wldcordeiro** [comment]
How would we like to add this? Expose the `warning` package API as part of JSS core to its plugins? I could take a stab at this but it looks like we just need to elaborate on how we'd like the integration to look like.

**Comment by kof** [comment]
its already done mostly https://github.com/cssinjs/jss-nested/blob/master/src/index.js

Need to check which plugins need it too.

**Comment by kof** [comment]
It is jss-extend only.

**Comment by kof** [comment]
done.
