### ISSUE TITLE
Guidance on using static flexboxgrid css through CLI

### ISSUE THREAD

**Issue by rosskevin** [cssinjs/jss#316]
@kof , I could really use some guidance here.

I would like to use my jss process with flexboxgrid.com's css. I'm aware of [roylee0704/react-flexbox-grid](https://github.com/roylee0704/react-flexbox-grid) but I just don't like the approach.

Given that most of their code simply uses the original flexboxgrid.com code as a css module, I figured I could do the same with jss.

## Implementation

So, to get the flexigrid.com `src` css as json, I use the following:

```javascript
const myth = require('myth')
const fs = require('fs')
const cssToJss = require('jss-cli').cssToJss

const mythCss = fs.readFileSync('node_modules/flexboxgrid/src/css/flexboxgrid.css', 'utf8')

// run myth to generate css without prefixes
const css = myth(mythCss, {browsers: []})

// convert css to json using jss-cli
const jss = cssToJss({code: css})

// make es2015 content
const jssJson = `export default ${JSON.stringify(jss, null, 2)}\n`.replace(/"/g, "'")

// save es2015 file
fs.writeFileSync('./ui/src/components/Grid/flexboxgrid.js', jssJson)
```

This gives me [this json es6 source file](https://gist.github.com/rosskevin/c4229456e83436b7c60fc3a79a9cddf8#file-flexboxgrid-js).

I then create a styleSheet for use amongst the components: 

```javascript
// @flow
import {createStyleSheet} from 'jss-theme-reactor'
import flexboxgrid from './flexboxgrid'

const styleSheet = createStyleSheet('flexboxgrid', () => {
  return flexboxgrid
})

export default styleSheet
```

And then try and use it (example `Grid` component):

```javascript
// @flow
import React, {Component, PropTypes} from 'react'
import classNames from 'classnames'
import pure from 'recompose/pure'
import styleSheet from './styleSheet'

type Props = {
  children: Element<any>,
  component: string,
  fluid: boolean,
  className: ?string,
}

class Grid extends Component<DefaultProps, Props, void> {
  static contextTypes = {
    styleManager: PropTypes.object.isRequired
  }
  static defaultProps: DefaultProps = {
    component: 'div',
    fluid: false
  }
  props: Props

  render (): Element<any> {
    const classes = this.context.styleManager.render(styleSheet)
    const { children, component, className: classNameProp, fluid, ...rest } = this.props
    const className = classNames({
      [classes[ '.container-fluid' ]]: fluid, // use without the leading '.' didn't work...hmmm
      [classes[ '.container' ]]: !fluid
    }, classNameProp)

    return React.createElement(component, { className, ...rest }, children)
  }
}

export default pure(Grid)
```

## Questions

1.  The [browser rendered css appears to have extra dots in front of class names](https://gist.github.com/rosskevin/c4229456e83436b7c60fc3a79a9cddf8#file-browser-rendered-css-html), what am I missing in this process?
  ```css
..container-fluid, .container-4008186696 {
  margin-left: auto;
  margin-right: auto;
}
  ```
2.  In the `render`, I also had to specify my class with a leading dot(`.`), whereas I don't normally.

3.  It doesn't look like jss is converting selectors properly, the source `'.container-fluid, .container'` turns into `.container-fluid, .container-4008186696`

3.  Is using the original `src` css from flexigrid.com a non-starter?  I'd like to only take on the react interface to the smarter css code, not an entire grid system itself.  Thoughts?

**Comment by kof** [comment]
Nice! First of all, converter was experimental and is probably not much in use in the wild. I never had time to finish a number of feature it needs (#166)

1. The dots: css you are trying to convert has global selectors. JSS is by default named: true. In order to use global style CSS as is, you need to put option named: false.
1. Yes its because of point 1. You have class names as rule names.
1. Same problem
1. Yes, you actually want to convert source (scss/sass whatever) to jss. It would be much nicer. You would be able to convert variables, functions etc, which would result in smaller code and it could be modularized.

The code you wrote basically would work if you put named: false into options, however the flexboxgrid selectors become global and you loose namespacing.

Another option is to enhance the css to jss converter and make it
- Use rule names instead of class names and use the named sheet which it is by default. You would basically need to remove prefixes like dots and camelize the selectors.
- Then you would need to properly convert  selectors like '.a .b .c {}' to 3 separate rules, also you could make use of jss plugins like jss-extend etc.

**Comment by rosskevin** [comment]
Thanks @kof.  I see I could go the global route, but I think I'll give it a shot and convert the source fully so it is jss enabled.  Thanks again.

**Comment by rosskevin** [comment]
BTW - I'm working on this internally, would love to open source it but don't want to be the owner of it (I don't have time to maintain yet another OS project).  If anyone wants to take ownership, I'm happy to contribute all my work.

**Comment by kof** [comment]
@rosskevin I think we could add this to jss-cli repository, lets talk about how you approaching this!

**Comment by rosskevin** [comment]
@kof - I just used a couple of regexes and converted the rest manually.  I don't think there is much if any value to add to the cli repo.  I was speaking more of having a JSS based grid project out there, which I'm willing to contribute the code I converted.

Regarding how I ended up, here's the bulk of the conversion (the rest was manual):

```javascript
const myth = require('myth')
const fs = require('fs')
const cssToJss = require('jss-cli').cssToJss
const camelCaseLib = require('camelcase')

function cleanMultiSelector (key) {
  const selectors = key.split(',')
  const newSelectors = []
  for (let selector of selectors) {
    selector = camelCaseLib(selector.trim())
    // console.log(selector)
    newSelectors.push(selector)
  }

  const newSelector = newSelectors.join(', ')
  return newSelector
}

//------------------------------------------------------------------------------------------
// this is a modified version of https://github.com/substack/camelize/blob/master/index.js
function walk (obj) {
  if (!obj || typeof obj !== 'object') return obj
  if (isDate(obj) || isRegex(obj)) return obj
  if (isArray(obj)) return map(obj, walk)
  return reduce(objectKeys(obj), function (acc, key) {
    if (key !== ':root') {
      var camel = camelCase(cleanMultiSelector(key))
      acc[ camel ] = walk(obj[ key ])
    }
    else {
      acc[ key ] = obj[ key ]
    }
    return acc
  }, {})
}
function camelCase (str) {
  return str.replace(/[_.-](\w|$)/g, function (_, x) {
    return x.toUpperCase()
  })
}

var isArray = Array.isArray || function (obj) {
    return Object.prototype.toString.call(obj) === '[object Array]'
  }

var isDate = function (obj) {
  return Object.prototype.toString.call(obj) === '[object Date]'
}

var isRegex = function (obj) {
  return Object.prototype.toString.call(obj) === '[object RegExp]'
}

var has = Object.prototype.hasOwnProperty
var objectKeys = Object.keys || function (obj) {
    var keys = []
    for (var key in obj) {
      if (has.call(obj, key)) keys.push(key)
    }
    return keys
  }

function map (xs, f) {
  if (xs.map) return xs.map(f)
  var res = []
  for (var i = 0; i < xs.length; i++) {
    res.push(f(xs[ i ], i))
  }
  return res
}

function reduce (xs, f, acc) {
  if (xs.reduce) return xs.reduce(f, acc)
  for (var i = 0; i < xs.length; i++) {
    acc = f(acc, xs[ i ], i)
  }
  return acc
}
//------------------------------------------------------------------------------------------

const srcCss = fs.readFileSync('node_modules/flexboxgrid/src/css/flexboxgrid.css', 'utf8')

// run myth to generate css without prefixes
// const css = myth(srcCss, {browsers: []})

// convert css to json using jss-cli
let jss = cssToJss({ code: srcCss })

// recursive walk and camelize keys
jss = walk(jss)

// make es2015 content
let jssJson = `export default ${JSON.stringify(jss, null, 2)}\n`
  .replace(/"/g, "'")
  .replace(/'(\w+)':/g, '$1:')
  .replace(/'@media \(SmViewport\)'/g, "[theme.breakpoints.up('sm')]")
  .replace(/'@media \(MdViewport\)'/g, "[theme.breakpoints.up('md')]")
  .replace(/'@media \(LgViewport\)'/g, "[theme.breakpoints.up('lg')]")

// save es2015 file
// fs.writeFileSync('./ui/src/components/Grid/flexboxgrid.js', jssJson)

// save the es2015ish file (invalid)
fs.writeFileSync('./target/flexboxgrid-jss.js', jssJson)
```
