### ISSUE TITLE
[jss-vendor-prefixer] Weird prefix bug with transitions in IE

### ISSUE THREAD

**Issue by cvle** [cssinjs/jss#317]
I have a weird bug:

On IE11 this works correctly 

```
{
  root: {
     transition: "all 550ms ease-in 0ms",
  }
}

# becomes:
transition: all 550ms ease-in 0ms;
```

But without specifying the delay, it gives me a wrong output:

```
{
  root: {
     transition: "all 550ms ease-in",
  }
}

# becomes:
transition: -ms-all 550ms ease-in;
```

I couldn't reproduce this on an older webkit browser.

**Comment by kof** [comment]
Interesting bug.

**Comment by cvle** [comment]
I just noticed using a delay other than zero will result in the same bad prefix.

**Comment by cvle** [comment]
Edge browser does the same but with the `-webkit-` prefix.

**Comment by kof** [comment]
@cvle can you help out with this bug?

**Comment by cvle** [comment]
Sure, once I get some spare time, though this might take a while.

**Comment by kof** [comment]
Is it a matter of weeks?

**Comment by cvle** [comment]
Hm.. ok, let me take a first look at it next week. I'll write about what I find.

**Comment by cvle** [comment]
I tracked down the bug in `css-vendor`.

IE screwed up again and behaves like this:
```javascript
el.style["transition"] = "all 200ms ease"
console.log(el.style["transition"])
```
```
200ms ease
```

I'm preparing a PR.

**Comment by kof** [comment]
hmm, how can we fix that?

**Comment by kof** [comment]
Rewrote tests, added ci with browserstack, no need to fix some failing tests and then I can take a look at this thing. If you can help me fixing those failing tests, it would speed up everything.

**Comment by kof** [comment]
Do you have a browserstack account u can use ?

**Comment by cvle** [comment]
> Do you have a browserstack account u can use ?

Unfortunately not.

**Comment by kof** [comment]
Ping me on gitter, I will give you access to my browserstack account.

**Comment by AleshaOleg** [comment]
Done in https://github.com/cssinjs/css-vendor/pull/26. This one, can be closed.
