### ISSUE TITLE
[jss-nested] rules order in attached sheet when using .addRule

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#318]
Currently when a sheet is already deployed and attached and addRule is used, the order is not correct. Nested rules are added before their parents. Index option is not used in StyleSheet.addRule method in this case. It is not possible to insert rules at any position like in an array, because it will throw `DomRenderer.js:189 Uncaught IndexSizeError: Failed to execute 'insertRule' on 'CSSStyleSheet': The index provided (1) is larger than the maximum index (0).`

**Comment by kof** [comment]
This is basically the release blocker for  https://github.com/cssinjs/aphrodisiac

**Comment by nathanmarks** [comment]
What are the key benefits of this approach (CSSOM modification) vs string manipulation?

**Comment by kof** [comment]
node.textContent would replace the entire style sheet when inserting just one rule. This is the reason why aphrodite uses asap and aggregates new rules and then does one string replacement. As I want to  avoid asap, entire sheet insertion for every new rule will be an overhead. So the idea is to use DOM api for rules insertion which is not a problem per se. It is just the jss internal implementation detail to put rules in the right order.

**Comment by kof** [comment]
I think I have almost nailed it.
