### ISSUE TITLE
[jss + all plugins] building process breaks on OS Windows

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#323]
Building process breaks on OS Windows in jss and any other plugins on lines like this:
``````````js
"build:max": "NODE_ENV=development webpack src/index.js dist/jss.js",
"build:min": "NODE_ENV=production webpack src/index.js dist/jss.min.js",
"build:test": "NODE_ENV=test webpack tests/index.js tmp/tests.js",
``````````
Because Windows doesn't know how to set global variables in Unix way. As sultion we can use https://www.npmjs.com/package/cross-env and add it to jss and all plugin repositories. (it's already used in jss-compose and jss-expand)

**Comment by kof** [comment]
Yep.

**Comment by kof** [comment]
Adding it to jss.
