### ISSUE TITLE
[jss-global] Plugin that enables global styles without using an option

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#324]
We can have this syntax for global styles:

``` javascript
{
  '@global': {
    html: {globalStyles},
    button: {globalStyles}
  },
  button: {localStyles}
}
```
- It allows us to use global selectors any time, without being forced to use a separate sheet with an option `{named: false}`.
- Also it allows us to remove `{named}` option and related logic from the core. Core is always namespaced.
- It is explicit about globals, which is a good thing.

**Comment by kof** [comment]
To sum up the discussion with @nathanmarks on gitter:

- we should call it @global to avoid conflicts
- we should support `@global button` case as well
- we should think of supporting @global  within other rules, so that its like nested but with less complex

**Comment by kof** [comment]
Just finished removing dependency to the "named" option in all repositories.

**Comment by kof** [comment]
Now will start to implement:

```
'@global': {
  html: {color: 'red'}
}
```
and

```
'@global html': {
  color: 'red'
}
```

**Comment by kof** [comment]
Need  a list of all cases where @global should work, like inside of @media etc.

**Comment by giuseppeg** [comment]
fwiw CSS Modules calls this `:global`

**Comment by kof** [comment]
One naming conflict came up as we discussed this feature with @mxstbr: what do we call global, stuff like: `button  {color: red}`  or also stuff like `.my-button-123345 span {color: red;}`. In the first case we use a selector which applies to the entire document, in the second its a scoped selector. Is the second case still global in terms of terminology?

**Comment by giuseppeg** [comment]
> Is the second case still global in terms of terminology? 

Yes and no, it will affect the entire subtree and in my opinion it shouldn't be valid or allowed otherwise we are going back to the old and not isolated css :)

**Comment by kof** [comment]
I think its fine to keep the '@global' name also when nesting them.  I would see it as global in terms of what is generated after this keyword.

**Comment by giuseppeg** [comment]
To clarify I think that those kind of rules are still `global`.

When you scope a selector like `button` there is a context switch, now global rules defined within this new context are relative to it.

The default context is the document or `:root` element.

**Comment by mxstbr** [comment]
The reason you need this escape hatch is for the following case:

```JSX
<div dangerouslySetInnerHTML={{ __html: someHtmlString }} />
```

How do you now style the contents with JSS if you have no way of attaching class names? You can't without the global.

Sure, this isn't an everyday use case but I've run into this problem a handful of times in two years of doing React and I wouldn't want to add a CSS processing pipeline just to style one div's contents.

**Comment by kof** [comment]
@mxstbr it sounds like you just confirmed our current plan for `@global` implementation. In your particular example you could style its contents using global css scoped to document as well as scoped to the div by adding a class to it: `<div className={classes.something} dangerouslySetInnerHTML={{ __html: someHtmlString }} />` and then scoping global stuff inside of the "something" rule.

**Comment by mxstbr** [comment]
Yeah that's exactly right, this was in response to the earlier 

> it will affect the entire subtree and in my opinion it shouldn't be valid or allowed otherwise we are going back to the old and not isolated css :)

**Comment by giuseppeg** [comment]
That is exactly how [scoped styles](https://css-tricks.com/saving-the-day-with-scoped-css/) worked – the idea was abandoned for the same reason I explained.

However I see the benefit of supporting such a feature for use cases like @mxstbr's.
I am just trying to think if there is a better way, maybe `dangerouslySetGlobalStyles` otherwise shrug `@global` is perfectly ok.

**Comment by kof** [comment]
@nathanmarks do you think we should create 2 separate plugins for @global in the root and @global as a nested rule? It may be even in one package, but separately installable plugins. Because if someone uses jss-nested and nested @global statements they partially have the same functionality. So people may want to pick just one.

**Comment by kof** [comment]
Nevermind. Decided to leave it in one until it is a real use case.

**Comment by kof** [comment]
Released
