### ISSUE TITLE
[jss-grid] Plugin that polyfils css grids

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#327]
Idea comes from @ai, IE has no support for grids. We could eventually make it work through jss.

**Comment by iamstarkov** [comment]
is there any polyfills to look into for inspiration?

**Comment by kof** [comment]
Some, for e.g. https://github.com/FremyCompany/css-grid-polyfill

**Comment by kof** [comment]
I think this is a very complex task and most likely will be only effective when implemented natively. I think now its way too much out of scope for me. If someone wants to integrated a polyfill (if it needs integration at all) I am happy to help from JSS perspective.
