### ISSUE TITLE
index precedence not working on root element

### ISSUE THREAD

**Issue by rosskevin** [cssinjs/jss#329]
https://github.com/cssinjs/jss/blob/master/docs/js-api.md#attach-style-sheets-in-a-specific-order

I'm trying to take precedence in styling over the [material-ui#next] (https://github.com/callemall/material-ui/blob/next/src/Paper/Paper.js#L7) `Paper` element that specifies `index: -10` with my stylesheet `index: 1` on my root element:

```
const styleSheet = createStyleSheet('AfRoot', (theme) => {
  const { breakpoints } = theme
  return {
    root: {
      display: 'flex'
    }
  }
}, { index: 1 })
```

![landing_-_dummy_com](https://cloud.githubusercontent.com/assets/136564/19124971/dafbb7a4-8afa-11e6-91c1-301f5afb9a86.png)

This led me to think (based on the docs) that the _lower the index_, the _higher the precedence_, so I tried changing my index from `1` to `-100` and it still did not take precedence.  I captured the order of attachment and indexes in the debugger:

```
DummyAppFrame
AfGlobal {named: false}
AfRoot: -100
AfAppBar
AppBar: -5
Paper: -10
Toolbar: -1
IconButton: -10
Ripple: -15
Text: -10
AfAppDrawer
Drawer: -5
AfLanding
AfDialog: 100
```

Which yielded:
![landing_-_dummy_com](https://cloud.githubusercontent.com/assets/136564/19125785/095e2d72-8afe-11e6-8ba8-1d0336185526.png)

So `Toolbar: -1` has a higher precedence than `Paper: -10` - I'm having hard making sense of this.

1. ~~Is it true that the lower the number (including negatives), the higher the precedence?~~ No, higher number should be more specific.
1. ~~How does an undefined index factor in, as a zero?~~ As 0.
1. What is the recommended practice values a library should use for index precedence? e.g. should material-ui be using higher numbers?
1. Is this a bug?

**Comment by kof** [comment]
Something @nathanmarks probably knows about.

**Comment by kof** [comment]
> How does an undefined index factor in, as a zero? 0 is the default.

**Comment by kof** [comment]
I actually thought higher number means higher specificity, which would mean that higher number is lower in the list.

**Comment by rosskevin** [comment]
> I actually thought higher number means higher specificity, which would mean that higher number is lower in the list.

Thanks @kof, yes I misread the doc in my confusion and I have updated the text above.

So the first scenario is the one I'm confused with.  Neither `1` nor `100` would take precedence/be more specific/attach lower in the dom.

**Comment by kof** [comment]
> What is the recommended practice values a library should use for index precedence? e.g. should material-ui be using higher numbers?

I think library level should have lower numbers, because it needs to be overwritable by user styles.

**Comment by kof** [comment]
Can you submit a failing test?

**Comment by rosskevin** [comment]
[This test](https://github.com/cssinjs/jss/blob/master/tests/functional/priority.js#L153) logically already proves the right behavior in `jss`, yet it's not what is manifested in my dom.  What else could be affecting this?  The only oddity in my webpack setup is that I include the `material-ui/src` directly as an alias (uses one transpilation pipeline).

**Comment by kof** [comment]
maybe you are using some old jss version which doesn't support index property?

**Comment by kof** [comment]
make sure to verify the version from your build, package.json might be a bitch.

**Comment by nathanmarks** [comment]
Try remove your `node_modules` folder and reinstall. I encountered a similar issue (might have been changes in jss-theme-reactor though) and actually tried writing tests for `jss` to reproduce but was unable to. I ended up reinstalling my dependencies and it worked fine.

**Comment by nathanmarks** [comment]
@kof I have other concerns about this feature. It is a **massive** help and allows us to do things that aren't currently possible with CSS in JS libraries otherwise.

However, when you have a lot of components, it's hard to "keep track". 

In a way, I think defining this priority in a central location might be a preferable approach. The reason I say that is because a sheet shouldn't necessarily care where it is rendered, it shouldn't need to depend on the priority of other sheets. 

It's also very hard to move things around relative to each other without stepping on toes.

I think that passing the index should be the responsibility of a module that "manages" the sheets. WDYT?

**Comment by kof** [comment]
a definite yes.

**Comment by nathanmarks** [comment]
@kof Do you think this is the responsibility of `jss` or for consuming projects?

**Comment by kof** [comment]
Consuming project. Warning?

**Comment by rosskevin** [comment]
> Try remove your node_modules folder and reinstall.

Done, on two different machines with the same results.

I have also seen this in the past and removal/reinstall did work.  This time, it just isn't making a difference.

**Comment by nathanmarks** [comment]
Let me see if I can re-reproduce.

**Comment by nathanmarks** [comment]
Also @rosskevin I'll be refactoring how priority is set for mui this weekend. Nothing is going to be put in individual stylesheets anymore. We'll have everything in a centralized location for configuring that. I'll reference this issue when I make the PR.

**Comment by nathanmarks** [comment]
@rosskevin here's how i'm configuring it in the docs in that PR: https://github.com/nathanmarks/material-ui/blob/9918e48feafab27e22bbe81dcd5bb7e9e11d43bd/docs/site/src/components/App.js#L25

**Comment by nathanmarks** [comment]
@rosskevin https://github.com/callemall/material-ui/blob/next/docs/site/src/components/App.js#L25

**Comment by nathanmarks** [comment]
@rosskevin are you still having the issue with that setup?

**Comment by rosskevin** [comment]
@nathanmarks I apologize for taking so long to confirm - been out ill.  Your changes work well for us, thank you!
