### ISSUE TITLE
Idea: ability to set a default unit, then use Numbers instead of strings.

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#33]
`px` would be the default. For example, so that we can replace

``` js
var style = {
  '.button': {
    width: '20px'
  }
}
```

with

``` js
var style = {
  '.button': {
    width: 20
  }
}
```

but if a different unit than the default `px` is wanted, then perhaps something like

``` js
jss.defaultUnit = 'em';
// or
jss.createStyleSheet(style, {defaultUnit: 'em'})
```

**Comment by trusktr** [comment]
gss also uses a px default.

**Comment by kof** [comment]
https://github.com/jsstyles/jss-px

works same way as in jquery.

**Comment by trusktr** [comment]
OOOOhhhh yeaaaaah. Niiiice.
