### ISSUE TITLE
[repl] use es6 by default for jss notation

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#330]
- [x] add babel to the runtime
- [x] convert input, use default exports

**Comment by DenisIzmaylov** [comment]
Could you please explain more details about this issue?

**Comment by kof** [comment]
We can add bable runtime and be able to write styles in ES6 notation, right now its evaluated "as is". Also I would rathe write an export statement than a return:

```js
export default {
  button: {
    color: 'red'
  }
}
```

**Comment by kof** [comment]
released!!! thanks @vsashyn
