### ISSUE TITLE
[jss-vendor-prefixer] Does not add -moz- prefix in Firefox 49

### ISSUE THREAD

**Issue by atabel** [cssinjs/jss#331]
I've seen this failing for css property  `'appearance'` .

I've been debugging this and the root of the problem seems to be this:
https://hacks.mozilla.org/2016/09/firefox-49-fixes-sites-designed-with-webkit-in-mind-and-more/

In https://github.com/cssinjs/css-vendor/blob/master/src/prefix.js#L24 you're checking whether `'WebkitTransform'` is in style, which returns `true` in FF 49. So the lib is detecting FF as Webkit.

The problem is there are css properties (for example `'appearance'`) which are not implemented in FF as `'-webkit-appearance'`, but `'-moz-appearance'`.

As a result, this function https://github.com/cssinjs/css-vendor/blob/master/src/supported-property.js#L34 will return `false` because it is searching for `'appearance'` or `'-webkit-appearance'` in `style` instead of `'-moz-appearance'`

As you can see in this screenshot, CSSProperties instances in FF49 have some Webkit properties:

![prefixer](https://cloud.githubusercontent.com/assets/1849576/19444250/fd8398a2-948f-11e6-8a4d-e9da97db9fad.png)

**Comment by atabel** [comment]
I can prepare a PR for https://github.com/cssinjs/css-vendor
A simple fix would be changing the props order [here](https://github.com/cssinjs/css-vendor/blob/master/src/prefix.js#L14) and check Moz before Webkit.

**Comment by kof** [comment]
Wow, wtf, now we can't  rely on vendor prefixes any more.

**Comment by kof** [comment]
Yes, will accept a pr, thanks!

**Comment by cvle** [comment]
I know different browsers used to adopt webkit prefixes because they were widely popular. This was the case with older versions of IE, Firefox and Opera. It is not clear how the situation is at the moment. The safest way would be to check webkit at the very last.

**Comment by cvle** [comment]
I see this has been already addressed in the PR, great!

**Comment by kof** [comment]
yeah, you are right, lets do that!

**Comment by kof** [comment]
published
