### ISSUE TITLE
[jss-expand] Better documentation

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#336]
- don't use double array values in examples except of multi value values (it might confuse)
- rely on jss-preset-defaults in examples
- multi value values

**Comment by kof** [comment]
@typical000  Just added jss-expand to the repl to play around easily.

**Comment by kof** [comment]
An often complain I have heard is the need to use camel case for property names, kebab case is same bad because it requires quotes, but actually with jss-expand we don't have this prob any more because we can  use the expanded version in the most cases. A good thing to document.

**Comment by kof** [comment]
Ok I went through the documentation, simplified it a lot, lets get some feedbacks if this is ok, closing it for now.

**Comment by kof** [comment]
Will wait until tomorrow for feedbacks regarding documentation and do the announcement.

**Comment by typical000** [comment]
Cool!!! Tomorrow I'll take a look to docs too. Maybe we forgot something.

**Comment by kof** [comment]
Added jss-expand to jss-preset-default and added it to the general documentation for plugins setup.
