### ISSUE TITLE
A value of the "content" property is unboxing to incorrect CSS

### ISSUE THREAD

**Issue by scalder27** [cssinjs/jss#337]
Correct at first look styles

``` js
const styles = {
  button: {
    '&:before': {
      content: 'hi!'
    }
  }
}
```

will transform to css that doesn't work

``` css
.button:before {
  content: hi!;
}
```

Of course, there is a workaround.

``` js
const styles = {
  button: {
    '&:before': {
      content: '"hi!"'
    }
  }
}
```

But it doesn't feel right.

**Comment by kof** [comment]
Yeah, I was thinking back and forth  about it, on the one hand it is exactly what should be technically there as it is now, on the other hand, new users won't think that deep and also 2 quotes isn't very nice optically.

I think we should fix it and make the inner quotes optional by checking if they are there or not.

**Comment by kof** [comment]
@scalder27 do you want to fix it?

**Comment by scalder27** [comment]
Yeah! Making inner quotes optional will be great! It will provide a backward compatibility and will be more convenient for new users.
I want to fix it. I'm not sure when exactly, but I'll do it.

**Comment by scalder27** [comment]
I was thinking about values of the content property. There are a lot of possible variants, including values with no quotes:

```css
content: normal;
content: none;
content: " (" attr(href) ")";
content: "quote mark: " open-quote;
content: no-close-quote;
content: unset;
```

This issue will require a whitelist of values and a lot of checks. Moreover, I'm afraid this behavior could be misleading, and error prone.

Maybe it doesn't worth efforts. And a note in the docs will be sufficient.

**Comment by kof** [comment]
Ah, exactly, now I recall why I decided to not fixing it. You would need to maintain all possible values in order to know what needs quotes.
