### ISSUE TITLE
devDependencies do not work in Node 7

### ISSUE THREAD

**Issue by sapegin** [cssinjs/jss#338]
I wanted to send pull request but just increasing a version is not enough. devDependencies won’t install on Node 7 because of `codecov` which uses deprecated version of `graceful-fs` and this is the latest version of `codecov`.

```
❯ npm i
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

...

❯ npm ls graceful-fs
jss@5.5.5 /Users/tema/jss
...
├─┬ codecov@1.0.1
│ └─┬ execSync@1.0.2
│   └─┬ temp@0.5.1
│     └─┬ rimraf@2.1.4
│       └── graceful-fs@1.2.3
...
```

They have an issue for that since June: https://github.com/codecov/codecov-node/issues/19.

**Comment by kof** [comment]
Hmm, can we have different engines for dev and prod? Because its a dev only dependency.

**Comment by kof** [comment]
Oh actually it shouldn't be a problem as long as we don't use engine-strict. You still can use node 7, right?

**Comment by kof** [comment]
The only problem you get is when you try to install it for development, not as a dependency.

**Comment by sapegin** [comment]
Yeah, it works fine but [breaks the CI](https://travis-ci.org/sapegin/react-styleguidist/jobs/171828852).

**Comment by kof** [comment]
We can temporarily remove coverage, because it is actually currently broken anyways #301

**Comment by sapegin** [comment]
Cool ;-)

**Comment by kof** [comment]
Hmm, the probl is it is used not just in jss repository, but in many others, so maybe it is still better to actually fix this.

**Comment by sapegin** [comment]
There’s even a quite old PR with a fix: https://github.com/codecov/codecov-node/pull/22

**Comment by kof** [comment]
A workaround `yarn install --ignore-engines`

**Comment by sapegin** [comment]
I’m thinking about the right solution for this problem because it also won’t install in Node 4. And yarn treat `engines` as a an error, while npm as just a warning.

Probably we should use `engines` only to specify requirements for package consumers, not for developers. For JSS I’d set it for `>= 4`.

For developers `engine` field of packages in `devDependencies` should be used. For example if you have `eslint` in `devDependencies` it won’t install on Node 0.12 no matter what you have in `engines` yourself.

What do you think?

**Comment by kof** [comment]
Hmm, how would you know which node version to use if you  want to install it for development?

**Comment by kof** [comment]
Documentaiton?

**Comment by kof** [comment]
I think you are actually right, using node for installing frontend packages brought this ambiguity for engines, it was always ment for the end users in node.

**Comment by sapegin** [comment]
Contribution guidelines I think is the best place since there's no way to separate engine requirements.

**Comment by kof** [comment]
Sometimes problems are so easy to fix!

**Comment by sapegin** [comment]
Will you accept PRs with these changes? Update engines to `>=4` in jss, react-jss, etc.

**Comment by kof** [comment]
yes!

**Comment by sapegin** [comment]
Done!

**Comment by awestroke** [comment]
A fix is pushed but no new version is released, so this is still an issue.

**Comment by IsenrichO** [comment]
Still an issue for me. Is there any progress on this?

**Comment by kof** [comment]
This has been fixed long time ago!!! You probably experience something else, please create a new issue.
