### ISSUE TITLE
Make a perf test if cssText is faster then style.prop

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#34]
http://stackoverflow.com/questions/21011126/dom-replace-entire-style-attribute-cssstyledeclaration-on-element

**Comment by trusktr** [comment]
Wow, speaking of what I made above, look at this [new API](http://updates.html5rocks.com/2014/11/frame-timing-api) just for that reason!

**Comment by kof** [comment]
Yeah, I think webkit has already had something  like this internally

**Comment by kof** [comment]
when we have it, people can finally start to write rendering performance tests for their libs ...
