### ISSUE TITLE
[styled-jss] Styled Primitive Components

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#341]
Create a small library that allows to style primitives similar to styled-components. [Some pseudo code.](https://gist.github.com/kof/3277ee04d2100bab3e6c6c33656edce7)

**Comment by kof** [comment]
We need this done before starting it https://github.com/cssinjs/jss/issues/356

**Comment by kof** [comment]
Some more thoughts

// Base styles, like a regular jss object.
const styled = Styled({
    root: {
        margin: 10
    },
    baseButton: {
        padding: 10
    }
})

const NormalButton = styled('button', {
    composes: '$baseButton',
    border: '1px solid grey'
    color: 'black'
})

// Composition over styled() same like styled-components
const PrimaryButton = styled(NormalButton, {
    color: 'red'
})

// One can use classes AND styled primitives.
const MyComponent = ({classes}) => (
    <div className={classes.root}>
        <PrimaryButton>
    </div>
)
const MyStyledComponent = injectSheet(styled)(MyComponent)

cc @cssinjs/core

**Comment by LestaD** [comment]
@kof any progress here?

**Comment by kof** [comment]
Yes, me and @lttb are evaluating some interesting interfaces, but its not ready yet.

**Comment by LestaD** [comment]
@kof Can I help you?

**Comment by kof** [comment]
Yes, we are preparing some syntax variants and will need user feedbacks, we will post the question here soon cc @lttb

**Comment by kof** [comment]
You see actually already 2 possible syntaxes, what are your thoughts on them? What do you NOT understand?

**Comment by LestaD** [comment]
All syntaxes is readable.

**Comment by LestaD** [comment]
https://gist.github.com/kof/3277ee04d2100bab3e6c6c33656edce7#gistcomment-2034780

**Comment by lttb** [comment]
## Variant 3

There are some points about yet another concept:
- we declare **style primitives** for component in the lower case on the top level:
```js
{
  button: {
    color: 'red' 
  }
}
```
- we can use **primitive modifier** starts with Capital letter, eg:
```js
{
  App: { padding: '10px' }, // on the top level it turns into <div> with modifier className

  button: {
    color: 'black',

    Primary: {
      color: 'red'
    }
  }
}
```
- we can compose **modifiers** with something like `primitiveModifier`:
```js
{
  button: {
    color: 'black',

    Normal: {
      border: '1px solid black'
    },
    Secondary: {
      composes: '$buttonNormal' // -> button.Normal styles
    }
  }
}
```
- we can also declare **modifiers** just on the top level:
```js
{
  button: {
    color: 'black',
  },
  buttonNormal: {
    border: '1px solid black'
  },
  buttonSecondary: {
    composes: '$buttonNormal'
  }
}
```
- full example
```jsx

const styles = {
  App: { padding: 30px },
  
  button: { 
    padding: '10px', 

    Normal: { 
      border: '1px solid black' 
    }, 
    Primary: { 
      color: 'red' 
    }, 
    Secondary: { 
      composes: '$buttonNormal', 
      color: 'green' 
    }
  } 
}

const MyComponent = ({ styled }) => (
  <styled.App>
    <styled.button />
    <styled.button.Primary />
  </styled.App>
)

const MyStyledComponent = injectStyled(styles)(MyComponent)
```

**Comment by kof** [comment]
closing, as we got it released https://github.com/cssinjs/styled-jss
