### ISSUE TITLE
Reduce file size 

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#342]
Babel inlines a lot of utility functions. We need to make sure they are externalized. For a utility of this size its a huge overhead.

**Comment by umidbekkarimov** [comment]
Here https://babeljs.io/docs/plugins/transform-runtime/ comes handy

**Comment by umidbekkarimov** [comment]
Results for `dist` bundles is not satisfying.
Current size:

<img width="665" alt="screen shot 2016-11-03 at 16 40 55" src="https://cloud.githubusercontent.com/assets/4734297/19966242/5c71c80a-a1e4-11e6-8efc-1a6ebcbb0e7a.png">

With `transform-runtime`

<img width="267" alt="screen shot 2016-11-03 at 16 41 03" src="https://cloud.githubusercontent.com/assets/4734297/19966243/5c723db2-a1e4-11e6-825d-511fe190ee2d.png">

<img width="662" alt="screen shot 2016-11-03 at 16 40 59" src="https://cloud.githubusercontent.com/assets/4734297/19966241/5c71cb16-a1e4-11e6-9f13-946dae4b4b51.png">

But in case if all (or at least most of) libs in app refers to `babel-runtime` trade can be won

**Comment by kof** [comment]
So why is it bigger with transform-runtime plugin?

**Comment by umidbekkarimov** [comment]
`babel-runtime` also adds extra [helpers](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js). (not all of them, only required)

**Comment by kof** [comment]
I am more concerned about the lib build, not the dist build. Most of the time people use it from the lib using their build tools and all the utils do not need to be inlined, they can be a dependency.

**Comment by kof** [comment]
you left polyfill: true, currently its not polyfilling, so you added stuff, thats the reason maybe?

**Comment by kof** [comment]
I was trying to add https://babeljs.io/docs/plugins/external-helpers/ ... still can't figure out a good way for  injecting babelHelpers  into the build.

**Comment by umidbekkarimov** [comment]
@kof how do you want to inject it ?

**Comment by umidbekkarimov** [comment]
For `umd` you can "prebuild" `helpers.js` file and add it as webpack entry 

For `lib` - you will have to repeat steps that `babel-transform-runtime` already does for you

**Comment by kof** [comment]
For umd it should be inlined in the build I suppose. For the lib - should be a dependency from node_modules, so that its reused across all projects.

**Comment by kof** [comment]
I wonder why its so complex to set up or what we need to use to make it simple.

**Comment by umidbekkarimov** [comment]
> For the lib - should be a dependency from node_modules, so that its reused across all projects.

For that we have [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime),

So as I said before - my suggestion is:
* For `lib` use  [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime) with `{polyfill: false, regenerator: false}`
* For `umd` use  [external-helpers](https://babeljs.io/docs/plugins/external-helpers) with `global.babelHelpers = require("babel-core").buildExternalHelpers();` entry file

**Comment by umidbekkarimov** [comment]
I can create PR tonight, but don't expect "big" size changes

**Comment by umidbekkarimov** [comment]
Also take a look at [this](https://medium.com/modus-create-front-end-development/optimize-es6-output-size-performance-ninja-tricks-included-d4fc2d313f66) blog post to understand how bundle size depends on code style

**Comment by kof** [comment]
> global.babelHelpers = require("babel-core").buildExternalHelpers(); entry file

That would mean that you attach babelHelpers object to the window in the browser. Thats ugly.  I think it should be inlined for the umd.

**Comment by kof** [comment]
Also the prob with external-helpers is that we need to manually define what we use and I don't want to maintain this list and also I don't want the full helpers package to be loaded, its too big.

**Comment by kof** [comment]
@umidbekkarimov any updates?  a new release is comming, I would love to do something about this…

**Comment by umidbekkarimov** [comment]
<img width="711" alt="screen shot 2016-12-21 at 21 45 10" src="https://cloud.githubusercontent.com/assets/4734297/21399921/20a9227e-c7c7-11e6-86de-3e389bcc1142.png">

Got this with `babel-runtime` for `lib`.
For `umd` we will need to hardcode helpers, which is not worth it as I think.

**Comment by kof** [comment]
@rofrischmann how did you get this done in fela?

**Comment by kof** [comment]
Maybe for the umd build we should use webpack2?

**Comment by rofrischmann** [comment]
I actually did nothing. Fela's core is ~200 lines. Using very basic javascript and no ES2015 `class` syntax made Babel producing almost no extra stuff. For UMD I still highly recommend Rollup, but Webpack 2 seems great as well :P

**Comment by kof** [comment]
I guess rollup did all the magic. Because your builds look perfect.

**Comment by kof** [comment]
Now to close this issue

- [ ] use webpack 2 in all repositories
- [ ] use transform-runtime in all repositories

**Comment by nathanmarks** [comment]
@kof Rollup is great for libraries -- it uses a very different technique which isn't great for a single massive bundle but is rather handy for things like libraries and UMD builds for them since everything gets hoisted into a single scope.

Nothing wrong with webpack2 either. Browsers actually prefer a combination of the two techniques in practice. (scope hoisting vs module closures). Don't fret over it anyways 😄

**Comment by kof** [comment]
closing this unresolved, because I don't see any good ways to do this with webpack.
