### ISSUE TITLE
Unexpected specificity when 2 equal rules are in 2 different sheets

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#347]
As discussed with @nathanmarks, it is possible that 2 equal rules exist in 2 different sheets rendered at different times. Class name generation uses rules style object at the moment. It might be a problem when:

1. a: {color: 'red', float: 'left'}
1. b: {float: 'right'}
1. `<span class="a b" />`  - b is supposed to overwrite float prop in "a".
1. in different sheet  a: {color: 'red', float: 'left'} rule co-exist
1. once the second sheet is rendered, it will have a higher specificity based on source order, it will have the same selector as the first rule and so will replace the first rule
1. after that b rule will no longer overwrite float property of the "a" rule.

**Comment by kof** [comment]
Generated class name needs to be unique across all sheets and stay deterministic at the same time. We need to use some unique sheet identifier when generating class names for the rules.

**Comment by kof** [comment]
One suggestion is to make class names of all rules before the current rule part of the key that is used to generate an id: `rule2Id = createHash(styles + rule1.id + rule0.id)`

**Comment by nathanmarks** [comment]
@kof What happens to the other rules when 1 rule changes in the sheet or a new rule is added?

**Comment by kof** [comment]
I think changing all the selectors would have too many implications, so for simplicity it should be static.

**Comment by nathanmarks** [comment]
Any noticeable overhead?

**Comment by kof** [comment]
You mean iterating over previous rules and taking their class names? Will measure it. I think it won't be a deal breaker. For sure if user would provide unique sheet names, it would be faster. If everything happens within `generateClassName` function, a higher level abstraction which has a sheet name can pass own generateClassName function and use the sheet name.

**Comment by kof** [comment]
1. Update: using other rules class names seems a bit complicated.
2. Another idea is to provide an "id" option which is unique for the sheet. But the problem is then that we require a user to ensure the uniqueness.
3. Using `createShash(meta + name + styles)` to generate an id would solve that problem for 99% of cases, no guarantee though.

**Comment by kof** [comment]
merged
