### ISSUE TITLE
Use options.meta when generating class name

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#349]
cc @nathanmarks

**Comment by nathanmarks** [comment]
This could definitely help address https://github.com/cssinjs/jss/issues/347

**Comment by kof** [comment]
@nathanmarks wanna take it?

**Comment by nathanmarks** [comment]
Sure 👍

**Comment by cvle** [comment]
I'm using meta to prepend my classNames too, this would simplify my code. Though I always had the feeling that I was misusing the `meta` feature. Any thoughts about introducing a new options parameter for this?

**Comment by kof** [comment]
Why is it misusing and why to introduce another option for this? Initially I though meta for providing an info about a sheet. In react-jss it is used to put component name  on style tag name.

**Comment by kof** [comment]
As I was reading the PR https://github.com/cssinjs/jss/pull/350 I realized why you think it feels like a hack. Its because the meta format passed by the user can be anything and we would need to normalize it before putting it into a class name.

**Comment by cvle** [comment]
For me `meta` was for attaching an arbitrary piece of information to a stylesheet that must not directly relate to debugging/namespacing purposes. So it could be in any format and might not make sense prepending to a class name depending on the use case. Though to be honest I couldn't think of any other use case yet for `meta` other then for providing an identifier to a style sheet. The term `meta` is very generic. It would be more clear, if we would have something like `sheetName`. Having `meta` for arbitary info and `sheetName` as an identifier seems to make sense for me.

I'm not feeling strongly about this. Just some food for thought.

**Comment by kof** [comment]
Yeah, you are right.

**Comment by kof** [comment]
Maybe in order to not to have to normalize the meta in order to be part of class name, we should think of a different property name to be used specifically as a class name prefix? @nathanmarks ?

**Comment by kof** [comment]
As discussed, to guarantee class name valid string, we need either to do a lot of parsing or a new property which is expected to be  class valid.

**Comment by kof** [comment]
One suggestion is to use a generic `name` or `id` field. But at the end, abstractions can always overwrite the `generateClassName` function and built the class name using data they have. So for now we are putting it on hold.

**Comment by kof** [comment]
Closing this in favor of #347 and using createShash(meta + rule.name + stylesStr) to generate an id.
