### ISSUE TITLE
[aphrodisiac] ssr needs to clean up styles

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/jss#352]
I'm starting a simple server-side rendered app with home and about routes, using aphrodisiac.  I just do
```es6
import {sheet} from 'aphrodisiac'

type Props = {
  body?: any
}

export default class Html extends Component<void, Props, void> {
  render(): React.Element<any> {
    // render body so that jss sheets will be added
    const __html = renderToString(this.props.body)
    return (
      <html>
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
          <meta name="description" content="" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
          <title>Pason Power</title>
          <link rel="stylesheet" href="https://unpkg.com/bootstrap@4.0.0-alpha.3/dist/css/bootstrap.min.css" />
          <style type="text/css" id="server-side-styles">
            {sheet.toString()}
          </style>
        </head>
        <body>
          <div id="root" dangerouslySetInnerHTML={{__html}} />
        </body>
      </html>
    )
  }
}
```

When I visit `/` for the first time, I just get the CSS specific to that route.  Then I go to `/About`.  The CSS rules for `/` get served up in addition to the rules for `/About`, because they're stuck in the global `JSS` state on the server side.

If `StyleSheet` simply provided a `clear` method that removed all of its rules, then I could call it after rendering my response and nothing would be stuck around for the next response.

But these globals make me nervous.  They're being shared by requests coming from all clients.  I would feel much more comfortable about creating a different JSS instance for each request and passing it down through react `context`.  I think the SSR example should do it that way.

**Comment by kof** [comment]
Unfortunately (or luckily), aphrodisiac knows nothing about react. Which means it doesn't know when a new response comes in, I have just added reset() and toString() to the api, [see](https://github.com/cssinjs/aphrodisiac#serverside-rendering) Let me know if it works for you and I will publish a new version then.

Another possibility for you is to create a module with a get() function, which returns you a current aphrodisiac object, then implement a reset() function and call it somewhere where you know that a new request comes in.

**Comment by jedwards1211** [comment]
@kof I think this is a problem with `jss`-only SSR too.  I don't see any indication that the SSR example would clean up styles between requests.

I think I may decide not to use aphrodisiac and just create a different instance of `jss` for each request, passing it down through react `context`, and create something very similar to `react-jss` that gets `localJss` from `context` instead of as an argument to the HOC.

If you like that approach I could make a PR to `react-jss`.

**Comment by kof** [comment]
Yes, in react context, we can use a provider to pass jss over context. Lets create an issue in react-jss and yes I like it.

**Comment by kof** [comment]
As for aphrodisiac, it is still important I think, because it should work without react as well.

**Comment by jedwards1211** [comment]
@kof wait, my approach would fail to cache style sheets, right?
If a `StyleSheet` were not bound to a specific global registry, and could be attached to any local jss registry that was passed in, then there would be no need to create a new `StyleSheet` for every request.

**Comment by kof** [comment]
lets discuss it in a separate issue in react-jss repository.

**Comment by jedwards1211** [comment]
okay

**Comment by kof** [comment]
released aphrodisiac with a reset function, closing this.
