### ISSUE TITLE
Remove all sheets from the registry

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#353]
Lets introduce a convenience method to remove all sheets from the registry at once. It can be used for testing, but mainly for SSR, when a new request comes in.

**Comment by kof** [comment]
Same is in aphrodisiac #352

**Comment by cvle** [comment]
Sharing one global JSS instance for SSR is not save when requests are processed concurrently.

**Comment by kof** [comment]
It is safe as long as renderToString call is sync.

**Comment by cvle** [comment]
Correct, I just want to make sure that we mention this, in case we advocate this approach.

**Comment by jedwards1211** [comment]
I'd still like to see creating a separate sheets registry for each request become the recommended solution

**Comment by kof** [comment]
Me too.
