### ISSUE TITLE
[css-vendor] supportedValue is generally broken

### ISSUE THREAD

**Issue by cvle** [cssinjs/jss#354]
Supported values for some shorthand properties always returns false: e.g. in Firefox:
```javascript
cssVendor.supportedValue('background', 'red')
```
```javascript
false
```
The style property returns:
```
red none repeat scroll 0% 0%
```
Same happens with transition values and probably with others. Some shorthand values get processed by the browser and returned in a different form, preventing the current mechanisms from performing correctly.

**Comment by cvle** [comment]
This returns false too in chrome and firefox and possibly others:
```javascript
cssVendor.supportedValue('color', 'rgba(255, 255, 255, 1.0)')
```
```javascript
false
```

**Comment by kof** [comment]
wondering how this has worked before.

**Comment by cvle** [comment]
We can use a similar but slightly different way to detect whether a value is supported. Instead of setting and testing for equality we do this:

- Set the value to be tested.
- Check whether browser has changed the style value
- Reset style value
- Return true when browser has changed the style value, otherwise false

This should do the trick
