### ISSUE TITLE
Dynamic Sheets for theming and animations

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#356]
The idea is to have value functions and rule functions which accept an object and let JSS render them dynamically. This will allow us __efficient__  dynamic theming. The idea has been around for a while, but this time me and @nathanmarks have got a plan.

## What signature will value function and rule function have?

```javascript
{
  button1: {
    padding: 15,
    // Value function.
    color: props => props.buttonColor
  },
  // Rule function.
  button2: props => ({
    padding: props.padding,
    color: props.color
  })
}
```

## How do we know if a rule or prop needs a rerender?

We don't, we just call all dynamic values and compare new results with the current once.
We need to have a proof that calling all dynamic values on each update is an __actual__ perf problem. Right now this is a premature optimization, but if we need it, here are some options:

1. User defines properties which  are used within the value function / rule function
1. Optionally babel transform does a static analysis and provides those properties.

All suggestions are __NOT__ exclusive.

### Suggestion 1

Caching is ensured by the user. It is an opt-in.

```javascript
{
  button: {
    color: (nextProps, prevProps, prevValue) => {
      // User can prevent rerender by comparing props manually.
      // If user returns previous value, no rerendering happens.
      if (nextProps.primary === prevProps.primary) return prevValue

      return calculateColor(nextProps)
    }
  }
}
```

### Suggestion 2

It is basically suggestion 1 + a helper function which allows nicer caching notation.

```javascript

function cache(valueFn, ...propNames) {
  return (nextProps, prevProps, prevValue) => {
    if (hasChanged(propNames, nextProps, prevProps)) {
      return valueFn(nextProps)
    }
    return prevProps
  } 
}

{
  button: {
    color: cache(props  =>  calculateColor(props), 'primary')
  }
}
```
### Suggestion 3

Its  a caching integrated into JSS itself.

```javascript
{
  button: {
    // Once property "primary" has changed, JSS will call user's value function and get the new value.
    color: [props  =>  calculateColor(props), 'primary']
  }
}
```

## How do we make sure to render minimum CSS?

1. If a rule contains lots of dynamic values, it makes sense to make the entire rule dynamic - user should use function for rule declaration. In this case the entire rule will be rerendered if any property needs to rerender.
1. If a rule contains just just one or few dynamic props - value function should be used. In this case we should create a separate rule which contains just one property. This will save some bandwidth for SSR, because we are not copying all static properties of the rule together with the dynamic one.

## Fallbacks

We need to make sure fallbacks are rendered first, like we already do (@mxstbr pointed this out).

Example

```javascript
{
  button: {
    color: props => props.buttonColor
    fallbacks: {
      color: 'red'
    }
  }
}
```

## We will need a registry for dynamic rules and values.

1. We will need to differentiate dynamic values / rules and static. If a rule has no value functions nor its rule definition is a function - it is a static rule. 
1. We need a registry for dynamic rules.
1. We need to ref. the CSSRule in the virtual rule in case it needs to be modified

## When to modify rules and when to copy.

1. In case of react-jss, a sheet is reused between all elements of one component.
1. If a Rule is used by more than 1 element, they may have different states. If a rule is dynamic, it needs to be copied, otherwise - same rule can be used for both.
1. A dynamic rule needs to get an additional ID (or a ref) which identifies a particular element (component instance), which uses that rule. This way we know that a rule is used by more than 1 element and needs to be copied.
1. As we now have every rule associated with an element, on every further change we can modify proper rule.

## API for passing sheet props.

We need an API which can be called with an object as param, so that JSS can call dynamic values/rules and take care of the rendering.

Example
```javascript
const sheets = new SheetsManager()
sheets.update({primary: true})
```

## How to know what to render when new props is passed

We will try to rerender all dynamic values/rules. Caching mechanism will prevent performance issues.

##  What are the valid edge cases for perf?

- Animations - this API shouldn't be misused for high frequency updates.

**Comment by cvle** [comment]
So when the sheets are updated rules will change but the class names will remain the same right?

**Comment by kof** [comment]
Yes, we need to keep class names static, because we have no way to update the class name on an element from jss stand point.

**Comment by kof** [comment]
Updated the description.

**Comment by jcperez-ch** [comment]
Ok, I see that the end goal is to have an internal solution for `JSS` and not related to `react-jss` specific.

I just finished to pulish a fix for my [PR](https://github.com/cssinjs/react-jss/pull/53) that allows a ThemeProvider in React to inject a theme descriptor (meaning an object that defines variables) to provide those variables to all decorated Components using the current theme.
The usage is described in the [README](https://github.com/jcperez-ch/react-jss/blob/composed-styles/README.md#using-composition-for-theming) of my branch.

Definitely my approach will fulfill theming only for react users.

**Comment by mxstbr** [comment]
Just mentioning here that your apporach @jcperez-ch for the ThemeProvider will break, because in React pure components block context updates. You need to have an event listener (like `react-broadcast`) to avoid this issue, which is what `react-router`, `redux` and also `styled-components` do. (see [here](https://github.com/styled-components/styled-components/blob/master/src/models/ThemeProvider.js))

**Comment by jcperez-ch** [comment]
@mxstbr I understand the fact that pure components won't update if context changes.  But the components that consume the `theme` context are the wrappers (meaning the JSS Wrapper which won't be pure), not the wrapped components.  I am not sure if I need to tweak the shouldComponentUpdate function, but I kinda feel confident that it won't affect wrapped components since the `sheet` prop injected by the JSS Wrapper is always different.

Anyway thanks for flagging that out, I would add some more unit tests to verify.

**Comment by mxstbr** [comment]
No, pure components _block_ context updates. If a component returns `false` from its `shouldComponentUpdate`, none of its children get the context update, even though they should.

Imagine a `NeverRerender` component:

```JS
class NeverRerender extends Component {
  // Never rerender this component after the first render
  shouldComponentUpdate() { return false; }

  render() { return this.props.children; }
}
```

Now if you have a component tree like this:

```JSX
<ThemeProvider theme={someTheme}>
  <NeverRerender>
    <ThemedButton />
  </NeverRerender>
</ThemeProvider>
```

The `ThemedButton` will **never ever** update its theme, even if you change the `theme` prop of the `ThemeProvider`, because the `NeverRerender` component blocks context updates for its children.

**Comment by cvle** [comment]
Please refocus on the proposed idea, which is a solution independent of react.

**Comment by jcperez-ch** [comment]
Gotcha now. Indeed a solution independent of react is ideal. Thanks again for the clarification

**Comment by umidbekkarimov** [comment]
What about streams?

```javascript
const sheet = jss.createStyleSheet()

const ruleStream = propsStream
// compose rule
    .map(({buttonColor, padding, color}) => ({
        button1: {
            padding: 15,
            color: buttonColor,
        },
        button2: {
            color,
            padding,
        }
    }))
    // check if changed
    .distinctUntilChanged()

const sheetStream = Observable.of(jss.createStyleSheet())
// combine sheet with rules
    .combineLatest(ruleStream, (sheet, rules) => sheet.setRules(rules))
    // attach on every change
    .do((sheet) => sheet.attach())
    .finally(() => sheet.detach())
```
____

Aslo something related https://github.com/davidkpiano/RxCSS

**Comment by kof** [comment]
Streams seems to be out of scope for this issue, it can be a separate library. This issue is about a lower level implementation I think. I would be more than happy if someone does a streaming abstraction on top of jss though.

**Comment by cvle** [comment]
I am concerned about whether the keyword `props` might end up confusing for React users as in React `props` is a distinct concept that describes component inputs. Alternatively we could use `vars` as for Sheet Variables or Theme Variables. The latter term is commonly used for css based themes.

**Comment by kof** [comment]
I think if you use it with react, you will really pass the props.

**Comment by cvle** [comment]
It wasn't clear for me on the proposal, so props can be updated on a per style sheet level. 👍

**Comment by cvle** [comment]
> I think if you use it with react, you will really pass the props, similar to styled-components.

I thought about this more. Because the class names remain static as you said, this wouldn't work for React. Normally we share a StyleSheet among the same components, changing the StyleSheet according to one's individual props will change the appearance of all other components of the same kind. 

Styled-Components creates new class names for each change, that can be reused among the same components.

We would need to have a similar approach. Maybe having a class name for the static part and a class name for the dynamic one, that varies.

**Comment by nathanmarks** [comment]
@cvle 

We definitely need to append new variations of rules. We shouldn't be replacing existing since as you rightly mentioned, it will change the look/feel for all instances.

**Comment by kof** [comment]
@cvle looking into it again: yeah, dynamic rules can't share class names between elements.

**Comment by kof** [comment]
Here is an update on  the progress:

1. I have introduced a `sheet.update(data)` method which will call all function values with that data argument and render the returned result.

2. In "react-jss" I will split a sheet into 2 sheet: static and dynamic. I will walk over styles object and move props with function values into separate styles object.
    ```
    const styles = {
      button: {
        float: 'left',
        color: (data) => data.color
      }
    }

    will be compiled by react-jss (later by a separate package)

    // Static Sheet.
    const styles = {
      button: {
        float: 'left'
      }
    }

    // Dynamic Sheet.
    const styles = {
      button: {
        composes: staticSheet.getRule('button'),
        color: (data) => data.color
      }
    }

    ```

**Comment by kof** [comment]
Right now plugins do not react on dynamic values changes, this will be part of a separate feature, probably a new hook `onChangeValue`, so that plugins like vendor-prefixer or default-unit can implement this hook and modify the value before its applied to the dom.

**Comment by DenisIzmaylov** [comment]
Probably we should not retry styled-components mistakes.

Instead of this we can keep architecture consistency with React.js (+ React Native) and just introduce Virtual CSS to JSS including a kind of Reconciliation algorithms and [ReactDOMServer](https://facebook.github.io/react/docs/react-dom-server.html).

It means on each `render()` in React component we can calculate CSS from JSS.

That is part of the one of our React Native applications which we developed for our customer a few months ago:

```javascript
// ...
  render() {
// ...
    const fontSize = props.fixedFontSize ? INSIGHTS_FONT_SIZE : scaledFontSize || basicFontSize
    const insightTextStyle = [
      styles.itemText,
      { fontSize },
      isScaling && styles.itemTextScaling,
    ]
    const containerStyles = [
      styles.item,
      props.style,
      isScaling && styles.itemScaling,
    ]
    return (
      <TouchableOpacity
        activeOpacity={0.75}
        style={containerStyles}
        onPress={this._onCardPress}
        >
        {isScaling && (
          <View style={[styles.itemInnerScaling]}>
            <AutoText
              style={styles.itemText}
              maxHeight={maxContentHeight}
              initialFontSize={scaledFontSize || BASIC_FONT_SIZE}
              onComplete={({ fontSize }) => this.handleScaleComplete({ fontSize })}
              >
              {finalContent}
            </AutoText>
          </View>
        )}
// ...
```

As you noticed - React Native uses Inline Styles approach.

For React Web we can use just something like:

```javascript
  return (
    <MyCard className={stylesheet.renderToStyle([styles.myCard, styles.cardWithToolbar])}
```

See also:

+ https://bugs.chromium.org/p/chromium/issues/detail?id=387952
+ https://ryantsao.com/blog/virtual-css-with-styletron

**Comment by kof** [comment]
@DenisIzmaylov I am not sure how this is related to the current issue, can you please move your comment to a separate one, so that we can discuss it separately?

**Comment by kof** [comment]
Merged.

**Comment by kof** [comment]
released
