### ISSUE TITLE
jss.version is broken

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#357]
Lately I started to use cross-env, but that broke current way for version env variable replacement.

I was already looking to replace the current solution by babel-plugin-inline-package-json. But this one only supports "require" calls, no imports. 

I am happy to any suggestions or maybe someone can fix that babel-plugin, or we just use a require in this case but its not nice.

**Comment by umidbekkarimov** [comment]
Here you go http://astexplorer.net/#/O0SIDMBBNi

**Comment by kof** [comment]
The problem is to replace the version using package.json so that we don't have to maintain it in 2 places.

**Comment by kof** [comment]
Ah so you suggest to use an own transform and require the package.json manually ... that could work as well.

**Comment by umidbekkarimov** [comment]
Yep, I can create PR, tomorrow.

**Comment by kof** [comment]
Cool, where do you put that transform function?

**Comment by kof** [comment]
fixed, will be released with the next major release.
