### ISSUE TITLE
unable to get sheets from local jss used in a component during SSR

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/jss#360]
If a module (e.g. for a React component) creates its own jss so that it can specify which plugins it needs, all works fine -- on the client side, since each sheet gets attached to the DOM.

But when doing server-side rendering, the current proposed method is to get the sheets from the global jss instance -- which wouldn't include sheets from any of the local jss instances used by some modules.

This is why [my PR](https://github.com/cssinjs/react-jss/pull/56) for `react-jss` passes down a `SheetsRegistry` via `context` rather than a jss instance.  Even if you decide not to accept that PR, we will need to solve this issue another way.

**Comment by kof** [comment]
What is the use case where you would want to create separate jss instances ins specific components? The idea for separate instances was not because you could create a jss instance in every component. It was because you could create an instance for the project.

**Comment by jedwards1211** [comment]
@kof I'm thinking about the future where people use jss in React library components.  If those libraries need specific jss plugins, and they don't create a local jss instance, they have to tell the user to put those plugins in their global jss config.  And it's even possible that two libraries would need conflicting jss plugin config.

So I think the best pattern for library components is to create a local jss with the needed plugins.  But if that's the case we need something like my PR to pass down a `SheetsRegistry` for SSR, or those components' styles won't get rendered on the server side.

Does that make sense?

**Comment by kof** [comment]
Yeah, makes sense to me. So we allow them to use different jss instances, but they are able to grab the sheets registry from the context and though everything can be aggregated.

**Comment by kof** [comment]
As we exported SheetsRegistry now next step is react-jss changes. I assume we are done for jss core.

**Comment by jedwards1211** [comment]
Awesome, thanks!
