### ISSUE TITLE
Typescript definitions for JSON DSL.

### ISSUE THREAD

**Issue by zerkalica** [cssinjs/jss#361]
Do you think about typesafe styles builder, like [typestyle](https://github.com/typestyle/typestyle) ?

**Comment by kof** [comment]
Thats super nice! I would love types such types annotations for typescript as well as for flow. But I don't have resources for it. I can keep the issue in case some will see it and wants to implement.

**Comment by cvle** [comment]
I opened an issue specifically for typescript type definitions that I'm already working on: https://github.com/cssinjs/jss/issues/362

**Comment by cvle** [comment]
To clarify my previous comment. The typescript definitions I'm working on will focus on the API and not the full JSON DSL.

**Comment by kof** [comment]
Also, if we have type definitions we don't need a css linter, right or do we?

**Comment by ai** [comment]
Nope. Linters is not only about right value for right property. There are many other rules. For example, that all proprerties are supported by all browsers. All that this two colors are too similar and user will not see a difference. Or warning about slow CSS properties (Facebook has custom rule for it).

**Comment by kof** [comment]
https://github.com/typestyle/typestyle/issues/37

**Comment by cvle** [comment]
The JSON DSL of `jss` depends on what plugins are used. Due to this dynamic nature, I don't think we can provide exact type definitions. 

For example this is only valid when `jss` is used with the `jss-camel-case` plugin:

```javascript
{
  fontSize: "10px"
}
```

And this is only valid when `jss` is used with the `jss-default-unit` plugin:
```javascript
{
  "font-size": 10, 
}
```

The list goes on and on. 

I'm still thinking about whether we could provide typescript definitions that includes all possible variations, but then they would be very permissive and of little help except maybe for autocompletion if at all. Moreover, who can say how _all possible variations_ looks like?

Or maybe we provide type definition presets?

You see this is all quiet complicated.

First step is to have robust type definitions for the API and its plugins, which I'm working on.

**Comment by cvle** [comment]
> Also, if we have type definitions we don't need a css linter, right? cc @ai

typescript only ensures that you are using a valid type, and not if you are using a valid value. So linters are necessary.

`typestyle` has a static JSON DSL as they don't support plugins. This makes it a lot easier for them to have a typesafe JSON DSL.

**Comment by kof** [comment]
So can be select type defs, depending on what plugins are used?

**Comment by kof** [comment]
Optionally, typings can be done for a default preset.

**Comment by cvle** [comment]
We could probably do something like this:
```typescript
jss.createStyleSheet<TDefaultPreset>(styles);
```

And when a user needs different plugins, they need to define their own type:
```typescript
jss.createStyleSheet<TCustomType>(styles);
```

And without type checks:
```typescript
jss.createStyleSheet(styles);
```

**Comment by zerkalica** [comment]
Or generate type defs from multiple plugins.

CustomType often is combination of some plugins.

```js
// @flow

type Base = {
  fontSize: string;
}

type UnitInPixels = {
  fontSize: number;
}

type NoCamelCaseBase = {
  'font-size': string;
}
type NoCamelCaseUnitInPixels = {
  'font-size': string;
}
```

**Comment by cvle** [comment]
We probably can find a way to provide "building blocks" to help users combine their own "CustomType" easily.

**Comment by cvle** [comment]
@zerkalica An automated type generator would be the holy grail, but let's get there in smaller steps :-)

**Comment by zerkalica** [comment]
Smaller step is type definition for common set of plugins.

**Comment by devdoomari** [comment]
plugin-issues can be solved by 'merging' types:

https://www.typescriptlang.org/docs/handbook/declaration-merging.html

here's one example:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-css-modules/index.d.ts#L32

**Comment by kof** [comment]
Turns out there is already a good project https://github.com/typestyle/typestyle/

Now we just need to make it work with jss.

**Comment by devdoomari** [comment]
@kof
typestyle/typestyle#37
I guess that didn't work out :(

how about we can 'steal' some definitions from typestyle, and work from there :P

anyway, I'm willing to help on JSS-typescript, as typestyle is barely usable with multiple media queries.
(TypeStyle uses FreeStyle, and FreeStyle has faulty implementations regarding style-orders - e.g. order of media-queries can get mixed-up)

**Comment by kof** [comment]
> how about we can 'steal' some definitions from typestyle, and work from there :P

sure, I can't help though as I am using flow

**Comment by appsforartists** [comment]
I may end up throwing together a really lazy TS definition, primarily to get autocomplete on keys of `styleSheet.classes`.

I need to type `create` and `setup` before it's usable, but it's essentially:

```typescript
declare namespace jss {
  export interface StyleSheet<R> {
    attach(): StyleSheet<R>,
    classes: {
      [K in keyof R]: string;
    },
  }
  
  export function createStyleSheet<R>(rules: R, options: {}): StyleSheet<R>;
}

```

**Comment by kof** [comment]
Thats a beginning :)

**Comment by appsforartists** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21851

**Comment by appsforartists** [comment]
You could probably get a lot of bang:buck if you relied on [`@types/react`'s `CSSProperties`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react/index.d.ts).  If you're using the camel-case and default-unit plugins, you can check for a property in `CSSProperties` and use its type if one exists; falling back to `[string]: any` if it isn't found (or if those plugins aren't used).

**Comment by kof** [comment]
closing in favour of https://github.com/cssinjs/jss/issues/776
