### ISSUE TITLE
Typescript type definitions for the API

### ISSUE THREAD

**Issue by cvle** [cssinjs/jss#362]
I'm already working on it. This can be assigned to me.

**Comment by kof** [comment]
I thought you are working on types for jss api, but you are working on it for the json dsl as well?

**Comment by cvle** [comment]
I might have misinterpret the other issue. I'm focusing on the API.

**Comment by kof** [comment]
exactly!

**Comment by kof** [comment]
Ping me when typescript annotations are usable, I will make an announcement on twitter! Closing this issue as I don't see why we need it.

**Comment by cvle** [comment]
My thought was keeping this, so that:
- the community can see that we are working on it
- can track the progress

Anyway I will ping you when they are ready to be discussed.

**Comment by kof** [comment]
Ok, then reopening.

**Comment by Truedrog** [comment]
Is there any progress on this?

**Comment by devdoomari** [comment]
I'm not sure how we can coax typescript to check JSS's current JSON-format.
How about having 'extra-helper' methods for creating JSON format?

e.g.
```javascript
const styles = {
  button: {
    fontSize: 12,
    '&:hover': {
      background: 'blue'
    }
  },
  ctaButton: {
    extend: 'button',
    '&:hover': {
      background: color('blue').darken(0.3).hex()
    }
  },
  '@media (min-width: 1024px)': {
    button: {
      width: 200
    }
  }
}
```
would be:
```typescript
const styles: JSSStyle = {
  button: Style({
    fontSize: 12,
    on(JSSEvents.HOVER): Style({
      background: 'blue'
    })
  }),
  ctaButton: Style({
    extend: 'button',
    on(JSSEvents.HOVER): Style({
      background: color('blue').darken(0.3).hex()
    }),
  }),
  forScreens({ minWidth: 1024 }): Style({
    button: {
      width: 200
    }
  }),
}
```

**Comment by Valbrand** [comment]
@devdoomari I understand the reason behind what you've proposed, but I also think it hurts what's beautiful about JSS. The signal-noise ratio is too low IMO, although I can't think of any better solution from the top of my head. I think some type definitions may not even be possible, since plugins may define what's allowed and what's not. Am I right?

**Comment by kof** [comment]
It has to go over public interfaces, no special fn calls. In JSS core it is jss.createStyleSheet(), jss.createRule(), sheet.addRule(), sheet.addRules()

**Comment by devdoomari** [comment]
@Valbrand 
well, for plugins, we can do:

```typescript
const style: JSSStyleCore & JSSStylePlugin1 & JSSStylePlugin2 = {
    ...
}
```

**Comment by vyrotek** [comment]
@devdoomari If I understood you right you're talking about using TypeScript Intersection Types like in this TSX React example? You'd basically just add `& JSSStyleCore` to CounterProps and now your props has styles typing on it. Sounds straightforward to me.

![image](https://user-images.githubusercontent.com/518436/29340263-ea065f9a-81d2-11e7-8f8a-f996e675e7e3.png)

**Comment by appsforartists** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21851

**Comment by kof** [comment]
closing in favor of https://github.com/cssinjs/jss/issues/776
