### ISSUE TITLE
Adding an @media rule throws in this case

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#363]
Original issue https://github.com/cssinjs/aphrodisiac/issues/4

Reproducible when you call `.addRule()` without `float: left`.
```javascript
{
  base: {
    float: 'left',
    '@media only screen and (min-width: 1024px)': {
      width: px(20),
    }
  }
}
```

**Comment by tiagojsalmeida** [comment]
@kof any investigation regarding this issue?

**Comment by kof** [comment]
Didn't come to it yet, but soon. I actually already know what to do there, just need a bit time.

**Comment by tiagojsalmeida** [comment]
Awesome! Thanks @kof ;)

**Comment by kof** [comment]
Ok now on it.

**Comment by kof** [comment]
Strange, it just works right now.

**Comment by kof** [comment]
Ok got it reproduced.

**Comment by kof** [comment]
Latest jss doesn't throw any more, so it renders already. The only bug now is the warning, which I am fixing now

**Comment by kof** [comment]
And then releasing a new aphrodisiac version.

**Comment by kof** [comment]
fixed and released
