### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by tiagojsalmeida** [cssinjs/jss#364]
Hey guys.

My friend @PepijnSenders made some quick benchmarks with some css-in-js libraries like yours here: https://github.com/PepijnSenders/css-in-js-perf-tests/

JSS turned out to be the slowest and we would like to know why and if you have plans to improve performance.

**Comment by cvle** [comment]
You are not using `jss` correctly. At the moment you have to create a separate `jss` instance on each run, otherwise the style sheets will pile up.

```javascript
import { create } from 'jss';
import preset from 'jss-preset-default';
import React from 'react';
import { renderToString } from 'react-dom/server';
import { App } from '../components/App';
import { styles } from '../styles';

export const jssCase = () => {
    const jss = create(preset());
    const { classes: { container, button } } = jss.createStyleSheet(styles).attach();

    const renderedHtml = renderToString((
        <App classNames={{
            container,
            button,
        }} />
    ));

    const css = jss.sheets.toString();

    return `
        <html>
            <head>
                <style type="text/css">${css}</style>
            </head>
            <body>${renderedHtml}</body>
        </html>
    `;
};
```
```
aphrodite          x  5,364 ops/sec ±1.07% (83 runs sampled)
jss                x  7,413 ops/sec ±1.22% (80 runs sampled)
jss-without-preset x 10,860 ops/sec ±1.27% (84 runs sampled)
glamor             x 11,333 ops/sec ±1.23% (80 runs sampled)
```

The number will probably be even better, when we provide a way to reuse the `jss` instance for SSR (e.g. separate style sheet registry)

@tiagojsalmeida By the way you didn't include the cxs dependency in your project.

**Comment by cvle** [comment]
`glamor` is caching the style sheet using a hash, so it only creates a style sheet on first run and uses the cache on subsequent runs. This why it performs fast in this benchmark.

@kof Do you think a similar caching mechanism would benefit `jss`?

**Comment by PepijnSenders** [comment]
Hey @cvle, thanks for clearing that up for us. I also removed the cache from glamor after every run, so the results should be even better:

```
  5 tests completed.

  aphrodite          x  6,088 ops/sec ±7.65% (62 runs sampled)
  jss                x 11,291 ops/sec ±8.39% (75 runs sampled)
  jss-without-preset x 11,622 ops/sec ±17.20% (52 runs sampled)
  glamor             x  6,623 ops/sec ±14.67% (67 runs sampled)
  cxs                x 12,121 ops/sec ±3.80% (75 runs sampled)

Fastest is: cxs,jss
```

**Comment by cvle** [comment]
This looks a lot better 👍

**Comment by kof** [comment]
Guys, you are awesome, thanks for making that bench, I wanted actually to do it in the main bench runner, was really curious. I am actually surprised that aphoridite and glamor are only +-50% slower.

Aphrodite is using asap, aren't you measuring air there?

**Comment by kof** [comment]
> glamor is caching the style sheet using a hash, so it only creates a style sheet on first run and uses the cache on subsequent runs. This is why it performs fast in this benchmark.
@kof Do you think a similar caching mechanism would benefit jss?

Yeah there is def. a  room for some caching here. Lets create a separate issue.

**Comment by kof** [comment]
Did any one take a look why is cxs fast?

**Comment by PepijnSenders** [comment]
@kof check out the updated tests.

**Comment by PepijnSenders** [comment]
FYI, the repo location changed: https://github.com/hellofresh/css-in-js-perf-tests

**Comment by kof** [comment]
Haha just wanted to link it in the docs)) good timing

**Comment by PepijnSenders** [comment]
Hehe, that is very good timing indeed.

**Comment by kof** [comment]
If you want we can also put it into cssinjs repo.

**Comment by PepijnSenders** [comment]
I think it looks more independent if we keep it there right? 😉

**Comment by kof** [comment]
So it doesn't make an impression bench is optimized for jss?))) I think it doesn't matter because the code is open.

**Comment by kof** [comment]
But I don't really care, I thought it would be better for discoverability and from namespace perspective. U would need to maintain it anyways)))

**Comment by PepijnSenders** [comment]
That's true 😄, there's also a blog post coming up that's in draft mode right now. But let's leave it the way it is for now.

On a different note, I saw you also reside in Berlin, we should grab a ☕️ some time #notarecruiter.

**Comment by kof** [comment]
Only if you really #notarecruiter)))))

**Comment by PepijnSenders** [comment]
FYI: https://engineering.hellofresh.com/the-css-in-js-battle-89c34a7a83ea#.igooociw6 😄
