### ISSUE TITLE
How to get reference to generated style element?

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#366]
I have a small problem: I'm using ShadowDOM. This means that the global styles generated by JSS don't apply inside of shadow roots.

One solution (which I don't like, and which is [probably the only solution at the moment](https://github.com/w3c/webcomponents/issues/609)), is to copy the `textContent` of global `<style>` elements (or clone them) into new `<style>` elements inside of the shadow roots. As you can imagine, this can be expensive if there are hundreds or thousands of custom elements with shadow roots.

I was going to use this approach (for now, even though I don't like it), but I need some way to be able to get a reference to the generated `<style>` elements. I thought maybe if they had IDs or something that I could get the references and finally get their `textContent`.

I tried [logging the result from `createStyleSheet`](https://jsfiddle.net/trusktr/qm26s2mz/), but don't see any reference there. Is there some way to get a reference?

**Comment by kof** [comment]
Even if you get the style element and get its content, it doesn't really solve you problem. The probelm is shadow dom, not jss. It doesn't play nice with global css.

**Comment by kof** [comment]
for you hack its `sheet.renderer.element`

**Comment by kof** [comment]
Or you could simply get the css string from sheet by `sheet.toString()`

**Comment by kof** [comment]
Also you could clone the node `sheet.render.element.cloneNode()` and insert it in your root, maybe this is the fastest way.

**Comment by trusktr** [comment]
I guess this is a good question: which is more preferable?

1. Generating one `<style>` element per shadow root so that all elements in all roots are styled, or
1. Applying styles to each element instance via `style` attribute without having to consider shadow roots.

In both cases, the elements I wish to style are custom elements of my library, and the JSS styles are handled within those classes. In case 1, the `stylesheet.classes` would be added to the custom element `classList` property on instantiation. In case 2, rules are applied to the custom element's `style` attribute on instantiation.

**Comment by trusktr** [comment]
Seems like option 1 performs better, while option 2 is easier to code and maintain.

**Comment by trusktr** [comment]
@kof Constructible style sheets (`new CSSStyleSheet`) have landed in Chrome! We're still waiting on Firefox and Safari.

Is there a way to share the style sheet from one `<style>` element with another `<style>` element, as a workaround?

**Comment by kof** [comment]
What is the use case?
