### ISSUE TITLE
[jss-expand] More array syntaxes

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#370]
Currently we have a limited number of props which support array syntax without double arrays. Should't we add more of them? https://github.com/cssinjs/jss-expand/blob/master/docs/index.md#using-arrays-for-space-separated-properties

for e.g. `border: [1, 'solid', borderColor]`

**Comment by kof** [comment]
@typical000 wdyt?

**Comment by kof** [comment]
This comes from talking to @giuseppeg who's first impression on `border: {width: 1, style: 'solid', color}` i s that its a bit verbose. 

I think it comes from being used too much to the shorthands in css.

**Comment by kof** [comment]
The advantage of using array syntax vs. string is:

1. default units
1. variables without string interpolation

I think we should work in both directions, expanded syntax and simplified (just one array) array syntax.

**Comment by typical000** [comment]
Sure, we can add them. With properties like `border` I agree. But what we can do with properties like `transition` ?
Because now we support (this situation is described in docs):
`````````````````````````````````js
transition: ['opacity 200ms', 'width 300ms']; // --> transition: opacity 200ms, width 300ms; 
`````````````````````````````````
And, if we add `transition` property to `propArray` we'll drop support of precedent example, but start support of:
`````````````````````````````````js
transition: ['opacity', 200]; // --> transition: opacity 200ms;
`````````````````````````````````
As for me second solution is better. Who want to write an array of long strings? :)
@kof wdyt?

NOTE: In any case we still support:
`````````````````````````````````js
transition: [['opacity', 200]['width', 300]]; // --> transition: opacity 200ms, width 300ms
`````````````````````````````````

**Comment by typical000** [comment]
I can add those properties:
1. border
2. border-bottom
3. border-left
4. border-top
5. border-right
6. box-shadow
7. flex (Need to add to jss-default-unit too)
8. outline
9. text-shadow
10. transform (Need to add to jss-default-unit too)
11. transition (Need to add to jss-default-unit too)

**Comment by typical000** [comment]
Added PR https://github.com/cssinjs/jss-expand/pull/14

**Comment by kof** [comment]
merged
