### ISSUE TITLE
React - Passing down wrapper classes css specificity issue

### ISSUE THREAD

**Issue by liveresume** [cssinjs/jss#372]
It seems like we cannot pass down wrapper classes from parent to child because of CSS specificity. In particular, when multiple classes are specified on a component with equal properties, classes that come later in the stylesheet override those before it.

So this is not possible:

```js
const parentStyles = {
  buttonWrapper: {
    width: '300px',
    color: 'blue',
  }
}
@injectSheet(parentStyles)
class Parent extends React.Component {
  render () {
    const { sheet: { classes } } = this.props
    return (
      <div>
        <Button className={classes.buttonWrapper} />
      </div>
    )
  }
}

const buttonStyles = {
  buttonBase: {
    color: 'red',
  }
}
@injectSheet(buttonStyles)
class Button extends React.Component {
  render () {
    const { className, sheet: { classes } } = this.props
    return (
      <button className={classNames(classes.buttonBase, className)} />
    )
  }
}
```

The parentStyles are added to the stylesheet before the buttonStyles.  So the button will turn out to be red and 300px, instead of blue and 300px.

What are some ways to resolve?

**Comment by kof** [comment]
you can specify an [index option](https://github.com/cssinjs/jss/blob/master/docs/js-api.md#attach-style-sheets-in-a-specific-order)

**Comment by liveresume** [comment]
@kof I saw that but it would require keeping track of how deep the component is wrt to other injectors.  I realized that while componentWillMount works from parent to child, componentDidMount goes the other way.  So I moved the attach() to cdm and this solved the issue.  Although I think in some cases this might not work.  

I like the idea of attaching when css(...) is called like in Aphrodite, which totally solves specificity issues, but would need to write something.. Aphrodisiac doesn't seem to work well with dynamic theming so I'm not using that approach.

**Comment by kof** [comment]
Do you see something Aphrodite can do but aphrodisiac can't?

**Comment by kof** [comment]
>  it would require keeping track of how deep the component is wrt to other injectors. 

You just need to define one lever higher index in the child than in the parent. But I assume in your situation you don't know what index parent has, right?

>componentWillMount works from parent to child, componentDidMount goes the other way

You may get a FUC in this case, because DOM will be rendered faster than the sheet.

**Comment by liveresume** [comment]
Turns out my cdm approach broke for a special case as I had feared.  Switched it to pass nested level down via context, and use the negative of that value as jss index.  Works perfect so far.

**Comment by kof** [comment]
Can you give me an example how you do this?

**Comment by liveresume** [comment]
I used mobx's Provider to provide a better api over React context.  Created a provider in the app container that had my theme and added a store to track nested level with value = 1.  Used mobx @inject('theme', 'nestedLevelStore') in my @injectSheet(styles) HOC.  In the HOC we add 1 to the level, and then create a *new* provider, overriding the last, with the new level wrapping the child.  

So now that we have our nested level just call jss with the index = negative value of the level.

Might be good to post my code as a new project?

**Comment by kof** [comment]
Maybe you can rephrase it in more simpler words without relying on full mobx understading? So that I can grasp what you actually did on  low level)))

**Comment by kof** [comment]
I think we got this fix here https://github.com/cssinjs/react-jss/issues/61
