### ISSUE TITLE
[jss-compose] Conflict with other plugins

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#374]
Suppose we use order as here https://github.com/cssinjs/jss/blob/master/docs/plugins.md
We write such code:
```````````````````````````````````````````````js
linkActiveNoChildren: {
    composes: ['$linkNoChildren', '$linkActive']
}
```````````````````````````````````````````````
And, as result we receive browser warining:
> vendor.bundle.js:25585 Warning: [JSS] Referenced rule is not defined. 
.linkActiveNoChildren-3174634915 {
    composes: $linkNoChildren,$linkActive;
}

But, instead of warning jss-compose must generate classes like `this.props.sheet.linkActiveNoChildren === 'linkNoChildren-2021460718 link-2652749541 linkActive-1277801469 link-2652749541'`

Possibly jss-compose conflicts with jss-expand but i'm not sure. As a solution we can try to move jss-compose up in order and see what happens

**Comment by kof** [comment]
Can you show the full sheet you are using?

**Comment by typical000** [comment]
```````````````````````````````````````````````js
export default {
  // Links
  link: {
    color: vars.sidebarColor,
    padding: [1.5, 6, 1.5, 2.5],
    textDecoration: 'none',
    fontWeight: 300,
    display: 'block',
    borderTop: vars.border(vars.sidebarBorder),
    borderBottom: vars.border(vars.sidebarShadow),
    backgroundColor: vars.sidebarBg,
    transition: vars.transition(),
  },
  linkActive: {
    composes: '$link',
    backgroundColor: vars.sidebarBgActive,
  },
  // Links without childrens
  linkNoChildren: {
    composes: '$link',
    paddingRight: 2.5
  },
  linkActiveNoChildren: {
    composes: ['$linkNoChildren', '$linkActive']
  },
}
```````````````````````````````````````````````

**Comment by kof** [comment]
Looks like it should work, need to try out.

**Comment by typical000** [comment]
Removed all unused stuff. This code throws in repl the same warning:
```````````````````````````````````````````````````````js
return {
  link: {
    color: 'red',
  },
  linkActive: {
    composes: '$link',
  },
  // Links without childrens
  linkNoChildren: {
    composes: '$link',
  },
  linkActiveNoChildren: {
    composes: ['$linkNoChildren', '$linkActive']
  },
};
```````````````````````````````````````````````````````
In console:

> browser.js:49 Warning: [JSS] Referenced rule is not defined. 
.linkActiveNoChildren-3174634915 {
  composes: $linkNoChildren,$linkActive;
}

**Comment by typical000** [comment]
https://github.com/cssinjs/jss-preset-default/pull/4
https://github.com/cssinjs/jss/pull/378
Here is the fix

**Comment by typical000** [comment]
Mybe we need some single test inside jss main repo that includes all plugins together? Creating this test we will avoid such bugs, i think

**Comment by kof** [comment]
Definitely, we need to design all test scenarios which involve all plugins!

**Comment by kof** [comment]
But first things first, lets release the site, finish the jss-global, then do this.

**Comment by typical000** [comment]
yeah. Agree. Lets add todo)

**Comment by kof** [comment]
this is done I believe.
