### ISSUE TITLE
Flowtype definitions JSON DSL

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#375]
We have actually CSSOM types, which we can use to provide the JSON types for JSS. https://github.com/facebook/flow/blob/master/lib/cssom.js#L70

**Comment by jhessin** [comment]
Note my .flowconfig (produces no errors):

```
[ignore]

[include]
src/

[libs]
node_modules/jss/flow-typed

[lints]

[options]
unsafe.enable_getters_and_setters = true

[strict]

```

**Comment by kof** [comment]
closing in favor of https://github.com/cssinjs/jss/issues/776
