### ISSUE TITLE
global and local plugin configs when using 3rd party components that rely on JSS

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/jss#377]
I've been thinking about other problems that using JSS in library components poses, as I start writing my own npm packages that use JSS.

One example is vendor prefixing; a 3rd party component should probably allow external app code to apply vendor prefixing.  But in the current design, if a 3rd party component sets up a `jss` instance without `jss-vendor-prefixer`, its styles won't get prefixed no matter what.

@kof how do you think we should solve issues like this?

**Comment by kof** [comment]
>  a 3rd party component should probably allow external app code to apply vendor prefixing.

Why?

**Comment by kof** [comment]
I think a component should be self-contained, which means it should work as-is if rendered on the page.

**Comment by jedwards1211** [comment]
@kof I would think that the app creator would want to be in control of prefixing so that they don't have to add prefixes for any browsers they don't support, and so that 3rd party comps don't have to worry about it

**Comment by jedwards1211** [comment]
but maybe I'm overthinking this

**Comment by kof** [comment]
You make an assumption here that there is a difference in terms of vendor prefixing to support all browsers. The runtime vendor prefixer currently works for all and will be much better very soon, we are refactoring it right now. When you are talking about static vendor prefixing serverside, you are right, thoguh you are talking about a bunch of css props which you would want to optimize out. I think its not the highest prio right now, we have better tasks to solve.

**Comment by jedwards1211** [comment]
Makes sense, thanks!

**Comment by kof** [comment]
If you have spare time let me know on gitter, we have a bunch of important issues to solve!
