### ISSUE TITLE
[jss-font-face] Create font-face plugin

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#38]
Async font loading using this technic

http://www.filamentgroup.com/lab/font-loading.html

https://github.com/filamentgroup/font-loading/blob/master/data-uris-cookie.html

**Comment by dubert** [comment]
:+1:

**Comment by kof** [comment]
Seems like we should use a fonts check observer if we want to render the app once font is loaded https://www.filamentgroup.com/lab/font-events.html
