### ISSUE TITLE
[jss-nested] nesting inside of jss-global block

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#380]
```
{
  '@global': {
    '.text': {
      '& button': {
        'font-style': 'italic'
      }
    }
  }
}
```

**Comment by typical000** [comment]
When this bug will be fixed, I'll update https://github.com/cssinjs/site to latest jss version and plugins.

**Comment by kof** [comment]
Fixed locally, just finalizing for release.

**Comment by kof** [comment]
Along the way made some perf improvements (20-30%)

**Comment by kof** [comment]
Fixed and released.
