### ISSUE TITLE
jss-nested conflict

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#387]
@oliviertassinari commented on [Sun Dec 18 2016](https://github.com/cssinjs/jss-global/issues/4)

Using the following rule is raising at that [line](https://github.com/cssinjs/jss-nested/blob/master/src/index.js#L25) as the `GlobalContainerRule` do not implement the `getRule` method as the `StyleSheet` [one](https://github.com/cssinjs/jss/blob/master/src/StyleSheet.js#L133).

```js
{
  '@global': {
    html: {
      background: '#eee',
       '@media (max-width: 767px)': {
         userSelect: 'none',
      },
    },
  },
}
```

---

@kof commented on [Sun Dec 18 2016](https://github.com/cssinjs/jss-global/issues/4#issuecomment-267823001)

Seems to be similar to https://github.com/cssinjs/jss/issues/380 but I will add a test for this case as well.

**Comment by kof** [comment]
Fixed and released.

**Comment by oliviertassinari** [comment]
Thanks.
