### ISSUE TITLE
[jss-vendor-prefixer] Wrong prefixed values

### ISSUE THREAD

**Issue by PhiLhoSoft** [cssinjs/jss#392]
Testing JSS (among other libraries), I use the new v. 6 (upgrading from v. 5.5.6) and started to use the vendor prefixer plugin.
I test it in the CSS-in-JS perf test: https://github.com/PhiLhoSoft/css-in-js-perf-tests/tree/complex-test-case

I see the [JSS syntax](https://github.com/cssinjs/jss/blob/master/docs/json-api.md) uses arrays for properties with several values. It makes sense, but several other libraries use them to provide fallback values, and that's what *inline-style-prefixer* assumes, for example.
I see that fallbacks have a specific syntax, like:
```
{
  container: {
    display: 'flex'
    fallbacks: [
      {display: 'box'},
      {display: 'flex-box'}
    ]
  }
}
```
Side note (a bit off-topic): I am not fan of this syntax, global to the class thus requiring to repeat the property name... And more difficult to adapt in the context of this issue...

Anyway, I guess that jss-vendor-prefix still issues an array of values (like *inline-style-prefixer*) instead of adapting to the new (?) syntax, so I get a warning at generation time:

> The invalid value `-webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex` has been used as `display`.

and the result indeed gives rules like:

    display: -webkit-box, -moz-box, -ms-flexbox, -webkit-flex, flex;

or

    background-image: -webkit-linear-gradient(to bottom, chartreuse, aquamarine), -moz-linear-gradient(to bottom, chartreuse, aquamarine), linear-gradient(to bottom, chartreuse, aquamarine);

which are, obviously, incorrect.

Thank you for this very interesting and complete library... 😄

**Comment by kof** [comment]
1.  inline-style-prefixer is not made for jss, it needs to be wrapped.
2. We switched from array value syntax for fallbacks, used that before, for a good reason.

So what is this issue about? What do you want me to do?

**Comment by PhiLhoSoft** [comment]
I mentioned *inline-style-prefixer* as an example, as it is mentioned by libraries as an external tool, or used internally to do the job. I shouldn't have mentioned it as it introduces confusion, but I thought it was an inspiration for your implementation.

The issue is really with JSS and its plugin, which produces incorrect code, as shown.

**Comment by PhiLhoSoft** [comment]
Ah, I did more tests, and it is very puzzling, I guess the problem is in my project...
When I apply *inline-style-prefixer* on one of my test cases (cxs), several others (fela, free-style, j2c and jss) are auto-prefixed, incorrectly in the case of JSS, of course! I have to investigate to see the source of the leak!
Perhaps ES6 modules (via Babel) are not isolated as much as I thought...

That said, using JSS with preset default or explicitly with the vendor prefixer plugin does nothing, ie. I see no prefixes. Is it supposed to do that on the server side, where there is no user agent? Other libraries default to adding all prefixes...

**Comment by kof** [comment]
> I thought it was an inspiration for your implementation.

No, they work radically different, this project existed years before I believe.

**Comment by kof** [comment]
> Is it supposed to do that on the server side, where there is no user agent? Other libraries default to adding all prefixes...

No, jss-vendor-prefixer is for browsers only, like mentioned everyhwere https://github.com/cssinjs/jss-vendor-prefixer

**Comment by kof** [comment]
For SSR we have  a separate issue https://github.com/cssinjs/jss/issues/279

Initially I thought to leave it up to the user. You can actually pass the css string to the autoprefixer.

**Comment by kof** [comment]
jfyi: We are refactoring the prefixing login right now https://github.com/cssinjs/css-vendor/pulls

**Comment by kof** [comment]
The new vendor prefixer will run tests which compare all results with autoprefixer and will make it fully conform.

**Comment by kof** [comment]
I still don't see what specific problem you stumbled upon…

**Comment by kof** [comment]
> Anyway, I guess that jss-vendor-prefix still issues an array of values 

No, it doesn't, it never did. It always results in just one value.

**Comment by PhiLhoSoft** [comment]
OK, I saw "*at runtime, in the browser*", but it didn't explicitly said it doesn't work on server-side, so I mentally jumped to (wrong) conclusions.

I will just close this issue. Thanks for the answers.
