### ISSUE TITLE
Can i attach minified styles?

### ISSUE THREAD

**Issue by LestaD** [cssinjs/jss#396]
I want to attach minified styles to page to optimize SSR

**Comment by kof** [comment]
You want to minify CSS output when rendering JSS on server-side? Sure you can.

**Comment by LestaD** [comment]
@kof how?

**Comment by kof** [comment]
Well you know how to get a css string from jss, right? then you need to call your minfier and pass that string.

**Comment by LestaD** [comment]
@kof oh. Thanks
