### ISSUE TITLE
Do not use babel-runtime

### ISSUE THREAD

**Issue by zerkalica** [cssinjs/jss#397]
My example webpack project:

```
webpack --config examples/app/webpack.config.es5.js --json | webpack-bundle-size-analyzer
```

With jss:

```
jss: 44.95 KB (17.3%)
core-js: 34.35 KB (13.2%)
process: 5.17 KB (1.99%)
babel-runtime: 3.03 KB (1.16%)
```

Without jss:

```
process: 5.17 KB (1.99%)
```

I do not use babel-runtime and core-js, but babel-runtime dependency in jss leaves my no choise: about 34 KB overhead of core-js.

Just add loose option to es2015 plugin and babili to produce compact and optimized code, runtime checks is unnecessary:

```json
{
  "presets": [["es2015", {"loose": true}], "stage-0"],
  "env": {
      "production": {
        "presets": ["babili"]
      }
    }
}
```

**Comment by kof** [comment]
Why is core-js there? Havn't expected it.

**Comment by zerkalica** [comment]
babel-runtime depends on core-js

**Comment by kof** [comment]
cc @umidbekkarimov

**Comment by kof** [comment]
Do you guys see what exactly causes babel-runtime to import core-js?  and how to avoid it?

**Comment by kof** [comment]
@zerkalica not using it will result in inlining all the utilities.

**Comment by umidbekkarimov** [comment]
* `babel-runtime/helpers/typeof` 
    * `core-js/symbol/iterator`
    * `core-js/symbol`
* `babel-runtime/helpers/extends`
    * `core-js/object/assign`
* `babel-runtime/helpers/createClass`
    * `core-js/object/define-property`

**Comment by kof** [comment]
Doesn't it require specific modules? why should it end up with the entire core-js?

**Comment by umidbekkarimov** [comment]
> Doesn't it require specific modules?

Yep

> why should it end up with the entire core-js?

It's not entire [core-js](https://github.com/zloirock/core-js#features)

**Comment by kof** [comment]
Still 34KB is way more than we have when inlining ... so it must be importing more than we use.

**Comment by zerkalica** [comment]
Example:

compiled lib/Jss.js:

```js
var _extends2 = require('babel-runtime/helpers/extends');
```

node_modules/babel-runtime/helpers/extends:

```js
var _assign = require("../core-js/object/assign");
```

../core-js/object/assign:
```js
module.exports = { "default": require("core-js/library/fn/object/assign"), __esModule: true };
```

babel-runtime not needed in libraries like jss.
If you use loose: true option, generated inline helpers are smaller than import declarations from babel-runtime.

**Comment by kof** [comment]
So its an entirely different implementation of "assign" function we use if using core-js. Babel inline functions are very small.

**Comment by kof** [comment]
How can we get babels inline functions required so that they are not copied over and over for every module?

**Comment by zerkalica** [comment]
Why it's a problem?

1. Say, generated helpers is about 5% in code, in 100KB project it's about 5KB, in 1MB project - 50KB. I think, it's not a problem - 50KB helpers instead of 34KB in 1MB app on frontend.
2. Decoupling. I prefer isolated code without or with minimum dependencies on third party libraries. Some developers create [your own optimized polyfills](https://github.com/Riim/cellx/tree/master/src/JS) with minimum functionality, instead of using fat, slow and overcomplicated core-js.
3. Dependency doubling. What if core-js or babel-runtime major version is old in some library? It was recently in react and fbjs. I had to manually remove node_modules/react/node_modules after each update.
4. core-js not optimized for module size and loads too much bootstrap code.
5. If you want speed optimized code, avoid using constructions that generates fat helpers: class inheritance (prefer composition), destruction (Object.assign), async/await (promises)
 
If you use flow, runtime checks in production code not needed. In babel i can't disable generation of thin helpers:  ``` _classCallCheck, _possibleConstructorReturn, var _extends = ... || for ... ``` But i try to investigate this problem and completly disable helpers generation.

I think using babel-runtime in projects < 1MB is bad practics. Generated helpers can be much, much smaller.

**Comment by kof** [comment]
I agree regarding core-js. But copies of helpers inline is also a waste, for e.g. https://github.com/rofrischmann/fela is using rollup and it makes perfect builds - check it out. I was trying to achieve the same without switching to rollup.

**Comment by zerkalica** [comment]
What do you mean? Dead code elimination or what?

**Comment by kof** [comment]
The way rollup packages the lib build.

**Comment by zerkalica** [comment]
It does not fix a problem, only masks it. It's a hack, [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js) replaces by regexp inline helpers in code, produced by babel. And creates single babelHelpers object per builded file. But what if our code is not in one chunk?

I think better to create global babelHelpers object and place it in each our app entry point.

**Comment by zerkalica** [comment]
Look at [fusebox helpers](https://github.com/fuse-box/fuse-box/blob/master/docs/builtin-plugins.md#typescript-helpers)

ex. [assign](https://github.com/fuse-box/fuse-box/blob/master/assets/libs/fuse-typescript-helpers/__assign.js) helper declares function in FuseBox.global registry.

**Comment by kof** [comment]
Seems reasonable, though I was looking to a way to achieve that using just babel.

**Comment by iamstarkov** [comment]
I would argue for removing polyfiills from the repo, as far as every app has its own unique environment every polyfill will be either inefficient or verbose. So i think that polyfilling environment is an app's responsibillity. What do you think

**Comment by kof** [comment]
yes, we need to remove it

**Comment by kof** [comment]
I oversaw some aspects of that decision.

**Comment by iamstarkov** [comment]
thats okay

**Comment by kof** [comment]
Closing this, will be release later at some point.

**Comment by kof** [comment]
released without babel-runtime
