### ISSUE TITLE
[jss-expand] Crash on empty array value

### ISSUE THREAD

**Issue by PhiLhoSoft** [cssinjs/jss#398]
Although the bug is mine (I think there is no reason to pass an empty array as a value), I report a little problem that has an easy fix, avoiding this plugin to crash...

In the `styleDetector` function, there is a check on arrays:

    if (value.constructor === Array && value[0].constructor !== Array) {

It crashes if the array is empty. A simple check can avoid this...
BTW, I wonder why you used this check instead of `Array.isArray` used below.

**Comment by kof** [comment]
Array.isArray is better. I guess @typical000 used constructor because its faster, but its less robust. I would switch to isArray.

It will fix the empty array check at the same time.

Please send a pr.

**Comment by PhiLhoSoft** [comment]
Done. Also check for empty string values.

**Comment by kof** [comment]
Released
