### ISSUE TITLE
[jss-isolate] isolate: false doesn’t work with jss-nested

### ISSUE THREAD

**Issue by sapegin** [cssinjs/jss#401]
This rule works fine:

```js
hasSidebar: {
	isolate: false,
	paddingLeft: 200,
},
```

But if I add nested part, `.hasSidebar` will be added to jss-isolate reset:

```js
hasSidebar: {
	isolate: false,
	paddingLeft: 200,
	'@media (max-width: 600px)': {
		paddingLeft: 0,
	},
},
```

Same if I add `isolate: false` inside media query too.

**Comment by kof** [comment]
Will check it out soon, sounds like a bug. If you want to try fixing it let me know.

**Comment by sapegin** [comment]
I’ll look into that in the evening.

**Comment by sapegin** [comment]
But how exactly it should work? Should it be isolated in this case?

```js
hasSidebar: {
	isolate: false,
	paddingLeft: 200,
	'@media (max-width: 600px)': {
		paddingLeft: 0,
	},
},
```

Or only in this?


```js
hasSidebar: {
	isolate: false,
	paddingLeft: 200,
	'@media (max-width: 600px)': {
		isolate: false,
		paddingLeft: 0,
	},
},
```

**Comment by kof** [comment]
I think it makes sense that `isolate` option applies, visually it looks like @media query is just extending the rule.

**Comment by sapegin** [comment]
Yeah, I agree. This change fixes the problem for me:

```diff
-    if (rule.options.parent && rule.options.parent.type === 'keyframe') return
+    if (rule.options.parent && (rule.options.parent.type === 'keyframe' || rule.options.parent.type === 'conditional')) return
```

I can send a pull request with it.

**Comment by kof** [comment]
Sounds good!

**Comment by sapegin** [comment]
Done: https://github.com/cssinjs/jss-isolate/pull/6

**Comment by kof** [comment]
published
