### ISSUE TITLE
Referencing an empty element ?

### ISSUE THREAD

**Issue by dagatsoin** [cssinjs/jss#403]
Why this code throws a warning?

```
const form = {
  wzForm_label: {},

  wzForm__stacked: {

    "& $wzForm_label": {
      display: "block",
      marginBottom: "10px",
      fontWeight: "bold"
    }
  }
}
```

-> `VM1155 browser.js:49 Warning: [JSS] Could not find the referenced rule wzForm_label. 
undefined`

**Comment by kof** [comment]
tried in the repl http://cssinjs.github.io/repl/ it doesn't , which means you are using an old version.
