### ISSUE TITLE
[jss-nested] Can't reference a rule from a non nested rule

### ISSUE THREAD

**Issue by dagatsoin** [cssinjs/jss#405]
related to https://github.com/cssinjs/jss/issues/403

As I am using BEM notation I need to declare them before use, but a strange things happens:

```
return{
  wzForm__small: {},

  [`select$wzForm__small,
    textarea$wzForm__small,
    input[type]$wzForm__small,
    input:not([type])$wzForm__small`]: {
    height: "10px",
    padding: "10px",
    fontSize: "10px"
  },
};
```
gives wrong css:

```
.select$wzForm__small,
    textarea$wzForm__small,
    input[type]$wzForm__small,
    input:not([type])$wzForm__small-186909326 {
  height: 10px;
  padding: 10px;
  font-size: 10px;
}
```

but it works when you reference a rule from a nested nested rule.

```
return{
  wzForm__small: {},
  
  foo:{
    [`& select$wzForm__small,
      & textarea$wzForm__small,
      & input[type]$wzForm__small,
      & input:not([type])$wzForm__small`]: {
      height: "10px",
      padding: "10px",
      fontSize: "10px"
    }
  }
};
```

gives:

```
.foo-3044032647 select.wzForm__small-2315792072, .foo-3044032647 textarea.wzForm__small-2315792072, .foo-3044032647 input[type].wzForm__small-2315792072, .foo-3044032647 input:not([type]).wzForm__small-2315792072 {
  height: 10px;
  padding: 10px;
  font-size: 10px;
}
```

**Comment by kof** [comment]
$variable is a part of jss-nested plugin, which means you can use it only inside a nested rule

**Comment by kof** [comment]
Also why do you use this ugly BEM notation, JSS is designed to avoid the need for it.

**Comment by dagatsoin** [comment]
How would you write this so ? I can'f find a clear way.

**Comment by kof** [comment]
I don't know clearly your use case.

**Comment by kof** [comment]
Maybe give me a simplified version in pure CSS of what you want to achieve.

**Comment by dagatsoin** [comment]
I am used to write my css rules with BEM notation. So if JSS is not meant for that, what guideline can I use ?

For example, what is the equivalent for a rule like this: `.wzFrom--input__big` ?

**Comment by kof** [comment]
BEM notation is an ugly hack to fix conflicting namespaces problem. In  JSS namespaces are generated and conflict free, you don't need any guidelines, just write nice names.

**Comment by kof** [comment]
you seem to be trying to achieve this:

```
return{
  wzForm__small: {
    'select &': {
      color: 'red'
    },
  },
};
```

**Comment by dagatsoin** [comment]
Ok, so I ended with this:

```
return{
  wzForm:{
    display:"block",
    width:"50%",
    [`& select$wzForm__small,
      & textarea$wzForm__small,
      & input[type]$wzForm__small,
      & input:not([type])$wzForm__small`]: {
      height: "10px",
      padding: "10px",
      fontSize: "10px"
    }
  },
  
  wzForm__small: {
    width:"20%",
  },
};
```
