### ISSUE TITLE
[cssinjs] Extract the engine into a separate project

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#406]
We built a site that renders md files from different repositories https://github.com/cssinjs/cssinjs

We could extract it into a separate engine so that any other project can use it as a static site generator.

The question is if there is a serious demand in this and who will be the first projects using it besides of our http://cssinjs.org site.

**Comment by kof** [comment]
Here is an article about our documentation site https://medium.com/@oleg008/new-documentation-site-for-jss-6c472cec841d

**Comment by DenisIzmaylov** [comment]
Just a one questions:

+ Why did not use www.gitbook.com + www.webpackbin.com?

And a few thoughts:

+ Use the font from GitHub or GitBook Docs with the same font-size and font-family. At the moment letters are small for reading. New font requires to adopt perception to read it. That all makes unnecessary cognitive load. 

+ White background is more useful according to GitHub UI. Almost developers used to white background for reading docs. We should not stress them.

**Comment by kof** [comment]
Why? 

Because we load  md files dynamically from all configured repositories, __versioned__!

But yes I also feel something is wrong with our typography there. I would gladly steal from github fonts and margins, cc @typical000

**Comment by typical000** [comment]
Maybe we can try with white background and font from github. Don't know for now.
But, seriously - we don't use some non-standart colors that calls epilepsy attack to our readers. :)
Lightly grey is just like 'white but not white', and all is readable, but don't look as a copy of something else.

**Comment by kof** [comment]
I don't see much of an issue with the background (I am not a designer), but font and margins/paddings/line-heights feels different, when switching from github, I always want to go back)

**Comment by kof** [comment]
By the way, we are not using webpackbin for the repl, because they serve a completely different purpose, repl is a playground to see what the compiled css looks like, webpackbin - to make working demos. We should setup an official playground for demos as well, so one can take a demo and quickly start experimenting.

**Comment by typical000** [comment]
> I always want to go back)

Bad. This shouldn't happen. Maybe in those days I'll try to change all to github style

**Comment by iamstarkov** [comment]
redesign is completely offtopic on this issue. pls create new one to discuss, if you want so

**Comment by DenisIzmaylov** [comment]
You're absolutely right. Extracted to https://github.com/cssinjs/jss/issues/428

**Comment by kof** [comment]
Doesn't seem like there is enough demand, should we close it  @typical000 ?

**Comment by typical000** [comment]
Yes, we can close it!
