### ISSUE TITLE
[cssinjs] Add version to the script tag

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#409]
Currently browser caches the scripts, seems like githubs cdn doesn't provide proper headers. I think we should add the version from package.json to the script src when generating html files.

**Comment by kof** [comment]
@typical000 can you please take a look?

**Comment by typical000** [comment]
@kof sure, created pr - https://github.com/cssinjs/cssinjs/pull/11

**Comment by kof** [comment]
Thanks!
