### ISSUE TITLE
[jss-rtl] Plugin for transforming to Right-To-Left (RTL)

### ISSUE THREAD

**Issue by pofigizm** [cssinjs/jss#410]
Learn more about ploblem and solution for postcss - https://github.com/MohammadYounes/rtlcss

**Comment by kof** [comment]
The idea is cool, somebody needs to take over it though. This might be something that can be used inside of the plugin. https://github.com/kentcdodds/rtl-css-js

**Comment by DenisIzmaylov** [comment]
This plugin is also could be useful:

+ https://github.com/vkalinichev/postcss-rtl

**Comment by kof** [comment]
Someone should wrap rtl-css-js by @kentcdodds into a jss plugin. It won't be me until I need it myself.

**Comment by alitaheri** [comment]
I've implemented the plugin: [jss-rtl](https://github.com/alitaheri/jss-rtl)
@kof any chance I can promote it from your repository? (or if possible become a member and move it here)?

**Comment by kof** [comment]
Lets reference it from documentation. I have in the main repository everything with the same code style and tools, and I am planing to use [mrm](https://github.com/sapegin/mrm) in order to manage all plugins in a more automated way.
