### ISSUE TITLE
Adjacent sibling selector

### ISSUE THREAD

**Issue by janhartmann** [cssinjs/jss#412]
I could not find any examples on how to use the adjacent sibling selector, e.g `.room-<id> + .room-<id>`.

I've tried using the following without any luck: 

```js
const styles = {
	room: {
		display: "flex",
		padding: [25, 20],
		"$room + $room": {
			borderTop: [1, 'solid', '#eee'],
		}
	}
}
```

But great library! :-)

**Comment by kof** [comment]
You want to target current rule?

**Comment by kof** [comment]
If you are already using jss-nested which is part of default preset, you can simply do `& + &`, like in sass, & is replaced by the parent class.

**Comment by janhartmann** [comment]
Ah heck, yes - it did not work since each element was wrapped in another div.

**Comment by kof** [comment]
So its what you need? Otherwise I don't know what you are trying to achieve.

**Comment by janhartmann** [comment]
The output is correct `& + &`. So no issues. Closing is fine
