### ISSUE TITLE
Deterministic StyleSheet id

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#413]
Now we got a use case for having a deterministic id for the sheet. Currently its needed by https://github.com/iamstarkov/jss-increase-id-specificity/ . cc @iamstarkov

**Comment by kof** [comment]
I see 2 possibilities for the implementation:
1. Implement it as part of the core
2. Make it an interface and let others pass it over options or/and setter.

In both cases we gonna need a new hook which is called after all onProcessRuleHooks. It could be `onProcessSheet(sheet)`.

**Comment by iamstarkov** [comment]
> 1. Implement it as part of the core

as far as so far only my plugin ever needed it, i dont see that much value in implementing id in a core

**Comment by kof** [comment]
@iamstarkov check it out on https://github.com/cssinjs/jss/tree/process-sheet-hook

**Comment by iamstarkov** [comment]
i decided to go with `sheet.toString()`. i guess its deterministic enough

**Comment by kof** [comment]
Ok as we found a solution without id, it seems to be irrelevant for now. Hook `onProcessSheet` is already in master. Closing this for now.

**Comment by kof** [comment]
onProcessSheet hook is released
