### ISSUE TITLE
Expose murmurhash function used for hash creation

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#418]
@iamstarkov suggested to export the function in order to let plugins and other dependents to use it directly from the package instead of installing it as an own dependency.

The question is if it makes sense to expose internal hashing and if it should be overwriteable by  a user legally.

**Comment by iamstarkov** [comment]
1) it will allow bundle to not grow 'cause of several hash implementations.
2) hash function will be consistent across jss ecosystem

my use case looks like this:

```js
import { create as createJss, hash } from 'jss';
import { create as createInjectSheet } from 'react-jss';
import presetDefault from 'jss-preset-default';
import increaseIdSpecificity from 'jss-increase-id-specificity';

const jss = createJss();

jss
  .setup(presetDefault())
  .use(increaseIdSpecificity({ hash }))

const injectSheet = createInjectSheet(jss);

export default injectSheet;

```

**Comment by kof** [comment]
@cvle @nathanmarks

**Comment by kof** [comment]
The question is why would the bundle grow if you depend on the exact same package "murmurhash-js" on npm?

**Comment by iamstarkov** [comment]
@kof answer is that you cant ensure that it will always be the case

**Comment by kof** [comment]
in that particular case, the alrgorithm is not changing any more, that package is very stable and actually  10loc, so exposing it would make it public API, where generateClassName function is actually an optional override and murmurhash is an internal implementation detail at the moment. Considered #432 we can actually close this one.

For e.g. we now change the way generateClassName works inside. If we would have exposed murmurhash before, we would need to incremant major version as removing it from the package would mean a breaking change.
