### ISSUE TITLE
rule.selector setter rewrite

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#419]
Currently we have a bunch of logic in [there](https://github.com/cssinjs/jss/blob/master/src/plugins/RegularRule.js#L57) which is needed in order to keep rule.className and sheet.classes in sync with rule.selector. Maybe we don't need it after all. If a plugin needs to set a selector, it can be just the selector. Property .className can stay as it was initially defined as well as the sheet.classes. So the rule won't be found over sheet.getRule('.new-selector') after rule.selector = '.new-selector' has been set and thats ok.

Also in jss-compose I am setting  a className, instead we should be setting the `.selector`

**Comment by iamstarkov** [comment]
i like it

**Comment by kof** [comment]
I am on it.

**Comment by kof** [comment]
released with v9
