### ISSUE TITLE
Option for specifying insertion point comment text

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#421]
We have a [comment node support](http://cssinjs.org/setup?v=v6.2.0#specify-dom-insertion-point) to specify where jss should start render the sheets in the head.

I found a need for an option to specify different text for the comment node to look for.

For e.g. u use material-ui with jss-theme-reactor together with react-jss and you want react-jss sheets rendered after jss-theme-reactor sheets.

Now we can pass an option to name  jss-theme-reactor insertion point differently than the one for react-jss like this:

```
import {create} from 'jss'
const jss = create({insertionPoint: 'mui-jss'})
```

**Comment by kof** [comment]
cc @nathanmarks

**Comment by kof** [comment]
Btw what is a better name for that option? insertionPoint, comment, insertAfter ?

**Comment by iamstarkov** [comment]
i have a question regarding this

> This can be useful if you have another dependency that needs to come before or after the jss Style Sheets for cascading specificity purposes.

what are the real world use cases?

**Comment by kof** [comment]
The example I described when using jss-theme-reactor and react-jss at the same time __is__ a real world case I got right now. Sheets of jss-theme-reactor come later in the order and though, selectors from react-jss can't overwrite them without using tricks. In the application it means that a UI lib css can't be overwritten by application CSS.

**Comment by kof** [comment]
Its basically [this string](https://github.com/cssinjs/jss/blob/master/src/backends/DomRenderer.js#L83) passed over options instead of hardcoded.

**Comment by kof** [comment]
released
