### ISSUE TITLE
Recommendations for production

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#422]
When an app gets big, it is possible there could be many components creating and destroying encapsulated stylesheets and rules, f.e. stylesheets inside a React component.

What are your suggestions for the best production performance?

**Comment by kof** [comment]
react-jss is doing very aggressive caching, it not only creates style sheet for the component just once, it also reuses the same style sheet between all component instnaces aka elements. We use it at chatgrape for the chat, which has already a very big code base and we are not even close to having any perf issues in JSS, you will likely to get some with react or whatever you use than with JSS.

You can shoot you into the foot of course if you recreate all the sheets at runtime all the time, but even then I doubt you will notice any performance overhead. Loook at the benchmarks http://cssinjs.org/performance, its performance is actually way more than you ever gonna need. And now imagine you render only the part you have visually visible (react-jss does that for you).

**Comment by kof** [comment]
so if you are not using react-jss or want you own wrapper:
1. reuse sheets after they are created
2. reuse them between the same elements
3. ideally detach/attach when they are used/unused, though this is not proven to have any perf impact.

**Comment by trusktr** [comment]
Thanks, I'll take a look at react-jss about the caching. I'm making Custom Elements, not exactly React, but maybe I can borrow some ideas.

**Comment by trusktr** [comment]
@kof Nice perf tests! I'm getting an error on http://jsperf.com/jss-vs-css/3:

<img width="1006" alt="screen shot 2017-02-16 at 10 20 05 am" src="https://cloud.githubusercontent.com/assets/297678/23034710/87b411d6-f431-11e6-9af7-3b7344184d66.png">

**Comment by kof** [comment]
looking into it.

**Comment by kof** [comment]
I see the problem.

**Comment by kof** [comment]
Will revisit all of them

**Comment by trusktr** [comment]
On this one, http://jsperf.com/css-selectors-amount-influences-dom-performance/3, I get 
<img width="1016" alt="screen shot 2017-02-16 at 10 25 02 am" src="https://cloud.githubusercontent.com/assets/297678/23034894/33344350-f432-11e6-924c-58329dea756d.png">

**Comment by kof** [comment]
jsPerf is unbelievable, its more often broken than its working. I can't update te test case right now. Maybe you are more lucky. The problem is that url used for jss is outdated, it needs to be this one https://unpkg.com/jss/dist/jss.js
