### ISSUE TITLE
[cssinjs] Site typography

### ISSUE THREAD

**Issue by DenisIzmaylov** [cssinjs/jss#428]
*Extracted from https://github.com/cssinjs/jss/issues/406#issuecomment-280821335*

It would be great to use the font from GitHub or GitBook (generated docs) with the same font-size / font-family / etc. At the moment letters are small for reading. New font requires to adopt perception to read it. That all makes unnecessary cognitive load. 

White background is more useful and comfortable according to GitHub UI. Almost developers used to see white background for reading docs. We should not stress them.

> @kof:
> But yes I also feel something is wrong with our typography there. I would gladly steal from github fonts and margins, cc @typical000

> @typical000:
> Bad. This shouldn't happen. Maybe in those days I'll try to change all to github style

**Comment by iamstarkov** [comment]
i dont see that much value in fixing this issue

**Comment by kof** [comment]
Its a low hanging fruit, lets do this! Value is subjective here, but to me and seems like some others it stands out.

**Comment by typical000** [comment]
Done https://github.com/cssinjs/cssinjs/pull/13
Additionaly:
1. Added styles-jss link
2. Renamed 'External projects' -> 'Projects'
3. Solved all eslint error
4. Updated dependencies

**Comment by typical000** [comment]
merged yesterday. Can be closed

**Comment by kof** [comment]
cool, thanks!

**Comment by kof** [comment]
published
