### ISSUE TITLE
Unique, persistent class names

### ISSUE THREAD

**Issue by agiz** [cssinjs/jss#429]
Whenever I change some property (i.e. font size), name of the class changes as well.

I would like to know assigned class names ahead of time or at least to not change when adjusting property's value.

My use case is that I have a html element that I want to render only once. Then, after each additional hot reload (triggered by property change), just update modified values.

My current approach is:
- render html and attach style sheet on initial run
- change some property
- remove attached style sheet (to avoid duplicates on failed hot reload)
- attach new style sheet (but this one has different class names)
- do the manual mapping and replace old class names with new ones (a bit of a hassle)

Is there any better way?

**Comment by kof** [comment]
> Whenever I change some property (i.e. font size), name of the class changes as well.

How do you change it, can you give me an example?

**Comment by kof** [comment]
I guess you are changing your original style object and then rerender the entire sheet manually.

**Comment by kof** [comment]
What are you trying to achieve?

**Comment by agiz** [comment]
@kof, In essence I am trying to have changed style object applied over already rendered html. Why? Well because hot reloading might not work all the time but I force it to apply hot patch anyway. Now this causes duplicate entries so to avoid, I only render html once and then remove and (want to) re-attach new style object over existing html. I hope you understand what I am trying to do.

**Comment by kof** [comment]
Are u using react-jss?

So basically you are trying to fix hot reloading?

**Comment by agiz** [comment]
No, I am just using jss. I cannot fix hot reloading (long story - content script of an extension), however I can enforce patching anyway (but this causes side effects).
```
...
const {classes} = jss.createStyleSheet(styles).attach()

if (!document.body.getElementById('button')
  document.body.innerHTML = <button id="button" class="${classes.button}">Button</button>
```

As I change `styles`'s attributes I want to re-apply new style on already rendered html however ${classes.button} gets new class name. Now I know a few ways to "hack/fix" this but I wonder if there is a better solution.

**Comment by kof** [comment]
Why is a new class name a problem?

**Comment by agiz** [comment]
By using above `if` statement the `button` element gets rendered (and has correctly assigned class name) only on initial run. Each subsequent hot-reload changes `classes.button` variable and thus `button` no longer has the correct class name bound to it's class name. I am not here to report an issue with jss :) I just want to know the correct code pattern for my case.

**Comment by kof** [comment]
So basically you are attaching a new style sheet with new classes, but still using the old one in the markup and don't want to rerender the markup? Still trying to understand what happens.

**Comment by agiz** [comment]
Yes, exactly. What are my options here?

**Comment by kof** [comment]
A logical consequence here is to update the element with a new class name. In react its very easy an  is done automatically. In your case I don't know. As right now we are talking about development mode you could rerender the entire view if updating specific nodes is not an option.

**Comment by agiz** [comment]
At the moment I remember previous class name object and map it over new class name object. The way I see it is that this step wouldn't be necessary if class names were persistent. Is there any way to make them persistent?

**Comment by kof** [comment]
for testing purposes you could pass your own generateClassName function and generate names differently, but def. not for production.

**Comment by kof** [comment]
see http://cssinjs.org/js-api?v=v6.3.0#setup-jss-instance
