### ISSUE TITLE
Extended "Generate your own class names" example creates bogus style sheet.

### ISSUE THREAD

**Issue by agiz** [cssinjs/jss#430]
I've slightly extended "[Generate your own class names](http://cssinjs.org/js-api/?v=v6.3.0#generate-your-own-class-names)". You can see my changes [here](http://codepen.io/anon/pen/oZvWWp?editors=0010).

Issue is, that styles object is not properly transformed to style sheet. This is the output of `styleSheet.toString()`:

```
<style type="text/css">
.my-fancy-id {
  fontSize: 24;
  &:hover: [object Object];
}
.my-fancy-id {
  extend: button;
  &:hover: [object Object];
}
@media (min-width: 1024px) {
  .my-fancy-id {
    width: 300;
  }
}
</style>
```

If there is an error on my part I sincerely apologize.

**Comment by kof** [comment]
are u using the preset? you are lucking jss-nested plugin.

**Comment by agiz** [comment]
Got it! Thanks.
