### ISSUE TITLE
New old id generation algorithm - back to the future

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#432]
Me and @iamstarkov just had a discussion about #356 and decided to reimplement the id generation algorithm. 

Right know we JSON.stringify the rules and generate hashes with murmurhash in order to have predictable unique class names in order to support SSR.

We found a way to avoid that overhead and still support SSR.

1. We revert the algorithm to the very first version where simple counters have been used to ensure the uniqueness.
2. In order to support SSR, JSS will generate a "rulesmap", which will be used then at runtime on the client  in order to obtain the original ids, generated on the server.

This will not only allow us to implement unique class names for dynamic rules in #356 but will also increase an overall performance by factor 3.

cc @nathanmarks @cvle @iamstarkov @typical000 @sapegin @oliviertassinari

**Comment by kof** [comment]
Implementation details:

1. Id's are simple counters of format:  `{jssId}-{ruleId}`. We need jssId to support multiple jss instances. Both `jssId` and `ruleId` are simple counters.
2. As we need to transfer the rules map to the client, we need some place where it can be placed inside of a document.  I see 2 options for this:
  1. We can to tell user to put rulesmap into data-rulesmap attribute of the style tag, define an id on this style tag, tell jss that id.
  2. We can let jss generate the style tag with the id and data-rulesmap attribute and return it to the user
3. When jss kicks in on the client, it needs to parse the json string from the style tag attribute, use the ids when creating Rule instances, so that they match exactly the SSR CSS.

**Comment by oliviertassinari** [comment]
That sounds good to me. Does it mean we would no longer have to removed the SSR generated CSS on the client?
Also, that's new generation algorithm is allowing really short class names. That's good for the payload.

**Comment by kof** [comment]
> Does it mean we would no longer have to removed the SSR generated CSS 

Yes, because we have dynamic values, its not not immutable. This should be out of concern though, because its blazingly fast.

**Comment by kof** [comment]
corrected my answer

**Comment by nathanmarks** [comment]
This is an awesome find/idea. When is it being implemented?

Funny how solutions can stare you right in the face sometimes.

**Comment by kof** [comment]
Its [wip] (https://github.com/cssinjs/jss/pull/433), I have been struggling with dynamic rules id generation and @iamstarkov came up with the idea to provide the map from the server and use non-deterministic ids.

**Comment by kof** [comment]
Right now I have still the problem to identify the sheets, I am not sure we can rely on the order we have on the backend and client.

**Comment by iamstarkov** [comment]
@kof what do you mean by "order we have on the backend and client"?

**Comment by iamstarkov** [comment]
we discussed that, and you may have control on that

**Comment by iamstarkov** [comment]
give me a sec

**Comment by iamstarkov** [comment]
my proposed change to jss's ssr https://github.com/cssinjs/examples/blob/gh-pages/react-ssr/src/server.js
```diff
import React from 'react'
import {renderToString} from 'react-dom/server'
import {SheetsRegistryProvider, SheetsRegistry} from 'react-jss'
import Button from './Button'

export default function render() {
  const sheets = new SheetsRegistry()

  const app = renderToString(
    <SheetsRegistryProvider registry={sheets}>
      <Button />
    </SheetsRegistryProvider>
  )

  return '' +
`<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title>Server-side rendering with rehydration</title>
    <link rel="stylesheet" href="../../example.css" />
-    <style type="text/css" id="server-side-styles">
-      ${sheets.toString()}
-    </style>
+    ${sheets.getStyleTags()}
+    <!-- or -->
+    ${sheets.getStyleTags().forEach(elem => elem.setAttribute('arbitrary', 'attr')) }
  </head>
  <body>
    <a href="https://github.com/cssinjs/examples/tree/gh-pages/react-ssr" title="View on Github" class="github-fork-ribbon" target="_blank">View on Github</a>
    <div id="app">${app}</div>
    <script src="./app.js"></script>
  </body>
</html>`
}
```

**Comment by kof** [comment]
this isn't much of a problem, the prob is that in pure jss without react-jss we have no idea if a sheet is going to be rendered in the  browser in the same order as on the server, rehydration data has to rely on that. Even with react I am not sure this is guaranteed.

**Comment by kof** [comment]
Does react guarantees that when rendering on the client first time, it renders exactly the same thing like the SSR did?

**Comment by iamstarkov** [comment]
> Does react guarantees that when rendering on the client first time, it renders exactly the same thing like the SSR did?

why wouldnt it?

**Comment by kof** [comment]
dunno, its a question)

**Comment by kof** [comment]
but actually any framework would need to guarantee that otherwise it would need a full rerender on startup.

**Comment by kof** [comment]
I mean the whole point of rehydration is to start the js powered application  on top of server rendered one without rerender the whole thing, if it rerenders, we have no problems anyways.

**Comment by iamstarkov** [comment]
and why do you care about the order?

if styletags would be generated 1 to 1 with components, you need only `data-jss-map` attribute on styletags wo/ need to care about the order, right?

**Comment by kof** [comment]
if components are the same sheets will be too, but if its possible that the client for e.g. skips rendering one component in the middle, without full rerender, then  it is fucked up.

**Comment by iamstarkov** [comment]
i dont understand you

**Comment by kof** [comment]
If server renders this:

```
SheetA
SheetB
SheetC
CompA
CompB
CompC
```

But the client renders this:

```
SheetA
SheetC
CompA
CompC
```

Without a full rerender of the App.  Rehydration will use Data from the server and will use the ids map for SheetC from SheetB, but I guess this shouldn't be possible anyways.

**Comment by iamstarkov** [comment]
there are several cases of this behavior, e.g. when you want
a) decrease ssr cpu load
b) cache components on ssr, but you dont want to cache privacy related components, so on ssr you render layout skeleton to deliver best perceived performance and later on client side we render full-blown app

**Comment by kof** [comment]
In this case, react would rerender the whole thing, right?

**Comment by iamstarkov** [comment]
let me check with colleagues

**Comment by iamstarkov** [comment]
but i still cant get why does jss need to care about the order, when you can link stylesheets to components with dom node attributes.

am i right that `rulesmap`s are scoped to stylesheet, right?

**Comment by kof** [comment]
```
      sheets.add(jss.createStyleSheet({
        a: {color: 'red'},
        b: {color: 'green'}
      }).attach())
      sheets.add(jss.createStyleSheet({
        c: {color: 'blue'}
      }).attach())
      expect(sheets.toMap()).to.eql([{a: 'a-id', b: 'b-id'}, {c: 'c-id'}])
```

You can see how the map looks like, its an array, where each object is a  map of rule name to a class name and represents a sheet. The order needs to be the same.

**Comment by kof** [comment]
Another topic: we are [currently doing ](https://github.com/cssinjs/jss/blob/master/src/plugins/RegularRule.js#L39)JSON.stringify/parse of the styles object in order to clone it and not mutate the original object, but it costs some performance. I would love to avoid this, the question is how to make it obvious that we mutate without introducing unexpected behavior to the user.

**Comment by kof** [comment]
Also we currently rely on rule.originalStyle in some places.

**Comment by kof** [comment]
We can advise users to use a function to generate the styles object or to deepClone the styles object when passing it to JSS, because it will mutate that object. Basically users should care about it only if they create multiple sheets using the same styles object.

**Comment by kof** [comment]
Also we could accept a function instead of styles object which returns the styles object in order to make it even a bit simpler

**Comment by iamstarkov** [comment]
```
      sheets.add(jss.createStyleSheet({
        a: {color: 'red'},
        b: {color: 'green'}
      }).attach())
      sheets.add(jss.createStyleSheet({
        c: {color: 'blue'}
      }).attach())
      expect(sheets.toMap()).to.eql([{a: 'a-id', b: 'b-id'}, {c: 'c-id'}])
```

we should find a way to identify sheets by some kind of identifier, order is fragile

**Comment by kof** [comment]
> we should find a way to identify sheets by some kind of identifier, order is fragile

the only way is to create hashes … are u sure order is fragile?

**Comment by iamstarkov** [comment]
look

      sheets.add(jss.createStyleSheet({
        a: { color: 'red' },
        b: { color: () => 'green' }
      }).attach())
      sheets.add(jss.createStyleSheet({
        a: { color: () => 'blue' }
      }).attach())
      expect(sheets.toMap()).to.eql([{a: 'a-id', b: 'b-id'}, {a: 'a-id'}])

fragile is order in case if you cant guarantee original rule names

**Comment by iamstarkov** [comment]
sorry

**Comment by kof** [comment]
> order is fragile in case if you cant guarantee original rule names

rule names are the same, its about the sheets order, I am  not sure its a prob.

**Comment by cvle** [comment]
React Stack definitely has a deterministic order. I assume that the initial render on React Fiber will be deterministic (need verification).

Another note is that Fiber apparently doesn't come with SSR initially and will probably rely on community solutions. I can't say how those community solutions will be. My guess is that it will match the render order on the client (need verification).

> Initial version of Fiber won't ship with an SSR renderer but should be easier to build on top 
> https://twitter.com/dan_abramov/status/792324589594566656

**Comment by kof** [comment]
Can we go with this logic: if SSR renders only critical markup/css - don't call `jss.rehydrate()`, if client renders identical view when it kicks in - rehydarate?

**Comment by cvle** [comment]
React gives a warning when markup form server differs from the client, can't we assume they are always the same? Who uses server rendering to render a critical markup that differs from the clients render?

**Comment by cvle** [comment]
And another thought I have is: Do we need to transmit a map of classNames to the client? Can't the server and client calculate it independently using counters and still have the same result?

**Comment by kof** [comment]
I am wondering right now as well, counters are invoked in exact same, there is no randomness. If ssr logic is the same, there should be no difference, if it is not, client would render a different view and though update the entire document where needed, which essentially mens there is no need in rehydration in such a case.

**Comment by kof** [comment]
Released without rehydration. Lets see if it broke anything.

**Comment by kof** [comment]
Increased only minor version because I expect no breaking change.

**Comment by rasentry** [comment]
@kof This changes broke my SSR.

 (client) ader-wrapper fade-0-256 fade-0-191 in-0-
 (server) ader-wrapper fade-0-3 fade-0-0 in-0-1" d

**Comment by kof** [comment]
@rasentry do you know how?

**Comment by rasentry** [comment]
@kof I just upgraded to v7 and stil do not see obvious reason why this happen. Trying to understand...

**Comment by kof** [comment]
Let me know if I can help to debug this. Ideally I need some simple working that reproduces the issue.

**Comment by jcheroske** [comment]
I'm seeing this in next.js as well:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This 
generally means that you are using server rendering and the markup generated on the server was
not what the client was expecting. React injected new markup to compensate which works but you
have lost many of the benefits of server rendering. Instead, figure out why the markup being 
generated is different on the client or server:
 (client) <div class="paper-0-0" style="color:rgba
 (server) <div class="paper-0-2" style="color:rgba
```
I'm pretty sure I understand what's happening, but I don't understand why next.js would act this way. 

When the next.js server first boots, the jss counter is at 0. If I hit my page everything works, and there is no React warning. If I refresh the browser, for some reason next.js reruns my component file, and re-injects the sheet, which increments the server-side jss counter. But the browser got refreshed, so its counter is back to zero.

I think you guys are right in thinking the the load order of React components is deterministic. What might not be though is the counter's starting point on the server. If you have five sheets, the counter will always increment five times in the same sheet order. But, where it always runs 0, 1, 2, 3, 4 on the client, it might run 13,14,15,16,17 on the server.

And, just to make sure I'm not missing something, is there a special format for the server-generated `<style>` tag? Meta info of some kind? Reading this thread, I didn't think so.

**Comment by kof** [comment]
So SSR rerenders, but counter continues to increase.

**Comment by kof** [comment]
I think we don't reset the counter between the requests.

**Comment by kof** [comment]
> And, just to make sure I'm not missing something, is there a special format for the server-generated <style> tag? Meta info of some kind? Reading this thread, I didn't think so.

no, just what it is in the docs.

Please open a separate issue for this story.

**Comment by jcheroske** [comment]
Is the counter in SheetRegistry?

**Comment by jcheroske** [comment]
@kof Just to be clear, you want a new bug report on the next.js counter issue?

**Comment by kof** [comment]
I think we can handle it in #457 as it seems to be specific to next.js

**Comment by kof** [comment]
lets create an example over there and see what we need to fix
