### ISSUE TITLE
[question] Dynamic themeing in JSS

### ISSUE THREAD

**Issue by mike-robertson** [cssinjs/jss#452]
I've been trying to add some dynamic themeing for a component library I'm building which uses JSS. I took a pretty naive approach (basically just using dynamic styles) which I think wouldn't be super performant since the theme would be shared across all components (unlike the use case for dynamic styles). Is there a better way of doing that using react-jss? I know that the dynamic naive approach won't work until the fix for issue #441 is complete, but is there an existing solution which integrates well with jss/react-jss at the moment? Here's what I was doing:

```js
import React, { Component } from 'react';
import injectSheet from 'react-jss';
import jss from 'jss';

const injectTheme = theme =>
  styles =>
    WrappedComponent => injectSheet(styles.update ? styles : jss.createStyleSheet(styles))(class extends Component {
      constructor(props) {
        super(props);
        theme.subscribe(palette => {
          this.props.sheet.update(palette);
        });
      }

      render() {
        return <WrappedComponent {...this.props} />;
      }
    });

export default injectTheme;
```

and a component would just use the result of calling `injectTheme` which I export instead of `injectSheet`. 

```js
import { injectSheet } from '../themes';

const styles = {
  container: {
    border: (palette: PaletteType): string => palette.border,
    borderCollapse: 'collapse',
    color: (palette: PaletteType): string => palette.textColorPrimary,
  },
};

// ... component defintion

export default injectSheet(styles)(Component);
```

This is probably the wrong approach, right? Is it worth just waiting for the fix for 441 and trying this, or should I be looking at another theme solution which isn't so naive? I've seen this http://cssinjs.org/jss-theme-reactor?v=v0.10.0, but it doesn't seem incredibly apparent to me how I would integrate that with react-jss (possibly it's not even ready for that since the docs aren't complete).

Sorry if this is the wrong place to ask this question!

**Comment by iamstarkov** [comment]
Why do you think it's a wrong approach?

I implemented it in similar way https://github.com/nordnet/nordnet-ui-kit/blob/feat/pure-jss/src/components/badge/badge.jsx

**Comment by mike-robertson** [comment]
I could be misunderstanding the dynamic themeing, but I was under the impression it would create a different sheet for each component instance for the dynamic styles. But a theme should be shared across all instances of that component (at least it seems logical), so you would have lots of extra work maintaining these sheets at the component instance level. Once again though, I could be misunderstanding how the dynamic styles are implemented.

**Comment by kof** [comment]
Styles for 1 component are split into 2: dynamic (with function values) and static sheets. Static once are reused across all elements of that component, dynamic are specific to each component.

**Comment by mike-robertson** [comment]
So that would mean if we 'abused' dynamic styles with themes, we would be creating way more stylesheets than we would really need since those 'dynamic' styles would actually be shared across all component instances (assuming only 1 theme is allowed).

**Comment by kof** [comment]
Its not really abusing, because function values is a nice fit for dynamic values, though if themes are known in advance and are limited to a certain amount, one could optimize the resulting CSS size  by composing classes instead of using function values. Depending on what you do, this might be a premature optimization.

**Comment by kof** [comment]
Not sure if this issue can be closed…
