### ISSUE TITLE
npm run bench fails

### ISSUE THREAD

**Issue by gugurete** [cssinjs/jss#453]
cannot run the benchmarks. Getting the following error:

> [robert@localhost jss]$ npm run bench
> 
> > jss@6.5.0 bench /home/robert/dev/jss
> > cross-env BENCHMARK=true karma start --single-run
> 
> 03 04 2017 08:52:41.418:ERROR [preprocess]: Can not load "webpack"!
>   WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> 

Steps to reproduce:

```
git clone https://github.com/cssinjs/jss.git
npm install
npm run bench
```

**Comment by kof** [comment]
fixed, thanks
