### ISSUE TITLE
Create a general style sheet for composing?

### ISSUE THREAD

**Issue by pjuke** [cssinjs/jss#454]
I'm using material-ui with it's [jss-theme-reactor](https://github.com/nathanmarks/jss-theme-reactor) and can't wrap my head around how to create one "general" style sheet that can be composed with underlying components.

Is it possible to create one "general" sheet with helper/utility classes, that can be included further down the DOM tree in other components?

Or, are you supposed to have an external stylesheet with your utility-classes and use them with the jss-compose plugin? I thought it would be cool if JSS could generate that style sheet instead.

**Comment by kof** [comment]
You have multiple ways to do so:

- Create a file with your utilities and export objects with styles, then use them as u see fit during component styles declarations

  ```js
  // utils.js
  export const ellipsis = {
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    display: 'block'
  }


  // Component.js

  const styles  = {
    container: {
      extend: utils.ellipsis
    }
  }

  ```

- Render  a sheet directly with jss and compose the classes as you see fit.

  ```js
  // utils.js
  export default jss.createStyleSheet({
    ellipsis: {
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      display: 'block'
    }
  }).attach().classes


  // Component.js

  const styles  = {
    container: {
      composes: utils.ellipsis
    }
  }
  ```

The first one has the advantage of not having a separate style tag for the utils which remains always attached or you need to manage the attach/detach calls. The second has the advantage of smaller amount of CSS generated at the end, only interesting for SSR.

**Comment by pjuke** [comment]
Thank you @kof, the 2nd approach seems more what I want to do since we're running an isomorphic application.

**Comment by kof** [comment]
Don't forget to add your company/project to this list http://cssinjs.org/who-is-using

**Comment by iamstarkov** [comment]
nice
