### ISSUE TITLE
[jss-compose] Cannot read property 'composes' of undefined

### ISSUE THREAD

**Issue by zerkalica** [cssinjs/jss#460]
After update, in jss-compose 3.0.0 i got a bug.

TypeError: Cannot read property 'composes' of undefined

in [jss-compose](https://github.com/cssinjs/jss-compose/blob/master/src/index.js#L56)

```js
 function onProcessRule(rule) {
    const {style} = rule // bug here, style is undefined
    if (!style.composes) return
```

rule is ConditionalRule without style prop.

Check for media query in stylesheet.

```js
 const styles = {
  '@media screen and (max-width: 768px)': {
     some: {
     }
   }
}

**Comment by typical000** [comment]
Encountered the same error on my project when updated dependencies.
The situation is the same - there are some empty selectors like:
`````````````````````
export default {
  link: {
  }
}
`````````````````````
Created PR: https://github.com/cssinjs/jss-compose/pull/3

**Comment by kof** [comment]
fixed and released

**Comment by roosta** [comment]
I hit this issue using react-jss, and after looking around a bit I saw that jss-preset-default pulls in version 3.0.0 of jss-compose which does not include the fix.

**Comment by kof** [comment]
jss-preset-default will pull the latest version if you reinstall

**Comment by kof** [comment]
^3.0.0 includes the 3.0.1

**Comment by roosta** [comment]
ok thanks :)
