### ISSUE TITLE
Memory witch-hunt

### ISSUE THREAD

**Issue by rosskevin** [cssinjs/jss#461]
I've got a problem with my app that I can't quite seem to catch, but ultimately under stress, my `selenium/standalone-chrome` dies after 46 sign in/out cycles.

Doing some heap analysis, I'm curious as to why I see my `attached` stylesheets also sticking around in memory.  It seems to top-down originate from the `SheetsRegistry`, bottom up it is `style` and `originalStyle` from `RulesContainer`.  I verified each as attached clicking on it and using `$0.attached` in the console.

![landing_-_dummy_com_and_fully_re-usable_components_ _issue__59_ _cssinjs_jss](https://cloud.githubusercontent.com/assets/136564/24882298/33f257ac-1e06-11e7-998d-8376ea440c25.png)

While I don't think this really has much if any impact on my issue, I was just curious, is there a reason these `attached` sheets are kept in memory?

**Comment by kof** [comment]
Why do you assume a created sheet should be removed from the memory?

**Comment by kof** [comment]
Did you think its like a write operation? Sheet created -> attached -> flushed… ?

**Comment by kof** [comment]
SheetsRegistry on the client exists in order to maintain the defined index option.

**Comment by kof** [comment]
Also the sheet would stick in memory just because you actually have a reference to it I assume.

If you want it really removed from the registry, it has a remove method.
