### ISSUE TITLE
Function values

### ISSUE THREAD

**Issue by kserjey** [cssinjs/jss#467]
Yep, it's come back. I found it when I worked with keyframes.
React [example](https://www.webpackbin.com/bins/-Khb9n0leQARkzqofLnl).

**Comment by kof** [comment]
thanks

**Comment by kof** [comment]
btw you are not using thee latest jss version

**Comment by kserjey** [comment]
Why? react-jss latest version is 6.0.0, which have jss 7.0.0 ![image](https://cloud.githubusercontent.com/assets/19753880/25004833/f7148d68-205e-11e7-8485-8860fcde4071.png)

**Comment by kof** [comment]
ah right its react-jss

**Comment by kof** [comment]
fixed in jss@7.0.2
