### ISSUE TITLE
Write an article about the history, positioning and the future of JSS

### ISSUE THREAD

**Issue by iamstarkov** [cssinjs/jss#470]
pls write an "behind the scene" aricle:

0) why did you decide to create yet another one css-in-js implementation
1) where and how did you start?
2) how did the process look like?
3) what were the challenges, decisions and reasons behind it in regards roadmap/releases?
4) what is the current state of the art?
5) whats your view about competitors?
6) whats your view about overall css-in-js scene?
7) whats up next?

**Comment by kof** [comment]
Did you create a new issue by accident?

I think some for the points like competitors landscape is a separate topic. We need to focus in one article on one topic. In #468 is the idea to explain how JSS works under the hood and why.

**Comment by iamstarkov** [comment]
i didnt create it by accident, this article is more like a wish for insights

**Comment by kof** [comment]
Ok so this one is more like a story about jss and its positioning and future roadmap vs the #468 is about how it works.

**Comment by iamstarkov** [comment]
@kof correct

**Comment by kof** [comment]
This will be mostly covered in the interview which will be published on friday.
