### ISSUE TITLE
function values doenst work with keyframes

### ISSUE THREAD

**Issue by xiaofan2406** [cssinjs/jss#471]
```
'@keyframes move': {
    '0%': {
      transform: 'translateX(0)'
    },
    '100%': {
      transform: ({size}) => `translateX(${size}px)`
    }
  }
```
Doesn't seem to work.

In addition, when this didn't work in my React Component, it messed up other `classes` injection as well.

**Comment by kof** [comment]
Lets see.

**Comment by kof** [comment]
Btw. I am not sure one should do this anyways. keyframes should be actually static.

**Comment by kof** [comment]
You can basically do the same using  transform directly, without keyframes.

**Comment by xiaofan2406** [comment]
I simplified the code when posting the issue.

The keyframe actually does not change, because my props wont change. But it is important for it to be initially calculated from props

**Comment by kof** [comment]
I see!

**Comment by octalmage** [comment]
I'm running into this as well. I have a BarChart in a table, and I'd love for it to animate from 0 width to it's actual width (based on the value) on load. After that the transition takes over. 

Thanks for the killer library.

**Comment by kof** [comment]
Will be fixed soon.

**Comment by kof** [comment]
Fixed and released in 7.1.2

**Comment by octalmage** [comment]
Woohoo thank you!

**Comment by xiaofan2406** [comment]
Thanks for fixing the bug 👍 

Just curious, since `react-jss` has updated the version, I am wondering have you thought about using lerna to manage these highly related packages?

**Comment by kof** [comment]
yes.

**Comment by kof** [comment]
Please use separate issues for separate topics, also we have a gitter chat.

**Comment by kof** [comment]
If you are interested in helping, let me  know and I will share what I think.

**Comment by kof** [comment]
will remove unrelated stuff from that issue
