### ISSUE TITLE
Equal style object properties should generate the same class declarations

### ISSUE THREAD

**Issue by raynor85** [cssinjs/jss#482]
At the moment a code like this:
`const styles = {
  foo: {
    color: 'red'
  }
}`
Generates something like this:
`.foo-0-10 {
  color: red;
}`

The mapping between the property of the object 'foo' should always generate the class 'foo-0-10' throughout the whole application, to avoid repetitions of generated classnames, independently of the shape of the objects which generated them (if it has only the prop 'foo' or if it has another property, etc). At the moment if you have different components that shares the same block of css could generate different blocks (one example is when you flip the ordering of one property with another within the styles object, but there are many others).

**Comment by kof** [comment]
There are 2 problems with that:

1. We would need to do hashing, which would slow down the class name generation a bit
1. You would get some specificity issues based on source order (please let me know if I need to expand on this)

**Comment by kof** [comment]
As I get no answer, I am closing it for now, if you want to continue this discussion, feel free to comment.
