### ISSUE TITLE
Wrong flow type args?

### ISSUE THREAD

**Issue by ffxsam** [cssinjs/jss#484]
Regarding this line:
https://github.com/cssinjs/jss/blob/master/src/Jss.js#L47

Should it be this instead?:

```js
  createStyleSheet(styles: Object, options?: StyleSheetOptions): StyleSheet {
```

**Comment by ffxsam** [comment]
This line is also causing a problem:
https://github.com/cssinjs/jss/blob/master/src/types.js#L88

It forces me to have to unnecessarily pass in `jss`:

```js
export default jss.createStyleSheet({
  blueHeader: {
    // not real - destroy this. DESTROY.
    color: 'blue',
    fontSize: 24,
    fontWeight: 'bold',
  },
}, { jss });
```

**Comment by kof** [comment]
Oh yeah, options should be optional

**Comment by ffxsam** [comment]
This is also wrong:
https://github.com/cssinjs/jss/blob/master/src/types.js#L88

You're using an actual class as a type. But I'm not sure why that's needed anyway as it's not part of the options. Maybe you meant to do `jss?: Class<Jss>`.

I'll see if I can find some time to do a PR soonish to fix these issues.

**Comment by kof** [comment]
options .jss is an instance of Jss class, am I using flow wrong? Still learning it.

**Comment by ffxsam** [comment]
I'm pretty new to it too. I checked with someone who knows Flow far better than I do, and that is indeed incorrect.

About to submit a PR..

**Comment by kof** [comment]
Thanks!

**Comment by ffxsam** [comment]
https://github.com/cssinjs/jss/pull/485
