### ISSUE TITLE
Unified Theming solution

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#488]
@iamstarkov has been working on a unified theming solution which will work for react-jss, styled-jss, styled-components and all others.

Current location of that repo https://github.com/iamstarkov/theming

This issue is for tracking a progress:

- [x] Released the `theming` package
- [x] Integrate in react-jss
- [ ] Integrate in styled-jss (https://github.com/cssinjs/styled-jss/issues/20)
- [ ] Integrate in styled-components

**Comment by iamstarkov** [comment]
I need feedback, pls take a look https://github.com/iamstarkov/theming/pull/2

**Comment by kof** [comment]
I think we can close this one, nothing we can do here.
