### ISSUE TITLE
getDynamicStyles() vs sheet.update()

### ISSUE THREAD

**Issue by igl** [cssinjs/jss#492]
Originally i thought this would be in styled-jss but after some digging i found that the api for this is coming from JSS.

## Problem
`stylesheet.update` method does not invoke nested function values that are extracted by `getDynamicStyles`.
This is similar to #471 which is addressing the issue with keyframes.

## Example
```jss
import styled from 'styled-jss'

const Button = styled('button')({
    color: 'black'
})

const BoldButton = styled(Button)({
    '&:hover': {
        fontWeight: 'bold',
        color: () => 'blanchedalmond'
    }
})

```
Generated css:
![screen shot 2017-05-16 at 15 10 16](https://cloud.githubusercontent.com/assets/293519/26107571/16fb59b8-3a4a-11e7-9d33-272359331ec9.png)

## Possible Solution

These should behave the same:

Recursive: https://github.com/cssinjs/jss/blob/master/src/utils/getDynamicStyles.js#L18
Flat: https://github.com/cssinjs/jss/blob/master/src/utils/updateRule.js#L6

I vote for having both recursive. But i am not experienced enough with the code base if this causes an issue elsewhere.

**Comment by kof** [comment]
You are most probably using an old jss version. Check the exact version you got installed in node_modules.

**Comment by igl** [comment]
jss@^7.1.2

I updated the issue with links to the source files causing the problems. It's in master

**Comment by igl** [comment]
ok it's not within jss... I added a test case and it succeeded.

I have to dig deeper within styled-jss or the jss setup within my project.
Will try to isolate the case. (unfortunately the test setup of styled-jss does not look at the generated css yet)

**Comment by kof** [comment]
Yes jss-nested has a test for this, https://github.com/cssinjs/jss-nested/blob/master/src/index.test.js#L593
