### ISSUE TITLE
Flow - jss.createStyleSheet(styles) throws an error

### ISSUE THREAD

**Issue by Ricardo-Marques** [cssinjs/jss#498]
`Undefined (too few arguments, expected default/rest parameters). This type is incompatible with StyleSheetOptions`

Editing https://github.com/cssinjs/jss/blob/master/src/Jss.js#L47 to
`createStyleSheet(styles: Object, options?: StyleSheetOptions): StyleSheet {`
fixes the issue.

**Comment by bigslycat** [comment]
Duplicates #495
