### ISSUE TITLE
Critical CSS of the docs

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#504]
@sapegin asked why this looks like there are lots of repetitions when you look at the generated critical css. Also for some reason `isolate: false` is there too.

**Comment by kof** [comment]
@typical000 maybe you have an idea?

**Comment by typical000** [comment]
Hm... Seems like how many times component was rendered - so many times same styles are repeated (for e.g. there are many *MenuItem* components and resulting classes like `.menuItem-0-33`)

**Comment by kof** [comment]
Shouldn't be the case, strange.

**Comment by kof** [comment]
Assigning this one to you @typical000 please take a look when you have time.

**Comment by kof** [comment]
fixed in 7.1.5
