### ISSUE TITLE
New lines broken on docs site examples 

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#510]
Now all examples are in one line)

**Comment by kof** [comment]
cc @typical000

**Comment by typical000** [comment]
Hm... seems like jss-isolate problem 0_o I'll take a look...

**Comment by kof** [comment]
oh, it might be the update of jss-isolate I did recently.

**Comment by typical000** [comment]
Yes, as expected - one `isolate: false` resolved all problems. Pushed to master.
So this issue can be closed.

**Comment by kof** [comment]
thanks!
