### ISSUE TITLE
Function values don't remove previous value when returning "null" or "undefined"

### ISSUE THREAD

**Issue by jaminthorns** [cssinjs/jss#514]
I think this might be due to the nature of how JSS converts JavaScript values to CSS, but I've noticed that if I have a function-valued rule, and that function returns a valid CSS value, then later returns `null` or `undefined`, the CSS value never gets removed from the stylesheet.

Intuitively, this should remove the CSS value, as invalid JavaScript values should not translate over to CSS values. Of course, I can also see why this would happen, since I'm guessing the JS -> CSS value translation code (which I haven't actually dug into), simply short circuits its calculation of the value when it sees that it's invalid.

If this isn't considered an issue, then feel free to close it. Here's an example of the issue: [Link](https://www.webpackbin.com/bins/-KmDhsKtqLZ3BCqqK0ae)

**Comment by kof** [comment]
I don't think its a bug but it might be a useful enhancement. Need to think a bit about its implications.

**Comment by kof** [comment]
One negative aspect of this might be the following: if the function that returns the value is not trivial or calls some other function and its result is unexpectedly falsy, you might end up with a removed property in an unexpected way and then wonder whats going on.
So this API proposal has n implicitness in it.

**Comment by lttb** [comment]
maybe we can remove property only if value is `null`? because `undefined`/`false` may be really implicitness

**Comment by jaminthorns** [comment]
@kof If the very 1st call of a function used as a JSS function value returns some invalid CSS value and doesn't add the CSS rule to the stylesheet (which is the current behavior), then why would a later call with an invalid return value removing the rule be unexpected? Is there another scenario I'm not thinking of?

**Comment by kof** [comment]
>  If the very 1st call of a function used as a JSS function value returns some invalid CSS value and doesn't add the CSS rule to the stylesheet

Thats simply because we don't verify if the value was valid and successfully valid)

**Comment by kof** [comment]
check this out https://github.com/cssinjs/jss/pull/678

**Comment by kof** [comment]
released
