### ISSUE TITLE
animating unmounting with react-transition-group not working 

### ISSUE THREAD

**Issue by grigored** [cssinjs/jss#516]
I'm trying to animate unmounting a component using react-transition-group. This uses a HOC 
TransitionGroup, that adds special lifehooks (like componentWillAppear, componentWillLeave) on the inner component. 
But because the injectSheet HOC sits in between the TransitionGroup and my inner component, the lifehooks are called on injectSheet instead of my inner component.

The workaround I'm using right now is using injectSheet in the parent of my component, and then passing the stylesheet as props.

Any better suggestions?

**Comment by kof** [comment]
Not really, its a problem of  TransitionGroup component.  It won't allow any HOC's around a component, not just JSS, right?

**Comment by kof** [comment]
What you can do of course is separate your component into presentational part with jss and the one with those hooks for TransitionGroup.

```js
<TransitionGroup>
  <MyComponentWithHooksForTransitionGroup>
     <MyRenderComponentWithJss />
  </MyComponentWithHooksForTransitionGroup>
</TransitionGroup>
``

**Comment by grigored** [comment]
When I initially considered this, I thought the unmount animation is related to the presentational part, but the truth is I don't need anything from the stylesheet for the animation, so you're right, this is a neat solution. Thanks!

**Comment by iamstarkov** [comment]
@kof I don't really follow. Do you have any examples at hand?

**Comment by kof** [comment]
Here is a better example:

```js

const MyPresentationalComponent = ({classes}) => <div className={classes.box}>something</div>

const MyPresentationalComponentStyled = injectSheet(styles)(MyPresentationalComponent)

// Now you can use it with ReactTransitionGroup
class MyContainerForTransitionGroup extends Component {
  componentWillAppear() {

  }

  render() {
    return <MyPresentationalComponentStyled />
  }
}
