### ISSUE TITLE
[cssinjs] website internal links lead to github

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#521]
Some time ago we broke the links. Links we have on the website should keep user on the website. Only external links should lead to the original website.

**Comment by kof** [comment]
cc @typical000 maybe you know something about it

**Comment by typical000** [comment]
Maybe they broke down after migration to preact. Need to take a look

**Comment by kof** [comment]
Did you have any luck?

**Comment by typical000** [comment]
Sorry, I haven't enough time to take a look. 
Think that next week we can do something with this.

**Comment by typical000** [comment]
Created PR https://github.com/cssinjs/cssinjs/pull/18
Seems like now all external links works like external, internal - like internal :)

**Comment by kof** [comment]
fixed, thanks!
