### ISSUE TITLE
[jss-default-unit] 

### ISSUE THREAD

**Issue by IsenrichO** [cssinjs/jss#525]
The [JSS-Default-Unit](https://github.com/cssinjs/jss-default-unit) package does not work properly for the `line-height` property when used in conjunction with the [JSS-Expand plugin](https://github.com/cssinjs/jss-expand).

To clarify, the jss-expand [docs](https://github.com/cssinjs/jss-expand/blob/master/docs/index.md#font) show that the `line-height` property may be nested inside `font` as so:
```javascript
font: {
  style: null,
  variant: null,
  weight: null,
  stretch: null,
  size: null,
  family: null,
  lineHeight: null
}
```

My config is given below:
```javascript
import Aesthetic, { createStyler } from 'aesthetic';
import { create } from 'jss';
import Preset from 'jss-preset-default';
import JSSAdapter from 'aesthetic-adapter-jss';
import AdminTheme from './themes/admin';

const defaultUnitOptions = {
  'line-height': 'px',
};
const presetOptions = {
  defaultUnit: defaultUnitOptions,
};
const jssInstance = create(Preset(presetOptions));

const aestheticInstance = new Aesthetic(
  new JSSAdapter(jssInstance),
  { stylesPropName: 'classNames' },
);

aestheticInstance.registerTheme('admin', AdminTheme);

export { aestheticInstance as aesthetic };
export default createStyler(aestheticInstance);
```

I have found that when I specify a `lineHeight` that is **not** nested inside `font`, it works as expected. For example,
```javascript
export const styler(theme => ({
  someThing: {
    fontSize: 16,
    lineHeight: 20,  // SUCCEEDS; this is mapped to `line-height: 20px;`
  },
})(MyComponent);
```

However, when nesting `lineHeight` within `font` (as jss-expand should allow), it fails to work properly. For example,
```javascript
export const styler(theme => ({
  someThing: {
    font: {
      size: 16,
      lineHeight: 20,  // FAILS; is mapped to `line-height: 20;` (no pixel unit)
    },
  },
})(MyComponent);
```

**Comment by kof** [comment]
There is a font-* props are non-standard, handled separately https://github.com/cssinjs/jss-default-unit/blob/master/src/defaultUnits.js#L108

**Comment by kof** [comment]
Btw. lineHeight is a unit that can be numeric, consider not using defaults for this case.

**Comment by IsenrichO** [comment]
In general, I prefer to use `line-height` without units... or, at least that's what I learnt was a best practice for that particular CSS property. However, we are in the practice of always using it with pixels at my place of work. In that spirit, I was interested in setting a default unit for the property.

To clarify, are you saying that using `font-line-height: 'px'` should work?

**Comment by kof** [comment]
> However, we are in the practice of always using it with pixels at my place of work. 

Maybe you really shouldn't, line-height should stay in proportion to font-size and unitles value is the right way to do so.

> To clarify, are you saying that using font-line-height: 'px' should work?

It should

**Comment by IsenrichO** [comment]
Awesome! Thanks for the help @kof !

**Comment by IsenrichO** [comment]
Having tried this now, I am finding that using `'font-line-height': 'px'` does not work.

**Comment by damianobarbati** [comment]
Are grid-layout styles considered by default unit? 
I'm doing the following now: `gridRowGap: theme.spacing + 'px'`

**Comment by kof** [comment]
not yet https://github.com/cssinjs/jss-default-unit/blob/master/src/defaultUnits.js

**Comment by damianobarbati** [comment]
@IsenrichO how did you solve the lineHeight default as px issue?

Neither is working:
```
fontSize: 18,
fontLineHeight: 27, // not working, getting font-line-height: 21px;
```
```
fontSize: 18,
lineHeight: 27, // not working, getting line-height: 21; (the unitless instead of px)
```

**Comment by HenriBeck** [comment]
@damianobarbati you will need to explicitly set the default unit of the line-height prop to be pixels:

```js
const defaultUnitOptions = {
  'line-height': 'px',
};
const presetOptions = {
  defaultUnit: defaultUnitOptions,
};
const jssInstance = create(Preset(presetOptions));
```

**Comment by damianobarbati** [comment]
Oh no... anything less verbose and not requiring to import-then-configure presets? 😞

All I'm doing right now is just:
```
import { jss, ThemeProvider } from 'react-jss';
```

**Comment by kof** [comment]
lineHeight is a unitless property in css by design, us it that way without unit, its better

**Comment by damianobarbati** [comment]
@kof you're totally right, using the default unitless: defintely more robust.
