### ISSUE TITLE
First SSR render has no sheets attached

### ISSUE THREAD

**Issue by walshie4** [cssinjs/jss#527]
Setting up JSS on the server side and I've been noticing that the call to `sheets.toString` call returns nothing for the first request
![image](https://user-images.githubusercontent.com/945703/27720664-ab9276fa-5d0f-11e7-94b0-0b6f9e2c2afa.png)

However on subsequent requests the CSS is available on the server and so content loads perfectly with JS disabled. 
![image](https://user-images.githubusercontent.com/945703/27720700-ed4a61e8-5d0f-11e7-94a9-d878fffac302.png)

Has anyone seen anything like this?  I would guess [this line](https://github.com/cssinjs/jss/blob/b4ff4332797d0a665e2dfeb382b6121a00e7b82a/src/SheetsRegistry.js#L61) is the culprit, but I haven't looked into where sheets are `.attached`.

As an aside, the `react-ssr` example (found [here](https://github.com/cssinjs/examples/blob/c7863b7ac9c59d93286034df7e530b94a39bb42c/package.json#L51)) isn't really Server-Side rendering (or at least it's such a simple example it's hard to relate to given that it just generates static content).  If I have some time I'll toss up a PR to add one where there is a running web server involved.

**Comment by kof** [comment]
It is most probably related to your logic, which does't render stuff on on first request. If you can create a simple reproducible example, I can look into it.

**Comment by kof** [comment]
We released react-jss 7, check it out.
