### ISSUE TITLE
Move jss code to a "core" repository 

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#538]
I think it will help to communicate organizational structure of jss more clearly if we move this code to the core. I want to avoid people thinking of jss as of this repository only, but rather to show that it is the core and there is much more to discover.

I would keep docs in this repo. Maybe also benchmarks which use all other repos.

Also the question is if we should also change the package name in this case.

Also the question is should we rename this package to "core" or move the code. Its a matter of what should users star. I think this repo still remains the main one for the user.

cc @cssinjs/core wdyt?

**Comment by typical000** [comment]
Good idea, as for me!
For statistic - there are many people who is using jss-core without react-jss or styled-jss? Maybe they are against. :)

**Comment by kof** [comment]
we may want to keep jss package name …

**Comment by iamstarkov** [comment]
The reasoning is unclear for me

**Comment by kof** [comment]
Ok, so the reasoning is: when we communicate about JSS, it is not exactly clear what it is. Some think it is just this repo, where it is multiple projects like react-jss and styled-jss. Better?

**Comment by iamstarkov** [comment]
yes, i got it.

**Comment by iamstarkov** [comment]
lets see what other eco-systems do.

* eslint, eslint-plugin-*, eslint-preset-*, babel-eslint
* babel, babel-plugin-*, babel-preset-*, babel-{runtime,polyfill,register}

and back to ours one:

* jss, jss-plugin-*, jss-preset-*, styled-jss

do we need jss-core?

**Comment by kof** [comment]
eslint is the core and the only interface at the same time, jss has a core
but it is more a low level thing, react-jss is for e.g. interface for
react. So in react world jss is actually react-jss.

It happened already multiple times that people compared SC with jss core
for e.g.

**Comment by lttb** [comment]
I think that this makes sense. For me it's clear to have `jss` as an entry point to the jss-eco-system, that would aggregate jss-solutions, docs etc.

Today `jss` looks more like a cssinjs library, not like an eco-system at all, and `jss-core` would help to clarify these things.

In example with `babel`, `babel` has `babel-core`, but `babel` is like an eco-system front, that links to its components.

**Comment by kof** [comment]
I agree. Basically we have been good with jss repo before react-jss and styled-jss, but now, it makes less sense.

**Comment by oliviertassinari** [comment]
I haven't been involved in the decision of using one repository per package. What's wrong with the other way around, putting everything into this one? As far I can tell from my experience hacking around Babel to write plugins, it would have been painful the other way around.

**Comment by kof** [comment]
Its a different discussion, this issue is just about repo renaming. There are many pros and contras about monorepo vs multirepo approaches. Last time I did the research I ended up with multirepo. Right now I need to try out https://github.com/sapegin/mrm to see if it solves the problem with managing same files across repos.
