### ISSUE TITLE
visual studio code extension support

### ISSUE THREAD

**Issue by ikzjfr0** [cssinjs/jss#540]
I think jss is great, but it's absent from an extension support for visual studio code

**Comment by iamstarkov** [comment]
@ikzjfr0 what do you mean by "extension support"?

**Comment by kof** [comment]
So please add add whatever is needed to visual studio code. I would love to have it but I can't do everything.

**Comment by kof** [comment]
Of course I am more than happy to provide any help from my side and if you want it can be a repo under cssinjs org.

**Comment by ikzjfr0** [comment]
Apologize for my poor question. 
I was asking for a IntelliSense support in visual studio code. You know if css is in a separate .css file, IntelliSense works fine. However, it does not come if in .js files. See below compare:

![intellisense](https://user-images.githubusercontent.com/6456056/28505480-bac24df6-7067-11e7-84a0-cf19fb3f2c92.gif)
![no intellisense](https://user-images.githubusercontent.com/6456056/28505481-bac289d8-7067-11e7-814a-6126e7995e3e.gif)

**Comment by goleary** [comment]
This is way late, but in case anyone else comes looking:

This is not exactly intellisense for jss like you find in Material-UI, but it's better than nothing.

[Autocomplete snippets (like emmet)](https://marketplace.visualstudio.com/items?itemName=carbonid1.emmet-jss)
