### ISSUE TITLE
Fix flow error in flow 0.50.0

### ISSUE THREAD

**Issue by AfflatusX** [cssinjs/jss#541]
After upgrading my flow to 0.50, jss 8.1.0 reports following flow errors:

`node_modules/jss-theme-reactor/node_modules/jss/lib/plugins/RegularRule.js.flow:46
 46:     else if (generateClassName) this.className = generateClassName(styleStr, this, options.sheet)
                                                                                        ^^^^^^^^^^^^^ unused function argument
   10: export type generateClassName = (str: string, rule: Rule) => string
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no more than 2 arguments. See: node_modules/jss-theme-reactor/node_modules/jss/lib/types.js.flow:10
`

**Comment by iamstarkov** [comment]
how was you able to use jss-theme-reactor with jss 8.1.0?

**Comment by iamstarkov** [comment]
https://github.com/nathanmarks/jss-theme-reactor/blob/master/package.json#L35

**Comment by iamstarkov** [comment]
can you show me output of this:

```
cat node_modules/jss-theme-reactor/node_modules/jss/package.json | grep version 
```

**Comment by iamstarkov** [comment]
@AfflatusX and btw, could you help out with flow typings?

**Comment by kof** [comment]
@AfflatusX I can see from your stack trace that this is not the latest JSS core you are using.

**Comment by kof** [comment]
Please reopen if it happens with the latest one. Please verify package.json of the installed package.
