### ISSUE TITLE
[jss-vendor-prefixer] text-Align right

### ISSUE THREAD

**Issue by kazazor** [cssinjs/jss#542]
it seems that on Chrome `text-align: right` need to be set as: `text-align: -webkit-right`, but this doesn't happen...

**Comment by kof** [comment]
how did you come to the knowledge that this css value requires a prefix?

**Comment by kof** [comment]
text-align: right is a very old property/value, supported for a long time. Please bring a proof it requires a prefix.

**Comment by kazazor** [comment]
No need to close the issue, you just asked and I added :)

With just `right`:
<img width="1237" alt="screen shot 2017-07-21 at 3 25 43 pm" src="https://user-images.githubusercontent.com/1577655/28463439-0c4f8b70-6e29-11e7-8559-bc20649f0fed.png">

with `-webkit-right`:
<img width="1257" alt="screen shot 2017-07-21 at 3 25 58 pm" src="https://user-images.githubusercontent.com/1577655/28463448-183b7dcc-6e29-11e7-8747-33141f53c8a1.png">

P.S:
I would advise to create an issue template so that people opening issues will know what is expected from them to fill :)

**Comment by kazazor** [comment]
The use case is on a div inside a table cell

**Comment by kof** [comment]
I ment something reproducible and isolated.

**Comment by kof** [comment]
I closed it because it is ridiculous. It clearly works. And thanks for the tip, as soon as it becomes a problem I will add a template.

**Comment by kof** [comment]
So its not about text, but about a table cell. I don't know if this is new or something.

**Comment by iamstarkov** [comment]
> > Both WebKit and Gecko support a prefixed version of left, center, and right, that applies not only to inline content but also to block elements. This is used to implement the legacy align attributes on table elements and <center>. Do not use these on production Web sites.  
> > — MDN's documentation on text-align, https://developer.mozilla.org/en/docs/Web/CSS/text-align
> https://stackoverflow.com/a/35128141/1057730

**Comment by iamstarkov** [comment]
sorry, its obsolete value and issue is closed properly

**Comment by kazazor** [comment]
Thanks @iamstarkov !
That's a really good answer :)

>I closed it because it is ridiculous

@kof - No need to respond like that, IMHO I was trying to help.

**Comment by kof** [comment]
Yeah even the mozilla docs says not to use it.

**Comment by kof** [comment]
> @kof - No need to respond like that, IMHO I was trying to help.


I didn't mean to offend.
