### ISSUE TITLE
[jss-nested] seems like dynamic nested rules aren't updated if selector contains pseudoselector like :after

### ISSUE THREAD

**Issue by adamborowski** [cssinjs/jss#545]
Does jss-nested declaration support dynamic styling? It seems that if you put a function as an entry, sheet.update() won't take an effect and you always get initial value. For top level declarations it just works.
From some investigation I've found that nested rules miss _Renderable_
![image](https://user-images.githubusercontent.com/3614676/28560604-b6b8c690-711b-11e7-815c-68dc2975ce24.png)

There is a logic which updates dom if that value is present and maybe it is the problem...

```

 /**
     * Get or set a style property.
     */
    value: function prop(name, nextValue) {
      var $name = typeof this.style[name] === 'function' ? '$' + name : name;
      var currValue = this.style[$name];

      // Its a setter.
      if (nextValue != null) {
        // Don't do anything if the value has not changed.
        if (currValue !== nextValue) {
          nextValue = this.options.jss.plugins.onChangeValue(nextValue, name, this);
          Object.defineProperty(this.style, $name, {
            value: nextValue,
            writable: true
          });
          // Defined if StyleSheet option `link` is true.
          if (this.renderable) this.renderer.setStyle(this.renderable, name, nextValue); //<<<<<<<<<<<<<<
        }
        return this;
      }

      // Its a getter, read the value from the DOM if its not cached.
      [...]
    }
```

**Comment by adamborowski** [comment]
And interesting line from StyleRule.js
```
 // If selector setter is not implemented, rerender the sheet.
      // We need to delete renderable from the rule, because when sheet.deploy()
      // calls rule.toString, it will get the old selector.
      delete this.renderable;
      if (sheet) {
        sheet.rules.register(this);
        sheet.deploy().link();
      }
```

**Comment by adamborowski** [comment]
https://github.com/cssinjs/jss/issues/500 - seems to be fixed, using  "version": "7.0.2"
seems that upgrade will solve that problem

**Comment by adamborowski** [comment]
working example: https://www.webpackbin.com/bins/-Kpsid58UF-SopzSHZiC

**Comment by adamborowski** [comment]
I've caught the source of the problem... I've used single colon but it should be double color, then it works :)

**Comment by kof** [comment]
strange, mb needs to be documented
