### ISSUE TITLE
createGenerateClassName: production variant

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#546]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

I think that we have an opportunity to save bandwidth with SSR without losing runtime performance.
I have been [experimenting with the following logic](https://github.com/callemall/material-ui/blob/v1-beta/src/styles/createGenerateClassName.js#L30).

**Comment by iamstarkov** [comment]
from the code

```js
      // Change the base representation from 10 to 36 in order to shorten the className.
      // That helps with SSR perfs.
      // I'm expecting the runtime/bandwidth tradeoff to worth it.
```

**Comment by iamstarkov** [comment]
did you bench it? does it worth the change?

**Comment by kof** [comment]
Lets create a bench comparing  with toString(36) and without, but my gut feeling is that its fast.

**Comment by oliviertassinari** [comment]
It's quick slower than to keep the base 10 representation, still we have almost 10**7 ops/s https://esbench.com/bench/5979b76999634800a0348b7a

**Comment by kof** [comment]
![screen shot 2017-07-27 at 1 14 21 pm](https://user-images.githubusercontent.com/52824/28667867-a39db80a-72cd-11e7-8a5c-87db3c38bfde.png)

Its quite slower, need to take  a look at the higher level impact, when benching more realistic scenarios. Maybe its still not noticeable.

**Comment by oliviertassinari** [comment]
That makes me wondering, react is using the base 10 representation with his `data-reactid` on the server. I have found 123 matches on a sample page while having 323 class names generated.

**Comment by oliviertassinari** [comment]
After all, I would say that the optimization isn't needed. Replacing `.Typography-markedDisplay3Center-4150222374` with `.c342` is already awesome.

**Comment by kof** [comment]
You mean optimzation from base 10 to base 36?

**Comment by oliviertassinari** [comment]
Yes. After more thoughts. I think that base 10 / base 36 don't change much on a performance point of view, but base 10 can make debug easier so I would rather stick to base 10.

**Comment by kof** [comment]
Why is it easier for debugging?

**Comment by kof** [comment]
Just looked at numbers, base 10 doesn't make any sense, because it starts shortening after the number is so huge that you start [warn](https://github.com/callemall/material-ui/blob/v1-beta/src/styles/createGenerateClassName.js#L19) user about a memory leak before.

**Comment by kof** [comment]
Another question when reading your code, you are not using base 36 for [production](https://github.com/callemall/material-ui/blob/v1-beta/src/styles/createGenerateClassName.js#L27) but using it in the [last case](https://github.com/callemall/material-ui/blob/v1-beta/src/styles/createGenerateClassName.js#L34) which happens only if you have no meta option, which never happens in mui. So you are actually not using base 36 at all)

**Comment by oliviertassinari** [comment]
@kof What are you talking about? The base 10 is the default base used by everybody, it doesn't shorten maybe with IEEE 754 but that's another issue.

Thanks, [fixed](https://github.com/callemall/material-ui/commit/4f2cb58c9bdeb8ac210b20e6621cfab58c0aeaca).

**Comment by oliviertassinari** [comment]
I have forgotten to remove that occurrence.

**Comment by kof** [comment]
Right, tricked myself into wrong direction.

**Comment by kof** [comment]
Tested base 36 in a high level test, seems to make no difference in performance, I think we are good to go there.

**Comment by kof** [comment]
Btw. why to make it for production only, why not always use base 36?

**Comment by oliviertassinari** [comment]
@kof I have rolled back to base 10 on the Material-UI project. I make me think that it's a micro optimization and we need a real test case to measure it. Given the incertitude, I think that it's better to choose simplicity.

**Comment by kof** [comment]
I did some math, not sure how accurate and yes, its not very important optimization:

Lets take average selectors amount on a page 3000 [here](http://cssstats.com/) are some stats.

```js
var arr = []
for (var i = 0; i < 3000; i++) arr.push(i)
arr.toString().length //13889

var arr1 = []
for (var i = 0; i < 3000; i++) arr1.push((i).toString(36))
arr.toString().length //10667

(13889 - 10667) * 100 / 13889 // 23 %
```

So given 3000 selectors we win 23% in size.

Not sure if it makes any sense

**Comment by oliviertassinari** [comment]
> Lets take average selectors amount on a page 3000

I don't think that it's true anymore with code splitting. For instance, I have 300 selectors in a large landing page with code spiling.

**Comment by oliviertassinari** [comment]
The more selector a page has, the more interesting that change it.

**Comment by kof** [comment]
If 300 selectors is a more realistic number then this optimization really doesn't make any sense because it is 1089bytes vs863 bytes. Who gives a shit)

**Comment by kof** [comment]
c5253a17d43caf615730938815e699d4cc812043

**Comment by oliviertassinari** [comment]
🎉

**Comment by kof** [comment]
I am also thinking to add a `classNamePrefix` option which would allow mui and react-jss to not write custom class name generator.

very tempting…

**Comment by oliviertassinari** [comment]
@kof I have thought about it too. I don't know what's best.

**Comment by kof** [comment]
for e.g. the built-in generator also supports multiple jss version. In case for some reason user ended up with different jss versions at runtime.

**Comment by oliviertassinari** [comment]
What about using the logic directly? Is appending the meta to the className a wrong default behavior?

**Comment by kof** [comment]
yeah, meta may be very different, for e.g. in react-jss we put way more information into it. I have actually got a nice way give me a sec.

**Comment by kof** [comment]
https://github.com/cssinjs/jss/pull/551/commits/dba3c2fdd5121847e1e7e62c3a7afd0ebffcdfe4

**Comment by kof** [comment]
Ok ended up with simply adding  classNamePrefix.

**Comment by oliviertassinari** [comment]
Sounds good, the only ⚠️  would be about documenting that it's only working in dev mode.

**Comment by kof** [comment]
right.

**Comment by kof** [comment]
tbh createGenerateClassName is completely undocumented, even how to require it. I would actually need to export it from the index.

**Comment by kof** [comment]
released with v9
