### ISSUE TITLE
insertionPoint option is not used for createStyleSheet function

### ISSUE THREAD

**Issue by darkowic** [cssinjs/jss#547]
Checked the code
```
  createStyleSheet(styles: Object, options: StyleSheetFactoryOptions = {}): StyleSheet {
    let index = options.index
    if (typeof index !== 'number') {
      index = sheets.index === 0 ? 0 : sheets.index + 1
    }
    const sheet = new StyleSheet(styles, {
      ...options,
      jss: (this: Jss),
      generateClassName: options.generateClassName || this.generateClassName,
      insertionPoint: this.options.insertionPoint,
      Renderer: this.options.Renderer,
      index
    })
    this.plugins.onProcessSheet(sheet)
    return sheet
  }
```

Even though you pass your `insertionPoint` in options it will be overwritten by default setting...

Found it while using new material ui beta release.

**Comment by kof** [comment]
Do you have a use case for an override of the insertionPoint option over createStyleSheet?

**Comment by darkowic** [comment]
Material ui beta version
```
          const sheet = this.jss.createStyleSheet(styles, {
            meta: name,
            name,
            insertionPoint: CHANNEL,
            link: false,
            ...this.sheetOptions,
            ...currentStyleSheet.options,
          });
```

I want to use `insertionPoint` to place styles in correct place

**Comment by darkowic** [comment]
I'm changing it right now. Will do pull request soon

**Comment by kof** [comment]
You are changing what?

**Comment by darkowic** [comment]
@kof here in material ui beta 
https://github.com/callemall/material-ui/blob/v1-beta/src/styles/withStyles.js#L140
`createStyleSheet` is used to create style sheet for specific component


In material ui code they expect (incorrectly btw) that insertion point
```
insertionPoint: CHANNEL,
```
 will be overridden with `CHANNEL` ('material-ui'). I simply want to insert style sheets in different place in my application to be able to override styles without '!important' all the time (I use styled components).

Maybe @oliviertassinari can confirm that this is behaviour he expects

**Comment by oliviertassinari** [comment]
> insertionPoint option is supposed to be a Jss option

Oops, I have missed that point. I thought it was supported after reading the [jss-theme-reactor](https://github.com/nathanmarks/jss-theme-reactor/blob/master/src/styleSheet.js#L9) source code.

@kof What do you want to do here? I can update the styling solution of Material-UI accordingly.

**Comment by kof** [comment]
I think its because it worked that way before, but was not documented that way. So I changed it to make it more clear which options are accepted where. I think as long as there is no use case in overriding insertion point from the sheet, its better to keep it Jss option.

**Comment by oliviertassinari** [comment]
> I think as long as there is no use case in overriding insertion point from the sheet, its better to keep it Jss option.

I don't know, we had a PR in that direction lately https://github.com/callemall/material-ui/pull/7505. The limitation with the jss option is that you will most likely inject it once with `<JssProvider />` then react-jss / Material-UI will use it to inject the CSS. So the question is.
Do we want to separate the injection location of the Material-UI components with react-jss?
My intuition would say no.

If we don't, no need for that option and I will update the code/documentation of Material-UI.

**Comment by kof** [comment]
Good point. There should be no need as mui components will be always imported first and their styles will be rendered before user styles. So if mui uses react-jss we don't need it, otherwise we do.

**Comment by kof** [comment]
The question is what to do right now as mui is in the transitional state.

**Comment by oliviertassinari** [comment]
@kof let's keep thing simple. if it's ok for @darkowic and @cdharris we will make Material-UI less opinionated by using the default injection point of JSS.

**Comment by kof** [comment]
I think thats fine, considered one can pass own jss instance and define insertion point if needed.

**Comment by darkowic** [comment]
For now default `injectionPoint` is not set. I would like to have at least an option to set the `injectionPoint`. Maybe in a theme?

**Comment by oliviertassinari** [comment]
@darkowic Provide a custom jss instance with JssProvider. [We have two examples of that](https://github.com/callemall/material-ui/tree/v1-beta/examples) on the Material-UI repository. You can also find an example on the react-jss project.

**Comment by darkowic** [comment]
Ok, I configured `JssProvider` and passed jss instance to it.
```
const jss = create(preset());
jss.options.createGenerateClassName = createGenerateClassName;
jss.options.injectionPoint = 'material-ui';
```
and it is not working.

I console log the sheet from https://github.com/callemall/material-ui/blob/v1-beta/src/styles/withStyles.js#L140
![sheet](https://user-images.githubusercontent.com/11510581/28669458-9ec14ca0-72d4-11e7-9d45-13b09123c85a.png)
Jss is set correctly. But still the `injectionPoint` option set for `StyleSheet` has higher priority then `jss` instance. When I overwrite the `insertionPoint` for sheet 
```
              var sheet = _this3.jss.createStyleSheet(styles, (0, _extends3.default)({
                meta: name,
                name: name,
                insertionPoint: _themeListener.CHANNEL,
                link: false
              }, _this3.sheetOptions, currentStyleSheet.options));
              sheet.options.insertionPoint = _themeListener.CHANNEL;
```
then it works.

So, @kof looks like `createStyleSheet` is broken because it will always set `undefined` as `insertionPoint`.

**Comment by kof** [comment]
because its insertionPoint

**Comment by kof** [comment]
I think this one can be closed

**Comment by darkowic** [comment]
Ok. My fault now. Thanks!
