### ISSUE TITLE
I checked benefit page but not sure what Atomizer doesn't provide which JSS does

### ISSUE THREAD

**Issue by jitendravyas** [cssinjs/jss#556]
Has anyone used both?
https://github.com/acss-io/atomizer

**Comment by kof** [comment]
They are very different in DX.

**Comment by iamstarkov** [comment]
atomizer is a configurator to construct atomic classnames to use in regular atomized apps, but its still regular css and regular classnames. jss in react-jss in particular is css-in-js and provide better developer experience

**Comment by iamstarkov** [comment]
its not only different DX, its rather different paradigm

**Comment by kof** [comment]
don't say better, otherwise css gods will come for you)

**Comment by jitendravyas** [comment]
@iamstarkov I agree that it's different paradigm but I was talking about the benefit mentioned on JSS page. Almost all those benefits are of Atomic CSS/Atomizer too.

**Comment by kof** [comment]
thats because they both aim to solve similar issues, but they do it in very different ways. Also I need to add more and slightly refactor the benefits page. Add more jss and cssinjs very specific benefits.
