### ISSUE TITLE
Animation plugin

### ISSUE THREAD

**Issue by serapath** [cssinjs/jss#56]
Hi, I'm following the **jss** progress for quite a while now.
I'm currently looking into javascript based animation libraries and experimenting a bit with [velocityjs](https://github.com/julianshapiro/velocity).

In **Velocity** and also in **jQuery** they use a syntax that goes approximately like this:

``` js
var DOMelement = document.querySelector('div.ball');
animate({
  elements: [DOMelement], // one or more dom/jquery elements
  properties: { /* css properties state at end of animation */ },
  options: { /* delay, duration, loop, etc... of animation transition */ }
});
```

I feel it would be **GREAT** if **jss** could be easily made compatible with animation libraries.
I personally don't like the **animate API** so much, but anyway would love to see some compatibility here, so that I don't need to translate between jss and for example $.animate :-)

**Comment by kof** [comment]
This is an idea for animation plugin ... if simple transition and keyframe animations won't work for you.

**Comment by barneycarroll** [comment]
What would be the purpose of the plugin?

I've been using JSS and Velocity together. They're not incompatible at all!

**Comment by kof** [comment]
Could be a special syntax for animations implemented by a plugin which could transform the animation to transition/keyframes.

**Comment by serapath** [comment]
Hey @barneycarroll, do you have a repository that shows the usage?
I'd like to incorporate JSS into my workflow, but I don't know exactly how and I'm afraid of (beside all the other things I'm doing/learning/... to investigate time into JSS to find out it'll not gonna work :-))
Probably all unnecessary concerns.

I forked Velocity and created a pull request to add browserify/commonJS support without leaking a global to the 'window object' and would love to start using JSS, now that I plan to make heavy use of js based animation libraries anyway.

**ACTUALLY:** For "JSS", this would be a nice selling point, by showing how this is a perfect fit when it comes to javascript based animation libraries, where you specify css properties and their transitions over time anyway :-)

@kof I don't like plugins at all, they are some kind of "pest". Why would i need grunt and then write grunt plugins or gulp and write gulp plugins and jquery and jquery plugins...
...Instead of plugins i can just write standalone libraries and use them instead with whatever else i like.

Please don't make "yet another plugin ecosystem", but instead make it compatible to enable people to use it with whatever...

**Comment by kof** [comment]
Everything has its pros and cons, I want jss core stay tiny, everything else is just plugins, use them when you need them.

**Comment by serapath** [comment]
When I think of "plugin", I think of a pattern like:

   var jss = require('jss');
   var jssPluginX = require('jssPluginX'); // needs 'jss' to be present

I would rather see something like

   var jssX = require('jssX');  // where 'jssX' internally does "require('jss');"

If I need to combine certain features, I would then do either:

    var jssX = require('jssX');   // where 'jssX' internally does "require('jss');"
    var jssY = require('jssY');   // where 'jssY' internally does "require('jss');"

or

    var jssXY = require('jssXY');  // where 'jssXY' internally does "require('jssX')" and "require('jssY')"

That way, I can use any of those "standalone" or require multiple and underneath they require the same "jss" library.

Another way would be that they will work similar to **browserify**, which uses "transforms", so that you pipe data through them and you can combine as many of them as you want.

**Comment by kof** [comment]
just in case, I just added @keyframes prefixing https://github.com/jsstyles/jss-vendor-prefixer

**Comment by serapath** [comment]
A friend pointed me to [css-modulesify](https://github.com/css-modules/css-modulesify). With the help of that, i might be able to run that through [css2jss](https://github.com/jsstyles/jss/blob/15/bin/cssToJss.js).

Before running it through css2jss, it was already prefixed with the component name, but if i understand correctly, jss prefixes it again. Is it possible to disable that or make jss pick up the prefixes?
Do you see a way to combine this in a nice way with JSS?

**Comment by kof** [comment]
jss prefixer is a plugin, just don't use it if you don't need it

**Comment by serapath** [comment]
Oh nice :-)

**Comment by kof** [comment]
I would look into direction of how to make for e.g. this https://github.com/lvivski/animatic usable nicely together with jss.

**Comment by kof** [comment]
velocityjs is a horrible code base.

**Comment by serapath** [comment]
thx for the link :-) will check it out

**Comment by kof** [comment]
Closing this for now, until specific ideas arise.
