### ISSUE TITLE
Font-face and webpack url/file-loaders

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/jss#562]
@kof how are we supposed to use `jss` while still letting webpack resolve needed files?

Snippet:
```
jss.createStyleSheet({
    '@font-face': {
        fontFamily: 'San Francisco',
        src: [
            'url("../fonts/sf.eot")',
            'url("../fonts/sf.eot?#iefix") format("embedded-opentype")',
            'url("../fonts/sf.woff2") format("woff2")',
            'url("../fonts/sf.woff") format("woff")',
            'url("../fonts/sf.ttf") format("truetype")',
            'url("../fonts/sf.svg") format("svg")',
        ],
    },
}).attach();
```

Here fonts are not resolved by webpack!

**Comment by damianobarbati** [comment]
Help :(

**Comment by kof** [comment]
Sorry, forgot this one. I am  not using webpack for this. In fact for webpack it is a regular js file unless you write a special loader. You can though use just a constant and inject it over webpack for e.g.

```js

  new webpack.DefinePlugin({
    __DEV__: !NODE_ENV || NODE_ENV === 'development',
    __TEST__: NODE_ENV === 'test',
    __STATIC_PATH__: JSON.stringify(STATIC_PATH),
    'process.env.NODE_ENV': JSON.stringify(NODE_ENV)
  })
```

**Comment by damianobarbati** [comment]
@kof I didn't understand: what should I do with env constants? @@
Can I import a font as a normal file and pass that to jss rule with some syntax or do you have any example with webpack+jss font-face working? :(

Thanks!

**Comment by kof** [comment]
My suggestion was about resolving a url. It is basically not using a relative one, but instead use a base path variable provided over webpack or from anywhere else.

**Comment by damianobarbati** [comment]
I have loaders in place and I could do `import fontSvg from '../fonts/sf.eot'` but then how to use them?

**Comment by damianobarbati** [comment]
Solved:
```
import { jss } from 'react-jss';
import sfWoff from './fonts/sf.woff';

jss.createStyleSheet({
    '@global html, body': {
        fontFamily: 'San Francisco',
    },
}).attach();

jss.createStyleSheet({
    '@font-face': {
        fontFamily: 'San Francisco',
        fontWeight: 'normal',
        fontStyle: 'normal',
        src: `url(${sfWoff}) format("woff")`,
    },
}).attach();
```

**Comment by rizalibnu** [comment]
Thanks @damianobarbati
