### ISSUE TITLE
[jss-expand] box-shadow with 0 blur 

### ISSUE THREAD

**Issue by timsnadden** [cssinjs/jss#563]
To create a single pixel box-shadow, it should be possible to declare:

`boxShadow: { x: 0, y: 0, blur: 0, spread: 1 }`

This leads to a blurry box-shadow unless `blur` is a string. e.g. 

`boxShadow: { x: 0, y: 0, blur: '0', spread: 1 },`

**Comment by kof** [comment]
@typical000 can you please take a  look?

**Comment by typical000** [comment]
Fixed. Created pr - https://github.com/cssinjs/jss-expand/pull/23

**Comment by kof** [comment]
published 4.0.1
