### ISSUE TITLE
[jss-nested] Too many nested rules impact performances ?

### ISSUE THREAD

**Issue by fkhadra** [cssinjs/jss#564]
Hey,

First of all, thank you for the amazing work.

I'm just wondering if too many nested rules can impact the performances? Is there a rule of thumb to follow when using nested rules?

Thanks.

**Comment by kof** [comment]
It can, but I can't tell any number. Don't overuse them, more than 3 levels is most of the time also hard to read.

**Comment by fkhadra** [comment]
Thank you.
