### ISSUE TITLE
[css-vendor] If attribute value is a function returning `!important` it transforms to `false`

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#565]
@mistadikay commented on [Thu Aug 17 2017](https://github.com/cssinjs/react-jss/issues/142)

Hey,

Before describing the issue let me tell you a bit of a background, so it will be clear why `!important` is used in the first place.

We're working on embeddable widgets that can be included into our clients websites. Every client has a unique configuration where we specify various options including theming. Some websites use `!important` in their css and it affects our widget styles. The only way to override `!important` is by using another `!important` (I'm writing and crying now), but we don't want to put it on every attribute value by default because we will go to hell for that. So what we did is made a possibility to override certain values in theming configuration on a case-to-case basis.

For example (oversimplified case): the input in our widgets, has `color: ({ theme }) => theme.color`. Our default `theme` looks like this `{ color: '#f00' }`.

The website we're putting our widgets on has `input: { color: '#000 !important' }` in their css. So they will override our amazing red color. In order to solve this we override `theme` in configuration to `{ color: '#f00 !important' }`. But when stylesheets are appended instead of `#f00 !important` there is... `false`. 😐 Which is awkward.

Here is reproducible isolated case:
https://www.webpackbin.com/bins/-KrlDTFL8FtibtlIfHc4

I understand that it might be a rare and specific use-case, but maybe I'm doing something wrong or there is an explanation for such behavior. Thanks.

---

@kof commented on [Thu Aug 17 2017](https://github.com/cssinjs/react-jss/issues/142#issuecomment-323204545)

Its a pretty common case for embeddable widgets. I would write a plugin to auto add !important to each value.

---

@kof commented on [Thu Aug 17 2017](https://github.com/cssinjs/react-jss/issues/142#issuecomment-323204980)

So an actual bug is that if you are using function values and it returns a value with !important, it renders a false. It is actually not related to react-jss nor is the story why you use important is relevant here as far as I can see.

**Comment by kof** [comment]
Might be related to some plugin, can't reproduce it with just core library.  https://www.webpackbin.com/bins/-KrmCekQyZgPhK_4KnhO

**Comment by anasanzari** [comment]
Same issue

**Comment by SimplerSoftware** [comment]
The value is being changed in the plugin call to 'vendor.supportedValue'. The following line is changing it: 
if (!cache[cacheKey]) cache[cacheKey] = false;

**Comment by kof** [comment]
@SimplerSoftware is this evtl fixed as well?

**Comment by AleshaOleg** [comment]
Added support in `css-vendor` of `!important` in arrays and two dimensions arrays https://github.com/cssinjs/css-vendor/pull/34/commits/03b6603d0708660e5e9053ba8a4653a89293e7ad

Do we need to support string values with `!important`? Because in JSS tests it exist https://github.com/cssinjs/jss/blob/8c42e5f967a3375ce43d6c5cc131937c73e25e3a/benchmark/tests/to-css-value.js#L15

But in JSS docs I found only usage with arrays - http://cssinjs.org/json-api?v=v9.4.0#support-of-important

**Comment by AleshaOleg** [comment]
Fixed, can be closed.

**Comment by kof** [comment]
fixed in jss-vendor-prefixer v1
