### ISSUE TITLE
[jss-vendor-prefixer] Support for `display: sticky` is missig

### ISSUE THREAD

**Issue by TiddoLangerak** [cssinjs/jss#577]
Safari currently still requires the `-webkit-` prefix, but this doesn't seem to be added automatically by `jss-vendor-prefixer`.

**Comment by AleshaOleg** [comment]
@TiddoLangerak hey, you can't use `display: sticky`. There is no `sticky` value for `display`. Use it with `position`. Should be closed.

**Comment by kof** [comment]
true, checked on safari prefix is added

**Comment by oliviertassinari** [comment]
@kof I believe we have lost this capability between [JSS v9](https://material-ui.com/demos/app-bar/) and [JSS v10-alpha.12](https://next.material-ui.com/demos/app-bar/).

**Comment by kof** [comment]
@oliviertassinari this issue was created because @TiddoLangerak used display instead of position. Please create a new issue!
