### ISSUE TITLE
Author dictates class names

### ISSUE THREAD

**Issue by jescalan** [cssinjs/jss#582]
Ok, so I know this is pretty far fetched, but curious to get your thoughts. I think JSS is wonderful for all of its features, but there are times when integrating it into a complex build system and getting the classes out of it isn't the ideal approach for some projects. For example, with smaller static sites that don't use components, server rendering, or a large complex build pipeline, and are basically just html/css/js with some light preprocessing steps to get things like html layouts/includes, autoprefixer, es6, etc. For these purposes, right now, most people will go to something like sass/less/stylus. But I would honestly much rather just use regular javascript than a sort of javascript-y and css-y parsed language to get these features, like JSS does.

Right now with JSS, I can use the full power of js to author the css how I want, and I can compile and extract it as static css, which is amazing. But since there is no way to dictate your own class names, or turn off the auto-generated class names as far as I could tell, you still need to do some kind of wizardry with build tools in order to actually use said static css, because there's no way to match your style rules to your html elements due to the auto-generated class names.

I guess what I'm after here is kind of adapting jss to a different use case other than larger apps built with complex build systems, components, etc. and more widely applicable to smaller, simpler sites. And all it would take would be an option to turn off the auto-generated class names, and some minor syntax addition where the author could declare their own class name.

Any thoughts on this direction?

**Comment by kof** [comment]
Thanks for your feedback.

>  For example, with smaller static sites that don't use components,

JSS was create to handle complex applications with componentization.

> But since there is no way to dictate your own class names

[There is](http://cssinjs.org/js-api?v=v9.0.0-pre.4#generate-your-own-class-names)

Also you can use global classes using [jss-global](http://cssinjs.org/jss-global?v=v2.0.0) plugin, which is part of the default preset. 

Also you should take a look at [jss-compose](http://cssinjs.org/jss-compose?v=v4.0.0) which allows you to compose generated and global classes.
