### ISSUE TITLE
JSS class name prefix. 

### ISSUE THREAD

**Issue by octalmage** [cssinjs/jss#583]
JSS guarantees class name uniqueness inside of a React application, but not necessarily on the page. I'm using React in a WordPress plugin so any number of CSS files can be included on my application page. Is there currently a way to prefix all of my generated CSS classes with a string, like "jason_ul_01" for example. 

If not it seems like this should be possible with a plugin and I'd be happy to make it. 

Thanks!

**Comment by kof** [comment]
Hi, thanks for your question. What prevented you from finding the answer in the [docs](http://cssinjs.org/js-api?v=v9.0.0-pre.4#generate-your-own-class-names) ?

**Comment by octalmage** [comment]
Thank you! I was searching for class "namespace" and "prefix".
