### ISSUE TITLE
Nested rule is [Object object]

### ISSUE THREAD

**Issue by janhartmann** [cssinjs/jss#584]
Anyone know why my nested rule is said to be `[Object object]`?

![screen shot 2017-09-20 at 12 32 48](https://user-images.githubusercontent.com/1107383/30634350-dfffe5ae-9dff-11e7-8eaf-06ee718c9510.png)

Code:

```js
import { create as createJss } from "jss";
import preset from "jss-preset-default";
import { createStyleManager, createStyleSheet } from "jss-theme-reactor";

const theme = {
    colors: {
        background: "#111",
        text: "#999",
        textHighlight: "#fff",
        primary: "#3f4ebb"
    }
};

const styleManager = createStyleManager({
    jss: createJss(preset()),
    theme
});

const styleSheet = createStyleSheet("navigation-block", () => ({
    root: {},
    title: {
        textTransform: "uppercase",
        fontSize: "11px"
    },
    list: {
        listStyle: "none",
        padding: 0,
        margin: "15px 0",
        "& li": {
            background: "red"
        }
    }
}));

const NavigationBlock = ({ title, children }) => {
    const classes = styleManager.render(styleSheet);
    return (
        <nav className={classes.root}>
            <span className={classes.title}>{title}</span>
            <ul className={classes.list}>
                <li>dfsf</li>
                {children}
            </ul>
        </nav>
    );
};
```
I am a bit lost here, running all versions updated.

**Comment by kof** [comment]
1. your setup lacks jss-nested plugin
2. can you switch to react-jss from jss-theme-reactor ?

**Comment by janhartmann** [comment]
Hi kof,

I updated my code - I thought the preset() included that one?

I had problems with ReactJSS since I tried to use ThemeProvider and JssProvider together, which failed.

**Comment by kof** [comment]
preset includes that one, I assume no plugins are applied at all.

**Comment by janhartmann** [comment]
It seems like it, any troubleshooting for me?

**Comment by kof** [comment]
you can try creating the same sheet directly with jss instance and see if they work.

**Comment by kof** [comment]
besides of that you should check what versions are actually used

**Comment by janhartmann** [comment]
I was missing a dependency "jss" (wth) in my package json, after installing that it worked. 

Thank kof, nice with quick response. All the best.

**Comment by nicduke38degrees** [comment]
Just noting for others that might end up here. The reason we were seeing this `[Object object]` in our stylesheets was in fact because none of the plugins were running. We'd made the mistake of not exporting a custom Jss instance and consuming this across our modules. Instead we had `import jss from 'jss'` for each module.

```typescript
// init_styles.ts
import jss from "jss";
import preset from "jss-preset-default";
jss.setup(preset());

// another module
import jss from "jss";

jss.createStylesheet({...}) // this jss instance does not have the presents setup
```

might seem obvious to some people but just here for those that might get similarly stuck :)
