### ISSUE TITLE
Project status? Compare to Radium? JSS/CSS is the analog to JSX/HTML?

### ISSUE THREAD

**Issue by mikeaustin** [cssinjs/jss#587]
Sorry for creating a github issue, but I didn't see a group/chat for jss. Commands and questions:

JSS looks like the perfect match to JSX and HTML - define in JavaScript, but compile to CSS. Bridging React Native and React Web is also very cool, laying out the roadmap for cross-platform apps. But I've noticed src hasn't been updated in a few months. But then it's at version 8.1. But then, it 'only' has 2500 GitHub stars. From my perspective, it's difficult to gauge this project. Any feedback? I think others may feel the same, I don't think it's just me.

One last question, which would be nice in the README, is how it compares with Radium. I found both projects by reading about Material-UI and how they used inline styles, but then want to go back to CSS. JSS seems like the perfect match.

**Comment by jcheroske** [comment]
Material UI choose JSS as it's styling solution. I think that says
something. This is an absolutely fantastic library that's constantly
evolving.

**Comment by mikeaustin** [comment]
Ok, I'll give it a try then. I didn't know how deep the rabbit hole went until I started Googling "jss vs" :) And then there's the react-native-web vs material-ui battle. So many choices.

**Comment by kof** [comment]
Thank you for your questions.

- There is gitter chat.
- There is comparison to radium in benefits section
- Recent changes happen in the "next" branch
- 2 months without commits does not mean anything.

**Comment by mikeaustin** [comment]
@kof Oh I see gitter now, but it's a tiny link mixed in with build testing and code coverage so I glossed over it. Maybe add a more prominent link? "next" branch.. got it. I'll check it out.

**Comment by typical000** [comment]
@mikeaustin take a look here http://cssinjs.org here you can find gitter more easier)
