### ISSUE TITLE
https://opencollective.com/jss/backer/2/website 404

### ISSUE THREAD

**Issue by krisdante** [cssinjs/jss#593]
The link is broken, cannot become backer

**Comment by kof** [comment]
hey, thanks for the issue! where does this link come from? What are your steps?

**Comment by kof** [comment]
Oh, I see, it is from the bottom on the page!

**Comment by kof** [comment]
OpenCollective broke a bunch of links, I am waiting for an answer for them, if they can't fix it soon, I will just point all links to the main open collective page https://opencollective.com/jss. For now, feel free to just use this one.

**Comment by kof** [comment]
they fixed it.
