### ISSUE TITLE
[jss-nested] Application fails when use jss-nested in IE11

### ISSUE THREAD

**Issue by sergeyzwezdin** [cssinjs/jss#600]
When I connect jss-nested and add nested styles my application fails to load with error: `Unable to load "@global" property which is NULL`.

There is screenshot with error message:

![image](https://user-images.githubusercontent.com/800755/31766285-8daad2b2-b4e0-11e7-84ca-9367a3d524e1.png)

Does jss-nested supports IE11?

**Comment by kof** [comment]
It does, the error should not be IE specific. Please provide a reproducible example for e.g. using codesandbox.io

**Comment by sergeyzwezdin** [comment]
Ok, I will. Thanks.

**Comment by kof** [comment]
@sergeyzwezdin any updates?

**Comment by sergeyzwezdin** [comment]
@kof Ok, it seems we can't reproduce it on latests versions. Thank you!
