### ISSUE TITLE
[jss-global] Can't change styles dynamically

### ISSUE THREAD

**Issue by RamonBalthazar** [cssinjs/jss#602]
I'm trying to dynamically change the font for `body` from inside my `CustomThemeProvider` using `props` but it works only for the first time, whenever I send new props to `CustomThemeProvider` the body style remains untouched.

Sample code:

```javascript
...

const stylesheet = {
  '@global': {
    body: {
      fontFamily: props => getFontFamily(props.site.styles.font),
    },
  },
};

export default injectSheet(stylesheet)(CustomThemeProvider);
```

**Comment by kof** [comment]
Can you please show an example on codesandbox without CustomThemeProvider in order to make sure the problem is in jss?

**Comment by kof** [comment]
@RamonBalthazar any updates?

**Comment by aslafy-z** [comment]
Same for me, I just reproduced it here: https://codesandbox.io/s/vml5lxmvy

**Comment by RamonBalthazar** [comment]
Sorry folks, never get this to work but didn't need either because our project changed

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/682

**Comment by DurgaPammi** [comment]
how can we right the JSS for the below example :

<Collapsible trigger="Start here">
    <p>This is the collapsible content. It can be any element or React component you like.</p>
  </Collapsible>
CSS is:

.Collapsible__trigger {
display: block;
font-weight: 600;
text-decoration: none;
color: #ffffff;
position: relative;
border: 1px solid white;
padding: 10px;
background: #f3f4f4;
color: black;
}
.Collapsible__trigger:after {
font-family: 'FontAwesome';
content: '\f107';
position: absolute;
right: 10px;
top: 10px;
display: block;
transition: transform 300ms;
}
.Collapsible__trigger.is-open:after {
transform: rotateZ(180deg);
}
.Collapsible__trigger.is-disabled {
opacity: 0.5;
background-color: grey; }

Can You please any one help me about this
