### ISSUE TITLE
[ts] File './node_modules/@types/jss/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by andyjessop** [cssinjs/jss#603]
I get the above IDE error (VSCode). Installed jss with `npm install jss`, and added this to a component:
```
import * as React from 'react';
import { create } from 'jss'; // errors here on 'jss'
import './App.css';

const jss = create();
```
This is with a fresh install of `create-react-app`.

**Comment by andyjessop** [comment]
I think I have installed the wrong types package...

**Comment by kof** [comment]
Please check if the types are for this library and send a pr over there if they are outdated which might be the case. I am  not maintaining ts typings personally.

**Comment by kof** [comment]
@andyjessop  any updates?

**Comment by andyjessop** [comment]
I had installed the wrong package. The `@types/jss` package is not for this project: https://www.npmjs.com/package/@types/jss
