### ISSUE TITLE
Observable rules

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#607]
This should work:

```typescript
const buttonStyle$ = Observable.of({
  backgroundColor: 'blue',
  fontWeight: 'bold',
});

jss.createStyleSheet(
  {
    button: buttonStyle$,
  },
  {  
    link: true,
  },
);
```

**Comment by appsforartists** [comment]
Looking at [the docs](http://cssinjs.org/plugins?v=v9.0.0), this seems like it would be a pretty simple plug-in: 

1. Listen for new rules in `onCreateRule`.
2. If `decl` is observable,
  1. Return a new rule
  2. ```typescript
      decl.subscribe(
        (currentProps) => // sync resulting rule's props to currentProps
      );
      ```
3. If not, return an empty value

**Comment by kof** [comment]
Yep, pretty sure we can do this.

**Comment by kof** [comment]
Regarding deletion - we normally don't delete props, we set values, there is always a default value you can set to achieve what you want. For e.g. instead of removing property opacity use 0.

**Comment by kof** [comment]
CSSOM API does support though removing https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration

**Comment by appsforartists** [comment]
Interesting.  I don't have a concrete use case for deletion either - just seemed like a good idea to clean up after ourselves.  FWIW, deletion and defaults would behave differently for inherited properties like color, but I've yet to build an interaction where I needed to delete a k:v pair.
