### ISSUE TITLE
link() may fail when used with jss.setup(preset()) and observable rules

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#614]
In the [Material Motion JSS Demo](https://material-motion-demos.firebaseapp.com/parallax-jss/), this was failing:

```typescript
  jss.setup(preset());

  const sheet = jss.createStyleSheet({
    container: {
      touchAction: 'none',
      width: '100vw',
      height: '100vh',
      overflow: 'hidden',
      background: '#F7DF1E',
    },

    foreground: foreground$,
    background: background$,
  }).attach().link();
```

with a "You forgot `{ link: true }`" warning.  When I dug into it, it appeared that `foreground` and `background` had `isDynamic` set to `undefined`, which meant no `cssRule` was being generated for them, which made JSS think `link` hadn't been called (even though it had).

For some reason, manually instantiating `jss` works around the issue: http://codereview.cc/D3445

I haven't been able to reproduce this in a test in the `jss` repo.  For now, I'm tempted to just use the workaround; however, I wanted to document the problem so it can be remembered (and maybe eventually) fixed.

**Comment by kof** [comment]
Should be fixed by https://github.com/cssinjs/jss/pull/615

**Comment by appsforartists** [comment]
I'll try to take a look at this again on Monday and confirm.

**Comment by kof** [comment]
I think we fixed that.
