### ISSUE TITLE
Figure out how to handle plugins in conjunction with observable rules

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#616]
In pre-streaming JSS, the `onProcessRule` hook was called once during `createRule` - it's responsible for doing things like converting `borderRadius` to `border-radius`.

If a rule is streaming, when and how often should hooks be called?  An author with the default preset installed probably expects this emission: `{ borderRadius: 4 }` to be written to `<style>` as `border-radius: 4px`.  

The naive way to do this would be to run each observable rule's style emission through `options.jss.plugins.onProcessStyle`.  Would that have a significant impact on performance?  Is there a better place to address this?

**Comment by appsforartists** [comment]
In the mean time, I'm passing each value through this function:

```typescript
function transformForJSS(style: {}) {
  const result = jssDefaultUnit().onProcessStyle(
    jssCamelCase().onProcessStyle(style),
    {type: 'style'}
  )
  return result;
}
```

**Comment by appsforartists** [comment]
One solution: a new hook: `onProcessDynamicStyle` that explicitly runs only on observable rules. It means plugin authors would have to explicitly support observables, but reduces the number of rules that would run on each emission, and means you don't end up hacking the observable plug-in to fit the `onProcessStyle` API.

**Comment by kof** [comment]
Btw. isObservable was updated, https://github.com/sindresorhus/is-observable/commit/877aa30099960ad2d891cd2e394f4ab75f7dbfe5

Should we switch back?

**Comment by appsforartists** [comment]
This is the wrong thread to have that discussion, but I'm not convinced there's value there.  Our check is technically more accurate (since it checks the return value of `[$$observable]()`).  More importantly, mixing CJS and ESM is deoptimizes Webpack bundles.  There's no need to add an external dependency for a trivial one-line function that is already in the codebase.

**Comment by kof** [comment]
ups, posted in the wrong issue, removing…

**Comment by kof** [comment]
I totally forgot that dynamically setting property using CSSOM API works for both, camel case and dash separated notation. We don't have a use case to modify property name over a plugin for now. For value changes we already have a hook `onChangeValue`.

I think this issue can be closed, @appsforartists please confirm.

**Comment by appsforartists** [comment]
I'm pretty sure I opened the issue because it wasn't working - I recall one of my demos not having border radius applied, for instance.

Even if CSSOM handles camel case, we'd still need something to handle appending units.

**Comment by kof** [comment]
Auto units are already working with `onChangeValue` [see](https://github.com/cssinjs/jss-default-unit/blob/master/src/index.js#L84)

**Comment by kof** [comment]
No use
