### ISSUE TITLE
[jss-expand] add border-image to expanded border version

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#621]
Just stumbled over the need to use image as a border (gradient) and realized we don't have image property for border:

```js
border: {
  width: 1,
  style: 'solid',
  image: `linear-gradient(to bottom, #fff 0%, #fff 0%, #f0f0f0 100%)`
}
```

**Comment by kof** [comment]
cc @typical000

**Comment by typical000** [comment]
Done. Created PR https://github.com/cssinjs/jss-expand/pull/26

**Comment by kof** [comment]
merged, thanks!
