### ISSUE TITLE
Plugin to add a prefix to the CSS selector

### ISSUE THREAD

**Issue by natew** [cssinjs/jss#622]
This is mostly a question about the plugin API. I'm attempting to make this work currently, but not sure if it's possible.

Basically, want to prepend something like `.myParentSelector ` to every selector that's output to the stylesheet, but changing rule.selector in the plugin actually changes it in the className, not the stylesheet.

Is this possible?

I see an options.generateClassName and selectorText, but neither seem exactly relevant.

**Comment by kof** [comment]
Instead of telling what you are trying to do, it would help you more to tell what you are trying to achieve. 

Take a look at jss-nested

**Comment by natew** [comment]
@kof I am injecting a JSS-styled thing into another page. But I need to add some global styles now to reset and only apply inside that scoped area. Ideally I'd use web components but it seems not quite ready/supported.

So I have

```html
<body>
  <div>...not my code..</div>
  <div class="mycode">...my code..</div>
</body>
```

And I need to apply some base styles that attach to every div inside .mycode.

Before, I could just do:

```css
body * {
  display: flex;
}
```

But now if I do:

```css
.mycode * {
  display: flex;
}
```

The class selector will override all the JSS rules. I think for now I can just make every property have `!important` which may work, am going to test that. But the root problem is I can't have a global style like above and then override it in JSS.

If I could add a plugin that prefixed my selectors with `.mycode [selector]` then this would solve the issue as well.

**Comment by kof** [comment]
jss-nested and jss-global already allow you this

**Comment by natew** [comment]
Hm.. here's what I see.

```js
parent: {
  '& *': { flexFlow: 'column' }
},
child: {
  flexFlow: 'row'
}
```

But the specificity of the parent now overrides the child, meaning there's no way for me to set "base" styles that are scoped to a certain parent:

![image](https://user-images.githubusercontent.com/12100/32627315-de1770fe-c546-11e7-9010-a9206806ac64.png)

**Comment by kof** [comment]
it is by design of css that way. Another choice is to use jss-isolate and extend it with properties you want to set, if it should apply to every element you style.

**Comment by natew** [comment]
Yea, so do you see the use case now at least? It would be nice to be able to modify the final selector thats output, so I can do this in certain environments.

jss-isolate would still not work because it's not using a specific selector.

The use case here is to make JSS more compatible with real world use cases where you may not have control of some outside styles. It may not be clean, but I do think it's a valid improvement. I'd be willing to write a PR, but want to agree on the use of it.

**Comment by kof** [comment]
Well, the problem is that you will have other global selectors in that case and they may override your base styles you want to apply, so if you really want to use it in an environment which might break your code, jss-isolate + https://github.com/iamstarkov/jss-increase-specificity is the way to go

**Comment by natew** [comment]
I tried increase-specificity, it's broken at the moment. That would have solved my problem but it actually tries to inject the specificity selectors as className's unfortunately. So you get:

```html
<div className=":not(\20):not(\20).cs012></div>
```

I will open a bug there.

**Comment by kof** [comment]
I am using it, something is in your setup. Please check the versions and evtl create a demo on codesandbox

**Comment by kof** [comment]
I think you need at least JSS 8

**Comment by natew** [comment]
Using JSS 9, with the following setup:

```
jss.use(jssNested(), jssDefaultUnit(), jssPropsSort(), jssIncreaseSpecificity())
```

No preset or anything. I'll try and whip up a codepen when I get a minute if you don't see anything obviously wrong here.

Following versions:

```
"jss": "^9.0.0",
    "jss-default-unit": "^8.0.0",
    "jss-nested": "^6.0.0",
    "jss-props-sort": "^6.0.0",
    "jss-increase-specificity": "^0.3.5"
```

**Comment by benatkin** [comment]
Here's a trick I used to override a couple rules with jss-nested, since I didn't want to go beyond the preset just for this:

``` js
import { classes } from './styles';
const html = `<a class=".${classes.tab}._over._ride">My tab</a>`;
```

``` js
const styles = {
  tabs: {
    padding: '5px', // this doesn't need to be overridden
    '&._over._ride': {
      color: 'black',
      textDecoration: 'none'
    }
  }
};
```

It requires adding some classes to the specific element in the HTML, but I can live with that for my current use case. jss-increase-specificity allows allows adding them to the outside. in a way it's nicer to have them targeting specific rules/elements.

**Comment by halimb** [comment]
@kof  solution ([jss-increase-specificity](https://github.com/iamstarkov/jss-increase-specificity)) worked great for me.

was having a had time with a react app embedded in a legacy page filled with greedy css selectors..

Thanks!

**Comment by TimboKZ** [comment]
For people coming from Google, here's a hack I used in a component library for making all styles `@global` and adding a custom `.chonky-` prefix to all class names (with `react-jss@10.4.0`). I made a wrapper for `createUseStyles`:

```ts
export const makeChonkyStyles = <C extends string = string>(
    makeStyles: (theme: ChonkyTheme) => Styles<C>
) => {
    const selectorMapping = {};
    const makeGlobalStyles = (theme: ChonkyTheme) => {
        const localStyles = makeStyles(theme);
        const globalStyles = {};
        const localSelectors = Object.keys(localStyles);
        localSelectors.map((localSelector) => {
            const globalSelector = `chonky-${localSelector}`;
            const jssSelector = `@global .${globalSelector}`;
            globalStyles[jssSelector] = localStyles[localSelector];
            selectorMapping[localSelector] = globalSelector;
        });
        return globalStyles;
    };

    const useStyles = createUseStyles<ChonkyTheme, C>(makeGlobalStyles as any);
    return (...args: any[]) => {
        const styles = useStyles(...args);
        const classes = {};
        Object.keys(selectorMapping).map((localSelector) => {
            classes[localSelector] = selectorMapping[localSelector];
        });
        return { ...classes, ...styles };
    };
};
```

This function can be used as follows:
```tsx
const useStyles = makeChonkyStyles(() => ({
    fileListWrapper: {
        minHeight: (viewConfig: FileViewConfig) => viewConfig.entryHeight,
        height: '100%',
    },
}));

export const FileList: React.FC<FileListProps> = () => {
    const viewConfig = { entryHeight: 100 };
    const classes = useStyles(viewConfig);

    return <div className={classes.fileListWrapper} />;
);
```

Which will render the HTML below and apply styles correctly.
```
<div class="chonky-fileListWrapper"></div>
```
