### ISSUE TITLE
Allow function values to utilize the 'priority' parameter of the style.setProperty method and be able to set it to 'important'.

### ISSUE THREAD

**Issue by SimplerSoftware** [cssinjs/jss#629]
When using function values, I need to be able to use '!important'.  However, since function values are using the CSSOM 'setProperty' method, the value being set cannot have '!important', see [here](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty).  In order to be able to use '!important', the setProperty method must utilize the 3rd optional parameter and set it to 'important'.  

FYI - This is currently being called in the DomRenderer.js file, line 42.

Thanks!

**Comment by kof** [comment]
good catch!

**Comment by kof** [comment]
released in v9.4.0
