### ISSUE TITLE
Class names broken in 9.3.1

### ISSUE THREAD

**Issue by janhartmann** [cssinjs/jss#630]
I just updated my `react-jss` to 8.0.0 and my `jss` to 9.3.1 and of result of that, by class names was transformed into invalid names (escaping issue?):

<img width="513" alt="screen shot 2017-11-14 at 11 17 01" src="https://user-images.githubusercontent.com/1107383/32767620-a465beac-c92d-11e7-8f2e-4394f6cff1f6.png">

Used as such: 

```js
const StyledNetworkGraphAnalysisPage = injectSheet(styles)(withTheme(NetworkGraphAnalysisPage));
```

**Comment by janhartmann** [comment]
I discovered if I use:

```js
const StyledNetworkGraphAnalysisPage = withTheme(injectSheet(styles)(NetworkGraphAnalysisPage));
```

Then it works now.

**Comment by kof** [comment]
Hmm, escaped class names should work actually

**Comment by kof** [comment]
Yeah, there is still an issue with jss cc @oliviertassinari

**Comment by kof** [comment]
should be fixed now, please update
