### ISSUE TITLE
Custom selector with declared props class

### ISSUE THREAD

**Issue by afganhalbana** [cssinjs/jss#636]
Let's say i have 
 ```
navbarWrapper: {
		backgroundColor: '#008000',
		position: 'absolute',
		width: '100%',
		'&:after': clearFloat(),
		'&>ul': {
			height: 63,
			padding: 0,
			margin: 0,
			listStyle: 'none',
			'&>li': {
				float: 'left',
				display: 'inline-block',
				'&>a': {
					padding: '22px 15px',
					textDecoration: 'none',
					color: '#fff',
					display: 'block',
					fontWeight: 500
				},
				'&:hover': {
					backgroundColor: '#690800'
				},
				'&:after': clearFloat()
			}
		}
	},
	searchWrapper: {
		backgroundColor: 'red'
	}
```
i want on the hover in li section to be something like _"All the li except the li with props class searchWrapper"_, i already tried to concatenate the string tobe some thing like
```
[`&:hover{$searchWrapper}`]: {
        backgroundColor: '#690800'
}
```
but it got error undefined since the searchWrapper is just a property instead of the variable. Is there any way to do that? i couldnt figured this out.

**Comment by kof** [comment]
I think you are looking for something like this:

```js
{
  navbarWrapper: {
   	backgroundColor: '#008000',
   	position: 'absolute',
   	width: '100%',
   	'&>ul': {
   		height: 63,
   		padding: 0,
   		margin: 0,
   		listStyle: 'none',
   		'&>li': {
   			float: 'left',
   			display: 'inline-block',
   			'&>a': {
   				padding: '22px 15px',
   				textDecoration: 'none',
   				color: '#fff',
   				display: 'block',
   				fontWeight: 500
   			},
   			'&:hover:not($searchWrapper)': {
   				backgroundColor: '#690800'
   			},
   		}
   	}
   },
   searchWrapper: {
   	backgroundColor: 'red'
   }
}
```

Tip: remove all the nesting and use classes map directly instead for everything. Flat styles are easy to read.

**Comment by afganhalbana** [comment]
@kof It works well !! Since Im moving from sass its kinda hard to leaving this nesting behavior, even tho Im wondering to give more classes to some elements but im not really sure whether its good or bad practice. It would be great if we had a clear documentation covering all these things, thanks for the help and tip anyway.

**Comment by kof** [comment]
It is just a recommendation, I should probably write a separate document and describe all recommendations, I don't know though where to start and I don't have a list of things to describe.
