### ISSUE TITLE
About typescript d.ts file

### ISSUE THREAD

**Issue by linmodev** [cssinjs/jss#639]
Hi, I recently did some ts types, I'm a new to ts, so I can not guarantee the high quality of these types, but I want to participate in the typing of this item so can I submit this PR? This type may be very simple to write, I am sorry, because I am a novice

**Comment by linmodev** [comment]
https://github.com/linmodev/jss You can browse my commit

**Comment by kof** [comment]
Appreciate help, here is the right issue #361 and here is the current PR for this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21851
