### ISSUE TITLE
jss.createStyleSheet() calls collide with independent jss instances

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#644]
The docs currently encourage each component to have its own instance of JSS.  However, the instances are independent, which can lead to bugs:

```ts
// component1
const jss = createJSS().setup(preset());
const styleSheet = jss.createStyleSheet({
  scrim: {
    backgroundColor: 'red',
  //...
});

// component2
const jss = createJSS().setup(preset());
const styleSheet = jss.createStyleSheet({
  scrim: {
    backgroundColor: 'blue',
  //...
});
```

It looks like `component1` will have a red scrim and `component2` will have a blue one.  Unfortunately, because they are independent instances, each will generate the same `className` (e.g. `scrim-0-1`), so the two style declarations will conflict with one another.

## Potential solutions
1. Update the documentation to note this issue.  This would lead encourage authors to use the global instance, but could make npm-distributed components less encapsulated.
2. Maintain a `className` registry in jss, independent of the `jss` instance.  This would allow independently-configured `jss` instances to ensure they aren't creating colliding classes.  However, it could complicate garbage collection in server-side rendering.
3. Move `setup` to the `styleSheet` level, rather than the instance level.  This would allow each rendered page to use a single `jss` instance, even if an imported component depends on a different setup.
4. Add a random (hopefully unique) key to each `className`.  Then, the example would result in `scrim1209312031` and `scrim09834234`, which would not conflict.

4 is probably the best trade off between simplicity, minimizing changes, and fixing the issue.

**Comment by kof** [comment]
Omg, no, jss instance should be per app or basically per configuration. Where should we fix it?

**Comment by appsforartists** [comment]
I think you need to add a random hash to each class name.  Otherwise, you get the same problem with

```js
// some-npm-component

const jss = createJSS().setup(myConfig);
const styleSheet = jss.createStyleSheet({
  scrim: // ...
});

// app

import { Component } from 'some-npm-component';

const jss = createJSS().setup(preset());
const styleSheet = jss.createStyleSheet({
  scrim: // ...
});
```

**Comment by kof** [comment]
We have classNamePrefix option for this, as I assume there should not be hundreds of jss instances,  a few of them can be manually prefixed using that option.

**Comment by kof** [comment]
Most of the time you actually have just once instance, second instance may be needed if you have a part of an application which comes from a different package and uses a different jss setup for e.g.

**Comment by kof** [comment]
Where can we enhance the docs for this?

**Comment by appsforartists** [comment]
> Use an own instance if the component you build should be reusable within a different project with a probably different JSS setup.
> - http://cssinjs.org/js-api/?v=v9.3.3#create-an-own-jss-instance

is the section of the docs that needs fixing up.

But more than that, what's the harm in adding a random suffix to either each `className` individually, or one for the `styleSheet` that's included in each of its `className`s?  Even people developing distributed components shouldn't have to think about this if we can just fix it.

**Comment by kof** [comment]
True, we can add an JSS instance counter, then this issue is gone forever. Also we could use it instead of jss module counter https://github.com/cssinjs/jss/blob/master/src/utils/createGenerateClassName.js#L10

**Comment by kof** [comment]
should be fixed in v9.4.0

**Comment by appsforartists** [comment]
Sweet.  What was "proprity" supposed to say in https://github.com/cssinjs/jss/blob/master/changelog.md?

**Comment by kof** [comment]
setProperty has a 3rd argument, which is priority https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

**Comment by kof** [comment]
#629

**Comment by appsforartists** [comment]
(I was trying to point out a typo - was that word supposed to be "priority" instead of "proprity"?)

**Comment by kof** [comment]
lol, I mispelled it twice then
