### ISSUE TITLE
Can't resolve 'is-observable'

### ISSUE THREAD

**Issue by stunaz** [cssinjs/jss#650]
Having this issue witht the last release

`./node_modules/jss-default-unit/lib/index.js Module not found: Can't resolve 'is-observable' in '.../node_modules/jss-default-unit/lib'`

**Comment by kof** [comment]
On it!

**Comment by kof** [comment]
fixed in jss-preset-default@8.0.2

**Comment by stunaz** [comment]
fixed, thanks!
