### ISSUE TITLE
Start using prettier

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#651]
1. Start using https://github.com/prettier/eslint-config-prettier
1. Check settings of https://github.com/cssinjs/eslint-config-jss if they are compatible with prettier
1. Start using prettier via mrm https://www.npmjs.com/package/mrm-task-prettier

**Comment by Graham42** [comment]
PR opened https://github.com/cssinjs/jss/pull/671

**Comment by kof** [comment]
closing this for core, needs to be done for all plugins though
