### ISSUE TITLE
Could not find the referenced rule ... in @media

### ISSUE THREAD

**Issue by alex996** [cssinjs/jss#652]
I have trouble referencing a local rule inside a media query:

```js
const styles = theme => ({
  primary: {
    fontSize: '12px',
    '&$disabled': { // this works
      opacity: 0.5
    },
    '@media (min-width: 64em)': {
      height: '40px',
      '&:hover:not($disabled)': { // this does NOT work
        boxShadow: '0px 3px 5px 0px rgba(0, 0, 0, .5)'
      }
    }
  },
  disabled: {
    cursor: 'default'
  }
})
```

This fails with

```
Warning: [JSS] Could not find the referenced rule disabled in @media (min-width: 64em) 
```

The objective is to reference the local `disabled` class from within the same stylesheet. Does the library have support for it at the moment?

P.S. On my end, this happens as part of cssinjs/react-jss.

**Comment by kof** [comment]
its a bug https://github.com/cssinjs/jss/issues/446
