### ISSUE TITLE
[jss-isolate] Some preperties aren’t cross-browser

### ISSUE THREAD

**Issue by sapegin** [cssinjs/jss#653]
Some properties, like `-webkit-text-fill-color` behaves differently in different browsers, which cases issues like this, [described in detail](https://github.com/styleguidist/react-styleguidist/issues/739) at react-styleguidist:

**Chrome** (working):
![chrome](http://files.corygibbons.com/Screen-Shot-2017-12-18-at-6.53.23-PM.png)

**Safari** (broken):
![safari](http://files.corygibbons.com/Screen-Shot-2017-12-18-at-6.53.06-PM.png)

I guess `-webkit-text-fill-color` isn’t the only property that may cause issues, and it wasn’t the case in jss-isolate 4.x because it didn’t use initize and didn’t have any vendor-prefixed properties.

**Comment by kof** [comment]
we removed lately all experimental properties from jss-isolate
