### ISSUE TITLE
Add warning when multiple JSS versions are bundled

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#658]
We should warn the user when multiple JSS versions are detected in case user is unaware. This is easy in utils/moduleId

**Comment by kof** [comment]
cc @oliviertassinari

**Comment by oliviertassinari** [comment]
My motivation for such warning would be the following: JSS is a large dependency, you don't want to have two version bundled in your package. Like you would not want two version of React, effectively, it's not possible. Also, maybe we can save some bytes in production by not supporting it.

**Comment by kof** [comment]
So you are for deprecating support of multiple versions instead of warning? I would validate first regarding react and some others, I think it was an old issue and was fixed.

**Comment by oliviertassinari** [comment]
@kof I'm in favor of not supporting multiple versions. Adding a warning so people understand what's going one. Saving kB be removing all the code that makes it work.

**Comment by kof** [comment]
Btw. it should be also server side or build time, otheriwse it is possible to get different class names from ssr/build and client.

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/677
