### ISSUE TITLE
Prefix wrong in production when using react-jss

### ISSUE THREAD

**Issue by btmorex** [cssinjs/jss#659]
I'm not sure if this is a jss bug or react-jss bug, but since downgrading jss to 9.3.x solves the problem, I'm logging against jss. With NODE_ENV == production, my SSR class names are the development variant (SomeReactClass-), but when run in browser the css is added with the production class name variants (c) so it's not correctly applied to the SSR produced html. Nothing else in my environment has changed except for upgrading jss related dependencies.

**Comment by kof** [comment]
So basically what you are saying is that on SSR and production class names are still having development mode. Can you please provide something reproducible?

**Comment by btmorex** [comment]
Yeah, that's exactly it. It's part of a significant (currently, private) project, but I'll see if I can provide a minimal case. Started happening with jss 9.4.0, but I just noticed strange output from yarn list that might be related (two versions of jss being pulled in by react-jss):

├─ react-jss@8.2.0
│  ├─ hoist-non-react-statics@^2.3.1
│  ├─ jss-preset-default@^4.0.1
│  ├─ jss@^9.3.2
│  ├─ jss@9.4.0
│  │  ├─ is-in-browser@^1.1.3
│  │  ├─ symbol-observable@^1.1.0
│  │  └─ warning@^3.0.0
│  ├─ prop-types@^15.6.0
│  └─ theming@^1.3.0

**Comment by btmorex** [comment]
After further investigation, it looks like react-jss is always providing defaultClassNamePrefix, which is now applied in production. The problem is when doing SSR the code is not minified so classes are named like "WhateverReactClass", but in the minified js sent to the client classes are named like "o". Perhaps the fix is to check NODE_ENV in react-jss and don't set defaultClassNamePrefix in production?

**Comment by kof** [comment]
Oh, I see, thanks, tbc in https://github.com/cssinjs/react-jss/issues/191
