### ISSUE TITLE
Plugins need to react on rules prop modifications

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#66]
Need to think of an api how plugins can hook into rules prop changes and apply their changes.

**Comment by joshgillies** [comment]
Would employing something like `observ-*` at the core of the JSS api help here? For instance https://www.npmjs.com/package/observ-hash

**Comment by kof** [comment]
I was thinking about something way more minimalistic.

**Comment by joshgillies** [comment]
After spending some time with JSS I now see the point of this issue. 

```js
rule.prop('width', 10)
```

Should pass through the plugin pipeline before being set against a rule.

@kof have you further thoughts around this?

**Comment by kof** [comment]
Now as I use jss for some time, I learned:
1. jss is mostly for static styles, dynamic styles should be done inline
1. there are some very rare cases where one needs to manipulate the sheet.

So the questions are:
1. what are the use cases where we really need dynamic props?
2. Do they need to be high performance? For e.g. if we run all plugins on the rule, we don't need to force plugins implement anything specific to make this work, but this approach will have an overhead of applying every plugin to every property/value of the rule. Otherwise we need a way to enable plugin to react on specific property change of a rule. 
3. The most simplistic approach would be an .on method on rule instance to register a property handler. After that ".prop" setter would run all registered functions with prop, value and rule as arguments. We don't need  of ".off" method or any other emitter like methods as we have a very simplistic use case.

**Comment by kof** [comment]
After some nights on it, I think this is not something one would want to do at 60fps, its rather a single action. We should just run all plugins on .prop setter and rerender the whole rule.

**Comment by kof** [comment]
Another idea would be to rewrite plugins api and make every plugin react on every property instead on every rule. This way we could efficiently run plugins on prop modifications.

**Comment by kof** [comment]
I think right now it is not very important. Because it turns to be a rare case when people need to use .prop() function. I think for now I will close it.
