### ISSUE TITLE
[css-vendor] transition with css function call

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#661]
Original issue is here https://github.com/mui-org/material-ui/issues/9900#issuecomment-357923518

```
margin 225ms cubic-bezier(0.0, 0, 0.2, 1) 0ms
```

Turns to this:

```
 transition: margin 225ms cubic-bezier(0.0, false, false.2, false) 0ms;
```

**Comment by kof** [comment]
We should also take a look at this, different issue, but related to vendor-prefixer 1.0 https://github.com/mui-org/material-ui/issues/9903

**Comment by xaviergonz** [comment]
Yeah, the problems seems to be in css-vendor
export default function supportedValue(property, value)
https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js

if you call that with ('transition', 'margin 225ms cubic-bezier(0.0, 0, 0.2, 0) 0ms,width 225ms cubic-bezier(0.0, 0, 0.2, 0) 0ms') it returns "margin 225ms cubic-bezier(0.0, false, false.2, false) 0ms,width 225ms cubic-bezier(0.0, false, false.2, false) 0ms"
