### ISSUE TITLE
[JSS] unknown pseudo rules crash jss in browser

### ISSUE THREAD

**Issue by wouter-willems** [cssinjs/jss#662]
For example:
```
const styles = {
    'input::idontexist': {
        color: blue,
    }
};
```

This will crash in browser. It does give a warning but my page is missing all kinds of css styles.
This is a big problem for IE11 for example, as that does not know things like: `::-webkit-input-placeholder` or `::placeholder`.

the error:

`browser.js:49 Warning: [JSS] Can not insert an unsupported rule `
resulting in:

`DomRenderer.js:402 Uncaught DOMException: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (4294967295) is larger than the maximum index (4294967295).`

**Comment by kof** [comment]
Are those 2 separate errors? 4294967295 looks like you managed to insert this amount of rules, is it reproducible by just the code above? Also what JSS version and plugins are you using? Ideally a codesandbox example to make sure I have the same setup.

**Comment by wouter-willems** [comment]
Thank you for the quick response!
I havent managed to get a sandbox working to replicate it yet, ill get back to this
