### ISSUE TITLE
[jss-global] Link option does not work

### ISSUE THREAD

**Issue by aslafy-z** [cssinjs/jss#664]
I'm unable to use the `link` option mentioned in the JS api documentation with jss-global plugin. Every call to `sheet.update` after `sheet.attach` have been called triggers a

> Warning: Rule is not linked. Missing sheet option "link: true".

even with the right option, and sheet doesn't get refreshed.

I have been able to reproduce this behavior here: https://codesandbox.io/s/vml5lxmvy 

Could be the same as #602 but op didn't said about the `link` option usage.

**Comment by kof** [comment]
Thank you for the report, I will take a look asap. In the mean time if you can, you can also try to fix it and send me pr or clues :)

**Comment by sambhav-gore** [comment]
@kof I have a solution for this, want to submit a PR but stuck with linting issues.

**Comment by kof** [comment]
Ok, send a PR with lint errors, I will take a look.

**Comment by sambhav-gore** [comment]
@kof I already created a PR with lint errors fixed - #666

**Comment by Vadorequest** [comment]
I have this warning with `react-jss@8.2.1` and I have no idea what it may break or so.

**Comment by carlgunderson** [comment]
@kof is there an update on this issue based on #666? I'm getting the same warning but I'm not using an option called `link` anywhere, and can't find it mentioned in any docs...I'm using react-jss with jss-preset-default and this just started showing up. I don't have any dynamic properties inside my `@global` blocks.

**Comment by jpetitcolas** [comment]
I encountered a similar issue with a non global scope (see details on https://github.com/mui-org/material-ui/issues/10543 / sandbox: https://codesandbox.io/s/lpm6vop66l). May it be related?

**Comment by aslafy-z** [comment]
https://github.com/cssinjs/jss-global/pull/6

**Comment by aslafy-z** [comment]
This issue has been fixed with #1040.
Thanks @kof!
