### ISSUE TITLE
jss instance counter (moduleId) causes SSR class name mismatch

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/jss#665]
I hope I can impress upon everyone that **using counters for class names is very, very brittle and I've had to work through dozens of server/client class name mismatches because of counters.**  I'm getting pretty tired of it, and it doesn't seem sustainable to me.

This latest problem comes from the apparently new `moduleId.js` jss instance counter getting worked into the generated class names.  Here's the error I'm getting:

```js
Warning: Prop `className` did not match. Server: "MuiSvgIconroot-1-2-26 MuiIconButtonicon-1-2-22" Client: "MuiSvgIconroot-0-2-26 MuiIconButtonicon-0-2-22
```

I know you'll probably say it's up to us to ensure that the same jss instances get created in the same order on the server and client.  But this is getting increasingly difficult as some libraries like `material-ui` create their own `jss` instances.

**Comment by kof** [comment]
Yeah, counters are sensible in some situations. From your code I can see that the missmatch is the first number which is module id. It seems you got more than one JSS package on the server, while you have only one on the client?

**Comment by kof** [comment]
If this is the case, https://github.com/cssinjs/jss/issues/658 would have helped by warning you, right?

**Comment by jedwards1211** [comment]
@kof turns out what's happening is my hot reloading code on the server creates a new instance of jss when it reloads my SSR code.  This is a very typical example of the problems global variables (like the moduleId counter) cause...

**Comment by kof** [comment]
its not a new instance of jss, first number is module id and this is a a new jss module, it evaluates the module over and over

**Comment by jedwards1211** [comment]
@kof ah well I'm clearing `require.cache` when I perform a hot reload, so the `jss` modules are getting reloaded

**Comment by jedwards1211** [comment]
at the very least I'd like to have that counter variable exported so that I could delete that global variable myself

**Comment by kof** [comment]
so what you do is not a common case and I don'T need to look for a proper fix?

I think you can just reset the module id  jss/src/utils/moduleId

**Comment by jedwards1211** [comment]
It may not be a common case, but is there really no less brittle solution that people have come up with than counters?

**Comment by jedwards1211** [comment]
I can reset the module id but I can't reset the counter, because I don't have access to the `ns` GUID variable from that module.

**Comment by kof** [comment]
Hashing, downside is you need to stringify rules and create hashes, which has a cost.

**Comment by jedwards1211** [comment]
@kof so pass a map from hash to counter from server to client?

**Comment by jedwards1211** [comment]
That's the thing, a lot of tools like `redux` and `apollo` rely on passing state from the server to the client, right now `jss` relies on being able to recreate the same exact state on the client from scratch, which is brittle.

**Comment by kof** [comment]
Separate discussion.  I don't see why or what you can't reset now.

**Comment by kof** [comment]
JSS relies on react, which guarantees same execution order, again, its a long separate discussion.

**Comment by jedwards1211** [comment]
Sigh.  The number of times I've had to deal with SSR mismatch with JSS is depressing.

**Comment by kof** [comment]
Well, thats because there are bugs, not many people use ssr.

**Comment by jedwards1211** [comment]
Reseting the moduleId counter wasn't sufficient, the other counters are still messed up:
```js
Warning: Prop `className` did not match. Server: "MuiSvgIconroot-0-4-26 MuiIconButtonicon-0-4-22" Client: "MuiSvgIconroot-0-2-26 MuiIconButtonicon-0-2-22"
```
This is why I really hate the counters.

**Comment by jedwards1211** [comment]
I guess this is the best I can do but it feels like a huge hack:
```js
export default function createJss(): Jss {
  // forcibly reset jss moduleId to prevent SSR errors due to hot reloading
  require('jss/lib/utils/moduleId').default = 0
  const result = create(preset())
  result.id = 0
  return result
}
```

**Comment by kof** [comment]
https://github.com/cssinjs/react-jss/#multi-tree-setup

Your case is similar to multi tree setup, feel free to contribute with the docs for your case. You need

**Comment by kof** [comment]
Again, I think you do weird, non-standard things with your hot reload setup or otherwise, we should take a look at your case and either make it easier or document.

**Comment by jedwards1211** [comment]
Weird, non-standard things don't typically cause problems with packages that are written in a completely modular way and don't rely on global variables.  My hot reloading hasn't causes problems with Redux or Apollo SSR.  Why not just have the user pass in these ids instead of using a counter?

**Comment by kof** [comment]
Once you really want to talk about it and help out, ping me on gitter. Its a long discussion and this issue seems not a proper way to discuss it.

**Comment by jedwards1211** [comment]
I guess I'll spend some time thinking about the details of a less brittle approach then and let you know once I've figured it out.

**Comment by kof** [comment]
Btw. moduleid is there to allow using multiple jss package versions on the same page without class names conflicts. 

I guess graphql doesn't have to deal with global class names nature.

**Comment by kof** [comment]
One possibility would be to use a static module id instead of using global.

**Comment by wouter-willems** [comment]
Any updates on this issue?
What is the best practice to go around this problem?

**Comment by kof** [comment]
see https://github.com/cssinjs/jss/issues/658 and https://github.com/cssinjs/jss/issues/677
