### ISSUE TITLE
Writing a rule based on props

### ISSUE THREAD

**Issue by wouter-willems** [cssinjs/jss#675]
Hi, i am aware we can set a certain value based on a prop like this:

```
const styles = {
   color: props => props.bg
}
```

However, what if I want to write the whole rule based on a prop? So for example, let's say i dont have a props.bg property, i dont want to write the `color` property at all. If i return something like `undefined` or `null`, it will render `color: false` in my css.

So how can i conditionally write a rule based on a prop? Help is much appreciated =)

I tried solving this with jss-compose. But it doenst like like lambda's are supported for the `composes` property

**Comment by kof** [comment]
Function rules are already implemented http://cssinjs.org/json-api?v=v9.6.0#function-rules

**Comment by wouter-willems** [comment]
Wow, what a great and fast response, thank you very much!

**Comment by wouter-willems** [comment]
I am on version 9.6.0 of jss, and the function rules are not being recognized. Is there any other package that is required in order for this to work? I do also have the `link` option set to `true`

**Comment by kof** [comment]
can't do mind reading yet, need code
