### ISSUE TITLE
Postinstall script requires node to be on the PATH

### ISSUE THREAD

**Issue by alexanthony** [cssinjs/jss#680]
The postinstall donation script depends on node being on the PATH. On our build agents, we don't have any node binaries on the PATH so that we can be sure we're explicitly specifying which node version is being used. As a result, we can't use any version from 9.5.1 and above (install fails, to the whole job fails).

Could you change the postinstall script to print some other way? echo?

**Comment by kof** [comment]
I got this idea from preact and they have tons of users as well. I wonder if you should fix it, I never heard so far any one else with this issue.

**Comment by kof** [comment]
cc @developit

**Comment by developit** [comment]
Echo might be better, but you'll see the source.

**Comment by kof** [comment]
it needs a cross-platform echo

**Comment by alexanthony** [comment]
I think this is actually related to yarn's implementation of the --scripts-prepend-node-path behaviour described in https://docs.npmjs.com/cli/run-script - that's probably the right place to sort this
