### ISSUE TITLE
@keyframes not working in chrome [jss-vendor-prefixer] [jss-preset-default] 

### ISSUE THREAD

**Issue by jeffal** [cssinjs/jss#683]
**os:**
`macOS Sierra Version 10.12.6`

**browser:**
`Version 63.0.3239.132 (Official Build) (64-bit)`

**dependencies:**
`jss-preset-default`: `^4.3.0`
`react-jss`: `^8.3.3`

Using the default preset, the `keyframes` vendor prefix is being generated incorrectly...

<img width="250" alt="screenshot 2018-02-12 17 55 59" src="https://user-images.githubusercontent.com/2325629/36126424-04a19804-101e-11e8-85f8-56a835dd66d9.png">

The prefix should be...

<img width="199" alt="screenshot 2018-02-12 17 57 44" src="https://user-images.githubusercontent.com/2325629/36126481-403c1722-101e-11e8-8d6b-35484108c9ea.png">

**Comment by kof** [comment]
what vendor prefixer version have you got installed?

**Comment by kof** [comment]
it should be 7.0.0

**Comment by jeffal** [comment]
@kof Yes, this is the version installed by `jss-preset-default`. I was able to recreate this issue using the `Calendar` example. Modifying `jss.js` as follows:
```
// Setup jss plugins.
// import { create } from 'jss'
import { jss } from 'react-jss';
import extend from 'jss-extend'
import nested from 'jss-nested'
import camelCase from 'jss-camel-case'
import defaultUnit from 'jss-default-unit'
import vendorPrefixer from 'jss-vendor-prefixer'
import preset from 'jss-preset-default'

// const jss = create()
jss.setup(preset())

// jss.use(extend())
// jss.use(nested())
// jss.use(camelCase())
// jss.use(defaultUnit())
// jss.use(vendorPrefixer())

export default jss
```

The issue appears when using a combination of `react-jss` and the `jss-preset-default`. Using a created `jss` does not result in the added vendor prefixes.

Thank you!

**Comment by kof** [comment]
what is the source code you are using?

**Comment by kof** [comment]
oh, you prefixed the keyframes manually and got it double prefixed?

**Comment by jeffal** [comment]
Here is the source code: https://github.com/cssinjs/examples

I modified [jss.js](https://github.com/cssinjs/examples/blob/gh-pages/calendar/components/jss.js) here in order to confirm the issue was not related to my project.

Here is an example of the keyframe styles:
```
  '@keyframes example': {
    to: {
      background: '#fff'
    },
    from: {
      background: 'pink'
    }
  },
```

**Comment by kof** [comment]
https://codesandbox.io/s/9q244k377p
![screen shot 2018-02-13 at 7 42 40 pm](https://user-images.githubusercontent.com/52824/36167406-14591c8a-10f6-11e8-88c6-90a32162f757.png)

looks correct to me

**Comment by kof** [comment]
if you use react-jss, you don't need to setup plugins, default preset is already in place

**Comment by jeffal** [comment]
Thank you, I did not know this.

Here is an example with default preset that shows the issue:
https://codesandbox.io/s/4wk33xv4r9

**Comment by kof** [comment]
your example works correctly and generated css correct

**Comment by kof** [comment]
This applies all plugins second time, not its clear why.
