### ISSUE TITLE
[jss-nested] Keyframes cannot be added

### ISSUE THREAD

**Issue by dan-lee** [cssinjs/jss#685]
Simply adding this keyframe as a rule:
```
sheet.addRule('foo', {
  '@keyframes test': {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
})
```
throws following error 
> TypeError container.addRule(...).addRule is not a function

[**See this CodeSandbox**](https://codesandbox.io/s/kw801vjvwr) for repro and full error stack.

**Comment by kof** [comment]
See the test

https://github.com/cssinjs/jss/blob/602e3257d55849bdcf9831d111b029f383951c02/tests/functional/sheet.js#L330

**Comment by dan-lee** [comment]
Oops, thanks.

**Comment by janat08** [comment]
So how did you fix it?
