### ISSUE TITLE
Most important issue

### ISSUE THREAD

**Issue by pthrasher** [cssinjs/jss#686]
Just wanted to drop in and say you guys are doing really awesome work. Right now the community seems to be rallying around `styled-components` but I think JSS is the future and I hope the community comes around. Keep up the great work and I plan to pitch in on the effort with some PRs

🍻 🍺 :beers:

PS - Feel free to just close this. Just wanted to show some appreciation. :-) Thanks for all the hard work.

**Edit:** I know the team working on styled-components is doing great work too... Definitely not taking anything away from them. Plenty of kudos to go around... I just think JSS puts a better foot forward. We wouldn't know that if we didn't try more than one way!

**Comment by kof** [comment]
Wow, thank you very much, happy to hear!
