### ISSUE TITLE
JSS Causing Flow Error (JSS 9.8.1 & Flow 0.68.0)

### ISSUE THREAD

**Issue by EugeneZ** [cssinjs/jss#692]
This is the error:
```
Error -------------------------------------------------------- node_modules/jss/lib/renderers/DomRenderer.js.flow:262:32

Property `nodeType` is missing in string [1].

   node_modules/jss/lib/renderers/DomRenderer.js.flow:262:32
   262|   if (insertionPoint && typeof insertionPoint.nodeType === 'number') {
                                       ^^^^^^^^^^^^^^^^^^^^^^^

References:
   node_modules/jss/lib/renderers/DomRenderer.js.flow:11:20
    11|   insertionPoint?: InsertionPoint
                           ^^^^^^^^^^^^^^ [1]
```

I have already added `node_modules/jss/flow-typed` to the `[libs]` section in `.flowconfig`. This setup was working fine on Flow 0.62. I upgraded to 0.68, saw a bunch of problems, upgraded jss to the latest, and now get this.

**Comment by kof** [comment]
latest JSS version (9.8.1) is using flow 0.68 without errors

**Comment by dforsl** [comment]
I'm seeing the same error with JSS 9.8.1 and flow 0.69.0. Any findings @EugeneZ?

**Comment by kof** [comment]
if you clone the repo, npm i and npm run flow, do you get that error?

**Comment by dforsl** [comment]
It's successful!

**Comment by kof** [comment]
Means you are not using the version of JSS you are saying you are using, check your node_modules

**Comment by dforsl** [comment]
From node_modules/jss/package.json I can read version 9.8.1. But I'm probably missing something, trying to narrow it down.

**Comment by EugeneZ** [comment]
@dforsl Didn't have time to figure it out. It's very strange considering the flow error is clearly inside `jss` and seems to be a valid error, since `InsertionPoint` indeed does not have `nodeType` defined.

**Comment by kof** [comment]
always a good way to start digging by creating a fresh project and adding dependencies one by one
