### ISSUE TITLE
[jss-isolate] how isolate from globals

### ISSUE THREAD

**Issue by adantoscano** [cssinjs/jss#693]
Hi!
I'm developing a react widget to insert in many webs but I got problems with global styles.
i.e. lot of webs got `img{ heigth: 100% }`. I tried jss-isolate but `imgBtn: { isolate: true }` doesn't reset heigth property.
There is any way to reset global styles from parent componet to children?

**Comment by kof** [comment]
When you setup the plugin, you need to use https://github.com/cssinjs/jss-isolate#option-reset option `rest: 'all'`

**Comment by kof** [comment]
height: auto should be applied then https://github.com/iamstarkov/css-initials/blob/master/all.js#L123
