### ISSUE TITLE
[jss-vendor-prefixer] Edge doesn't support -ms- prefix for keyframes

### ISSUE THREAD

**Issue by Evalon** [cssinjs/jss#695]
Microsoft Edge 41.16299.334.0 doesn't support -ms- prefix for keyframes. So logic to add a prefix to keyframes in any situation doesn't work anymore and leads to not worked animations. But to be precise I did not find a changelog or something for Edge to be sure that was intentional.

**Comment by kof** [comment]
yes, lets fix this

**Comment by AleshaOleg** [comment]
@Evalon according to caniuse data - https://caniuse.com/#search=keyframes
Keyframes don't need a prefix. Aren't?

**Comment by Evalon** [comment]
For IE and Edge that's true, but for some old browsers it's still needed.

**Comment by AleshaOleg** [comment]
@Evalon we do not support, IE < 10 as I remember

**Comment by AleshaOleg** [comment]
@Evalon Can I close this issue?

**Comment by Evalon** [comment]
Probably, but plugin logic add prefix even for new browsers. And for IE and Edge is -ms-. That's follow to not worked keyframes in new browsers.

**Comment by AleshaOleg** [comment]
@Evalon there is a full support of keyframes for all of Edge version and IE >= 10. What's a problem?
Do you have any examples of non-working keyframes in Edge?

**Comment by Evalon** [comment]
Example:
https://codepen.io/anon/pen/GdmRyo

**Comment by Evalon** [comment]
@ubergrape
That's true and that's where is plugin did wrong. It's added -ms- prefix.

**Comment by AleshaOleg** [comment]
@Evalon ok, got it. Checking.

**Comment by AleshaOleg** [comment]
@Evalon take a look at this. https://codesandbox.io/s/lxl8mwj1l7

Tested on Microsoft Edge 41.16299.371.0

![photo_2018-05-01_21-04-34](https://user-images.githubusercontent.com/1459899/39486217-0b6d6d5e-4d84-11e8-8bc3-57625f4bc9c1.jpg)

https://www.dropbox.com/s/2w8cckokbh2lmn7/Microsoft%20Edge%205_1_2018%209_07_20%20PM.mp4?dl=0

**Comment by Evalon** [comment]
@ubergrape You use jss-preset-default that doesn't have the latest version of jss-vendor-prefixer in its turn it doesn't have latest css-vendor with the fix for Edge so prefix is empty. Try this (uses latest jss-vendor-prefixer):  https://codesandbox.io/s/1vkv3v9724

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/jss-vendor-prefixer/pull/12

**Comment by AleshaOleg** [comment]
Fixed in `8.0.1`. cc @Evalon. Thanks to you!

**Comment by azarual** [comment]
i have a keyframes that doesn't work  on edge even though it's so simple 
@keyframes backgroundAfter{
		0%{width:100%;}
		100%{width:340%;}
	}
you can see it on my website www.home-pharma.fr
can some one help me to solve it

**Comment by AleshaOleg** [comment]
@azarual thanks for reporting. Can confirm.
@kof @HenriBeck animations throw `keyframes` are not working at all in JSS@10. Can somebody check this? Seems prefixing by `css-vendor` working fine.

**Comment by kof** [comment]
@AleshaOleg can you create a separate issue with reproduction pls?

**Comment by AleshaOleg** [comment]
@kof https://github.com/cssinjs/jss/issues/1120

**Comment by AleshaOleg** [comment]
@azarual please check this answer - https://github.com/cssinjs/jss/issues/1120#issuecomment-500742090
