### ISSUE TITLE
Clarify array syntax and "!important"

### ISSUE THREAD

**Issue by davidbonnet** [cssinjs/jss#702]
# Motivation
Array syntax description is misleading. In particular, the examples with `!important` are not working as described:

```js
const styles = {
  button: {
    color: ['red', '!important'],
    margin: [[5, 10], '!important']
  }
}
```

Should be (note the second brackets around `'red'`):

```js
const styles = {
  button: {
    color: [['red'], '!important'],
    margin: [[5, 10], '!important']
  }
}
```

# Tasks
- [ ] Update link to array notation
- [ ] Update example

**Comment by kof** [comment]
this should work afaik ['red', '!important']

**Comment by damianobarbati** [comment]
@kof but I don't see this working: `border: [1, 'solid', '#f44336', '!important'],`, no important applied to the rule.

**Comment by HenriBeck** [comment]
@damianobarbati what plugins are you using?

**Comment by damianobarbati** [comment]
Just default ones I guess? 
```
"react-jss": "^8.4.0",
```
then in my code:
```
import { jss, ThemeProvider } from 'react-jss';
```

**Comment by HenriBeck** [comment]
Okay, can you then create a codesandbox where the problem exists?
It should work with the `jss` instance that `react-jss` provides.

**Comment by damianobarbati** [comment]
On online jss-playground I see the rule converted well:
```
export default {
    buy: {
        border: [1, 'solid', '#4caf50', '!important'],
    },
    sell: {
        border: [1, 'solid', '#f44336', '!important'],
    },
}
```
==>
```
.buy-0-1-8 {
  border: 1px solid #4caf50 !important;
}
.sell-0-1-9 {
  border: 1px solid #f44336 !important;
}
```

**Comment by damianobarbati** [comment]
@HenriBeck https://codesandbox.io/s/79opl9726 , the link class has no important applied?

**Comment by HenriBeck** [comment]
You will need to use this syntax for `!important`: `[[5, 10], '!important']`

**Comment by damianobarbati** [comment]
OK @HenriBeck thanks, I really hoped that syntax wasn't required!

BTW it's weird: I tried that syntax too in my app before asking about it here since it's not working.
But in the codesanbox it is! (same package.json versions)

I'll investigate further and post here if I find anything useful for reference.

**Comment by kof** [comment]
also you can use `1px solid !important` syntax, you won't get though for e.g. default unit applied
