### ISSUE TITLE
Jss server side render with custom createGenerateClassName 

### ISSUE THREAD

**Issue by up209d** [cssinjs/jss#704]
I used createGenerateClassName on both Client Side and Server Side 
```
const createGenerateClassName = () => {
  let counter = 0;
  return (rule, sheet) => {
    counter++;
    console.log(counter);
    return `custom--${rule.key}-${counter}`
  }
};

Then ...

<JssProvider jss={jss} generateClassName={createGenerateClassName()}>
   ...
</JssProvider>
```
By my expectation, every request ( browser refreshes ) it should log all the counter which were made. That is true by client side but not server side, I got full of the counter log for the very first request then after refreshing browser for following requests, client-side got full log every time meanwhile server-side got no counter log at all. That's so weird as a result, for every route change and after a refresh, I ended up with 

`Warning: Prop `className` did not match...`

I am using:
"react": "^16.2.0",
"react-jss": "8.4.0"
"jss": "9.8.1"

**Comment by kof** [comment]
it can only mean that you are not rerendering your component on the server on each request, I guess you have some sort of caching, but without actually seing the code I am useless.

**Comment by up209d** [comment]
@kof I tried to make the scenario here, not exactly but I can only get the counter log for the very first time of render function, in the following renders counter logging does not appear.

[](https://codesandbox.io/s/1qq6mj7j27)

**Comment by kof** [comment]
Hmm, needs further investigation, I also tried https://codesandbox.io/s/6jmrxkw50r

Seems like something is caching but its not clear what, might be a bug!

**Comment by kof** [comment]
@up209d do you want to dig into it?

**Comment by up209d** [comment]
@kof Yeah, I shall spend time looking into the src code. Since I used react-jss, I am not sure where is the source of that caching, could be inside jss core or react-jss itself. I shall report soon when I figure out the spot.

**Comment by up209d** [comment]
I got it, turn out `react-jss` cache `SheetsRegistry`, and if `SheetsRegistry` is cached, it won't call the new `createGenerateClassName`, instead it will use the cached SheetsRegistry. So in order to assign new `createGenerateClassName` we have to reset `registry` from `JssProvider`

https://codesandbox.io/s/xo6njj5mmq
