### ISSUE TITLE
[jss-default-units] default units for text-shadow

### ISSUE THREAD

**Issue by nicutimofte** [cssinjs/jss#708]
The values from text-shadow don't get a default value. 
The example below is from JSS Playground
![image](https://user-images.githubusercontent.com/18091830/39626521-ef0eefba-4faa-11e8-8d39-cd83a456afe3.png)

But with box-shadow it's working.
![image](https://user-images.githubusercontent.com/18091830/39626584-31f6bcfe-4fab-11e8-906a-f67275fe450e.png)
 
Am I doing something wrong ? 
Thanks!

**Comment by kof** [comment]
Looks like a bug either in jss-default-unit or in jss-expand

**Comment by HenriBeck** [comment]
This bug will be fixed in jss v10.
