### ISSUE TITLE
border-width array syntax is incorrect

### ISSUE THREAD

**Issue by helios1138** [cssinjs/jss#709]
```js
borderWidth: [1, 0, 1, 1]
```
results in
```css
border-width: 1px,0,1px,1px;
```
instead of
```css
border-width: 1px 0 1px 1px;
```

**Comment by kof** [comment]
yeah, core JSS syntax for this would be [[1, 0, 1, 1]], jss-expand doesn't know about this one. Wanna send an enhancement PR ? https://github.com/cssinjs/jss-expand/blob/master/src/props.js#L14

**Comment by helios1138** [comment]
@kof https://github.com/cssinjs/jss-expand/pull/29

**Comment by kof** [comment]
published
