### ISSUE TITLE
Mono Repo and NPM org

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#714]
I would like to propose to move the whole Jss project into a [Lerna](https://github.com/lerna/lerna) mono repo like babel and other projects did. I would also then move to a fixed mode for the versioning (like babel). This would also solve some problems with maintaining all of the dev dependencies of the repositories.

This would include the following repositories:
- jss
- react-jss, styled-jss and aphrodite-jss
- all of the currently provided plugins by Jss

Another idea would be to create npm organization and publish most packages under this organization.
 - jss -> `@jss/core`
 - react-jss (integrations) -> `@jss/react`
 - jss-expand (plugins): `@jss/plugin-expand`

**Comment by oliviertassinari** [comment]
I can only approve the idea 👍

**Comment by TrySound** [comment]
And this will solve the problem of reusing builder.

**Comment by kof** [comment]
I would need someone to commit finishing this migration, who can?

**Comment by TrySound** [comment]
So do we go with proposed jss scope?

**Comment by HenriBeck** [comment]
I would also include the provided integrations from the jss team in the monorepo. That way we could easily share code between them as well (Updating styled-jss to use the same JssProvider for example).

I could migrate it, but I won't have time before next week.

**Comment by kof** [comment]
After next week is fine, just need to be sure we can finish it and not leave it in half migrated state for months.

The reason I am not sure I would put them all into monorepo is because they have partially different setup, separate issue trackers and it feels like they are entirely separate projects. 

We need a clear decision framework on how to decide.

One possibility: everything that depends on JSS core, should be part of the monorepo, everything else - not.

**Comment by kof** [comment]
Ok, we got merged the first pr towards monorepo, now we need to move plugins to it

**Comment by kof** [comment]
@HenriBeck are you up for this?

**Comment by HenriBeck** [comment]
All of the plugin repos are now imported. Any other repos that should be imported?

**Comment by kof** [comment]
I checked, all plugins are here, is there anything else that is topping us from jss 10 release?

**Comment by HenriBeck** [comment]
I think we should need to archive the plugin repos and add a message to the readme.

**Comment by kof** [comment]
yes, immediately after release

**Comment by kof** [comment]
oh btw. we should check all the docs and fix the links to old repos

**Comment by HenriBeck** [comment]
Yeah, we need to update the links in the package.json files

**Comment by kof** [comment]
also mb add docs regarding esm builds? and generaly whats in the dist?

**Comment by kof** [comment]
Btw. the site was getting the docs for plugins for each repo, we could fix the site to the new repos as an intermediate step or we could move all markdown files from each plugin repo to the main docs dir

**Comment by kof** [comment]
Also I am wondering if babel plugin should be part of this release or a separate, it a minor version number in any case, but mb it should be one big announcement

**Comment by kof** [comment]
@HenriBeck are you on twitter? (if you want to be mentioned in the announcement)

**Comment by TrySound** [comment]
A have a couple of improvements before release.

**Comment by HenriBeck** [comment]
Is the babel plugin ready? I think we should test it to actually be ready when publishing.

We should also write a migration guide.

I'm on twitter but nonactive.

**Comment by kof** [comment]
babel plugin its def. not ready yet, yeah we should actually take more time for testing …

migration guide for babel plugin? Docs on my todo list, evtl even an article. But migration guide is not needed.

Unless you mean because of packages and esm. What are the points user should know?

**Comment by HenriBeck** [comment]
Yes, I don't mean a migration guide for the babel plugin. It's mostly about the package names.

**Comment by kof** [comment]
I think package names is too trivial to write a migration guide, a few more notes in the changelog should be enough.

**Comment by HenriBeck** [comment]
Okay, do we continue to use the changelog in the different packages or are we going to have one global changelog

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Good question, looking into babel its a single root changelog. I think it makes sense with monorepo and probably akes it easier for the user

**Comment by HenriBeck** [comment]
Do we delete the old changelogs then?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HenriBeck** [comment]
Or we just remove them without merging? They still exist in the old plugin repos.

**Comment by kof** [comment]
I think everything that lands in monorepo, yes

**Comment by kof** [comment]
There are tools for moving issues, we can automate it

**Comment by kof** [comment]
I used zenhub before, but this seems fine as well … whatever works.
