### ISSUE TITLE
Function values are not called inside jss-expand block

### ISSUE THREAD

**Issue by petrkrulis** [cssinjs/jss#715]
See example https://codesandbox.io/s/53n8rrlw7x. Size property has no effect. Generated css looks like this `font-size: function size(props) { return "120px"; };` There is a same problem when I try to use jss-expand inside a function value. https://codesandbox.io/s/k3n3o98wr3

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/682
