### ISSUE TITLE
Child selectors in function rules

### ISSUE THREAD

**Issue by afrankel-sfdo** [cssinjs/jss#721]
All variants of child selectors in a function rule don't appear to work. Non-function rules work as expected.

```
direct: props => ({
    color: theme.error,
    "& span": {
      color: theme.color
    }
  }),
```

https://codesandbox.io/s/llv18nznnm

![screen shot 2018-04-17 at 8 16 05 am](https://user-images.githubusercontent.com/31106469/38875437-99762546-4217-11e8-9237-3d0830c912c1.png)

**Comment by kof** [comment]
I think it is the same as #706

**Comment by afrankel-sfdo** [comment]
@kof seems reasonable, wasn't sure if `media queries` and `child selectors` are handled differently.

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/682
