### ISSUE TITLE
Flow typings only work for main module exports

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#722]
Because of the change that we only generate an `index.js.flow` type file, which simply exports from the src directory, when people try to import a file from jss directly for example `src/StyleSheet.js` flow doesn't find the types anymore.

I think that bundling every file as a `.js.flow` file makes more sense as the size is not really reduced because we currently need to ship the `src` folder as well.

**Comment by kof** [comment]
Do you have a real use case? Because public api is exported, one shouldn't import specific files. If one does, its a hack and its evtl ok to not have typings for this?

**Comment by HenriBeck** [comment]
Yeah, I'm not using it too use the API of the modules, but the types.

But this works as well:
```js
import type StyleSheet from 'jss/src/StyleSheet';
```
