### ISSUE TITLE
Validation failure: The “type” attribute for the “style” element is not needed and should be omitted

### ISSUE THREAD

**Issue by mikkopori** [cssinjs/jss#724]
Hello,

testing my application with a validator I ran into these warnings:

The “type” attribute for the “style” element is not needed and should be omitted

for example in

<style type="text/css" data-jss="" data-meta="MuiToolbar">
..
</style>

Since I noticed that validation errors were reported here earlier I thought I should report this as well. Did not find any mention of this particular warning.

:)

**Comment by kof** [comment]
didn't know adding optional type attribtute is an antipattern now

**Comment by oliviertassinari** [comment]
You can reproduce the warning on your documentation website with https://validator.w3.org/:
![capture d ecran 2018-06-10 a 13 09 20](https://user-images.githubusercontent.com/3165635/41200975-92db4bfe-6caf-11e8-9879-e5963a5d4446.png)

**Comment by oliviertassinari** [comment]
It should be as simple as removing this line:
https://github.com/cssinjs/jss/blob/602e3257d55849bdcf9831d111b029f383951c02/src/renderers/DomRenderer.js#L309
@mikkopori Do you want to work on it?

**Comment by mikkopori** [comment]
It would be fair since I reported this :)

Never worked on this before, but I guess I'll learn quick. It will take a couple of days before I have time to look into this, so if anyone is faster feel free.

**Comment by kof** [comment]
released 9.8.6
