### ISSUE TITLE
Export with ESM

### ISSUE THREAD

**Issue by brianmhunt** [cssinjs/jss#733]
Following the discussion in #728, I'm just opening this issue for tracking esm support.

Getting JSS support into Knockout proper was proving exceedingly challenging from a build-tool perspective, so we're going to wait on and retry once esm support lands.

I hope this is a useful issue to have open, and doesn't litter the repo issues — but if it does, please feel free to close.

**Comment by kof** [comment]
@brianmhunt feel free to contribute whats needed or you can as well start using it since I assume its all about tree shaking and can be seen as an optimization?

**Comment by kof** [comment]
Also ping me on gitter, I am curious to hear the use case you got.

**Comment by HenriBeck** [comment]
I don't know how much we can tree shake because we are using classes which are not really tree shakeable the last time I checked.

**Comment by TrySound** [comment]
I can handle them. Working on it.

**Comment by kof** [comment]
Yeah in jss core I don't think one can tree shake much.

**Comment by HenriBeck** [comment]
Implemented. Will be released with jss v10
