### ISSUE TITLE
Resolve global to window

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#736]
Webpack has this built in, we broke it during migration to rollup. Should we use https://www.npmjs.com/package/rollup-plugin-node-globals ?

Originates in #735

**Comment by TrySound** [comment]
I would use this explicitly
https://github.com/calvinmetcalf/rollup-plugin-node-globals/blob/master/src/global.js

**Comment by kof** [comment]
wanna add it?

**Comment by TrySound** [comment]
Sure

**Comment by kof** [comment]
released 9.8.7
