### ISSUE TITLE
Documentation - clarify where `link: true` goes

### ISSUE THREAD

**Issue by brianmhunt** [cssinjs/jss#738]
The JSS docs on observables mentions that one needs to use `link: true`, but does not mention where.

For example, given:

```js
    this.styles = jss.createStyleSheet(this.css).attach()
```

It's not clear which of the following is correct:

```js
    this.styles = jss.createStyleSheet(this.css, {link: true}).attach()
    this.styles = jss.createStyleSheet(this.css).attach({link: true})
```

Seems like it's neither; rather, if you trace `.attach`, it looks like it uses `this.options.link`, but the expected `jss.options` is undefined.

All to say, there's a gap that needs to be filled about where `link: true` goes.

**Comment by HenriBeck** [comment]
[Here](https://github.com/cssinjs/jss/blob/master/docs/json-api.md#observable-values) it says that observables need the Sheet option `link: true`.

Also the options for a Sheet a declared here: https://github.com/cssinjs/jss/blob/master/docs/js-api.md#create-style-sheet

**Comment by brianmhunt** [comment]
Thanks @HenriBeck ; the ambiguity is whether the `Sheet` option is on the attach or the create call.

**Comment by kof** [comment]
I don't get it, how did you come to think .attach() accepts an options argument? Please send a PR where you think its not clear.

**Comment by brianmhunt** [comment]
@kof Trivial fix that would've saved 10-15 minutes of wandering around the docs is #739

**Comment by kof** [comment]
yeah, I guess docs will never be perfect, thats one every one needs to send fixes like this one :)
