### ISSUE TITLE
[jss-nested] How to select components for jest testing

### ISSUE THREAD

**Issue by serendipity1004** [cssinjs/jss#743]
I am currently using jest and shallow to test my create-react-app that uses Material UI design library.

I would like to do something like

```
describe('BaseButton', () => {
  describe('when user clicks button', () => {
    it ('calls correct function to save the information', () => {
      const onButtonClickMock = jest.fn();
      const wrapper = shallow(
        <BaseButton
          onButtonClick={onButtonClickMock}
        />,
      );
      const buttonElement = wrapper.find('.base-button'); // I need to be able to find the element here but JSS nested creates random class name
      buttonElement.simulate('click'); 
      
      expect(onButtonClickMock).toHaveBeenCalledTimes(1);
      expect(onButtonClickMock).toHaveBeenCalledWith(true);
    });
  });
});
```

How do I make a selection of my testing element with randomly generated class name when using jss-nested? Surprisingly there is no one who has asked this question so I am guessing I am missing something.

**Comment by HenriBeck** [comment]
Use something like [jss-compose](http://cssinjs.org/jss-compose?v=v5.0.0)

**Comment by serendipity1004** [comment]
@HenriBeck So you are suggesting that I provide an extra class for every component that I render?

**Comment by kof** [comment]
@serendipity1004 I think this was asked many times, mb in react-jss. You can set your jss instance up generating simpler class names, so that you can access them by name. Also you can use a different attribute for e.g. data-test-id="your test" which is even better, since explicit.
