### ISSUE TITLE
[jss-nested] Camel case $refs not found (looking for kebab case)

### ISSUE THREAD

**Issue by ingermarie** [cssinjs/jss#790]
When trying to reference existing camel case classes with the following:
`styles.addRule('class': ['& > $existingCamelCaseClass']: {...})`
...an error will be thrown:
`Warning: [JSS] Could not find the referenced rule existing-camel-case-class in Styles.`

Rigging for looking up camel case classes would be a welcome feature, worst case an option would suffice. Please comment if any further information regarding environment is required.

Versions:
"jss": "^9.8.7",
"jss-nested": "^6.0.1"

source: http://cssinjs.org/jss-nested?v=v6.0.1#use-rulename-to-reference-a-local-rule-within-the-same-style-sheet

**Comment by HenriBeck** [comment]
Could you please create a codesandbox with the minimal amount of code to reproduce your bug?

**Comment by HenriBeck** [comment]
Maybe check your order of plugins. 

See: http://cssinjs.org/plugins?v=v9.8.7

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ingermarie** [comment]
Looks like it was the order of plugins that caused it (i.e. camel case was used before nested)
Thank you for the swift reply! :)
