### ISSUE TITLE
Combined class names

### ISSUE THREAD

**Issue by psa-gbellencontre** [cssinjs/jss#791]
Hi,
I'm using JSS with React for a few days, and I'm facing a problem with style override.

I have a Header component which contains a Logo component.
Each component has its own styles, but when the logo is in the header, I need to override some of its styles.

I need something like ".header.logo" to override logo when it's in header.

I looked for solutions in the doc, but didn't find anything.

Thank you for your time

**Comment by kof** [comment]
you can pass a class from the parent component to the child component or you can pass a prop and let the child adjust based on props

both works
