### ISSUE TITLE
[react-jss] Dynamic rules are rendered before the static ones

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#798]
_From @doasync on July 5, 2018 0:59_

Check this: https://codesandbox.io/s/3qqjrq77m5

Login button should be red, but it's white.

I guess, the bug occurs when the insertion point is at the end of the head.

_Copied from original issue: cssinjs/react-jss#269_

**Comment by HenriBeck** [comment]
_From @kof on July 5, 2018 2:45_

Bug is 90% in mui.

**Comment by HenriBeck** [comment]
_From @kof on July 5, 2018 2:46_

@oliviertassinari is it possible that mui fails to read the insertionPoint from context somehow?

**Comment by HenriBeck** [comment]
_From @kof on July 5, 2018 2:50_

@doasync same behaviour with regular value, so fn value has nothing to do with it. It is probably that jss from react-jss receives the insertion point and mui doesn't so react-jss renders after it since it doesn't need to sort with the same namespace.

**Comment by HenriBeck** [comment]
_From @oliviertassinari on July 5, 2018 11:44_

I can reproduce the same issue **without** Material-UI: https://codesandbox.io/s/wkky8j6rv8.

![capture d ecran 2018-07-05 a 13 45 59](https://user-images.githubusercontent.com/3165635/42321586-c95dbdf2-8059-11e8-9e18-47a85dde8529.png)

> Bug is 90% in mui.

Next time 😋

**Comment by HenriBeck** [comment]
_From @kof on July 5, 2018 12:57_

@oliviertassinari thanks for reproduction, you are right

It seems like the style sheet with dynamic values doesn't consider the static one when sorting and there is a defined insertion point

**Comment by HenriBeck** [comment]
Could it be that both sheets get the same index, but as the dynamic sheet is created after the static one, it places the element before the other one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HenriBeck** [comment]
Should be fixed in #819

**Comment by eric-burel** [comment]
Hi, I still feel like I am hitting this issue during rehydratation, in the context of an upgrade to Mui v4 to v5 (so styled components and jss coexists), see details there: https://github.com/mui-org/material-ui/issues/24109#issuecomment-919354562

My JSS styles are split into 2 groups: custom are respecting the insertion point, but "standard" Material UI style are not.
