### ISSUE TITLE
[react-jss] Readd forwardRef support

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#800]
_From @kof on June 12, 2018 8:52_

It was removed due to issues with redux-connect and the fact that it needs a major release, see #255 

Now we need to understand how redux-connect and similar can be supported.

_Copied from original issue: cssinjs/react-jss#256_

**Comment by HenriBeck** [comment]
I don't think we can support react-redux in any way, rather we need to wait for react-redux to not check against a function and rather against a valid react element described [here](https://github.com/reduxjs/react-redux/issues/914#issuecomment-377406014)

**Comment by HenriBeck** [comment]
_From @kof on June 12, 2018 9:6_

Yeah, but how can we release react-jss with forwardRef support without making it incompatible with so  many react-redux versions?

**Comment by HenriBeck** [comment]
I don't think we can.

**Comment by HenriBeck** [comment]
_From @kof on June 12, 2018 10:13_

Lets release this change in a major version as soon as https://github.com/reduxjs/react-redux/issues/914 is fixed

**Comment by acatcalledfrank** [comment]
Looks like [react-redux/issues/914](https://github.com/reduxjs/react-redux/issues/914) has been resolved so hopefully that's unblocked this?

**Comment by HenriBeck** [comment]
This was implemented in #943
