### ISSUE TITLE
[react-jss] prepare for react 17 (but maintain backward compat)

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#802]
_From @pradel on April 11, 2018 15:23_

From the react docs: `React version 17 will deprecate several of the class component API lifecycles: componentWillMount, componentWillReceiveProps, and componentWillUpdate.`

Would be great to have this library compatible :)

Can be migrated using https://github.com/reactjs/react-lifecycles-compat

Thanks!

_Copied from original issue: cssinjs/react-jss#231_

**Comment by HenriBeck** [comment]
_From @damianobarbati on June 2, 2018 9:50_

```
    <React.StrictMode>
        <ThemeProvider theme={theme}>
            <Router />
        </ThemeProvider>
    </React.StrictMode>
```

=> 

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in App

componentWillMount: Please update the following components to use componentDidMount instead: Jss(Home), Jss(Layout), Jss(Nav), SideEffect(NullComponent), ThemeProvider

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Jss(Home), Jss(Layout), Jss(Nav), ThemeProvider

componentWillUpdate: Please update the following components to use componentDidUpdate instead: Jss(Home), Jss(Layout), Jss(Nav)

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by HenriBeck** [comment]
_From @RusinovAnton on July 5, 2018 11:4_

Hey, I would like to help with this one. I need some heads up, is it correct that using following element for tests should cover all possible components with lifecycles?

```
<React.StrictMode>
  <ThemeProvider theme={theme}>
    <div />
  </ThemeProvider>
</React.StrictMode>
```

**Comment by HenriBeck** [comment]
_From @kof on July 5, 2018 11:8_

also JssProvider and the biggest one injectSheet() HOC creator

**Comment by damianobarbati** [comment]
Hey @HenriBeck do you need with this?

**Comment by HenriBeck** [comment]
I assume you are asking if I/we need help with this and yes, feel free to create a PR.

**Comment by felixputera** [comment]
Hi @HenriBeck,

I was looking into this matter and noticed that `react-jss` is also using the legacy context API which is also called in `componentWillReceiveProps`:
```js
    componentWillReceiveProps(nextProps: OuterPropsType, nextContext: Context) {
      this.context = nextContext
      const {dynamicSheet} = this.state
      if (dynamicSheet) dynamicSheet.update(nextProps)
    }
``` 
From the [context docs](https://reactjs.org/docs/context.html), it seems that legacy context will be deprecated too. If we need to support React 17, I think we might need a bigger refactor.

**Comment by HenriBeck** [comment]
The switch from the old lifecycle hooks doesn't require a breaking change because there is a polyfill for React 0.14.9 [here](https://github.com/reactjs/react-lifecycles-compat). 

The context switch is going to be quite more significant so let's to it afterwards in a separate PR.

**Comment by kof** [comment]
Subscribe #795 for updates about release date.

**Comment by canastro** [comment]
I'm trying to use React.forwardRef to get a ref to my jss component and when I use StrictMode I get the following warning:

```js
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DashdashEditor which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

    in div
    in MyJSSComponent
    in WithStyles(MyJSSComponent)
    in JssContextSubscriber (at my-external-component.tsx:95)
    in MyExternalComponent (at src/index.tsx:40)
```


On MyExternalComponent:
```js
class MyExternalComponent {
    containerRef = createRef();

    render() {
        return <MyJSSComponent ref={this.containerRef}>Hello</MyJSSComponent>
    }
}
```

on MyJSSComponent:
```js
const MyJSSComponent = React.forwardRef<Ref, Props>(({ classes, children }, ref) => (
  <div className={classes.root} ref={ref}>
    {children}
  </div>
));
```


PS: I know this issue is closed, but I would like to get feedback if this is a known issue before opening a new one.

**Comment by HenriBeck** [comment]
Please provide the version of `react-jss` you are on. But we haven't used `findDOMNode` in `react-jss` as far as I know.

Also, you aren't even using the `injectSheet` HOC from your posted code.

**Comment by canastro** [comment]
@HenriBeck 
Sorry forgot to add the export line where I inject the sheet. 

I'm using react-jss@10.0.0-alpha.12

**Comment by HenriBeck** [comment]
If you are using the latest alpha, I can promise you that this isn't an issue with `react-jss`

**Comment by canastro** [comment]
@HenriBeck 
You're right. The issue was with MobX observer. 
You can delete the previous comments in order to not cause confusion on others.

Thanks for the super quick answer.
