### ISSUE TITLE
Chuckhash images with JSS

### ISSUE THREAD

**Issue by psa-gbellencontre** [cssinjs/jss#820]
Hi,

I'm working with JSS for a few weeks, and today I'm facing a problem with images. It works well, but I would like to chunkhash images in production (mypicture-67e54fghg4.jpg) with webpack.

And it seems webpack file-loader does not recognize any images when I import them in JSS (with backgroundImage).

Maybe it's normal, but is there a workaround ?

Thanks for your time

**Comment by kof** [comment]
JSS is not responsible for this, feel free to write a function that does it for you or use something existing.
