### ISSUE TITLE
Are JSS#options part of the public API?

### ISSUE THREAD

**Issue by eps1lon** [cssinjs/jss#828]
Neither feature nor bug report. More a question for the maintainers considering the public API.

Currently `Jss#options` is not documented in the API docs and the typing (`InternalJSSOptions`) also indicates that these should not be used. However `react-jss` currently requires `options.createGenerateClassName` to be visible.

I'm currently working on ts definitions for `react-jss` and would like to know if this requires a change to the definitions for`jss` as well.

**Comment by kof** [comment]
Jss constructor is a private API, it is used by createStyleSheet and those options are public

**Comment by kof** [comment]
Same like StyleSheet is private, but createStyleSheet is public

**Comment by kof** [comment]
Yes

**Comment by HenriBeck** [comment]
Why would you need to access those? 

We are now exporting atleast some of the flow types from jss to be used by plugins and Integrations.

In the case of the Jss class:
We are exporting only the type of the class and the Options for the constructor

**Comment by eps1lon** [comment]
So why does `react-jss` depend on those private variables? I realize that this sounds purely academic since `react-jss` is tightly coupled with `jss` on purpose ~~but it kind of blocks typescript definitions over at DefinitelyTyped.~~ Or I just require `typeof Jss` to communicate the tight coupling between those two. Sorry about the unrelated ramble 😄 Appreciate your help.

@HenriBeck I don't. `react-jss` does 
https://github.com/cssinjs/react-jss/blob/06044cbf8e7596c30f03573605567f42fa1b0763/src/propTypes.js#L5
https://github.com/cssinjs/react-jss/blob/06044cbf8e7596c30f03573605567f42fa1b0763/src/JssProvider.js#L58

**Comment by HenriBeck** [comment]
Ohhh, I see what you mean. 

Yes, react-jss is obviously tightly coupled to jss itself.

You shouldn’t need those things for only the ts types though.

**Comment by kof** [comment]
I think we could avoid using jss.options there as well.

**Comment by eps1lon** [comment]
As far as I'm concerned this is resolved. Going to close this. Thank you for your time @kof  and @HenriBeck :+1:
