### ISSUE TITLE
[jss-template] plugin is built as 'jssNested' library

### ISSUE THREAD

**Issue by G-Rath** [cssinjs/jss#829]
I was adding `jss-*` plugins to my `webpack.cdn.js` (webpack config that uses `WebpackCdnPlugin`, and is just merged into other webpack configs), when I noticed that both `jss-template` & `jss-nested` export themselves globally as `jssNested`.

It seems that `jss-template` is [configured to output as `jssNested`](https://github.com/cssinjs/jss-template/blob/master/webpack.config.js#L21).

I'm guessing that's not intentional, as I can't find a documented reason (or otherwise that might tie `jss-template` & `jss-nested` together).

**Comment by kof** [comment]
Its a bug

**Comment by HenriBeck** [comment]
This will be fixed once jss@10 is released. @kof should we release a fix for the old versions?

**Comment by kof** [comment]
yeah

**Comment by HenriBeck** [comment]
Closing as this was fixed.
