### ISSUE TITLE
Generating and applying reusable single purpose classes rather than unique id classnames

### ISSUE THREAD

**Issue by ComLock** [cssinjs/jss#830]
__Is your feature request related to a problem?__ No, rather an idea.

__Describe the solution you'd like__
So you may have heard about css tachyons, which is basically single purpose utility classes.
Now remembering such tachyon names while programming is not what you want to do.

So while implementing my own html rendering library, I started generating such single purpose classes from style object in js. It also supports media queries. (I did not know about CSS-in-JS at the time). My code for generating css and classnames is spaghetti code :) So I was thinking what if a jss plugin could be written that did a better job than my code.

Example:

```js
{
    display: 'flex'
}
```

Becomes:

```css
.d-f{display:flex}
```

This means that any element that uses flex will simply have the class "d-f".
The size of css becomes minimalistic, while the number of classes per element grows a bit ;)

There are more advanced examples here:
- https://www.npmjs.com/package/render-js
- https://github.com/ComLock/render-js

Perhaps there is some other framework (that I could not find) plugged into react that already does this? It would be nice to not be limited to React and do SSR.

Perhaps even compile time (though thats not to applicable for dynamic components where styling changes depending upon props).

__Are you willing to implement it?__ Yes, but can I :)

**Comment by HenriBeck** [comment]
You could do that by just providing a custom `createGenerateClassName`.

Docs: http://cssinjs.org/js-api?v=v9.8.7#generate-your-own-class-names

Quick question:
Why don't you generate those styles and simply export the classes object?

`styles.js`
```js
const stylesheet = jss.createStyleSheet({
  dF: { display: flex },
});

stylesheet.attach();

export default stylesheet.classes;
```

`index.js`
```js
import classes from './styles';

// Use classes like classes.dF
```

You could even strictly type the classes actually.

```js
const styles = { dF: { display: 'flex' } };
const stylesheet = jss.createStyleSheet(styles);

stylesheet.attach();

const classes: {| [key: $Keys<typeof styles>]: string |} = stylesheet.classes;

export default classes;
```

**Comment by kof** [comment]
I think you are talking about atomic css. I think you could achieve that with a plugin. The question is why? Usually with this model people try to reduce css payload. Also it allows a different caching strategy. At the same time it brings a bunch of problems.

**Comment by ComLock** [comment]
@kof I guess its similar to atomic css, but I certainly do not like writing classnames for styling, I write style objects in js and generate css and classnames from it. No unused classes and low specificity is the result.

@HenriBeck Its the other way around. The stylesheet is generated from component style, not component style from predefined stylesheet. The developer never writes df, and should not care much about what the final classname becomes. The developer should also not need to think about vendor/browser prefixing.  In case of conflicting frameworks I guess supporting prefixing could be a good idea.

**Comment by ComLock** [comment]
@kof "At the same time it brings a bunch of problems." Any writeup of this. Very interested in knowing what those are.

**Comment by kof** [comment]
Yes, its atomic rendering, but user doesn't have to care about it. I was hesitating adding this plugin, because of the debugging problems it would bring. It needs at the same time some linting tools.

**Comment by ComLock** [comment]
@kof In terms of caching you are correct. Since the css is so small I typically inline it. So there are fewer requests. Reduces time to first paint on first visit, but doesn't affect future request too much.

**Comment by ComLock** [comment]
@kof Since everything is generated the arguments here are not so hard hitting: https://medium.com/simple-human/the-problem-with-atomic-css-d0c09c7aa38e

**Comment by ComLock** [comment]
@kof "I was hesitating adding this plugin"

Which plugin? render-js is not a jss plugin. So you probably meant something else.

**Comment by kof** [comment]
I ment a plugin to jss that would do this, I can write a bunch of things that are going to be a problem, but I will invest into this discussion only if someone is going to do it.

**Comment by trusktr** [comment]
> There is also glamor like interface on top of JSS

Ah, cool!

Another idea: maybe `jss` itself could be a function?

```js
const div = <div {...jss(red, active && bold, df)} />
```

**Comment by kof** [comment]
Whats the problem with using a separate package like glamor-jss?

**Comment by kof** [comment]
I see JSS core as a lower level interface, it does not need sugar APIs, it needs correctness, customizability and performance. Everything else can be built on top.

**Comment by trusktr** [comment]
> Whats the problem with using a separate package like glamor-jss?

Nothing at all. But it's easier to import 1 package than 2, especially if if we don't know about the second package, _then people will like JSS more out of the box_.

> I see JSS core as a lower level interface

Could be true, but honestly I never saw it that way. From the beginning I thought, "cool, a lib that let's me do clash-free CSS in JS easily with `jss.createStyleSheet`! instead of "cool, I'm going to make another CSS lib on top of this".

I'd prefer to just have some bonus features in the lib I was already using.

**Comment by kof** [comment]
It has evolved, there are many different interfaces now which use the core. Not knowing something can be fixed with better documentation and landing page. You can as well help here.

**Comment by trusktr** [comment]
True, could be as simple as adding glamor-jss to the "Abstractions on top of JSS" section

**Comment by kof** [comment]
Its there since it exists. Also added on the first readme but not published to cssinjs.org because we are in migration to monorepo.

**Comment by trusktr** [comment]
Oh okay, I see in Projects page. But where do we edit the menu for cssinjs.org to add it to the main menu? Or do you want only `cssinjs` org projects there?

**Comment by kof** [comment]
I think we can close this issue since it is not really actionable. The idea of rendering to atomic css is not new and if someone finds time I am happy to restart this discussion.
