### ISSUE TITLE
Is it possible to prefix all stylesheet rules with a custom selector or an id?

### ISSUE THREAD

**Issue by SamiEklund** [cssinjs/jss#835]
Hey!

I would like to prefix all my jss stylesheet rules with a custom ID. Stylesheet generated by jss would look something like the code below, instead of just having the ```.jss1``` part.

```css
#my-app .jss1 { }
#my-app .jss2 > img { }
```

**The issue**
Imagine you are implementing a plugin for an existing website containing Wordpress or SharePoint. Your app would probably be rendered inside some existing container in the website. The existing website then might implement some default styles for the container and its html elements like \<img\> or \<input\>. Most likely these styles will be more specific selectors than jss uses, since jss only speicifes one class.

**Example**
CSS insde the existing website
```css
.site-container .site-apps img {
  display: none;
}
```

CSS from my application using jss
```css
.jss1 > img {
  display: block;
}
```

In this case the existing solution would override the jss components styles, rendering all images in my application invisible.

**Comment by kof** [comment]
take a look at this plugin https://www.npmjs.com/package/jss-increase-specificity

**Comment by SamiEklund** [comment]
Thanks for the fast response! I checked it out and I believe it will solve my problem, even though I am bit unsure how the `:not(#\20)` works.
