### ISSUE TITLE
[react-jss] Drop support for react 0.13 and 0.14

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#836]
We currently still support React 13 and 14 as defined in the peer dependencies in the package.json. I think we can drop those versions without any significant problems.

I think we should hold off on dropping React 15 because most other react libaries still support it.

**Comment by kof** [comment]
What is the benefit of dropping it? We migrated away from componentWillReceiveProps already.

**Comment by HenriBeck** [comment]
We need to drop those versions (at least 13) for using the create context polyfill.

**Comment by HenriBeck** [comment]
Implemented in #851
