### ISSUE TITLE
Automatically generate final class names from nested class names, like CSS modules.

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#840]
__Is your feature request related to a problem? Please describe.__

Based on the docs, if we currently have this:

```js
const styles = {
  div: {
    '& .warn': {
      color: 'red',
    }
  },
}
```

the `.warn` class will not be scoped, left as-is. The output is like:

```css
.div-123876 .warn {
  color: red;
}
```

CSS modules by default generates random output classes for all nested classes, so CSS modules output is like

```css
.div-123876 .warn-634534 {
  color: red;
}
```

and the object returned from the module is like:

```js
import css from './foo.css'
console.log(css)
// {
//   div: 'div-123876',
//   warn: 'warn-634534',
// }
```

then we place all those classes in our markup.

__Describe the solution you'd like__

To accomplish this in JSS currently, we have to write it like this:

```js
const styles = {
  div: {
    '& $warn': {
      color: 'red',
    }
  },
  warn: {}
}
```

and then we get clash-free class names like we do with CSS modules.

It would be great if we didn't have to manually write all the classes at the top level, for a JSS plugin to automatically grab nested class names and generate the clash-free ones.

**Comment by trusktr** [comment]
The problem with the current is it is tedious to write many classes at the top level, and convert them to use `$` syntax.

If we don't use `$` syntax, then it is possible that the style from an outer component will clash with the style from an inner component.

**Comment by HenriBeck** [comment]
Why do you need to use the `jss-nested` syntax for that?

Just use:
```js
const styles = {
  div: {},
  warn: { color: 'red', }
}
```

Using the nested syntax should only be done in rare cases as it introduces some problems again which `jss` tries to solve, namely avoiding slow selectors.

**Comment by HenriBeck** [comment]
Then you will need to write top-level classes and use `$`

**Comment by kof** [comment]
Its an API design challenge. css-modules converts .className implicitly to scoped names, basically using the user defined name as a prefix. In JSS we always tried to be explicit. Namespaces are object keys.

This is not an easy thing to solve, since it would require a full selector parser, which would add complexity.

**Comment by kof** [comment]
Now the question is if we even want to keep this issue as a feature request or close it. 

Another question to @trusktr have you understood from the docs that the selector you are writing in nested way is getting scoped? If not can you please send us a PR to improve documentation where it is required?

**Comment by kof** [comment]
One idea could be to add a rule automatically if `& $warn` is used but such a rule is not defined.

**Comment by HenriBeck** [comment]
I wouldn't create rules automatically for that because it could also be a typo and users should only reference which actually exist.

**Comment by kof** [comment]
Yeah, we would loose the ability to warn about an unknown referenced rule, since it would be allowed to have one. Its the trade off in this case.

**Comment by kof** [comment]
I am not sure this case is worth fixing, we don't get this request often, I can't even recall one. I think we should rethink it once we get it more frequently.

**Comment by trusktr** [comment]
> This is not an easy thing to solve, since it would require a full selector parser, which would add complexity.

A simpler approach could be to just scope class names. Then for other selectors just prefix them with the scoped class name. This wouldn't require a full selector parser I don't think.

> have you understood from the docs that the selector you are writing in nested way is getting scoped?

I understand that

```js
const style = {
  foo: { '.bar': { color: 'red' } }
}
```

results in

```css
.foo-0-1-234 .bar { color: red }
```

but this still penetrates into child components that have any `.bar`s in them.

> One idea could be to add a rule automatically if & $warn is used but such a rule is not defined.

Aha! good idea!

Adding onto that idea: maybe an option like `jss.createStyleSheet({ ... }, { scopeNested: true })` could be used by the `jss-nested` to convert `& .warn` into (or treat the same as) `& $warn` and to also place the top-level empty objects if they don't exist.

**Comment by trusktr** [comment]
> I wouldn't create rules automatically for that because it could also be a typo and users should only reference which actually exist.

Maybe the `$foo` syntax would work as-is when `scopeNested: false`.

**Comment by trusktr** [comment]
Coming from using both CSS modules or Vue on different projects, I'm accustomed to all class names being scoped.

Here's a live Vue example: https://codesandbox.io/s/9q3pw1mpny

Inspect the red element, and you'll see the generated stylesheet uses `.foo[data-v-7ba5bd90]` for scoping.

**Comment by HenriBeck** [comment]
I think the option should be instead added to the `jss-nested` plugin as an option if we decide to implement it.

I would generally advise against it because I think it's an anti-pattern to use jss-nested like that. For me, `jss-nested` should only be used for pseudo-classes or nested at-rules if necessary.

**Comment by kof** [comment]
I was even thinking to create a separate jss-plugin-pseudo to not use for this case jss-nested. It opens some doors with isolation.

@trusktr for what vue does, preprocessing is required, because one needs a full css parser. Its an entirely different approach with its own downsides.

**Comment by trusktr** [comment]
Vue take the last selector in a combined selector, and just prepends the attribute to it, f.e. `.class .foo #header` becomes `.class .foo [data-vue=6512345]#header`.

It works with all sorts of selectors, so yeah, it's be complex.

Maybe we can do something simpler, like just convert all class names (identifier with a `.` like `.foo`), and leave other stuff as-is, which I don't think would require a CSS selector parser. In the docs, it would say that if you want scoping, you have to use classes, otherwise it doesn't scope (similar to `$foo` syntax).

As a start though, I'd be happy just `$foo` syntax and auto-creating the top-level objects.

**Comment by trusktr** [comment]
> As a start though, I'd be happy with just $foo syntax and auto-creating the top-level objects.

In fact, just that would be perfect enough for me!

At the moment, I have top-level lists like this in my styles:

```js
    section: {},
    hero: {},
    heroBackground: {},
    heroCaption: {},
    what: {},
    what2: {},
    news: {},
    useCases: {},
    iconContainer: {},
    icon: {},
    left: {},
    right: {},
    case: {},
    text: {},
    iconWrapper: {},
    newsBackground: {},
    newsArticle: {},
    date: {},
    content: {},
    logo: {},
    slider: {},
    slide: {},
    slideContent: {},
    sliderContainer: {},
    sliderWrapper: {},
    slideControls: {},
    arrow: {},
```

and every once in a while I forget to update it when I'm writing nested styles, and it is a then a hassle to have to scroll far away to update the list.

**Comment by HenriBeck** [comment]
I'm against this feature as this makes it 'easier' to write nested styles which is one of the things about css jss tries to solve.

Your problem only comes up when moving from css to jss. I think we can find a better way of doing it, maybe a converter which can 'unwrap' nested css styles.

**Comment by kof** [comment]
Yeah, I am undecided on this. I see both points. And yes, ideally nesting is used in really rare cases. In the most cases it can be in a better way.

**Comment by HenriBeck** [comment]
I think this problem only comes up when migrating from css or something like sass and simply just reformating the styles.

**Comment by trusktr** [comment]
> which is one of the things about css jss tries to solve.
> Your problem only comes up when moving from css to jss.

> ideally nesting is used in really rare cases

> I think this problem only comes up when migrating from css or something like sass

Personally I never nested in CSS, but I nested in Sass/Less/Stylus, which seemed an advantage to me, so I kept doing it in JSS.


I'm definitely interested to learn about alternative patterns I should use instead of nesting. 👍

**Comment by kof** [comment]
2 patterns will help:
1. Small components, dedicated for specific task.
2. No nesting, call the rule whatever you want, in a small component this won't be a problem and you won't need nesting mostly
