### ISSUE TITLE
Serverside rendering in Next.js, class names don't match on server vs client hydration

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#841]
I'm having this problem when using SSR in Next.js: https://github.com/zeit/next.js/issues/5106

Any thoughts on how to solve it?

**Comment by trusktr** [comment]
I guess solving https://github.com/cssinjs/jss/issues/457 would also solve this one.

**Comment by HenriBeck** [comment]
See: http://cssinjs.org/react-jss?v=v8.6.1#server-side-rendering

Also using `jss.createStyleSheet` will not work with React server-side rendering as it uses a different `generateClassName` which results in a different counter and the sheet will also not be added to the sheets registry and there not send with the initial HTML.

**Comment by trusktr** [comment]
Thanks! Got it working. Yep, had to move all styles to React components. So I put global styles on the root App component; that seems a good place for it.
