### ISSUE TITLE
How to make Jss use a specific registry?

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#842]
I thinking to make a sheet, then add it to the registry that I will then pass to `<JssProvider>`, so that I can make a sheet outside of a React component and have it hooked in.

Basically, I'm trying to avoid having mismatched class names on server and client.

Would `sheets.add(jss.createStyleSheet(...))` do the trick?

**Comment by kof** [comment]
registry is used as a place were all sheets are registered, it provides toString ... please try to read the code.

**Comment by trusktr** [comment]
Doesn't seem to work when I try it with react-jss in Next:

```js
  static getInitialProps({ renderPage }) {
    const sheets = new SheetsRegistry();

    sheets.add(jss.createStyleSheet(getGlobalStyles())) // HERE

    const decoratePage: HOC = Page => props => (
      <JssProvider registry={sheets}>
        <Page {...props} />
      </JssProvider>
    );

    const renderedPage = renderPage(decoratePage);

    const styles = (
      <style type="text/css" data-meta="jss-ssr" dangerouslySetInnerHTML={{ __html: sheets.toString() }} />
    );

    return { ...renderedPage, styles };
  }
```

Seems the styles don't appear in the page.

> please try to read the code.

I don't like resorting to reading code; i hope for docs! 😄

**Comment by kof** [comment]
your code looks like it should work, you can create a simplified codesandbox example
