### ISSUE TITLE
TypeStyle on JSS

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#850]
@kof @HenriBeck Do you think we can convince @basarat to switch from free-style to JSS under the hood in TypeStyle? https://github.com/typestyle/typestyle/issues/288

**Comment by HenriBeck** [comment]
Probably not, because we currently don't have any Typescript types.

If they decide to use `jss`, they can add either typings here or in DefinitelyTyped if they want to.

**Comment by trusktr** [comment]
> because we currently don't have any Typescript types.

That's true, but the TypeStyle layer doesn't have to care about that, the end users of TypeStyle would have a typed interface, regardless of what TypeStyle is built on.
