### ISSUE TITLE
[jss-compose] Unable to use JSS-Compose in Media Queries

### ISSUE THREAD

**Issue by kintendo** [cssinjs/jss#859]
__Expected behavior:__
I'm currently trying to use jss-compose in a media query. The expectation is that when the media query selector is triggered, the `button` class composes `btn-secondary` instead of `btn`
```javascript
const styles = {
  button: {
    composes: 'btn'
  },
  '@media (min-width: 1024px)': {
    button: {
      composes: 'btn-secondary'
    }
  }
}
```

__Describe the bug:__
When I try the example above, I am currently getting an error thrown. Cannot read `myClass` of undefined.

__Codesandbox link:__ 
https://codesandbox.io/s/9yz3ojqx4p

__Versions (please complete the following information):__
 - jss-compose: 5.0.0
 - jss: 9.7.0
 - Chrome
 - macOS

**Comment by HenriBeck** [comment]
`compose` isn't supported inside media queries right now. I'm assuming you only want that class to be applied when the media query matches. 

The reason behind that is we would need to change the mapping between the `src` classes to the actual `css` classes and not make changes to `css`. This user would need to be alerted of that change then. This merely is currently not possible, and I don't know if it will be.

**Comment by kof** [comment]
I didn't realize yesterday we can't actually do that without using matchQueries in js. I think this is currently out of scope of the project. We can reopen once there are more use cases.
