### ISSUE TITLE
Update @font-face typings

### ISSUE THREAD

**Issue by lkostrowski** [cssinjs/jss#861]
Since #199 JSS supports multiple font-face rules like this: 

```
const typographySheet = jss.createStyleSheet(
    {
        '@font-face': [
            {
                'font-family': 'Poppins',
                src: 'url("/fonts/poppins-light-webfont.woff2") format("woff2")',
                'font-weight': '300',
            },
            {
                'font-family': 'Poppins',
                src: 'url("/fonts/poppins-medium-webfont.woff2") format("woff2")',
                'font-weight': '500',
            },
        ],
    }
);

```

which is great but typings force me to use `as any` in two cases:
1: Single font-face - `src` key is not valid style key
2: Multiple font faces (example above) - throws typescript type warning

__Expected behavior:__
Types will be up to date

__Describe the bug:__
Type errors are thrown

__Versions (please complete the following information):__
 - jss: 9.8.7
 - Browser [e.g. chrome, safari]: chrome 69
 - OS [e.g. Windows, macOS]: Mac OS
- Typescript 3.0.3

**Comment by HenriBeck** [comment]
Which TS typings are you using?

We currently do not have TS typings in this repo, so the issue should most likely go to repo from which the types are from.

Website: http://henribeck.now.sh
Adresse: Stiefmütterchenweg 14, 22607 Hamburg
Tel: 0151 70118484
E-Mail: henribeck.dev@gmail.com

**Comment by lkostrowski** [comment]
you are right, @types were installed with Material UI and I made wrong assumption

**Comment by mnemanja** [comment]
@lkostrowski could you please point me to the other open issue, please?
