### ISSUE TITLE
[jss-default-unit] transition-delay requires a unit even for a zero value

### ISSUE THREAD

**Issue by timsnadden** [cssinjs/jss#863]
I was surprised to see that browsers (tested in chrome, firefox) treat a unitless `0` value for `transition-delay` as invalid. `jss-default-unit` only appends a unit to non-zero numbers leading to `transition-delay` not being set when I specify `transitionDelay: 0`.  
<img width="270" alt="cursor_and_bank_of_new_zealand" src="https://user-images.githubusercontent.com/221541/45936848-34579e80-c00f-11e8-9781-4b53ebf1b060.png">

**Comment by HenriBeck** [comment]
Interestingly the same applies to `animation-delay`.

Is this a big problem? Because if the property is invalid, it will behave the same as it's not applied which means it works the same as `0ms`.

**Comment by timsnadden** [comment]
The reason it came up for us is that we wanted to override an existing
setting on hover and it didn't take effect unless the value was set with a
unit ('0ms')

**Comment by kof** [comment]
The amount of inconsistencies in CSS is crazy.

**Comment by HenriBeck** [comment]
We could just simply add units to `0` as well.

**Comment by kof** [comment]
Not that simple, because some units actually require to be unitless, for e.g. opacity. If we implement #687 we will solve this issue as well.

**Comment by kof** [comment]
We need to maintain 2 lists: unitless and non-px props.  Ideally we should generate them from mdn data like we do for the vendor prefixer.

**Comment by kof** [comment]
tbc in #687

**Comment by HenriBeck** [comment]
We would just need to remove the `value !== 0` from:
https://github.com/cssinjs/jss/blob/master/packages/jss-plugin-syntax-default-unit/src/index.js#L38

**Comment by kof** [comment]
That would convert everything to `'0'`, I would try to keep numeric values as they are where possible.
