### ISSUE TITLE
Bug with "content: ' ';" CSS rule in IE11 

### ISSUE THREAD

**Issue by hamperl-design** [cssinjs/jss#866]
__Description:__
Found a Bug in IE11 with the css rule 'content:'
My rule looks like:
```
'&::before': {
                content : ' ',
                width   : '70px',
                height  : '10px',
                ....
```
Note the space between the Quotes in the content rule. This little space will break the whole App with an Error. Messeage is 

> Error: Unspecified error. 44 stack frames were collapsed. 
If I remove the space it will work fine!

__Versions (please complete the following information):__
 - jss: 9.5.6
 - Browser Internet Explorer 11:
 - OS Windows 7:

**Comment by kof** [comment]
what if you use `content: '" "'` ?

**Comment by kof** [comment]
Basically the thing in single quotes is a value, if you want to use custom text as a value, it needs additional quotes, as it is in actual css.

```
a {
  content: "abc"
}
```
The way JSS renders it is documented, it might seem confusing at first, but once you learn what values contant property accepts in CSS, it will make sense I hope.
