### ISSUE TITLE
Warning about missing insertion point even if it exist already

### ISSUE THREAD

**Issue by rodoabad** [cssinjs/jss#867]
__Expected behavior:__

There should be no warning if there is a custom insertion point (especially when it was inserted already in the correct position)

__Describe the bug:__
A clear and concise description of what happened instead of the expected behavior.

There should be no warning if there is a custom insertion point (especially when it was inserted already in the correct position)

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.

Internal.

__Versions (please complete the following information):__
 - jss:     "jss": "^9.8.7",
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Mac
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
I don't understand what needs to be done here, please reopen once you have a reproduction on codesandbox.
