### ISSUE TITLE
CSS escape issue on IE11

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#870]
__Expected behavior:__
Work on IE11

__Describe the bug:__
Doesn't work on IE11

__Codesandbox link:__ 
https://codesandbox.io/s/kovnpx9pzr

__Versions (please complete the following information):__
 - jss: 9.8.7

__Context__

I think it's a JSS issue because I can make it work with:
```js
var css = '.foo\\/bar-0-0-1 { background-color: red; }';
var head = document.getElementsByTagName('head')[0];
var s = document.createElement('style');
s.setAttribute('type', 'text/css');
s.setAttribute('id', 'cf-style');
if (s.styleSheet) {
// IE
s.styleSheet.cssText = css;
} else {
s.appendChild(document.createTextNode(css));
}
head.appendChild(s);
```

**Comment by kof** [comment]
Do you have the editor link to codesandbox? This one runs the code directly.

**Comment by oliviertassinari** [comment]
Sure https://codesandbox.io/s/kovnpx9pzr

**Comment by oliviertassinari** [comment]
It's good to know.

**Comment by kof** [comment]
Just tried it in alpha.10, seems to work, please reopen if it doesn't https://codesandbox.io/s/ko9x3qxk57
