### ISSUE TITLE
Switch to react-test-renderer for react-jss testing

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/jss#876]
I think we should switch to the plain react-testing-libary for testing react-jss as we don't necessarily need `enzyme` and in `react-testing-libary` we can't assert on react components.

This switch can be made after we move from karma to jest.

**Comment by kof** [comment]
The only important thing to me is that we don't test internals of components, but render output only.

**Comment by HenriBeck** [comment]
Done in #949
