### ISSUE TITLE
`gridGap: number` not appending `px` to css rule

### ISSUE THREAD

**Issue by amwill04** [cssinjs/jss#883]
Expected behavior:
Using `number` on `gridGap` should produce the the `css` rule with `px`
```
style = {
    gridGap: 15
}

// Should render the following:
/*
.style {
    grid-gap: 15px
}
*/

// Actually renders the following:
/*
.style {
    grid-gap: 15
}
*/
```

Describe the bug:
It is not appending the `px` onto the `css` rule meaning that the rule is ignored.

- Chrome 69
- MacOS 10.14
- react-jss 8.4.0

**Comment by kof** [comment]
Default unit doesn't know yet about grid-gap, this can be fixed in https://github.com/cssinjs/jss/issues/687

**Comment by kof** [comment]
as a workaround you can define gridGap: '15px'

**Comment by HenriBeck** [comment]
#885

**Comment by HenriBeck** [comment]
#893
