### ISSUE TITLE
[react-jss] better typings for props passed to the inner component

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#886]
Currently `classes` is defined as optional, because if option `inject` is used, it might not get passed. We need to investigate for a way to type it based on inject prop and make sure user doesn't have to do defensive programming because of that.

`injectSheet(styles, {inject: ['sheet', 'classes', 'theme']})`

Same problem with ts typings.

**Comment by HenriBeck** [comment]
I don't think this is possible, at least with flow, might be doable with typescript though.

Is there a case for not injecting the `classes` prop though?

**Comment by kof** [comment]
Dunno, one could use sheet and not use classes, seemed logically that if I can customize on prop, why not customize all of them. But I see your point, it could be a solution for mainstream, where you always use classes

**Comment by HenriBeck** [comment]
I don't see any point where you would not want to inject the classes. 
And sheet should only be injected when you need to access it which should rarely be.

An option which would make more sense to me is how the classes are merged.

**Comment by HenriBeck** [comment]
Done in #934
