### ISSUE TITLE
[jss-vendor-prefixer] Testing vendor prefixes

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#89]
The difficult part is that we need tests specific to vendors and versions, because there will be different results on different implementations. For e.g. at time of writing "animation: yyy;" test, all browsers needed a prefix, right now most of them support it unprefixed.

**Comment by kof** [comment]
We need to migrate tests there to mocha and co like in the jss repository and also add browserstack, because this really really needs a CI with real browsers.

**Comment by cvle** [comment]
I totally agree.

**Comment by kof** [comment]
I think we need to use something like [this](https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/static/prefixProps.js) to verify the test results.

**Comment by kof** [comment]
migrated the tests

**Comment by cvle** [comment]
> I think we need to use something like this to verify the test results.

Sounds like a good idea!

**Comment by AleshaOleg** [comment]
I think, it can be closed due https://github.com/cssinjs/css-vendor/pull/9. We already have testing of all old major browsers via browserstack with each of property.
