### ISSUE TITLE
[jss-plugin-syntax-global] TypeError: Cannot read property '@global' of undefined

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#899]
__Expected behavior:__

No errors. 

__Describe the bug:__

I can't create a stylesheet with an undefined rule. This can happen in Material-UI where we create CSS directly from the theme. 

__Codesandbox link:__ 

```jsx
import jss from "jss";
import presetDefault from "jss-preset-default";

jss.setup(presetDefault());
const s = jss.createStyleSheet({
  tutu: undefined
});
s.attach();
export default jss;
```

https://codesandbox.io/s/lyz1kryzl9

__Versions (please complete the following information):__
 - jss: 9.8.7

**Comment by kof** [comment]
- [ ] make sure global plugin handles null, undefined, ''

**Comment by sammi** [comment]
I'll have a look at this bug.
