### ISSUE TITLE
[jss-vendor-prefixer] - Prefix gradient

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#90]
- [ ] rewrite values like in gradient

**Comment by AleshaOleg** [comment]
Is there any reason to prefix gradients props like: `linear-gradient`, `repeating-linear-gradient`, `radial-gradient` or `repeating-radial-gradient`. All of them full well supported by all browsers. Link to [caniuse](https://caniuse.com/#search=linear-gradient). For example just Chrome 25 - have 0.01% of global usage:D Or Android browsers have 0.26%. This is a max value for all of browsers which need prefix. Other browsers have 0%. I don't want to prefix all of this values to make this props supported in so old browsers. @kof what you think?

**Comment by AleshaOleg** [comment]
At least nobody didn't came with a request to support this:D

**Comment by AleshaOleg** [comment]
Autoprefixer not support this props (not prefix them), and % of old browsers which need this too small to support this.

**Comment by kof** [comment]
Might be a good addition to https://github.com/cssinjs/css-functions
