### ISSUE TITLE
[Bug] "defaultClassNamePrefix" set to undefined in production

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#901]
_From @VintorezVS on October 23, 2018 6:0_

Custom "classNamePrefix" concatenated with "defaultClassNamePrefix" in production gives "customprefix-undefinedXXX" class names.

```
...
const defaultClassNamePrefix = env === 'production' ? undefined : `${displayName}-`
...
let classNamePrefix = defaultClassNamePrefix
...
if (contextSheetOptions && contextSheetOptions.classNamePrefix) {
    classNamePrefix = contextSheetOptions.classNamePrefix + classNamePrefix
}
...
```

_Copied from original issue: cssinjs/react-jss#304_

**Comment by kof** [comment]
thanks for the report

**Comment by HenriBeck** [comment]
So instead of undefined let's just use an empty string or would this break something as well?

**Comment by kof** [comment]
I think it would be fine, wanna send a PR?

**Comment by HenriBeck** [comment]
This should already be fixed: https://github.com/cssinjs/jss/commit/1e9ba74b12b453d9a9ecdc241ea6f91783d2a239#diff-15944e28391ef80a3f4e34ea8a2193f4R99

**Comment by kof** [comment]
true, @VintorezVS subscribe https://github.com/cssinjs/jss/issues/795 for notifications when v10 will be published

**Comment by airtonix** [comment]
Why is it even undefined in the first place?

**Comment by micaste** [comment]
@airtonix my understanding is that `classNamePrefix` stays in production. What was undefined in PROD and has been replaced by an empty string is `displayName`.
