### ISSUE TITLE
Issue with lineHeight

### ISSUE THREAD

**Issue by 4zuko** [cssinjs/jss#909]
__Expected behavior:__
Output should be:
```css
line-height: 16px;
```

__Describe the bug:__
If number is passed to `lineHeight` attribute instead of string with unit:
```javascript
lineHeight: 16;
```
result output is:
```css
line-height: 16;
``` 

`fontSize` behaves as expected.

__Codesandbox link:__ 
https://codesandbox.io/s/88lw4wrp30

__Versions (please complete the following information):__
 - jss: 9.8.7
 - Browser: All
 - OS: All

**Comment by 4zuko** [comment]
Not the issue. Works as expected. My fault.

**Comment by HenriBeck** [comment]
This isn't a bug, `line-height` can be unitless and there has no default unit.
You can still set your own default unit like described here: https://cssinjs.org/jss-default-unit?v=v8.0.2

**Comment by KevinAsher** [comment]
There is the CSS line-height property that does accept px and a unitless value, in that case this will be an issue.
