### ISSUE TITLE
Replace warning with smaller version

### ISSUE THREAD

**Issue by TrySound** [cssinjs/jss#913]
`warning` package is published as a strong mirror of fbjs thing. Maintainer even do not want to support esm. This requires to transpile more packages from commonjs when bundling app with rollup.

There is a smaller alternative https://github.com/alexreardon/tiny-warning. It doesn't allow passing arguments and interpolation should be used instead. It's distributed as esm and has flow types out of the box.

`react-router` already migrated to it.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L50-L51

**Comment by kof** [comment]
We still do support IE 9 same as react does, IE9 doesn't implement console unless devtools are open and this package has no fallback. So to do this we need to officially deprecate IE9 or add a fallback to tiny-warning.

I am curious if react-router maintainers know it.

**Comment by HenriBeck** [comment]
Do we need to support ie9? IE 9 has 0.13% usage globally

**Comment by HenriBeck** [comment]
I think we could configure our babel setup to transpile for browsers who have a usage bigger than 0.5%

**Comment by kof** [comment]
I personally don't, but I am not sure what the majority does.

**Comment by TrySound** [comment]
Hey, guys. ie9 is dead browser. I think major release is a good reason to stop supporting it.
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by kof** [comment]
That announcement from microsoft just means they don't ship any updates. Developers community will support or not support a browser based on usage statistics and the question is where to make a cut. 

I am happy to drop IE9, not sure regarding 10.

**Comment by TrySound** [comment]
tiny-warning now has IE9 support

**Comment by kof** [comment]
cool, thanks for the heads up

**Comment by kof** [comment]
I wonder how it is generating an error, because the error is thrown inside of a catch block, which does nothing ... I guess I am missing something

**Comment by TrySound** [comment]
Here's the reason of swallowed error. But it's dropped for production, so don't worry.
https://github.com/facebook/react/issues/4216

**Comment by kof** [comment]
> Chrome allows you to break on caught errors. That's why that try/catch is there. So that you can optionally toggle the breakpoint on and off.

That was the thing I missed

**Comment by HenriBeck** [comment]
Let’s migrate then?

**Comment by HenriBeck** [comment]
PR is merged

**Comment by oliviertassinari** [comment]
The tiny wording is misleading 😆

![capture d ecran 2018-12-31 a 19 59 38](https://user-images.githubusercontent.com/3165635/50566163-c40b9800-0d36-11e9-8753-56275b3d7b08.png)

---

![capture d ecran 2018-12-31 a 19 59 44](https://user-images.githubusercontent.com/3165635/50566164-ca9a0f80-0d36-11e9-82a9-7daca07058b7.png)

**Comment by TrySound** [comment]
It's esm and has less code. So yes, it's tiny. The size will be smaller in user bundle.

**Comment by kof** [comment]
I wonder why bundlephobia shows its bigger

**Comment by TrySound** [comment]
Perhaps uglify version used by service is not able to inline process.env.NODE_ENV
https://unpkg.com/tiny-warning@1.0.2/dist/tiny-warning.esm.js

**Comment by oliviertassinari** [comment]
How do you explain the bundle size increase in https://github.com/TrySound/react-router/blob/eb80f6525bf6d802f549dc1d7010cd2d1f636208/packages/react-router-dom/.size-snapshot.json?

**Comment by TrySound** [comment]
@oliviertassinari It was esm bundle. The difference is `tiny-` word or something.

**Comment by TrySound** [comment]
`warning` package is not standard. It's an unmaintained mirror of facebook internals which are not used even in react.

**Comment by TrySound** [comment]
And it's cjs. `warning` package maintainer is not interested in any changes. So tiny-warning is the best here.

**Comment by kof** [comment]
Lol

**Comment by oliviertassinari** [comment]
@kof Using warning & tiny-warning at the same time, doesn't help :).
