### ISSUE TITLE
Save/load stylesheets

### ISSUE THREAD

**Issue by brandondurham** [cssinjs/jss#916]
__Is your feature request related to a problem? Please describe.__
I’m working on a custom type testing tool where you can try out different fonts in the browser. Every time the visitor changes the font that’s loaded in the editor, I create a class with necessary font styles  using JSS. The visitor has the option of saving their layout, but I’m unclear about whether or not saving and loading JSS stylesheets is possible. 

__Describe the solution you'd like__
I would love to be able to save a JSS stylesheet in JSON (or any format, really) with styles intact, then later load that same stylesheet.

__Are you willing to implement it?__
If time permitted, but it would be a few months.

**Comment by brandondurham** [comment]
It isn’t quite that simple. I’m working in a rich text editor that styles some elements using inline styles. There are some elements where I override that and instead save those styles behind a class using JSS, then apply the class to the element. I need to reload _everything_ that was generated in the editor.

A visitor can change all kinds of properties in the editor. For one class they may be setting 12 or more CSS properties, and that’s just for what they have currently selected in the editor. The editor is kind of like a word processor in the browser, with many different custom controls for changing the text visually. There is no limit to the number of things they can set on any given selected text., and I need to be able to reload those in the state the left it when they revisit.

**Comment by HenriBeck** [comment]
Okay, then just save the styles the user has applied?

**Comment by HenriBeck** [comment]
Why can't you then not merely store the styles and some another reference? Seems to me that creating stylesheets with already defined styles and classes will create at least some problems.

**Comment by brandondurham** [comment]
These styles are created by actions in a rich text editor (Draft.js). For instance:

- the user selects some text in the text editor, then hits the “ligatures” on/off button
- the selected text is wrapped in a `<span/>` tag and a class with the `font-feature-settings: “liga”;` property is set — this creates a class called `.ffs-0-1`
- user hits “save” to save their layout to load and edit later

This is where I’m stuck. I don’t know how to export the data in my JSS stylesheet to save in my DB, and then reimport when the user opens this document again. I could save the CSS and then just load that in like regular CSS, but that means these classes are no longer recognized by JSS. They can’t be edited or removed with JSS because they’re in the stylesheet loaded in from the DB.

See what I mean?

**Comment by kof** [comment]
You have only 2 choices afaik. Either you safe the styles in objects and apply each rule to each node you want to style once you render while generating styles over jss or you safe the generated styles but then you can add to the same style sheet more while loading from the previously generated styles.

**Comment by kof** [comment]
If you want an easier way to match the styles when you generate them, you can use a hash based class names generator https://codesandbox.io/s/oor1k355qq

**Comment by HenriBeck** [comment]
Why can't you give each node you want to style an id which you can use to map the styles to the node? This id could then be used when initializing to apply the correct classname upon first load.

**Comment by HenriBeck** [comment]
Closing this as this can be implemented and we don't need a custom solution for this
