### ISSUE TITLE
Un-mount and re-mount JssProvider

### ISSUE THREAD

**Issue by scaredcat** [cssinjs/jss#917]
__Expected behavior:__
Expect dynamically generated style names and statically generated style names to be unique

__Describe the bug:__
I have a component wrapped by a JssProvider and  Theme provider eg.

```javasdcript
const jss = createJss()
jss.use(global(), nested(), extend(), compose(), camelCase(), vendorPrefixer())

      <JssProvider classNamePrefix={this.props.classNamePrefix} jss={jss}>
        <ThemeProvider theme={this.props.theme}>
          {this.props.children}
        </ThemeProvider>
      </JssProvider>
```

When I unmount this component and re-mount this component, any dynamically generated styles in the child components now have style names that clash with the original statically generated styles.

__Codesandbox link:__ 
Only happens in production. Will try to write an example soon

__Versions:__
 - jss: 
    "jss": "^9.8.1",
    "jss-camel-case": "^6.1.0",
    "jss-compose": "^5.0.0",
    "jss-global": "^3.0.0",
    "jss-nested": "^6.0.1",
    "jss-vendor-prefixer": "^8.0.1",
 - Browser [e.g. chrome, safari]: latest Chrome (Version 70.0.3538.77 (Official Build) (64-bit)
), latest Firefox (63.0 (64-bit))
 - OS [e.g. Windows, macOS]: Ubuntu 18.10

**Comment by HenriBeck** [comment]
It most likely has to do something with your generateClassName function I would guess. But without seeing more code I can’t tell with 100% certainty.

Once you are able to reproduce the issue on codesandbox we will definetly have a look at it.

**Comment by scaredcat** [comment]
Thanks for the quick reply. I've re-produced the issue here https://github.com/scaredcat/jss-class-generator-test
Since it requires a production build, I've deployed it using gh-pages:
https://scaredcat.github.io/jss-class-generator-test

pressing toggle unmounts the component, then remounts it when toggled back. Notice that the dynamic classnames applied to the third button now is the same as the static classname of the second button group.

The issue does not occur when running the code in development mode.

**Comment by HenriBeck** [comment]
In general I would advise against remounting the JssProvider. I don't think we can fix this bug, because it also happens when you don't use a custom jss instance.

**Comment by HenriBeck** [comment]
I think we should add a section in the docs to never remount the `JssProvider` so there are no class name conflicts.

**Comment by kof** [comment]
Can't we warn instead? I feel like docs won't help there ...

**Comment by HenriBeck** [comment]
Not really.

**Comment by kof** [comment]
We can warn in componentWillUnmount of JssProvider as long as there is no valid case to unmount it.

**Comment by HenriBeck** [comment]
I don't think there is a valid reason to unmount the provider.

**Comment by jarekwg** [comment]
We have a funky use case, where the page is not fully reactified.

We offer a tabbed view to the user, where each tab only has its contents loaded when the tab is in focus. The contents of the tabs are raw HTML, with some mount points for react to jump in. A component at one of these mount points requires the JSSProvider to function. Since the page isn't fully reactified, the provider only wraps this component directly, rather than encompassing everything on the page.

It's a bit of a mishmash, but I can see similar use cases where this issue crops up when the JSSProvider wraps a component at a low-level on the page due to various restrictions, and that component isn't always mounted.

If it's not an awful amount of work to support such a workflow, what's the harm?

**Comment by kof** [comment]
Is there a good reason to not wrap the entire thing into JssProvider?

**Comment by HenriBeck** [comment]
I guess as long as you save the `generateId` and don't create a new one on every mount, it should be fine.

**Comment by kof** [comment]
Yeah, but why making things more complicated if there is no good reason to not wrap entire thing.

**Comment by HenriBeck** [comment]
Nevertheless, it's possible to remount the topmost provider by saving the `generateId` and not generating a new upon remount.

**Comment by scaredcat** [comment]
It seems v10 of `react-jss` has the issue fixed regardless of whether re-using `generateId` or not:
Previously with v8 the static ID generator was re-used but the dynamic style Id started from scratch...
### v8
**First mount**
![screenshot from 2019-01-23 11-41-29](https://user-images.githubusercontent.com/19770543/51574982-433e5700-1f04-11e9-91ed-9baf90a55f30.png)
**Remount**
![screenshot from 2019-01-23 11-41-44](https://user-images.githubusercontent.com/19770543/51574983-446f8400-1f04-11e9-8872-2d53e7154af9.png)
Notice how the dynamic style classes have an ID generated that clash with the static styles on the re-mount. At this stage I'm not sure what was the cause of this, or why the same IDs for static styles were used.

### v10
**First mount**
![screenshot from 2019-01-23 11-40-14](https://user-images.githubusercontent.com/19770543/51574950-21dd6b00-1f04-11e9-8e6c-d2c566d38b1d.png)
**Remount**
![screenshot from 2019-01-23 11-40-28](https://user-images.githubusercontent.com/19770543/51574955-243fc500-1f04-11e9-9a15-0ec79b913bb4.png)
In v10 regardless of whether `generateId` was passed in as a prop, it seems to keep around the pointer to the generator used when re-mounting and increment both the static and dymanic style IDs.

**Comment by HenriBeck** [comment]
If it works now, that's great.

**Comment by kof** [comment]
Do we have a test that makes sure this keeps working?
