### ISSUE TITLE
[jss-extend] unable to access theme form extend function

### ISSUE THREAD

**Issue by evosch** [cssinjs/jss#920]
According the the Readme of jss-extend it appears possible to access theme from a function passed to extend. https://github.com/cssinjs/jss-extend#use-function-which-returns-a-style-object
But when I try this, there is no theme object available.

```
function Button({
  classes,
  children,
}) {
  return (
    <button className={classes.button} type="button">
      {children}
    </button>
  );
}

baseStyle = (data) => ({
  padding: [5, 10],
  borderRadius: data.theme.borderRadius,
});

const primaryStyle = (theme) => {
  return {
    button: {
      extend: baseStyle,
      backgroundColor: theme.colors.primary,
    },
  };
};

const primaryButton = injectSheet(primaryStyle)(Button);

    <ThemeProvider theme={theme}>
      <PrimaryButton>Test</PrimaryButton>
    </ThemeProvider>
}
```

**Comment by HenriBeck** [comment]
That only works when your data has a `theme` property, and this only happens if you pass a theme obj to the `react-jss` HOC.

The data you get in function values in `react-jss` are the props which are passed into the HOC and theme is not one of them.
