### ISSUE TITLE
Observables link is broken in main README

### ISSUE THREAD

**Issue by appsforartists** [cssinjs/jss#921]
On line 20 in the [README](https://github.com/cssinjs/jss/blob/f00774dee6930608ee0c9bb2d981b4c5ed3431c8/readme.md#L20), **Observables** links to https://github.com/cssinjs/jss/blob/master/docs/json-api.md#observable-values

There's nothing on that page presently about how to use observables with JSS.

**Comment by HenriBeck** [comment]
Fixed in #927
