### ISSUE TITLE
[jss-extend] didn't compile jss to css in extend

### ISSUE THREAD

**Issue by linchen2chris** [cssinjs/jss#922]
row: {
    marginBottom: "16px",
    display: "flex",
    justifyContent: "space-between",
  },
  rowEnd: {
    extend: "row",
    justifyContent: "flex-end",
  },
--------------------
compiled to 
![image](https://user-images.githubusercontent.com/3970087/48932510-50a48880-ef37-11e8-987e-67739681806f.png)

**Comment by kof** [comment]
your plugins setup seems wrong, you need to post a full story, ideally as codesandbox

**Comment by kof** [comment]
check the order, you seem to not use the default preset https://cssinjs.org/plugins?v=v9.8.7#order-does-matter or just use the preset.
