### ISSUE TITLE
Nested styles

### ISSUE THREAD

**Issue by SorEduard** [cssinjs/jss#923]
When I use nested styles like `&:focus $label` and step an arrow function for the attribute to get the props of the component, I catch the error `Warning: [JSS] Could not find the referenced rule radio in Radio, Themed, Dynamic.`

Example with error:
```
  input: {
    "&:checked + $radio": {
      backgroundColor: theme.palette.primary
    },
    "&:active + $radio": {
      color: props => props.color // this func
    }
  },
  radio: {
    width: "20px",
    height: "20px",
    ...
  }
```

Example without error:
```
  input: {
    "&:checked + $radio": {
      backgroundColor: theme.palette.primary
    },
    "&:active + $radio": {
      color: theme.palette.primary
    }
  },
  radio: {
    width: "20px",
    height: "20px",
    ...
  }
```

__Versions:__
 - JSS: 9.8.7
 - Browser: Chrome
 - OS: macOS

__Configuration:__
 - A razzle application with a minimal extension of the configuration (SSR)
 - Custom generateClassNames

**Comment by HenriBeck** [comment]
This is currently a known bug. If you really need this behaviour please use `react-jss@8.6.0`.

The bug is being tracked here for updates: #796
