### ISSUE TITLE
A strange off-by-one problem – incorrect style is applied sometimes

### ISSUE THREAD

**Issue by farcaller** [cssinjs/jss#926]
I'm trying to debug a problem where material-ui-kit pulls in material-ui that uses jss and I use it all with gatsby's SSR.

I'll work on a minimal reproducible build but what I see insofar is that **sometimes** jss is rendered incorrectly and all the elements get assigned jss+1 indices, exploding the page at random. It seems to be pretty consistent in that +1, e.g.

![image](https://user-images.githubusercontent.com/693/47595038-1d8dca00-d976-11e8-8cfc-10cd84642cc3.png)

is a good render, while

![image](https://user-images.githubusercontent.com/693/47595062-3b5b2f00-d976-11e8-88b9-a5b9e430962c.png)

is a bad one.

While I hunt for what exactly triggers the bad behavior, any ideas what could possibly cause this N+1?

```
npm ls|grep jss
│ ├─┬ @types/jss@9.5.7
│ ├─┬ jss@9.8.7
│ ├─┬ jss-camel-case@6.1.0
│ ├── jss-default-unit@8.0.2
│ ├── jss-global@3.0.0
│ ├─┬ jss-nested@6.0.1
│ ├── jss-props-sort@6.0.0
│ ├─┬ jss-vendor-prefixer@7.0.0
└─┬ react-jss@8.6.1
  ├── jss@9.8.7 deduped
  ├─┬ jss-preset-default@4.5.0
  │ ├── jss-camel-case@6.1.0 deduped
  │ ├─┬ jss-compose@5.0.0
  │ ├── jss-default-unit@8.0.2 deduped
  │ ├── jss-expand@5.3.0
  │ ├─┬ jss-extend@6.2.0
  │ ├── jss-global@3.0.0 deduped
  │ ├── jss-nested@6.0.1 deduped
  │ ├── jss-props-sort@6.0.0 deduped
  │ ├─┬ jss-template@1.0.1
  │ └── jss-vendor-prefixer@7.0.0 deduped
```

**Comment by HenriBeck** [comment]
I will close this as this isn't a problem of jss.
