### ISSUE TITLE
[react-jss] innerRef prop incompatible with React.createRef

### ISSUE THREAD

**Issue by bamaboy** [cssinjs/jss#935]
__Expected behavior:__
`innerRef` takes `React.createRef()` as valid propType.

__Describe the bug:__
I am using react 16 refs api, and passing ref to styled component. But since `React.createRef()` returns an object, and component's prop `innerRef` expected to be function, propTypes warning occurs.
```
Failed prop type: Invalid prop `innerRef` of type `object` supplied to `Jss(TabPicker)`, expected `function`.
```

__Versions (please complete the following information):__
 - jss: latest

**Comment by kof** [comment]
innerRef was designed before createRef api existed. Stay tuned for the version 10 release  https://github.com/cssinjs/jss/issues/795
