### ISSUE TITLE
[react-jss] Layout with nextjs

### ISSUE THREAD

**Issue by jonathangiamp** [cssinjs/jss#939]
__Expected behavior:__
With [nextjs](https://nextjs.org/), I want to be able to call header / footer components only one time at the top of my tree. Every component styles must be managed by react-jss.

__Describe the bug:__
Only the style of my main component is manage by react-jss. When document is client-side rendered, styles for Header/Footer are randomly rendered. When document is server-side rendered, styles aren't apply to Header/Footer components.

__Codesandbox link:__ 
Here a codesandbox to reproduce this issue: [CodeSandbox](https://codesandbox.io/s/l4k2v5lq8z).
Navigate with link to test client-side rendering. Access to page directly by typing url in the url bar to test server-side rendering.

__Versions:__
 - react-jss: 8.6.1
- jss-preset-default: 4.5.0
- [nextjs](https://nextjs.org/): 7.0.2
- Chrome: 71
- Node: 10.13.0
 - OS: macOS Mojave 10.14.1

**Comment by HenriBeck** [comment]
I think I figured out the problem.
In `_app.jsx` `ctx.renderPage` doesn't get the whole `App` component but only the page component.
So only the stylesheets of the current page will be caught by the `SheetsRegistry`.

Not sure if we can do anything about this.

**Comment by HenriBeck** [comment]
Alright, I figured out a way around this issue: https://codesandbox.io/s/mqnzz2w2yj
The changed code is inside `_document.jsx`

I will be updating the example in the next.js repo soon

**Comment by kof** [comment]
@HenriBeck anything we should update in https://github.com/zeit/next.js/tree/canary/examples/with-react-jss ?

**Comment by HenriBeck** [comment]
Already did.

**Comment by kof** [comment]
Cool thanks!

**Comment by jonathangiamp** [comment]
You rocks guys, thank you very much, I'm going to update my code 👌
