### ISSUE TITLE
Nested Objects Aren't Visible In the Classes Object

### ISSUE THREAD

**Issue by kwingat** [cssinjs/jss#955]
Is it not possible to nest objects like so:

    ` header: {
    width: "100%",
    marginBottom: "20px",
    justifyContent: "space-between",
    alignItems: "center",

    header_left: {
      justifyContent: "flex-start",
      marginLeft: "15px"
    },

    header_right: {
      justifyContent: "flex-end",
      width: "25%",

      filterDrop: {
        marginRight: "25px !important"
      }
    },
    }`

https://codesandbox.io/s/q3v9n23zv9

I wrote a console log for classes and don't see anything past header.

**Comment by HenriBeck** [comment]
You are using it wrong. Only top-level properties result in properties on the classes object.

https://codesandbox.io/s/k39lvx2rxo
