### ISSUE TITLE
IE 11 injection order is wrong

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#966]
__Expected behavior:__
IE 11 behaves as the other browsers.

__Describe the bug:__
IE 11
![capture d ecran 2019-01-01 a 15 52 44](https://user-images.githubusercontent.com/3165635/50573916-52d2f000-0ddd-11e9-811d-80c792564f10.png)

The other browsers
![capture d ecran 2019-01-01 a 15 52 52](https://user-images.githubusercontent.com/3165635/50573915-50709600-0ddd-11e9-8a96-856a22ad0c6a.png)

This is a v10 regression. It was first reported in https://github.com/mui-org/material-ui/issues/14045.

__Codesandbox link:__ 
https://codesandbox.io/s/z2k5o54p5m

__Versions (please complete the following information):__
 - jss: v1.0.0-alpha.5
 - Browser: IE 11

**Comment by oliviertassinari** [comment]
Before:
https://github.com/cssinjs/jss/blob/4c7c2fd3e0b2ff9983c274fc7197dd8154dc47ae/src/StyleSheet.js#L58-L65
After:
https://github.com/cssinjs/jss/blob/35e4f8d17c49d0688d660d20d467dc56ccf7e226/packages/jss/src/StyleSheet.js#L57-L64

**Comment by oliviertassinari** [comment]
The regression comes from https://github.com/cssinjs/jss/pull/857

**Comment by kof** [comment]
I have tried running that example on IE11, I get errors, how did you test it there?

**Comment by oliviertassinari** [comment]
@kof It's related to https://github.com/CompuIves/codesandbox-client/issues/1187. Codesandobx broke the IE 11 support at some point. I have used a naked project, something like CRA or Next.js. Maybe you can use the JSS documentation website?

**Comment by kof** [comment]
Interesting, actual source order of style tag is correct.

<img width="993" alt="screen shot 2019-01-02 at 00 06 46" src="https://user-images.githubusercontent.com/52824/50576799-55a40400-0e22-11e9-95f5-f38e8bfaf44a.png">

**Comment by kof** [comment]
funny, attaching sheets takes precedence over source order
