### ISSUE TITLE
TypeScript guide

### ISSUE THREAD

**Issue by NicholasLYang** [cssinjs/jss#969]
__Is your feature request related to a problem? Please describe.__
I've been scratching my head over typing JSS, specifically React JSS. I've read [this post](https://github.com/cssinjs/react-jss/issues/194) and tried to implement what they suggested, but it kind of falls apart with theming. In addition, I've noticed that there's already typings in the repo, but I can't make heads or tails of them without some usages. I've also tried looking at Material UI, but it's a little overwhelming.

__Describe the solution you'd like__
I'd really appreciate some examples of typing styles and how to implement theming, dynamic values, etc. Also a quick runthrough of the rational behind typings would be fantastic. One of the important, yet frustrating parts of TS is that typings can be written at several levels of granularity and choosing the level is extremely important.

__Are you willing to implement it?__
Yes! However, I'd need some guidance on the right way to use the typings.

**Comment by HenriBeck** [comment]
Sound great. Feel free to create a PR.

**Comment by HenriBeck** [comment]
Yes, should be in the docs under `Usage with typescript`.

@NicholasLYang No, we are in the process of refining the types right now and adding tests for them.

**Comment by Saturate** [comment]
I've used React-JSS and TypeScript for some time, feel free to ask any questions - I might be able to answer.

**Comment by NicholasLYang** [comment]
Hey @Saturate, I'm just struggling with the basics here. Let's say I'm trying to inject styles into a simple component, no theming, no dynamic values. Any chance you could provide a code snippet?

**Comment by Saturate** [comment]
@NicholasLYang 

Sure the following should be fine for you:

```
import * as React from 'react';
import injectSheet from 'react-jss';

const styles = {
	root: {
		color: 'red',
		fontWeight: 600
	}
};

export interface IHeadingProps {
	children: React.ReactNode;
}

class Heading extends React.Component<IHeadingProps> {
	public render() {
		return (
			<h1 className={this.props.classes.root}>{this.props.children}</h1>
		);
	}
}

export default injectSheet(styles)(Heading);
```

**Comment by HenriBeck** [comment]
@Saturate is this for the new typings or the old ones in definitely typed?

**Comment by NicholasLYang** [comment]
@Saturate, I'm a little confused by your example. `classes` isn't included as a prop, which gives an error for me in create-react-app (with TS). Also, styles is implicitly typed as a literal (due to const), which probably won't play nice with the injectSheet typing unless you widen the type, no?

**Comment by Saturate** [comment]
@HenriBeck these are for some I did, so a mutation of the ones in definitely typed. They should more or less fit the new ones, however there are some changes... As you documented in the other issue about TS.

@NicholasLYang I'm having this issue this them ans the new types as well, see:  https://github.com/cssinjs/jss/issues/972#issuecomment-453082335

**Comment by NicholasLYang** [comment]
This is a very dumb question, but where are you getting the typings? I don't think they're installed with the package, and `@types/react-jss` is pretty out of date. Are you just manually creating declaration files or linking the source code by hand?

**Comment by HenriBeck** [comment]
The typings are only in the v10 alpha.

**Comment by NicholasLYang** [comment]
Okay, I'm getting a grasp of things (thanks @HenriBeck, these typings are so much better than before). I can try to write up some documentation

**Comment by HenriBeck** [comment]
Closing as this was done in #1009
