### ISSUE TITLE
TypeScript declaration of classes should be class instead of interface

### ISSUE THREAD

**Issue by mfellner** [cssinjs/jss#970]
__Expected behavior:__
Inside `index.d.ts` the declaration of classes (e.g. Renderer, SheetsRegistry, etc.) should be `declare class` instead of `interface`.

__Describe the bug:__
When using jss in TypeScript, some types cannot be instantiated because they are declared as `interface` instead of `class`. Example:
```
'SheetsRegistry' only refers to a type, but is being used as a value here.
```

__Codesandbox link:__ 
https://codesandbox.io/s/m4p166n59y

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.7

**Comment by HenriBeck** [comment]
Thanks, will be fixed this evening.
