### ISSUE TITLE
injectSheet typings require very verbose usage currently

### ISSUE THREAD

**Issue by briman0094** [cssinjs/jss#972]
With the latest 10.0.x typings, any TypeScript usages of `injectSheet` require very verbose explicit type parameters to get the outer component type right. The biggest pain is that `InjectedProps<Styles, Theme>` is not exposed, so one has to declare the inner component's Props as `Props & { classes: { [key: string]: string } }`.

My suggestion for this would be to expose `InjectedProps` as `WithStyles` or a similar name (following the naming convention of packages such as `material-ui`) and to add defaults to the generic parameters, so the inner styled component could be declared as `Props & WithStyles`.

The next challenge is that `injectSheet` itself receives the generic `Props` type, and passes it to its return type, so TypeScript can't infer the inner Props from usage. This means that in order to get the correct outer props, `injectSheet` has to be called as `injectSheet<Styles, {}, Props & { classes: { [key: string]: string } }>( styles )( Component )`.

My suggestion for this would be to change the definition for `injectSheet` so that the generic Props type argument is declared on the return type like this:

```ts
export default function injectSheet<
  Style extends Styles,
  Theme extends object
>(
  styles: Style,
  options?: Options
): <Props extends InjectedProps<Styles, Theme>>(
  comp: React.ComponentType<Props>
) => React.ComponentType<Omit<Props, InjectedProps<Styles, Theme>>>
```

That way TypeScript can infer the type of `Props` from the usage when the return value from `injectSheet` is called with a Component.

I'd be happy to make these changes in a PR if there is no opposition to them or a better way to work around the current issues.

**Comment by briman0094** [comment]
I also just discovered that the return type of the `injectSheet` composer doesn't correctly omit the properties from `InjectedProps` on the returned Component. The last line should be changed to `React.ComponentType<Omit<Props, keyof InjectedProps<Styles, Theme>>>`

**Comment by HenriBeck** [comment]
The proposed changes sound great. Please make a PR, and I will review it then.

**Comment by Saturate** [comment]
> I updated the `react-jss` types: https://github.com/cssinjs/jss/blob/react-jss/update/packages/react-jss/src/index.d.ts
> 
> Feel free to have a look; those types should be published by the end of the week.

Seems like it's not omitting the `classes` props on the interface when you want to use it.

Example:

`Link.tsx`
```ts
export interface ILinkProps {
	href: string;
	className?: string;
	disableTabIndex?: boolean;
	ariaLabel?: string;
	children: React.ReactNode;
	classes: any;
}

const Link: React.SFC<ILinkProps> = props => {
	const className = classnames(props.classes.root, props.className);
	return (
		<a
			className={className}
			href={props.href}
			tabIndex={props.disableTabIndex ? -1 : undefined}
			aria-label={props.ariaLabel ? props.ariaLabel : undefined}
		>
			{props.children}
		</a>
	);
};

export default withStyles(styles)(Link);
```


`Page.tsx`
```ts
// ....
// ERROR:  Property 'classes' is missing in type
<Link href={...}>Link</Link>
//...
```

Full error:

```
[ts]
Type '{ children: string; className: any; href: string; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<ILinkProps & { classes?: Partial<any> | undefined; }, any, any>> & Readonly<{ children?: ReactNode; }> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & { ...; })'.
  Type '{ children: string; className: any; href: string; }' is not assignable to type 'ILinkProps'.
    Property 'classes' is missing in type '{ children: string; className: any; href: string; }'.
```

**Comment by HenriBeck** [comment]
Should be fixed now, I forgot to omit the props before adding them as optional again.

Usage:
```ts
import withStyles, { WithStyles } from 'react-jss';

const styles = {};

interface Props extends WithStyles<typeof styles> {
  isDisabled: boolean,
}

function Comp(props: Props) {
  return <button disabled={props.isDisabled}></button>
}

export default withStyles(styles)(Comp)
```

**Comment by HenriBeck** [comment]
The code works for me

**Comment by Saturate** [comment]
That's pretty strange, I'm using TypeScript 3.1.6 and both the compiler and VS Code gives me that error:

![image](https://user-images.githubusercontent.com/453018/50968975-2ace4580-14dd-11e9-934f-14367c1ddc67.png)

**Comment by briman0094** [comment]
I should be able to play with these new typings soon to see if I'm encountering the issues as well

**Comment by HenriBeck** [comment]
The new typings have been released now.

For an example see:
https://codesandbox.io/s/qqnz79vp6w

**Comment by muzea** [comment]
Consider this scenario, when need generics
```tsx
class Foo<T> extends React.Component<T> { }
const StyledComp = injectSheet(styles)(Foo)
```
We can't get the exact type of StyledComp now.

@HenriBeck

**Comment by HenriBeck** [comment]
@muzea Why do you need generic props?

**Comment by HenriBeck** [comment]
I think we can close this as the types from `react-jss` have been improved.
If you still have questions/suggestions, comment, and I can reopen the ticket if necessary.

**Comment by muzea** [comment]
@HenriBeck 
https://ant.design/components/table/#Table
https://github.com/ant-design/ant-design/blob/042fad7f9a904081f786e442c3c4248a0f13e1b3/components/table/interface.tsx#L123-L173

Like here, `columns` and `dataSource` 's  type is dependent on data. I think that in this case, there is no way to declare the type.

> you can only extend object types, in other words something that of a known structure
> https://github.com/Microsoft/TypeScript/issues/8853#issuecomment-224398399

[Related Discussion in Chinese](https://www.v2ex.com/t/530586)

**Comment by HenriBeck** [comment]
Yeah, that is a constraint, but I don't see how we are going to support this. This limitation will go away once we move to React Hooks.

**Comment by Frank1e0927** [comment]
![image](https://user-images.githubusercontent.com/17680956/58941787-156cf700-87af-11e9-83bd-ef170bb12ab9.png)

`"react-jss": "10.0.0-alpha.16"`

why i got this type error?

is there classes should be optional?

**Comment by Frank1e0927** [comment]
> Should be fixed now, I forgot to omit the props before adding them as optional again.
> 
> Usage:
> 
> ```ts
> import withStyles, { WithStyles } from 'react-jss';
> 
> const styles = {};
> 
> interface Props extends WithStyles<typeof styles> {
>   isDisabled: boolean,
> }
> 
> function Comp(props: Props) {
>   return <button disabled={props.isDisabled}></button>
> }
> 
> export default withStyles(styles)(Comp)
> ```

sure this type fixed? = =

**Comment by zakarehman270** [comment]
import styles from "../Style";
import injectSheet from "react-jss";
const Settings: React.FC<Props> = ({ ListProps, ListName, }: Props) => {
  const [List, setList] = useState(ListProps);
  const contextData = useContext(Context);
  const [radioValue, setRadioValue] = useState(1);
  const { classes } = props;
 console.log("kala",classes)
How Classes of injectsheet is import from props in reacttypescript???
