### ISSUE TITLE
The tests are published to npm

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#979]
__Expected behavior:__
We can reduce the size of the npm packages by not publishing the tests.

__Describe the bug:__
Here is one example:
https://unpkg.com/jss-plugin-camel-case@10.0.0-alpha.7/src/index.test.js

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.7

**Comment by kof** [comment]
We should definitely exclude .test.js from files in package.json

**Comment by oliviertassinari** [comment]
If we had a `priority: low` flag. I would have added it. I think that it can be a good first issue flag for a potential new contributor :).

**Comment by oliviertassinari** [comment]
I would encourage this solution:
**.npmignore**
```
/*
!/src/*.js
!/dist/*.js
*.test.js
```

**Comment by kof** [comment]
What is wrong with complexity:low flag? I don't think the priority is good term for this. Priority is different depending on a consumer. Complexity of fixing something is relative to the project itself.

**Comment by oliviertassinari** [comment]
Maybe replacing `complexity:low` with the convention: `good first issue`? 
Yes, complexity !== value

**Comment by kof** [comment]
We went away from using .npmignore because it was much harder to exclude things than to select things which need to be included. We just forgot that we have .test.js files as we moved to a monorepo, because we moved in projects which use this structure.

**Comment by kof** [comment]
We had a label like "good first issue" before and no single time people contributed to them, so I removed them because its just noise.

**Comment by kof** [comment]
I consider all complexity:low issues a good first issue and its easy to find if one looks through issues.

**Comment by kof** [comment]
NPM files supports glob pattern https://docs.npmjs.com/files/package.json#files so we can exclude those in it as well.

**Comment by mdsadiq** [comment]
i think this issue is fixed already 😅

**Comment by kof** [comment]
possible :)
