### ISSUE TITLE
Improve publishing experience for JSS maintainers

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#984]
## What want the release to do

- [ ] Manually set the version (or mb take it from changelog.md)
- [ ] Build with the new version, commit the size-snapshots with changes (or avoid them somehow), we use the verson in the JS build and this increases bundle sizes
- [ ] Update peer dependencies (#991)
- [ ] Make sure npm tag is set, e.g. an alpha release should not be published with dist tag "latest" otherwise all people get the update.
- [ ] Make it use the changelog.md and add its contents for the release to the release tag on github. This will send out an email to people who subscribed releases and they will get the changees.

**Comment by HenriBeck** [comment]
I think we can use the `postversion` npm hook for building, that hook should be run after bumping the version and before `lerna` commits the changes

**Comment by kof** [comment]
I think this is done now.
