### ISSUE TITLE
How can i use jss in nodejs

### ISSUE THREAD

**Issue by amitdhawan** [cssinjs/jss#985]
__Expected behavior:__

__Describe the bug:__
A clear and concise description of what happend instead of the expected behavior.

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.

__Versions (please complete the following information):__
 - jss:
 - Browser [e.g. chrome, safari]:
 - OS [e.g. Windows, macOS]:
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
https://cssinjs.org/jss-api?v=v10.0.0-alpha.8#style-sheets-registry

**Comment by amitdhawan** [comment]
import jss, {SheetsRegistry} from 'jss' will not work in nodejs 10 as that is available from nodejs 11.

**Comment by kof** [comment]
console.log(jss) and you see the problem

**Comment by amitdhawan** [comment]
i get this 
```
{ getDynamicStyles: [Getter],
  toCssValue: [Getter],
  SheetsRegistry: [Getter],
  SheetsManager: [Getter],
  RuleList: [Getter],
  sheets: [Getter],
  createGenerateClassName: [Getter],
  create: [Function: create],
  default:
   Jss {
     id: 0,
     version: '9.8.7',
     plugins: PluginsRegistry { hooks: [Object] },
     options:
      { createGenerateClassName: [Function],
        Renderer: [Function: VirtualRenderer],
        plugins: [Array] },
     generateClassName: [Function] } }
```

Not sure what exactly u mean.

**Comment by amitdhawan** [comment]
My requirement is to create css from JS object. Can you help me on this?

**Comment by kof** [comment]
require('jss').default

**Comment by amitdhawan** [comment]
@kof Thanks it works now.
```

const jss = require('jss').default;

function createStyleSheet() {

   return jss
   .createStyleSheet(
     {
       // "button" is a rule name; a class gets generated.
       button: {
         width: 100,
         height: 100
       }
     },
     {media: 'print'}
   )
  
}
const sheet = createStyleSheet();
console.log(sheet.toString());
```

**Comment by amitdhawan** [comment]
Just one more doubt why its attaching 0-0-1 in the output as below

```
.button-0-0-1 {
  width: 100;
  height: 100;
}
```

**Comment by Yzrsah** [comment]
@amitdhawan Wrap the sheet object in `"@global": { ... }`
