### ISSUE TITLE
Support of String in JSS

### ISSUE THREAD

**Issue by amitdhawan** [cssinjs/jss#986]
Is it possible to add a string in CSS by using JSS. The string i want to add has the rule included too like below:-

`@font-face {font-family: 'PointDEMO-Light';src: url('webfonts/38673B_0_0.eot');}`

should result in 
@font-face {
  font-family: 'PointDEMO-Light';
  src: url('webfonts/38673B_0_0.eot');
}

**Comment by amitdhawan** [comment]
@kof Kindly help.

**Comment by kof** [comment]
Did you see it in the docs? https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.8#font-face

**Comment by kof** [comment]
This is not supported.
