### ISSUE TITLE
[react-jss]: Observables do not work correctly

### ISSUE THREAD

**Issue by bhupinderbola** [cssinjs/jss#987]
__Expected behavior:__
Observables should work correctly.
__Describe the bug:__
When element is unmounted and mounted again, the observables stop working. It looking like after detaching, when static stylesheet is attached again, it does not get linked.

__Codesandbox link:__ 
https://codesandbox.io/s/1z1z54no0l

__Versions (please complete the following information):__
 -react- jss: 8.6.1
 - Browser [e.g. chrome, safari]: Chrome
 - OS [e.g. Windows, macOS]: Windows
Feel free to add any additional versions which you may think are relevant to the bug.

**Comment by kof** [comment]
sounds like a good bug to fix!

**Comment by HenriBeck** [comment]
Also, observables do not seem to work without explicitly passing `link: true` as an option to `injectSheet`

**Comment by kof** [comment]
That is strange, afaik react-jss should be passing link: true

**Comment by kof** [comment]
So we have 2 bugs here.

**Comment by kof** [comment]
This feature is not widely known, I wish we could do something about it.

**Comment by HenriBeck** [comment]
I think observables are hard to use in React as they aren't scoped to components, so you can only have a global state which updates all of the react components

**Comment by kof** [comment]
Doesn't seem like an unsolvable issue, if they need to connect to components, I am sure there are ways to do so, also even manually passing an observable anywhere you want isn't a problem.

**Comment by bhupinderbola** [comment]
I am not 100% sure, but it might be a jss issue. In https://github.com/cssinjs/jss/blob/v9.8.7/src/StyleSheet.js, detach does not change the this.linked, but in attach, we have if (!this.linked && this.options.link) this.link()

In the debugger, if I change this.linked to be false, then it works correctly. Is detach supposed to change this.linked to false?

**Comment by kof** [comment]
Pls try v10

**Comment by bhupinderbola** [comment]
In https://codesandbox.io/s/1z1z54no0l. changing react-jss from 8.61 to 10.0.0-alpha.8 solved the issue.

**Comment by bhupinderbola** [comment]
Do we know when v10 will go out of alpha state?

**Comment by HenriBeck** [comment]
Don't know yet, hopefully until the end of February
