### ISSUE TITLE
The CSS rule generated is not sorted as per the JS object input

### ISSUE THREAD

**Issue by amitdhawan** [cssinjs/jss#988]
Hi,

Im giving this input to createRule method of JSS
``` 
{ 
 fontFamily: 'Helevetica',
  fontStyle: 'Arial',
  fontStretch: 'abcd',
  unicodeRange: [ 'U+0020-007F', 'U+0020-007G', 'U+0020-007G' ],
  fallbacks:
   [ { src: 'url(/estPath.eot?#iefix) format(embedded-opentype)' },
     { src: 'url(estPath/) format(woff)' } ],
  src: 'url(/estPath.eot)'
 }
```
The output i get is not in the same order as input and doesn't look good to the end user:-
```
@font-face {
  src: url(/estPath.eot?#iefix) format(embedded-opentype);
  src: url(estPath/) format(woff);
  font-family: Helevetica;
  font-style: Arial;
  font-stretch: abcd;
  unicode-range: U+0020-007F, U+0020-007G, U+0020-007G;
  src: url(/estPath.eot);
}
```
Any plugin i do need to use for sorting it as per input or is it a bug?

**Comment by HenriBeck** [comment]
The output is in the correct format because fallbacks are always before any other properties.

**Comment by amitdhawan** [comment]
But this is not the case in your docs. Check out:- [https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.8](Check out fallbacks)

```
// Font-Face with src fallbacks.
const styles = {
  '@font-face': {
    fontFamily: 'MyWebFont',
    src: 'url(webfont.eot)',
    fallbacks: [
      {src: 'url(webfont.eot?#iefix) format(embedded-opentype)'},
      {src: 'url(webfont.woff2) format(woff2)'}
    ]
  }
}
```

compiles to:

```
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot');
  src: url(webfont.eot?#iefix) format(embedded-opentype);
  src: url(webfont.woff2) format(woff2);
}
```

**Comment by HenriBeck** [comment]
Actually, the docs are outdated in this case.

https://codesandbox.io/s/y292npxwzz

**Comment by amitdhawan** [comment]
But is this the CSS W3C standard?

**Comment by amitdhawan** [comment]
@HenriBeck not sure if this is the CSS w3C standard or JSS has implemented like this. Please provide your inputs on this.

**Comment by amitdhawan** [comment]
@HenriBeck It seems like a bug to me as everywhere on the Intenet i see the font-family as the top member of font-face rule. Check out:
https://css-tricks.com/snippets/css/using-font-face/

Should i be filing a new issues for this?

**Comment by HenriBeck** [comment]
No, I don’t think so. font faces should still work

**Comment by amitdhawan** [comment]
It doesn't look good in production environment. I don't think so it would be big change in the code.

**Comment by HenriBeck** [comment]
If you think there is a bug, create a codesandbox with a reproducible example.

**Comment by amitdhawan** [comment]
You have already created the sandbox. I can share the same link.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by amitdhawan** [comment]
I agree they don't matter, but it doesn't look good in production.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by amitdhawan** [comment]
It should be a bug as if u see on the internet no where css is provided in the manner jss provides.
It should be a minor enhancement in existing code also jss documentation is not up to date it should be update or the code should be updated as per just docs.

Let me know your thoughts.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by amitdhawan** [comment]
Also just think of this if the css is provided to a fortune 500 customer it will never ever expect this type of css.I think we should update the rules order for fallback.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com

**Comment by kof** [comment]
Can someone please explain to me what the issue is here? I don't understand.

**Comment by HenriBeck** [comment]
There is no real issue here. Just some small inconsistency with the docs.

**Comment by kof** [comment]
@amitdhawan can you please send a PR for the docs?

**Comment by amitdhawan** [comment]
@kof it seems to be a bug to me as the docs are as per industry standard, I can definitely work on fixing the issue though.

**Comment by kof** [comment]
Ok so you expect the fallbacks to be right in the order where `fallbacks` key is defined, but instead they are at the beginning of the rule, right?

I can see that this is not Ideal, but I can't see how this can cause bugs.

**Comment by kof** [comment]
Actually I see how fallbacks not being the first properties can be a bug. Fallbacks should always come before the properties which need them. If I write the fallbacks keyword after the property that needs the fallback, fallback won't be before that property in the resulting rule. On the other hand being before all the property makes sure they are always on the right place, no matter if user did it wrong or right.

**Comment by HenriBeck** [comment]
yeah, as I said this is a complaint on how we render/sort css properties,  so it’s not a bug.

I wouldn’t fix it, because we would need to do more work and it’s less safe. As well it shouldn’t matter how we render the css as long it works.

**Comment by amitdhawan** [comment]
@HenriBeck @kof this is a bug. U just checked the case in HTML and it doesn't render the ht.l in the font. You can test it by providing src with one woff and one eot font  at the top of fontface providing both font in single src tag.

Also, I noticed one more issue.The css also doesn't render if the fontfamily: Helvetica without the quotes i.e. ' ' which is the case if we use createrule and then toString method. It should result in fontfamily:'Helvetica'. So I would say please try to simulate these scenarios at your end.

**Comment by HenriBeck** [comment]
Please provide a codesandbox link if you think it's a bug.

**Comment by amitdhawan** [comment]
Ok.i will try to work over on over the weekend. I will also try to send html and the css generated by jss for issue reproduction.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

 
Amit Dhawan
Lead Software Engineer
Monotype Solutions India Pvt. Ltd.
Fourth Floor - Tower B, Prius Universal Plot A-3, 4 & 5, Sector -125
Noida 
201301
Phone +91  9953936137
Our Brand Family
​
Monotype.com
Olapic.com
