### ISSUE TITLE
Mock jss in jest [nodejs]

### ISSUE THREAD

**Issue by amitdhawan** [cssinjs/jss#989]
Im not able to mock jss module in jest using nodejs.
below is my mock code:-
```
jest.mock('jss', () => ({
    default: jest.fn(),
}));
```

though by above code im able to mock other node modules but not jss modules. Any help is appreciated?

**Comment by HenriBeck** [comment]
Please provide the error, but I'm guessing it has nothing to do with jss or jest, but with the mock implementation.

**Comment by amitdhawan** [comment]
There is no error but when i run the test it runs with original jss module.I doubt, is jss compatible with node.?

**Comment by HenriBeck** [comment]
Yes, it is compatible with it.

**Comment by amitdhawan** [comment]
Possible, you provide me example on how to mock jss in jest using nodejs. Im not able to find any help online too.

**Comment by amitdhawan** [comment]
Hey @HenriBeck Im able to mock, I was running the code rather than test.Thanks for the help. Would u be rather able to help me out in another issue though i.e. issue 97.
